package com.rsaame.pas.dao.model;

// Generated Mar 7, 2012 5:39:16 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.mindtree.ruc.cmn.utils.Utils;
import com.rsaame.pas.cmn.pojo.POJO;
import com.rsaame.pas.cmn.pojo.POJOId;

/**
 * TTrnGaccCashDetailsQuo generated by hbm2java
 */
public class TTrnGaccCashDetailsQuo extends POJO implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private TTrnGaccCashDetailsQuoId id;
	private long gcdGchId;
	private long gcdPolPolicyId;
	private long gcdPolEndtId;
	private Date gcdValidityExpiryDate;
	private String gcdSafeDwrMake;
	private BigDecimal gcdSafeDwrWeightKg;
	private BigDecimal gcdSafeDwrHeightCms;
	private BigDecimal gcdSafeDwrWidthCms;
	private String gcdSafeDwrAnchoredFlag;
	private String gcdCashResEmpEName;
	private String gcdCashResEmpAName;
	private String gcdCashResOccupation;
	private BigDecimal gcdCashResAmt;
	private Integer gcdPreparedBy;
	private Date gcdPreparedDt;
	private Integer gcdModifiedBy;
	private Date gcdModifiedDt;
	private Byte gcdStatus;

	public TTrnGaccCashDetailsQuo() {
	}

	public TTrnGaccCashDetailsQuo(TTrnGaccCashDetailsQuoId id, long gcdGchId,
			long gcdPolPolicyId, long gcdPolEndtId, Date gcdValidityExpiryDate) {
		this.id = id;
		this.gcdGchId = gcdGchId;
		this.gcdPolPolicyId = gcdPolPolicyId;
		this.gcdPolEndtId = gcdPolEndtId;
		this.gcdValidityExpiryDate = gcdValidityExpiryDate;
	}

	public TTrnGaccCashDetailsQuo(TTrnGaccCashDetailsQuoId id, long gcdGchId,
			long gcdPolPolicyId, long gcdPolEndtId, Date gcdValidityExpiryDate,
			String gcdSafeDwrMake, BigDecimal gcdSafeDwrWeightKg,
			BigDecimal gcdSafeDwrHeightCms, BigDecimal gcdSafeDwrWidthCms,
			String gcdSafeDwrAnchoredFlag, String gcdCashResEmpEName,
			String gcdCashResEmpAName, String gcdCashResOccupation,
			BigDecimal gcdCashResAmt, Integer gcdPreparedBy,
			Date gcdPreparedDt, Integer gcdModifiedBy, Date gcdModifiedDt,Byte gcdStatus) {
		this.id = id;
		this.gcdGchId = gcdGchId;
		this.gcdPolPolicyId = gcdPolPolicyId;
		this.gcdPolEndtId = gcdPolEndtId;
		this.gcdValidityExpiryDate = gcdValidityExpiryDate;
		this.gcdSafeDwrMake = gcdSafeDwrMake;
		this.gcdSafeDwrWeightKg = gcdSafeDwrWeightKg;
		this.gcdSafeDwrHeightCms = gcdSafeDwrHeightCms;
		this.gcdSafeDwrWidthCms = gcdSafeDwrWidthCms;
		this.gcdSafeDwrAnchoredFlag = gcdSafeDwrAnchoredFlag;
		this.gcdCashResEmpEName = gcdCashResEmpEName;
		this.gcdCashResEmpAName = gcdCashResEmpAName;
		this.gcdCashResOccupation = gcdCashResOccupation;
		this.gcdCashResAmt = gcdCashResAmt;
		this.gcdPreparedBy = gcdPreparedBy;
		this.gcdPreparedDt = gcdPreparedDt;
		this.gcdModifiedBy = gcdModifiedBy;
		this.gcdModifiedDt = gcdModifiedDt;
		this.gcdStatus = gcdStatus;
		
	}

	public TTrnGaccCashDetailsQuoId getId() {
		return this.id;
	}

	public void setId(TTrnGaccCashDetailsQuoId id) {
		this.id = id;
	}

	public long getGcdGchId() {
		return this.gcdGchId;
	}

	public void setGcdGchId(long gcdGchId) {
		this.gcdGchId = gcdGchId;
	}

	public long getGcdPolPolicyId() {
		return this.gcdPolPolicyId;
	}

	public void setGcdPolPolicyId(long gcdPolPolicyId) {
		this.gcdPolPolicyId = gcdPolPolicyId;
	}

	public long getGcdPolEndtId() {
		return this.gcdPolEndtId;
	}

	public void setGcdPolEndtId(long gcdPolEndtId) {
		this.gcdPolEndtId = gcdPolEndtId;
	}

	public Date getGcdValidityExpiryDate() {
		return this.gcdValidityExpiryDate;
	}

	public void setGcdValidityExpiryDate(Date gcdValidityExpiryDate) {
		this.gcdValidityExpiryDate = gcdValidityExpiryDate;
	}

	public String getGcdSafeDwrMake() {
		return this.gcdSafeDwrMake;
	}

	public void setGcdSafeDwrMake(String gcdSafeDwrMake) {
		this.gcdSafeDwrMake = gcdSafeDwrMake;
	}

	public BigDecimal getGcdSafeDwrWeightKg() {
		return this.gcdSafeDwrWeightKg;
	}

	public void setGcdSafeDwrWeightKg(BigDecimal gcdSafeDwrWeightKg) {
		this.gcdSafeDwrWeightKg = gcdSafeDwrWeightKg;
	}

	public BigDecimal getGcdSafeDwrHeightCms() {
		return this.gcdSafeDwrHeightCms;
	}

	public void setGcdSafeDwrHeightCms(BigDecimal gcdSafeDwrHeightCms) {
		this.gcdSafeDwrHeightCms = gcdSafeDwrHeightCms;
	}

	public BigDecimal getGcdSafeDwrWidthCms() {
		return this.gcdSafeDwrWidthCms;
	}

	public void setGcdSafeDwrWidthCms(BigDecimal gcdSafeDwrWidthCms) {
		this.gcdSafeDwrWidthCms = gcdSafeDwrWidthCms;
	}

	public String getGcdSafeDwrAnchoredFlag() {
		return this.gcdSafeDwrAnchoredFlag;
	}

	public void setGcdSafeDwrAnchoredFlag(String gcdSafeDwrAnchoredFlag) {
		this.gcdSafeDwrAnchoredFlag = gcdSafeDwrAnchoredFlag;
	}

	public String getGcdCashResEmpEName() {
		return this.gcdCashResEmpEName;
	}

	public void setGcdCashResEmpEName(String gcdCashResEmpEName) {
		this.gcdCashResEmpEName = gcdCashResEmpEName;
	}

	public String getGcdCashResEmpAName() {
		return this.gcdCashResEmpAName;
	}

	public void setGcdCashResEmpAName(String gcdCashResEmpAName) {
		this.gcdCashResEmpAName = gcdCashResEmpAName;
	}

	public String getGcdCashResOccupation() {
		return this.gcdCashResOccupation;
	}

	public void setGcdCashResOccupation(String gcdCashResOccupation) {
		this.gcdCashResOccupation = gcdCashResOccupation;
	}

	public BigDecimal getGcdCashResAmt() {
		return this.gcdCashResAmt;
	}

	public void setGcdCashResAmt(BigDecimal gcdCashResAmt) {
		this.gcdCashResAmt = gcdCashResAmt;
	}

	public Integer getGcdPreparedBy() {
		return this.gcdPreparedBy;
	}

	public void setGcdPreparedBy(Integer gcdPreparedBy) {
		this.gcdPreparedBy = gcdPreparedBy;
	}

	public Date getGcdPreparedDt() {
		return this.gcdPreparedDt;
	}

	public void setGcdPreparedDt(Date gcdPreparedDt) {
		this.gcdPreparedDt = gcdPreparedDt;
	}

	public Integer getGcdModifiedBy() {
		return this.gcdModifiedBy;
	}

	public void setGcdModifiedBy(Integer gcdModifiedBy) {
		this.gcdModifiedBy = gcdModifiedBy;
	}

	public Date getGcdModifiedDt() {
		return this.gcdModifiedDt;
	}

	public void setGcdModifiedDt(Date gcdModifiedDt) {
		this.gcdModifiedDt = gcdModifiedDt;
	}
	
	@Override
	public void setEndtId( Long endtId ){
		setGcdPolEndtId( endtId );
	}
	
	@Override
	public POJOId getPOJOId(){
		return this.getId();
	}
	
	@Override
	public void setPOJOId( POJOId id ){
		setId( (TTrnGaccCashDetailsQuoId) id );
	}
	
	@Override
	public void setValidityExpiryDate( Date ved ){
		setGcdValidityExpiryDate( ved );
	}
	
	@Override
	public void setValidityStartDate( Date vsd ){
		if( !Utils.isEmpty( getId() ) ) getId().setGcdValidityStartDate( vsd );
	}

	
	@Override
	public int getStatus(){
		 return gcdStatus;
	}

	@Override
	public void setStatus( Integer status ){
		gcdStatus=status.byteValue();
	}

	public Byte getGcdStatus(){
		return gcdStatus;
	}

	public void setGcdStatus( Byte gcdStatus ){
		this.gcdStatus = gcdStatus;
	}

	@Override
	public void setPreparedDate( Date preparedDate ){
		setGcdPreparedDt( preparedDate );
	}
	
	@Override
	public Date getPreparedDate(){
		return getGcdPreparedDt();
	}
}
