package com.rsaame.pas.dao.model;

// Generated May 20, 2013 11:08:40 AM by Hibernate Tools 3.4.0.CR1

/**
 * TMasPromoDiscCover generated by hbm2java
 */
public class TMasPromoDiscCover implements java.io.Serializable {

	private TMasPromoDiscCoverId id;
	//private TMasPromotionalCode TMasPromotionalCode;

	
	/*public TMasPromoDiscCover(TMasPromoDiscCoverId id,
			TMasPromotionalCode TMasPromotionalCode) {
		this.id = id;
		this.TMasPromotionalCode = TMasPromotionalCode;
	}
*/
	public TMasPromoDiscCoverId getId() {
		return this.id;
	}

	public void setId(TMasPromoDiscCoverId id) {
		this.id = id;
	}

	public TMasPromoDiscCover() {
	}

	public TMasPromoDiscCover(TMasPromoDiscCoverId id) {
		this.id = id;
	}

	/*public TMasPromotionalCode getTMasPromotionalCode() {
		return this.TMasPromotionalCode;
	}

	public void setTMasPromotionalCode(TMasPromotionalCode TMasPromotionalCode) {
		this.TMasPromotionalCode = TMasPromotionalCode;
	}*/

}
