package com.rsaame.pas.dao.model;

// Generated Jun 26, 2012 3:09:02 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.mindtree.ruc.cmn.utils.Utils;
import com.rsaame.pas.cmn.pojo.POJO;
import com.rsaame.pas.cmn.pojo.POJOId;

/**
 * TTrnGaccUnnamedPersonQuo generated by hbm2java
 */
public class TTrnGaccUnnamedPersonQuo extends POJO implements java.io.Serializable {

	private TTrnGaccUnnamedPersonQuoId id;
	private Long gupPolicyId;
	private Long gupBasicRiskId;
	private Integer gupRskCode;
	private Integer gupOcCode;
	private Integer gupRcCode;
	private Integer gupNoOfPerson;
	private BigDecimal gupSumInsured;
	private Byte gupStatus;
	private Date gupValidityExpiryDate;
	private Long gupEndtId;
	private Integer gupRiRskCode;
	private Integer gupBasicRskCode;
	private BigDecimal gupSalary;
	private Integer gupPreparedBy;
	private Date gupPreparedDt;
	private Integer gupModifiedBy;
	private Date gupModifiedDt;
	private Date gupStartDate;
	private Date gupEndDate;
	private String gupDescription;
	private Long gupBldId;
	private BigDecimal gupAgrLmt;

	public TTrnGaccUnnamedPersonQuo() {
	}

	public TTrnGaccUnnamedPersonQuo(TTrnGaccUnnamedPersonQuoId id,
			Date gupValidityExpiryDate) {
		this.id = id;
		this.gupValidityExpiryDate = gupValidityExpiryDate;
	}

	public TTrnGaccUnnamedPersonQuo(TTrnGaccUnnamedPersonQuoId id,
			Long gupPolicyId, Long gupBasicRiskId, Integer gupRskCode,
			Integer gupOcCode, Integer gupRcCode, Integer gupNoOfPerson,
			BigDecimal gupSumInsured, Byte gupStatus,
			Date gupValidityExpiryDate, Long gupEndtId, Integer gupRiRskCode,
			Integer gupBasicRskCode, BigDecimal gupSalary,
			Integer gupPreparedBy, Date gupPreparedDt, Integer gupModifiedBy,
			Date gupModifiedDt, Date gupStartDate, Date gupEndDate,
			String gupDescription, Long gupBldId, BigDecimal gupAgrLmt) {
		this.id = id;
		this.gupPolicyId = gupPolicyId;
		this.gupBasicRiskId = gupBasicRiskId;
		this.gupRskCode = gupRskCode;
		this.gupOcCode = gupOcCode;
		this.gupRcCode = gupRcCode;
		this.gupNoOfPerson = gupNoOfPerson;
		this.gupSumInsured = gupSumInsured;
		this.gupStatus = gupStatus;
		this.gupValidityExpiryDate = gupValidityExpiryDate;
		this.gupEndtId = gupEndtId;
		this.gupRiRskCode = gupRiRskCode;
		this.gupBasicRskCode = gupBasicRskCode;
		this.gupSalary = gupSalary;
		this.gupPreparedBy = gupPreparedBy;
		this.gupPreparedDt = gupPreparedDt;
		this.gupModifiedBy = gupModifiedBy;
		this.gupModifiedDt = gupModifiedDt;
		this.gupStartDate = gupStartDate;
		this.gupEndDate = gupEndDate;
		this.gupDescription = gupDescription;
		this.gupBldId = gupBldId;
		this.gupAgrLmt = gupAgrLmt;
	}

	public TTrnGaccUnnamedPersonQuoId getId() {
		return this.id;
	}

	public void setId(TTrnGaccUnnamedPersonQuoId id) {
		this.id = id;
	}

	public Long getGupPolicyId() {
		return this.gupPolicyId;
	}

	public void setGupPolicyId(Long gupPolicyId) {
		this.gupPolicyId = gupPolicyId;
	}

	public Long getGupBasicRiskId() {
		return this.gupBasicRiskId;
	}

	public void setGupBasicRiskId(Long gupBasicRiskId) {
		this.gupBasicRiskId = gupBasicRiskId;
	}

	public Integer getGupRskCode() {
		return this.gupRskCode;
	}

	public void setGupRskCode(Integer gupRskCode) {
		this.gupRskCode = gupRskCode;
	}

	public Integer getGupOcCode() {
		return this.gupOcCode;
	}

	public void setGupOcCode(Integer gupOcCode) {
		this.gupOcCode = gupOcCode;
	}

	public Integer getGupRcCode() {
		return this.gupRcCode;
	}

	public void setGupRcCode(Integer gupRcCode) {
		this.gupRcCode = gupRcCode;
	}

	public Integer getGupNoOfPerson() {
		return this.gupNoOfPerson;
	}

	public void setGupNoOfPerson(Integer gupNoOfPerson) {
		this.gupNoOfPerson = gupNoOfPerson;
	}

	public BigDecimal getGupSumInsured() {
		return this.gupSumInsured;
	}

	public void setGupSumInsured(BigDecimal gupSumInsured) {
		this.gupSumInsured = gupSumInsured;
	}

	public Byte getGupStatus() {
		return this.gupStatus;
	}

	public void setGupStatus(Byte gupStatus) {
		this.gupStatus = gupStatus;
	}

	public Date getGupValidityExpiryDate() {
		return this.gupValidityExpiryDate;
	}

	public void setGupValidityExpiryDate(Date gupValidityExpiryDate) {
		this.gupValidityExpiryDate = gupValidityExpiryDate;
	}

	public Long getGupEndtId() {
		return this.gupEndtId;
	}

	public void setGupEndtId(Long gupEndtId) {
		this.gupEndtId = gupEndtId;
	}

	public Integer getGupRiRskCode() {
		return this.gupRiRskCode;
	}

	public void setGupRiRskCode(Integer gupRiRskCode) {
		this.gupRiRskCode = gupRiRskCode;
	}

	public Integer getGupBasicRskCode() {
		return this.gupBasicRskCode;
	}

	public void setGupBasicRskCode(Integer gupBasicRskCode) {
		this.gupBasicRskCode = gupBasicRskCode;
	}

	public BigDecimal getGupSalary() {
		return this.gupSalary;
	}

	public void setGupSalary(BigDecimal gupSalary) {
		this.gupSalary = gupSalary;
	}

	public Integer getGupPreparedBy() {
		return this.gupPreparedBy;
	}

	public void setGupPreparedBy(Integer gupPreparedBy) {
		this.gupPreparedBy = gupPreparedBy;
	}

	public Date getGupPreparedDt() {
		return this.gupPreparedDt;
	}

	public void setGupPreparedDt(Date gupPreparedDt) {
		this.gupPreparedDt = gupPreparedDt;
	}

	public Integer getGupModifiedBy() {
		return this.gupModifiedBy;
	}

	public void setGupModifiedBy(Integer gupModifiedBy) {
		this.gupModifiedBy = gupModifiedBy;
	}

	public Date getGupModifiedDt() {
		return this.gupModifiedDt;
	}

	public void setGupModifiedDt(Date gupModifiedDt) {
		this.gupModifiedDt = gupModifiedDt;
	}

	public Date getGupStartDate() {
		return this.gupStartDate;
	}

	public void setGupStartDate(Date gupStartDate) {
		this.gupStartDate = gupStartDate;
	}

	public Date getGupEndDate() {
		return this.gupEndDate;
	}

	public void setGupEndDate(Date gupEndDate) {
		this.gupEndDate = gupEndDate;
	}

	public String getGupDescription() {
		return this.gupDescription;
	}

	public void setGupDescription(String gupDescription) {
		this.gupDescription = gupDescription;
	}

	public Long getGupBldId() {
		return this.gupBldId;
	}

	public void setGupBldId(Long gupBldId) {
		this.gupBldId = gupBldId;
	}

	public BigDecimal getGupAgrLmt() {
		return this.gupAgrLmt;
	}

	public void setGupAgrLmt(BigDecimal gupAgrLmt) {
		this.gupAgrLmt = gupAgrLmt;
	}
	
	@Override
	public POJOId getPOJOId(){
		return this.getId();
	}

	@Override
	public void setPOJOId( POJOId id ){
		setId( (TTrnGaccUnnamedPersonQuoId) id );
	}
	
	@Override
	public void setValidityExpiryDate( Date ved ){
		setGupValidityExpiryDate( ved );
	}
	
	@Override
	public void setValidityStartDate( Date vsd ){
		if( !Utils.isEmpty( getId() ) ) getId().setGupValidityStartDate( vsd );
	}
	
	@Override
	public int getStatus() {
		return getGupStatus();
	}

	@Override
	public void setStatus(Integer status) {
		setGupStatus(status.byteValue());
	}

	@Override
	public void setEndtId(Long endtId) {
		setGupEndtId(endtId);
	}
	
	@Override
	public void setPreparedDate( Date preparedDate ){
		setGupPreparedDt( preparedDate );
	}
	
	@Override
	public Date getPreparedDate(){
		return getGupPreparedDt();
	}
}
