package com.rsaame.pas.dao.model;

import java.util.Date;

import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapperId;

// Generated Feb 27, 2012 4:17:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * TTrnPolicyQuoId generated by hbm2java
 */
public class TTrnPolicyQuoId implements java.io.Serializable,POJOWrapperId {

	private long polPolicyId;
	private long polEndtId;

	public TTrnPolicyQuoId() {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	public TTrnPolicyQuoId(long polPolicyId, long polEndtId) {
		this.polPolicyId = polPolicyId;
		this.polEndtId = polEndtId;
	}

	public long getPolPolicyId() {
		return this.polPolicyId;
	}

	public void setPolPolicyId(long polPolicyId) {
		this.polPolicyId = polPolicyId;
	}

	public long getPolEndtId() {
		return this.polEndtId;
	}

	public void setPolEndtId(long polEndtId) {
		this.polEndtId = polEndtId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTrnPolicyQuoId))
			return false;
		TTrnPolicyQuoId castOther = (TTrnPolicyQuoId) other;

		return (this.getPolPolicyId() == castOther.getPolPolicyId())
				&& (this.getPolEndtId() == castOther.getPolEndtId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPolPolicyId();
		result = 37 * result + (int) this.getPolEndtId();
		return result;
	}

	/* 
	 * sets the id (like bldId , contentId etc ). left empty as there is no other id except PolicyId 
	 * which is taken care in a separate method setPolicyId().
	 */
	@Override
	public void setId(Long id) {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	/* 
	 * sets the validity start date. left empty as there is no field as validityStartDate in this POJO.
	 */
	@Override
	public void setVSD(Date vsd) {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD 

	}

	@Override
	public void setEndtId(Long endtId) {
		setPolEndtId( endtId );		
	}

	@Override
	public void setPolicyId(Long policyId) {
		setPolPolicyId( policyId );		
	}

	@Override
	public Long getId() {
		return getPolPolicyId();
	}

	@Override
	public Date getVSD() {
		return null;
	}

	@Override
	public Long getEndtId() {
		return getPolEndtId();
	}

	@Override
	public Long getPolicyId() {
		return getPolPolicyId();
	}

	@Override
	public String toStringPojoId(){
		return toString();
	}

	@Override
	public String toString(){
		return "TTrnPolicyId [polPolicyId=" + polPolicyId + ", polEndtId=" + polEndtId + "]";
	}
	
}
