package com.rsaame.pas.dao.model;

// Generated Jan 18, 2012 5:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.mindtree.ruc.cmn.utils.Utils;
import com.rsaame.pas.cmn.pojo.POJO;
import com.rsaame.pas.cmn.pojo.POJOId;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapper;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapperId;

/**
 * TTrnContentQuo generated by hbm2java
 */
public class TTrnContentQuo extends POJOWrapper implements java.io.Serializable{

	private TTrnContentQuoId id;
	private long cntPolicyId;
	private Long cntBasicRiskId;
	private Integer cntRskCode;
	private Integer cntCategory;
	private String cntDescription;
	private BigDecimal cntSumInsured;
	private Date cntValidityExpiryDate;
	private Integer cntDeclNo;
	private Date cntDeclDate;
	private Integer cntBasicRskCode;
	private Long cntEndtId;
	private Integer cntRiRskCode;
	private Byte cntStatus;
	private Integer cntPreparedBy;
	private Date cntPreparedDt;
	private Integer cntModifiedBy;
	private Date cntModifiedDt;
	private Date cntStartDate;
	private Date cntEndDate;
	private BigDecimal cntMplFire;
	private BigDecimal cntMplFlood;
	private BigDecimal cntMplFirePerc;
	private BigDecimal cntMplFloodPerc;
	private String cntADescription;
	private Long cntRiskDtl;
	private Integer cntRiskSubDtl;
	private String cntAddress;
	private Integer cntTradeCode;
	private BigDecimal cntQty;
	private Short cntNoChamber;
	private Integer cntEqCode;
	private Short cntManufacture;
	private Short cntYearOfMan;
	private String cntBiCoverDesc;
	private Long cntEqptSerialNo;

	public TTrnContentQuo() {
	}

	public TTrnContentQuo(TTrnContentQuoId id, long cntPolicyId,
			Date cntValidityExpiryDate) {
		this.id = id;
		this.cntPolicyId = cntPolicyId;
		this.cntValidityExpiryDate = cntValidityExpiryDate;
	}

	public TTrnContentQuo(TTrnContentQuoId id, long cntPolicyId,
			Long cntBasicRiskId, Integer cntRskCode, Integer cntCategory,
			String cntDescription, BigDecimal cntSumInsured,
			Date cntValidityExpiryDate, Integer cntDeclNo, Date cntDeclDate,
			Integer cntBasicRskCode, Long cntEndtId, Integer cntRiRskCode,
			Byte cntStatus, Integer cntPreparedBy, Date cntPreparedDt,
			Integer cntModifiedBy, Date cntModifiedDt, Date cntStartDate,
			Date cntEndDate, BigDecimal cntMplFire, BigDecimal cntMplFlood,
			BigDecimal cntMplFirePerc, BigDecimal cntMplFloodPerc,
			String cntADescription, Long cntRiskDtl, Integer cntRiskSubDtl,
			String cntAddress, Integer cntTradeCode, BigDecimal cntQty,
			Short cntNoChamber, Integer cntEqCode, Short cntManufacture,
			Short cntYearOfMan, String cntBiCoverDesc, Long cntEqptSerialNo) {
		this.id = id;
		this.cntPolicyId = cntPolicyId;
		this.cntBasicRiskId = cntBasicRiskId;
		this.cntRskCode = cntRskCode;
		this.cntCategory = cntCategory;
		this.cntDescription = cntDescription;
		this.cntSumInsured = cntSumInsured;
		this.cntValidityExpiryDate = cntValidityExpiryDate;
		this.cntDeclNo = cntDeclNo;
		this.cntDeclDate = cntDeclDate;
		this.cntBasicRskCode = cntBasicRskCode;
		this.cntEndtId = cntEndtId;
		this.cntRiRskCode = cntRiRskCode;
		this.cntStatus = cntStatus;
		this.cntPreparedBy = cntPreparedBy;
		this.cntPreparedDt = cntPreparedDt;
		this.cntModifiedBy = cntModifiedBy;
		this.cntModifiedDt = cntModifiedDt;
		this.cntStartDate = cntStartDate;
		this.cntEndDate = cntEndDate;
		this.cntMplFire = cntMplFire;
		this.cntMplFlood = cntMplFlood;
		this.cntMplFirePerc = cntMplFirePerc;
		this.cntMplFloodPerc = cntMplFloodPerc;
		this.cntADescription = cntADescription;
		this.cntRiskDtl = cntRiskDtl;
		this.cntRiskSubDtl = cntRiskSubDtl;
		this.cntAddress = cntAddress;
		this.cntTradeCode = cntTradeCode;
		this.cntQty = cntQty;
		this.cntNoChamber = cntNoChamber;
		this.cntEqCode = cntEqCode;
		this.cntManufacture = cntManufacture;
		this.cntYearOfMan = cntYearOfMan;
		this.cntBiCoverDesc = cntBiCoverDesc;
		this.cntEqptSerialNo = cntEqptSerialNo;
	}

	public TTrnContentQuoId getId() {
		return this.id;
	}

	public void setId(TTrnContentQuoId id) {
		this.id = id;
	}

	public long getCntPolicyId() {
		return this.cntPolicyId;
	}

	public void setCntPolicyId(long cntPolicyId) {
		this.cntPolicyId = cntPolicyId;
	}

	public Long getCntBasicRiskId() {
		return this.cntBasicRiskId;
	}

	public void setCntBasicRiskId(Long cntBasicRiskId) {
		this.cntBasicRiskId = cntBasicRiskId;
	}

	public Integer getCntRskCode() {
		return this.cntRskCode;
	}

	public void setCntRskCode(Integer cntRskCode) {
		this.cntRskCode = cntRskCode;
	}

	public Integer getCntCategory() {
		return this.cntCategory;
	}

	public void setCntCategory(Integer cntCategory) {
		this.cntCategory = cntCategory;
	}

	public String getCntDescription() {
		return this.cntDescription;
	}

	public void setCntDescription(String cntDescription) {
		this.cntDescription = cntDescription;
	}

	public BigDecimal getCntSumInsured() {
		return this.cntSumInsured;
	}

	public void setCntSumInsured(BigDecimal cntSumInsured) {
		this.cntSumInsured = cntSumInsured;
	}

	public Date getCntValidityExpiryDate() {
		return this.cntValidityExpiryDate;
	}

	public void setCntValidityExpiryDate(Date cntValidityExpiryDate) {
		this.cntValidityExpiryDate = cntValidityExpiryDate;
	}

	public Integer getCntDeclNo() {
		return this.cntDeclNo;
	}

	public void setCntDeclNo(Integer cntDeclNo) {
		this.cntDeclNo = cntDeclNo;
	}

	public Date getCntDeclDate() {
		return this.cntDeclDate;
	}

	public void setCntDeclDate(Date cntDeclDate) {
		this.cntDeclDate = cntDeclDate;
	}

	public Integer getCntBasicRskCode() {
		return this.cntBasicRskCode;
	}

	public void setCntBasicRskCode(Integer cntBasicRskCode) {
		this.cntBasicRskCode = cntBasicRskCode;
	}

	public Long getCntEndtId() {
		return this.cntEndtId;
	}

	public void setCntEndtId(Long cntEndtId) {
		this.cntEndtId = cntEndtId;
	}

	public Integer getCntRiRskCode() {
		return this.cntRiRskCode;
	}

	public void setCntRiRskCode(Integer cntRiRskCode) {
		this.cntRiRskCode = cntRiRskCode;
	}

	public Byte getCntStatus() {
		return this.cntStatus;
	}

	public void setCntStatus(Byte cntStatus) {
		this.cntStatus = cntStatus;
	}

	public Integer getCntPreparedBy() {
		return this.cntPreparedBy;
	}

	public void setCntPreparedBy(Integer cntPreparedBy) {
		this.cntPreparedBy = cntPreparedBy;
	}

	public Date getCntPreparedDt() {
		return this.cntPreparedDt;
	}

	public void setCntPreparedDt(Date cntPreparedDt) {
		this.cntPreparedDt = cntPreparedDt;
	}

	public Integer getCntModifiedBy() {
		return this.cntModifiedBy;
	}

	public void setCntModifiedBy(Integer cntModifiedBy) {
		this.cntModifiedBy = cntModifiedBy;
	}

	public Date getCntModifiedDt() {
		return this.cntModifiedDt;
	}

	public void setCntModifiedDt(Date cntModifiedDt) {
		this.cntModifiedDt = cntModifiedDt;
	}

	public Date getCntStartDate() {
		return this.cntStartDate;
	}

	public void setCntStartDate(Date cntStartDate) {
		this.cntStartDate = cntStartDate;
	}

	public Date getCntEndDate() {
		return this.cntEndDate;
	}

	public void setCntEndDate(Date cntEndDate) {
		this.cntEndDate = cntEndDate;
	}

	public BigDecimal getCntMplFire() {
		return this.cntMplFire;
	}

	public void setCntMplFire(BigDecimal cntMplFire) {
		this.cntMplFire = cntMplFire;
	}

	public BigDecimal getCntMplFlood() {
		return this.cntMplFlood;
	}

	public void setCntMplFlood(BigDecimal cntMplFlood) {
		this.cntMplFlood = cntMplFlood;
	}

	public BigDecimal getCntMplFirePerc() {
		return this.cntMplFirePerc;
	}

	public void setCntMplFirePerc(BigDecimal cntMplFirePerc) {
		this.cntMplFirePerc = cntMplFirePerc;
	}

	public BigDecimal getCntMplFloodPerc() {
		return this.cntMplFloodPerc;
	}

	public void setCntMplFloodPerc(BigDecimal cntMplFloodPerc) {
		this.cntMplFloodPerc = cntMplFloodPerc;
	}

	public String getCntADescription() {
		return this.cntADescription;
	}

	public void setCntADescription(String cntADescription) {
		this.cntADescription = cntADescription;
	}

	public Long getCntRiskDtl() {
		return this.cntRiskDtl;
	}

	public void setCntRiskDtl(Long cntRiskDtl) {
		this.cntRiskDtl = cntRiskDtl;
	}

	public Integer getCntRiskSubDtl() {
		return this.cntRiskSubDtl;
	}

	public void setCntRiskSubDtl(Integer cntRiskSubDtl) {
		this.cntRiskSubDtl = cntRiskSubDtl;
	}

	public String getCntAddress() {
		return this.cntAddress;
	}

	public void setCntAddress(String cntAddress) {
		this.cntAddress = cntAddress;
	}

	public Integer getCntTradeCode() {
		return this.cntTradeCode;
	}

	public void setCntTradeCode(Integer cntTradeCode) {
		this.cntTradeCode = cntTradeCode;
	}

	public BigDecimal getCntQty() {
		return this.cntQty;
	}

	public void setCntQty(BigDecimal cntQty) {
		this.cntQty = cntQty;
	}

	public Short getCntNoChamber() {
		return this.cntNoChamber;
	}

	public void setCntNoChamber(Short cntNoChamber) {
		this.cntNoChamber = cntNoChamber;
	}

	public Integer getCntEqCode() {
		return this.cntEqCode;
	}

	public void setCntEqCode(Integer cntEqCode) {
		this.cntEqCode = cntEqCode;
	}

	public Short getCntManufacture() {
		return this.cntManufacture;
	}

	public void setCntManufacture(Short cntManufacture) {
		this.cntManufacture = cntManufacture;
	}

	public Short getCntYearOfMan() {
		return this.cntYearOfMan;
	}

	public void setCntYearOfMan(Short cntYearOfMan) {
		this.cntYearOfMan = cntYearOfMan;
	}

	public String getCntBiCoverDesc() {
		return this.cntBiCoverDesc;
	}

	public void setCntBiCoverDesc(String cntBiCoverDesc) {
		this.cntBiCoverDesc = cntBiCoverDesc;
	}

	public Long getCntEqptSerialNo() {
		return this.cntEqptSerialNo;
	}

	public void setCntEqptSerialNo(Long cntEqptSerialNo) {
		this.cntEqptSerialNo = cntEqptSerialNo;
	}
	
	@Override
	public int getStatus(){
		return getCntStatus();
	}
	
	@Override
	public void setEndtId( Long endtId ){
		setCntEndtId( endtId );
	}
	
	@Override
	public POJOId getPOJOId(){
		return this.getId();
	}
	
	@Override
	public void setPOJOId( POJOId id ){
		setId( (TTrnContentQuoId) id );
	}
	
	@Override
	public void setValidityExpiryDate( Date ved ){
		setCntValidityExpiryDate( ved );
	}
	
	@Override
	public void setValidityStartDate( Date vsd ){
		//setCntStartDate( vsd );
		//Commented above line and added new line -- Fix for content start date going wrongly during versioning
		if(!Utils.isEmpty(getId())) getId().setCntValidityStartDate(vsd);
	}
	
	@Override
	public void setStatus(Integer status) {
		setCntStatus( status.byteValue() );
	}

	/* Not Applicable.*/
	@Override
	public void setEndtNo(Long endtNo) {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	@Override
	public void setPreparedBy(Integer preparedBy) {
		setCntPreparedBy(preparedBy);
	}

	@Override
	public void setPreparedDt(Date preparedDt) {
		setCntPreparedDt(preparedDt);
	}

	@Override
	public void setModifiedBy(Integer modifiedBy) {
		setCntModifiedBy(modifiedBy);
	}

	@Override
	public void setModifiedDt(Date modifiedDt) {
		setCntModifiedDt(modifiedDt);
	}

	/* Set TTrnContentQuoId.*/
	@Override
	public void setPOJOWrapperId( POJOWrapperId id ){
		setId( (TTrnContentQuoId)id );
	}

	/* Get TTrnContentQuoId.*/
	@Override
	public POJOWrapperId getPOJOWrapperId(){
		return getId();
	}

	@Override
	public void setStatus( int status ){
		setCntStatus( Integer.valueOf( status ).byteValue() );
	}

	@Override
	public Integer getPreparedBy(){
		return getCntPreparedBy();
	}

	@Override
	public Date getPreparedDt(){
		return getCntPreparedDt();
	}

	@Override
	public Integer getModifiedBy(){
		return getCntModifiedBy();
	}

	@Override
	public Date getModifiedDt(){
		return getCntModifiedDt();
	}

	@Override
	public void setPreparedDate( Date preparedDate ){
		setCntPreparedDt( preparedDate );
	}
	
	@Override
	public Date getPreparedDate(){
		return getCntPreparedDt();
	}
}
