package com.rsaame.pas.dao.model;

import java.util.Date;

// Generated Apr 18, 2012 3:51:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * VTrnPasGetEndtText generated by hbm2java
 */
public class VTrnPasGetEndtText implements java.io.Serializable {

	private VTrnPasGetEndtTextId id;
	private String endtText;
	private Integer endtPreparedBy;
	/*private Date endtPreparedDt;*/
	private Integer endtModifiedBy;
	private Date endtModifiedDt;
	private Integer edlSecId;
	

	
	public VTrnPasGetEndtText() {
	}

	public VTrnPasGetEndtText( VTrnPasGetEndtTextId id, String endtText ){
		super();
		this.id = id;
		this.endtText = endtText;
	}



	public VTrnPasGetEndtTextId getId() {
		return this.id;
	}

	public void setId(VTrnPasGetEndtTextId id) {
		this.id = id;
	}

	public String getEndtText() {
		return this.endtText;
	}

	public void setEndtText(String endtText) {
		this.endtText = endtText;
	}

	public Integer getEndtPreparedBy() {
		return endtPreparedBy;
	}

	public void setEndtPreparedBy(Integer endtPreparedBy) {
		this.endtPreparedBy = endtPreparedBy;
	}

	/*public Date getEndtPreparedDt() {
		return endtPreparedDt;
	}

	public void setEndtPreparedDt(Date endtPreparedDt) {
		this.endtPreparedDt = endtPreparedDt;
	}*/

	public Integer getEndtModifiedBy() {
		return endtModifiedBy;
	}

	public void setEndtModifiedBy(Integer endtModifiedBy) {
		this.endtModifiedBy = endtModifiedBy;
	}

	public Date getEndtModifiedDt() {
		return endtModifiedDt;
	}

	public void setEndtModifiedDt(Date endtModifiedDt) {
		this.endtModifiedDt = endtModifiedDt;
	}

	public Integer getEdlSecId() {
		return edlSecId;
	}

	public void setEdlSecId(Integer edlSecId) {
		this.edlSecId = edlSecId;
	}

	
}
