package com.rsaame.pas.dao.model;

// Generated Jul 10, 2012 6:11:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.rsaame.pas.cmn.pojo.POJO;
import com.rsaame.pas.cmn.pojo.POJOId;

/**
 * TTrnMarineTransit generated by hbm2java
 */
public class TTrnMarineTransitQuo extends POJO implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private TTrnMarineTransitQuoId id;
    private Short mtModeOfTransit;
    private String mtAStartPlace;
    private String mtEStartPlace;
    private Integer mtStartCity;
    private Integer mtStartCountry;
    private String mtADestinationPlace;
    private String mtEDestinationPlace;
    private Integer mtDestinationCity;
    private Integer mtDestinationCountry;
    private String mtABlAwbLrNo;
    private String mtEBlAwbLrNo;
    private Date mtBlAwbLrDate;
    private Date mtDepartureDate;
    private Short mtStoragePeriod;
    private Integer mtMtlCode;
    private Byte mtStatus;
    //private Date mtValidityStartDate;
    private Date mtValidityExpiryDate;
    private Integer mtPreparedBy;
    private Date mtPreparedDt;
    private Integer mtModifiedBy;
    private Date mtModifiedDt;
    private Date mtStartDate;
    private Date mtEndDate;
    private Long mtBldId;

    public TTrnMarineTransitQuo() {
    	//SONARFIX--26-04-2018---DO NOTHING IN METHOD	
    }

    public TTrnMarineTransitQuo(TTrnMarineTransitQuoId id,
	    Date mtValidityExpiryDate) {
	this.id = id;
	this.mtValidityExpiryDate = mtValidityExpiryDate;
    }

    public TTrnMarineTransitQuo(TTrnMarineTransitQuoId id,
	    Short mtModeOfTransit, String mtAStartPlace, String mtEStartPlace,
	    Integer mtStartCity, Integer mtStartCountry,
	    String mtADestinationPlace, String mtEDestinationPlace,
	    Integer mtDestinationCity, Integer mtDestinationCountry,
	    String mtABlAwbLrNo, String mtEBlAwbLrNo, Date mtBlAwbLrDate,
	    Date mtDepartureDate, Short mtStoragePeriod, Integer mtMtlCode,
	    Byte mtStatus, Date mtValidityStartDate, Date mtValidityExpiryDate,
	    Integer mtPreparedBy, Date mtPreparedDt, Integer mtModifiedBy,
	    Date mtModifiedDt, Date mtStartDate, Date mtEndDate, Long mtBldId) {
	this.id = id;
	this.mtModeOfTransit = mtModeOfTransit;
	this.mtAStartPlace = mtAStartPlace;
	this.mtEStartPlace = mtEStartPlace;
	this.mtStartCity = mtStartCity;
	this.mtStartCountry = mtStartCountry;
	this.mtADestinationPlace = mtADestinationPlace;
	this.mtEDestinationPlace = mtEDestinationPlace;
	this.mtDestinationCity = mtDestinationCity;
	this.mtDestinationCountry = mtDestinationCountry;
	this.mtABlAwbLrNo = mtABlAwbLrNo;
	this.mtEBlAwbLrNo = mtEBlAwbLrNo;
	this.mtBlAwbLrDate = mtBlAwbLrDate;
	this.mtDepartureDate = mtDepartureDate;
	this.mtStoragePeriod = mtStoragePeriod;
	this.mtMtlCode = mtMtlCode;
	this.mtStatus = mtStatus;
	this.mtValidityExpiryDate = mtValidityExpiryDate;
	this.mtPreparedBy = mtPreparedBy;
	this.mtPreparedDt = mtPreparedDt;
	this.mtModifiedBy = mtModifiedBy;
	this.mtModifiedDt = mtModifiedDt;
	this.mtStartDate = mtStartDate;
	this.mtEndDate = mtEndDate;
	this.mtBldId = mtBldId;
    }

    public TTrnMarineTransitQuoId getId() {
	return this.id;
    }

    public void setId(TTrnMarineTransitQuoId id) {
	this.id = id;
    }

    public Short getMtModeOfTransit() {
	return this.mtModeOfTransit;
    }

    public void setMtModeOfTransit(Short mtModeOfTransit) {
	this.mtModeOfTransit = mtModeOfTransit;
    }

    public String getMtAStartPlace() {
	return this.mtAStartPlace;
    }

    public void setMtAStartPlace(String mtAStartPlace) {
	this.mtAStartPlace = mtAStartPlace;
    }

    public String getMtEStartPlace() {
	return this.mtEStartPlace;
    }

    public void setMtEStartPlace(String mtEStartPlace) {
	this.mtEStartPlace = mtEStartPlace;
    }

    public Integer getMtStartCity() {
	return this.mtStartCity;
    }

    public void setMtStartCity(Integer mtStartCity) {
	this.mtStartCity = mtStartCity;
    }

    public Integer getMtStartCountry() {
	return this.mtStartCountry;
    }

    public void setMtStartCountry(Integer mtStartCountry) {
	this.mtStartCountry = mtStartCountry;
    }

    public String getMtADestinationPlace() {
	return this.mtADestinationPlace;
    }

    public void setMtADestinationPlace(String mtADestinationPlace) {
	this.mtADestinationPlace = mtADestinationPlace;
    }

    public String getMtEDestinationPlace() {
	return this.mtEDestinationPlace;
    }

    public void setMtEDestinationPlace(String mtEDestinationPlace) {
	this.mtEDestinationPlace = mtEDestinationPlace;
    }

    public Integer getMtDestinationCity() {
	return this.mtDestinationCity;
    }

    public void setMtDestinationCity(Integer mtDestinationCity) {
	this.mtDestinationCity = mtDestinationCity;
    }

    public Integer getMtDestinationCountry() {
	return this.mtDestinationCountry;
    }

    public void setMtDestinationCountry(Integer mtDestinationCountry) {
	this.mtDestinationCountry = mtDestinationCountry;
    }

    public String getMtABlAwbLrNo() {
	return this.mtABlAwbLrNo;
    }

    public void setMtABlAwbLrNo(String mtABlAwbLrNo) {
	this.mtABlAwbLrNo = mtABlAwbLrNo;
    }

    public String getMtEBlAwbLrNo() {
	return this.mtEBlAwbLrNo;
    }

    public void setMtEBlAwbLrNo(String mtEBlAwbLrNo) {
	this.mtEBlAwbLrNo = mtEBlAwbLrNo;
    }

    public Date getMtBlAwbLrDate() {
	return this.mtBlAwbLrDate;
    }

    public void setMtBlAwbLrDate(Date mtBlAwbLrDate) {
	this.mtBlAwbLrDate = mtBlAwbLrDate;
    }

    public Date getMtDepartureDate() {
	return this.mtDepartureDate;
    }

    public void setMtDepartureDate(Date mtDepartureDate) {
	this.mtDepartureDate = mtDepartureDate;
    }

    public Short getMtStoragePeriod() {
	return this.mtStoragePeriod;
    }

    public void setMtStoragePeriod(Short mtStoragePeriod) {
	this.mtStoragePeriod = mtStoragePeriod;
    }

    public Integer getMtMtlCode() {
	return this.mtMtlCode;
    }

    public void setMtMtlCode(Integer mtMtlCode) {
	this.mtMtlCode = mtMtlCode;
    }

    public Byte getMtStatus() {
	return this.mtStatus;
    }

    public void setMtStatus(Byte mtStatus) {
	this.mtStatus = mtStatus;
    }

    public Date getMtValidityExpiryDate() {
	return this.mtValidityExpiryDate;
    }

    public void setMtValidityExpiryDate(Date mtValidityExpiryDate) {
	this.mtValidityExpiryDate = mtValidityExpiryDate;
    }

    public Integer getMtPreparedBy() {
	return this.mtPreparedBy;
    }

    public void setMtPreparedBy(Integer mtPreparedBy) {
	this.mtPreparedBy = mtPreparedBy;
    }

    public Date getMtPreparedDt() {
	return this.mtPreparedDt;
    }

    public void setMtPreparedDt(Date mtPreparedDt) {
	this.mtPreparedDt = mtPreparedDt;
    }

    public Integer getMtModifiedBy() {
	return this.mtModifiedBy;
    }

    public void setMtModifiedBy(Integer mtModifiedBy) {
	this.mtModifiedBy = mtModifiedBy;
    }

    public Date getMtModifiedDt() {
	return this.mtModifiedDt;
    }

    public void setMtModifiedDt(Date mtModifiedDt) {
	this.mtModifiedDt = mtModifiedDt;
    }

    public Date getMtStartDate() {
	return this.mtStartDate;
    }

    public void setMtStartDate(Date mtStartDate) {
	this.mtStartDate = mtStartDate;
    }

    public Date getMtEndDate() {
	return this.mtEndDate;
    }

    public void setMtEndDate(Date mtEndDate) {
	this.mtEndDate = mtEndDate;
    }

    public Long getMtBldId() {
	return this.mtBldId;
    }

    public void setMtBldId(Long mtBldId) {
	this.mtBldId = mtBldId;
    }

    @Override
	public POJOId getPOJOId(){
		return this.getId();
	}
    
    @Override
    public void setPOJOId(POJOId id) {
	setId((TTrnMarineTransitQuoId) id);
    }

    @Override
    public int getStatus() {
	return getMtStatus();
    }

    @Override
    public void setStatus(Integer status) {
	setMtStatus(status.byteValue());
    }

    @Override
    public void setEndtId(Long endtId) {
	getId().setMtEndtId(endtId);
    }

    @Override
    public void setEndtNo(Long endtNo) {
    	
    	//SONARFIX--26-04-2018---DO NOTHING IN METHOD 
    }

    @Override
    public void setValidityStartDate(Date vsd) {
	getId().setMtValidityStartDate(vsd);
    }

    @Override
    public void setValidityExpiryDate(Date ved) {
	setMtValidityExpiryDate(ved);
    }

    @Override
	public void setPreparedDate( Date preparedDate ){
		setMtPreparedDt( preparedDate );
	}
    
    @Override
	public Date getPreparedDate(){
		return getMtPreparedDt();
	}
}
