package com.rsaame.pas.dao.model;

import java.math.BigDecimal;
import java.util.Date;

// Generated Sep 2, 2013 3:53:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * VRenewalStatusReportPas generated by hbm2java
 */
public class VRenewalStatusReportPasHT implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private VRenewalStatusReportPasHTId id;
    private Long quotationNo;
	private Long polRefPolicyId;
	
	private String clEDesc;
	private Integer polPolicyType;
	private String ptEDesc;
	private Integer polLocationCode;
	private String locEDesc;

	private String specialty;
	private String facRi;

	private Integer policyYear;
	private String insuredName;
	private Integer customerId;
	private Integer brCode;
	private Integer polAccexecCode;
	private Date quoExpiryDate;
	private Date polExpiryDate;
	private BigDecimal totalPremium;
	private Date polValidityExpiryDate;
	private Integer claimCount;
	private Integer claimCount2;
	private Integer claimCount3;
	private Integer claimCount4;
	private Integer claimCount5;
	private BigDecimal claimAmount;
	private Date effectiveDate;
	private BigDecimal newTotalPremium;
	private String brName;
	private BigDecimal osAmt;
	private String ppRegn;
	private String licensedBy;
	private Date dob;
	private String polRenTermTxt;
	private Integer brokerCode;
	private Integer polSchemeCode;
	private Integer polStatus;
	
	private Integer polDistributionChnl;
	private String scheme;
	private String custAddr;
	private String poBox;
	private String mobileNo;
	private String nationality;
	private BigDecimal prmRate;
	private Integer noOfNonRecoverableClmAmt;
	private Integer noOfNonRecoverableClm;
	private Integer claimType;
	private String polStatusDesc;
	private String reason;
	
	/**
	 * @return the reason
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * @param reason the reason to set
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	public VRenewalStatusReportPasHT(){
	}

	/**
	 * @param id
	 * @param policyNo
	 * @param clEDesc
	 * @param polPolicyType
	 * @param ptEDesc
	 * @param polLocationCode
	 * @param locEDesc
	 * @param specialty
	 * @param facRi
	 * @param policyYear
	 * @param insuredName
	 * @param customerId
	 * @param brCode
	 * @param polAccexecCode
	 * @param expiryDate
	 * @param totalPremium
	 * @param polValidityExpiryDate
	 * @param claimCount
	 * @param claimCount2
	 * @param claimCount3
	 * @param claimCount4
	 * @param claimCount5
	 * @param claimAmount
	 * @param effectiveDate
	 * @param newTotalPremium
	 * @param brName
	 * @param osAmt
	 * @param ppRegn
	 * @param licensedBy
	 * @param dob
	 * @param polRenTermTxt
	 * @param brokerCode
	 * @param polSchemeCode
	 * @param polStatus
	 * @param polDistributionChnl
	 */
	public VRenewalStatusReportPasHT( VRenewalStatusReportPasHTId id, Long policyNo, String clEDesc, Integer polPolicyType, String ptEDesc, Integer polLocationCode, String locEDesc,
			String specialty, String facRi, Integer policyYear, String insuredName, Integer customerId, Integer brCode, Integer polAccexecCode, Date quoExpiryDate, Date polExpiryDate,
			BigDecimal totalPremium, Date polValidityExpiryDate, Integer claimCount, Integer claimCount2, Integer claimCount3, Integer claimCount4, Integer claimCount5,
			BigDecimal claimAmount, Date effectiveDate, BigDecimal newTotalPremium, String brName, BigDecimal osAmt, String ppRegn, String licensedBy, Date dob,
			String polRenTermTxt, Integer brokerCode, Integer polSchemeCode, Integer polStatus, Integer polDistributionChnl,  Long quotationNo,
			Long polRefPolicyId, String scheme , String custAddr,String poBox,String mobileNo, String nationality,BigDecimal prmRate,Integer noOfNonRecoverableClmAmt,
			Integer noOfNonRecoverableClm ,Integer claimType ,String polStatusDesc,String reason){
		super();
		this.id = id;
		
		this.clEDesc = clEDesc;
		this.polPolicyType = polPolicyType;
		this.ptEDesc = ptEDesc;
		this.polLocationCode = polLocationCode;
		this.locEDesc = locEDesc;
		this.specialty = specialty;
		this.facRi = facRi;
		this.policyYear = policyYear;
		this.insuredName = insuredName;
		this.customerId = customerId;
		this.brCode = brCode;
		this.polAccexecCode = polAccexecCode;
		this.quoExpiryDate = quoExpiryDate;
		this.polExpiryDate = polExpiryDate;
		this.totalPremium = totalPremium;
		this.polValidityExpiryDate = polValidityExpiryDate;
		this.claimCount = claimCount;
		this.claimCount2 = claimCount2;
		this.claimCount3 = claimCount3;
		this.claimCount4 = claimCount4;
		this.claimCount5 = claimCount5;
		this.claimAmount = claimAmount;
		this.effectiveDate = effectiveDate;
		this.newTotalPremium = newTotalPremium;
		this.brName = brName;
		this.osAmt = osAmt;
		this.ppRegn = ppRegn;
		this.licensedBy = licensedBy;
		this.dob = dob;
		this.polRenTermTxt = polRenTermTxt;
		this.brokerCode = brokerCode;
		this.polSchemeCode = polSchemeCode;
		this.polStatus = polStatus;
		this.polDistributionChnl = polDistributionChnl;
		this.quotationNo = quotationNo;
		this.scheme = scheme;
		this.custAddr = custAddr;
		this.poBox = poBox;
		this.mobileNo = mobileNo;
		this.nationality = nationality;
		this.prmRate = prmRate;
		this.noOfNonRecoverableClmAmt = noOfNonRecoverableClmAmt;
		this.noOfNonRecoverableClm = noOfNonRecoverableClm;
		this.claimType = claimType;
		this.polRefPolicyId = polRefPolicyId;
		this.polStatusDesc = polStatusDesc;
		this.reason = reason;
	}

	/**
	 * @return the polRefPolicyId
	 */
	public Long getPolRefPolicyId() {
		return polRefPolicyId;
	}

	/**
	 * @param polRefPolicyId the polRefPolicyId to set
	 */
	public void setPolRefPolicyId(Long polRefPolicyId) {
		this.polRefPolicyId = polRefPolicyId;
	}

	/**
	 * @return the scheme
	 */
	public String getScheme() {
		return scheme;
	}

	/**
	 * @param scheme the scheme to set
	 */
	public void setScheme(String scheme) {
		this.scheme = scheme;
	}

	/**
	 * @return the custAddr
	 */
	public String getCustAddr() {
		return custAddr;
	}

	/**
	 * @param custAddr the custAddr to set
	 */
	public void setCustAddr(String custAddr) {
		this.custAddr = custAddr;
	}

	/**
	 * @return the poBox
	 */
	public String getPoBox() {
		return poBox;
	}

	/**
	 * @param poBox the poBox to set
	 */
	public void setPoBox(String poBox) {
		this.poBox = poBox;
	}

	/**
	 * @return the mobileNo
	 */
	public String getMobileNo() {
		return mobileNo;
	}

	/**
	 * @param mobileNo the mobileNo to set
	 */
	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	/**
	 * @return the nationality
	 */
	public String getNationality() {
		return nationality;
	}

	/**
	 * @param nationality the nationality to set
	 */
	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	/**
	 * @return the prmRate
	 */
	public BigDecimal getPrmRate() {
		return prmRate;
	}

	/**
	 * @param prmRate the prmRate to set
	 */
	public void setPrmRate(BigDecimal prmRate) {
		this.prmRate = prmRate;
	}

	/**
	 * @return the noOfNonRecoverableClmAmt
	 */
	public Integer getNoOfNonRecoverableClmAmt() {
		return noOfNonRecoverableClmAmt;
	}

	/**
	 * @param noOfNonRecoverableClmAmt the noOfNonRecoverableClmAmt to set
	 */
	public void setNoOfNonRecoverableClmAmt(Integer noOfNonRecoverableClmAmt) {
		this.noOfNonRecoverableClmAmt = noOfNonRecoverableClmAmt;
	}

	/**
	 * @return the noOfNonRecoverableClm
	 */
	public Integer getNoOfNonRecoverableClm() {
		return noOfNonRecoverableClm;
	}

	/**
	 * @param noOfNonRecoverableClm the noOfNonRecoverableClm to set
	 */
	public void setNoOfNonRecoverableClm(Integer noOfNonRecoverableClm) {
		this.noOfNonRecoverableClm = noOfNonRecoverableClm;
	}

	/**
	 * @return the claimType
	 */
	public Integer getClaimType() {
		return claimType;
	}

	/**
	 * @param claimType the claimType to set
	 */
	public void setClaimType(Integer claimType) {
		this.claimType = claimType;
	}

	/**
	 * @return the id
	 */
	public VRenewalStatusReportPasHTId getId(){
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId( VRenewalStatusReportPasHTId id ){
		this.id = id;
	}
/**
	 * @return the quotationNo
	 */
	public Long getQuotationNo(){
		return quotationNo;
	}

	/**
	 * @param quotationNo the quotationNo to set
	 */
	public void setQuotationNo( Long quotationNo ){
		this.quotationNo = quotationNo;
	}
	/**
	 * @return the policyNo
	 */
	

	/**
	 * @return the clEDesc
	 */
	public String getClEDesc(){
		return clEDesc;
	}

	/**
	 * @param clEDesc the clEDesc to set
	 */
	public void setClEDesc( String clEDesc ){
		this.clEDesc = clEDesc;
	}

	/**
	 * @return the polPolicyType
	 */
	public Integer getPolPolicyType(){
		return polPolicyType;
	}

	/**
	 * @param polPolicyType the polPolicyType to set
	 */
	public void setPolPolicyType( Integer polPolicyType ){
		this.polPolicyType = polPolicyType;
	}

	/**
	 * @return the ptEDesc
	 */
	public String getPtEDesc(){
		return ptEDesc;
	}

	/**
	 * @param ptEDesc the ptEDesc to set
	 */
	public void setPtEDesc( String ptEDesc ){
		this.ptEDesc = ptEDesc;
	}

	/**
	 * @return the polLocationCode
	 */
	public Integer getPolLocationCode(){
		return polLocationCode;
	}

	/**
	 * @param polLocationCode the polLocationCode to set
	 */
	public void setPolLocationCode( Integer polLocationCode ){
		this.polLocationCode = polLocationCode;
	}

	/**
	 * @return the locEDesc
	 */
	public String getLocEDesc(){
		return locEDesc;
	}

	/**
	 * @param locEDesc the locEDesc to set
	 */
	public void setLocEDesc( String locEDesc ){
		this.locEDesc = locEDesc;
	}

	/**
	 * @return the specialty
	 */
	public String getSpecialty(){
		return specialty;
	}

	/**
	 * @param specialty the specialty to set
	 */
	public void setSpecialty( String specialty ){
		this.specialty = specialty;
	}

	/**
	 * @return the facRi
	 */
	public String getFacRi(){
		return facRi;
	}

	/**
	 * @param facRi the facRi to set
	 */
	public void setFacRi( String facRi ){
		this.facRi = facRi;
	}

	/**
	 * @return the policyYear
	 */
	public Integer getPolicyYear(){
		return policyYear;
	}

	/**
	 * @param policyYear the policyYear to set
	 */
	public void setPolicyYear( Integer policyYear ){
		this.policyYear = policyYear;
	}

	/**
	 * @return the insuredName
	 */
	public String getInsuredName(){
		return insuredName;
	}

	/**
	 * @param insuredName the insuredName to set
	 */
	public void setInsuredName( String insuredName ){
		this.insuredName = insuredName;
	}

	/**
	 * @return the customerId
	 */
	public Integer getCustomerId(){
		return customerId;
	}

	/**
	 * @param customerId the customerId to set
	 */
	public void setCustomerId( Integer customerId ){
		this.customerId = customerId;
	}

	/**
	 * @return the brCode
	 */
	public Integer getBrCode(){
		return brCode;
	}

	/**
	 * @param brCode the brCode to set
	 */
	public void setBrCode( Integer brCode ){
		this.brCode = brCode;
	}

	/**
	 * @return the polAccexecCode
	 */
	public Integer getPolAccexecCode(){
		return polAccexecCode;
	}

	/**
	 * @param polAccexecCode the polAccexecCode to set
	 */
	public void setPolAccexecCode( Integer polAccexecCode ){
		this.polAccexecCode = polAccexecCode;
	}

	/**
	 * @return the expiryDate
	 */
	public Date getQuoExpiryDate(){
		return quoExpiryDate;
	}

	/**
	 * @param expiryDate the expiryDate to set
	 */
	public void setQuoExpiryDate( Date quoExpiryDate ){
		this.quoExpiryDate = quoExpiryDate;
	}

	/**
	 * @return the polExpiryDate
	 */
	public Date getPolExpiryDate(){
		return polExpiryDate;
	}

	/**
	 * @param polExpiryDate the polExpiryDate to set
	 */
	public void setPolExpiryDate( Date polExpiryDate ){
		this.polExpiryDate = polExpiryDate;
	}

	/**
	 * @return the totalPremium
	 */
	public BigDecimal getTotalPremium(){
		return totalPremium;
	}

	/**
	 * @param totalPremium the totalPremium to set
	 */
	public void setTotalPremium( BigDecimal totalPremium ){
		this.totalPremium = totalPremium;
	}

	/**
	 * @return the polValidityExpiryDate
	 */
	public Date getPolValidityExpiryDate(){
		return polValidityExpiryDate;
	}

	/**
	 * @param polValidityExpiryDate the polValidityExpiryDate to set
	 */
	public void setPolValidityExpiryDate( Date polValidityExpiryDate ){
		this.polValidityExpiryDate = polValidityExpiryDate;
	}

	/**
	 * @return the claimCount
	 */
	public Integer getClaimCount(){
		return claimCount;
	}

	/**
	 * @param claimCount the claimCount to set
	 */
	public void setClaimCount( Integer claimCount ){
		this.claimCount = claimCount;
	}

	/**
	 * @return the claimCount2
	 */
	public Integer getClaimCount2(){
		return claimCount2;
	}

	/**
	 * @param claimCount2 the claimCount2 to set
	 */
	public void setClaimCount2( Integer claimCount2 ){
		this.claimCount2 = claimCount2;
	}

	/**
	 * @return the claimCount3
	 */
	public Integer getClaimCount3(){
		return claimCount3;
	}

	/**
	 * @param claimCount3 the claimCount3 to set
	 */
	public void setClaimCount3( Integer claimCount3 ){
		this.claimCount3 = claimCount3;
	}

	/**
	 * @return the claimCount4
	 */
	public Integer getClaimCount4(){
		return claimCount4;
	}

	/**
	 * @param claimCount4 the claimCount4 to set
	 */
	public void setClaimCount4( Integer claimCount4 ){
		this.claimCount4 = claimCount4;
	}

	/**
	 * @return the claimCount5
	 */
	public Integer getClaimCount5(){
		return claimCount5;
	}

	/**
	 * @param claimCount5 the claimCount5 to set
	 */
	public void setClaimCount5( Integer claimCount5 ){
		this.claimCount5 = claimCount5;
	}

	/**
	 * @return the claimAmount
	 */
	public BigDecimal getClaimAmount(){
		return claimAmount;
	}

	/**
	 * @param claimAmount the claimAmount to set
	 */
	public void setClaimAmount( BigDecimal claimAmount ){
		this.claimAmount = claimAmount;
	}

	/**
	 * @return the effectiveDate
	 */
	public Date getEffectiveDate(){
		return effectiveDate;
	}

	/**
	 * @param effectiveDate the effectiveDate to set
	 */
	public void setEffectiveDate( Date effectiveDate ){
		this.effectiveDate = effectiveDate;
	}

	/**
	 * @return the newTotalPremium
	 */
	public BigDecimal getNewTotalPremium(){
		return newTotalPremium;
	}

	/**
	 * @param newTotalPremium the newTotalPremium to set
	 */
	public void setNewTotalPremium( BigDecimal newTotalPremium ){
		this.newTotalPremium = newTotalPremium;
	}

	/**
	 * @return the brName
	 */
	public String getBrName(){
		return brName;
	}

	/**
	 * @param brName the brName to set
	 */
	public void setBrName( String brName ){
		this.brName = brName;
	}

	/**
	 * @return the osAmt
	 */
	public BigDecimal getOsAmt(){
		return osAmt;
	}

	/**
	 * @param osAmt the osAmt to set
	 */
	public void setOsAmt( BigDecimal osAmt ){
		this.osAmt = osAmt;
	}

	/**
	 * @return the ppRegn
	 */
	public String getPpRegn(){
		return ppRegn;
	}

	/**
	 * @param ppRegn the ppRegn to set
	 */
	public void setPpRegn( String ppRegn ){
		this.ppRegn = ppRegn;
	}

	/**
	 * @return the licensedBy
	 */
	public String getLicensedBy(){
		return licensedBy;
	}

	/**
	 * @param licensedBy the licensedBy to set
	 */
	public void setLicensedBy( String licensedBy ){
		this.licensedBy = licensedBy;
	}

	/**
	 * @return the dob
	 */
	public Date getDob(){
		return dob;
	}

	/**
	 * @param dob the dob to set
	 */
	public void setDob( Date dob ){
		this.dob = dob;
	}

	/**
	 * @return the polRenTermTxt
	 */
	public String getPolRenTermTxt(){
		return polRenTermTxt;
	}

	/**
	 * @param polRenTermTxt the polRenTermTxt to set
	 */
	public void setPolRenTermTxt( String polRenTermTxt ){
		this.polRenTermTxt = polRenTermTxt;
	}

	/**
	 * @return the brokerCode
	 */
	public Integer getBrokerCode(){
		return brokerCode;
	}

	/**
	 * @param brokerCode the brokerCode to set
	 */
	public void setBrokerCode( Integer brokerCode ){
		this.brokerCode = brokerCode;
	}

	/**
	 * @return the polSchemeCode
	 */
	public Integer getPolSchemeCode(){
		return polSchemeCode;
	}

	/**
	 * @param polSchemeCode the polSchemeCode to set
	 */
	public void setPolSchemeCode( Integer polSchemeCode ){
		this.polSchemeCode = polSchemeCode;
	}

	/**
	 * @return the polStatus
	 */
	public Integer getPolStatus(){
		return polStatus;
	}

	/**
	 * @param polStatus the polStatus to set
	 */
	public void setPolStatus( Integer polStatus ){
		this.polStatus = polStatus;
	}

	/**
	 * @return the polDistributionChnl
	 */
	public Integer getPolDistributionChnl(){
		return polDistributionChnl;
	}

	/**
	 * @param polDistributionChnl the polDistributionChnl to set
	 */
	public void setPolDistributionChnl( Integer polDistributionChnl ){
		this.polDistributionChnl = polDistributionChnl;
	}

	public void setPolStatusDesc(String polStatusDesc) {
		this.polStatusDesc = polStatusDesc;
	}

	public String getPolStatusDesc() {
		return polStatusDesc;
	}
	
	
}
