package com.rsaame.pas.dao.model;

// Generated Aug 16, 2012 7:36:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * VTrnPasPremSumLocTmpId generated by hbm2java
 */
public class VTrnPasPremSumLocId implements java.io.Serializable {

	private BigDecimal coverSiAmt;
	private BigDecimal coverPrmAmt;
	private Long linkingId;
	private Long endtId;
	private Short class_;
	private Short secId;
	private String secName;
	private Long locationId;
	private String locationName;
	//private BigDecimal coverId;
	private BigDecimal commission;
	private Date valStartDate;
	private Date valExpDate;
	private BigDecimal status;
	private Character polQuoFlag;
	private Integer prmBasicRskCode;
	private BigDecimal prmBasicRskId;

	public VTrnPasPremSumLocId() {
	}

	public VTrnPasPremSumLocId(long endtId, short class_, short secId,
			long locationId, BigDecimal coverId, Date valStartDate,
			Date valExpDate) {
		this.endtId = endtId;
		this.class_ = class_;
		this.secId = secId;
		this.locationId = locationId;
		//this.coverId = coverId;
		this.valStartDate = valStartDate;
		this.valExpDate = valExpDate;
	}

	public VTrnPasPremSumLocId(BigDecimal coverSiAmt, BigDecimal coverPrmAmt,
			Long linkingId, Long endtId, Short class_, Short secId,
			String secName, Long locationId, String locationName,
			BigDecimal commission, Date valStartDate, Date valExpDate,
			BigDecimal status, Character polQuoFlag, Integer prmBasicRskCode,
			BigDecimal prmBasicRskId) {
		this.coverSiAmt = coverSiAmt;
		this.coverPrmAmt = coverPrmAmt;
		this.linkingId = linkingId;
		this.endtId = endtId;
		this.class_ = class_;
		this.secId = secId;
		this.secName = secName;
		this.locationId = locationId;
		this.locationName = locationName;
		this.commission = commission;
		this.valStartDate = valStartDate;
		this.valExpDate = valExpDate;
		this.status = status;
		this.polQuoFlag = polQuoFlag;
		this.prmBasicRskCode = prmBasicRskCode;
		this.prmBasicRskId = prmBasicRskId;
	}

	public BigDecimal getCoverSiAmt() {
		return this.coverSiAmt;
	}

	public void setCoverSiAmt(BigDecimal coverSiAmt) {
		this.coverSiAmt = coverSiAmt;
	}

	public BigDecimal getCoverPrmAmt() {
		return this.coverPrmAmt;
	}

	public void setCoverPrmAmt(BigDecimal coverPrmAmt) {
		this.coverPrmAmt = coverPrmAmt;
	}

	public Long getLinkingId() {
		return this.linkingId;
	}

	public void setLinkingId(Long linkingId) {
		this.linkingId = linkingId;
	}

	public Long getEndtId() {
		return this.endtId;
	}

	public void setEndtId(Long endtId) {
		this.endtId = endtId;
	}

	public Short getClass_() {
		return this.class_;
	}

	public void setClass_(Short class_) {
		this.class_ = class_;
	}

	public Short getSecId() {
		return this.secId;
	}

	public void setSecId(Short secId) {
		this.secId = secId;
	}

	public String getSecName() {
		return this.secName;
	}

	public void setSecName(String secName) {
		this.secName = secName;
	}

	public Long getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Long locationId) {
		this.locationId = locationId;
	}

	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public BigDecimal getCommission() {
		return this.commission;
	}

	public void setCommission(BigDecimal commission) {
		this.commission = commission;
	}

	public Date getValStartDate() {
		return this.valStartDate;
	}

	public void setValStartDate(Date valStartDate) {
		this.valStartDate = valStartDate;
	}

	public Date getValExpDate() {
		return this.valExpDate;
	}

	public void setValExpDate(Date valExpDate) {
		this.valExpDate = valExpDate;
	}

	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	public Character getPolQuoFlag() {
		return this.polQuoFlag;
	}

	public void setPolQuoFlag(Character polQuoFlag) {
		this.polQuoFlag = polQuoFlag;
	}

	public Integer getPrmBasicRskCode() {
		return this.prmBasicRskCode;
	}

	public void setPrmBasicRskCode(Integer prmBasicRskCode) {
		this.prmBasicRskCode = prmBasicRskCode;
	}

	public BigDecimal getPrmBasicRskId() {
		return this.prmBasicRskId;
	}

	public void setPrmBasicRskId(BigDecimal prmBasicRskId) {
		this.prmBasicRskId = prmBasicRskId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VTrnPasPremSumLocId))
			return false;
		VTrnPasPremSumLocId castOther = (VTrnPasPremSumLocId) other;

		return ((this.getCoverSiAmt() == castOther.getCoverSiAmt()) || (this
				.getCoverSiAmt() != null && castOther.getCoverSiAmt() != null && this
				.getCoverSiAmt().equals(castOther.getCoverSiAmt())))
				&& ((this.getCoverPrmAmt() == castOther.getCoverPrmAmt()) || (this
						.getCoverPrmAmt() != null
						&& castOther.getCoverPrmAmt() != null && this
						.getCoverPrmAmt().equals(castOther.getCoverPrmAmt())))
				&& ((this.getLinkingId() == castOther.getLinkingId()) || (this
						.getLinkingId() != null
						&& castOther.getLinkingId() != null && this
						.getLinkingId().equals(castOther.getLinkingId())))
				&& ((this.getEndtId() == castOther.getEndtId()) || (this
						.getEndtId() != null && castOther.getEndtId() != null && this
						.getEndtId().equals(castOther.getEndtId())))
				&& ((this.getClass_() == castOther.getClass_()) || (this
						.getClass_() != null && castOther.getClass_() != null && this
						.getClass_().equals(castOther.getClass_())))
				&& ((this.getSecId() == castOther.getSecId()) || (this
						.getSecId() != null && castOther.getSecId() != null && this
						.getSecId().equals(castOther.getSecId())))
				&& ((this.getSecName() == castOther.getSecName()) || (this
						.getSecName() != null && castOther.getSecName() != null && this
						.getSecName().equals(castOther.getSecName())))
				&& ((this.getLocationId() == castOther.getLocationId()) || (this
						.getLocationId() != null
						&& castOther.getLocationId() != null && this
						.getLocationId().equals(castOther.getLocationId())))
				&& ((this.getLocationName() == castOther.getLocationName()) || (this
						.getLocationName() != null
						&& castOther.getLocationName() != null && this
						.getLocationName().equals(castOther.getLocationName())))
				&& ((this.getCommission() == castOther.getCommission()) || (this
						.getCommission() != null
						&& castOther.getCommission() != null && this
						.getCommission().equals(castOther.getCommission())))
				&& ((this.getValStartDate() == castOther.getValStartDate()) || (this
						.getValStartDate() != null
						&& castOther.getValStartDate() != null && this
						.getValStartDate().equals(castOther.getValStartDate())))
				&& ((this.getValExpDate() == castOther.getValExpDate()) || (this
						.getValExpDate() != null
						&& castOther.getValExpDate() != null && this
						.getValExpDate().equals(castOther.getValExpDate())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getPolQuoFlag() == castOther.getPolQuoFlag()) || (this
						.getPolQuoFlag() != null
						&& castOther.getPolQuoFlag() != null && this
						.getPolQuoFlag().equals(castOther.getPolQuoFlag())))
				&& ((this.getPrmBasicRskCode() == castOther
						.getPrmBasicRskCode()) || (this.getPrmBasicRskCode() != null
						&& castOther.getPrmBasicRskCode() != null && this
						.getPrmBasicRskCode().equals(
								castOther.getPrmBasicRskCode())))
				&& ((this.getPrmBasicRskId() == castOther.getPrmBasicRskId()) || (this
						.getPrmBasicRskId() != null
						&& castOther.getPrmBasicRskId() != null && this
						.getPrmBasicRskId()
						.equals(castOther.getPrmBasicRskId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCoverSiAmt() == null ? 0 : this.getCoverSiAmt()
						.hashCode());
		result = 37
				* result
				+ (getCoverPrmAmt() == null ? 0 : this.getCoverPrmAmt()
						.hashCode());
		result = 37 * result
				+ (getLinkingId() == null ? 0 : this.getLinkingId().hashCode());
		result = 37 * result
				+ (getEndtId() == null ? 0 : this.getEndtId().hashCode());
		result = 37 * result
				+ (getClass_() == null ? 0 : this.getClass_().hashCode());
		result = 37 * result
				+ (getSecId() == null ? 0 : this.getSecId().hashCode());
		result = 37 * result
				+ (getSecName() == null ? 0 : this.getSecName().hashCode());
		result = 37
				* result
				+ (getLocationId() == null ? 0 : this.getLocationId()
						.hashCode());
		result = 37
				* result
				+ (getLocationName() == null ? 0 : this.getLocationName()
						.hashCode());
		result = 37
				* result
				+ (getCommission() == null ? 0 : this.getCommission()
						.hashCode());
		result = 37
				* result
				+ (getValStartDate() == null ? 0 : this.getValStartDate()
						.hashCode());
		result = 37
				* result
				+ (getValExpDate() == null ? 0 : this.getValExpDate()
						.hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37
				* result
				+ (getPolQuoFlag() == null ? 0 : this.getPolQuoFlag()
						.hashCode());
		result = 37
				* result
				+ (getPrmBasicRskCode() == null ? 0 : this.getPrmBasicRskCode()
						.hashCode());
		result = 37
				* result
				+ (getPrmBasicRskId() == null ? 0 : this.getPrmBasicRskId()
						.hashCode());
		return result;
	}

}
