package com.rsaame.pas.dao.model;

// Generated Mar 24, 2014 10:57:18 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.mindtree.ruc.cmn.utils.Utils;
import com.rsaame.pas.cmn.pojo.POJOId;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapper;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapperId;

/**
 * TTrnWctplPersonQuo generated by hbm2java
 */
public class TTrnWctplPersonQuo extends POJOWrapper implements java.io.Serializable {

	private static final long serialVersionUID = -1699140161871641147L;
	private TTrnWctplPersonQuoId id;
	private Long wprPolicyId;
	private Long wprBasicRiskId;
	private Long wprRskCode;
	private Long wprRtCode;
	private Long wprRcCode;
	private String wprAName;
	private String wprEName;
	private String wprAAddress1;
	private String wprEAddress1;
	private String wprAAddress2;
	private String wprEAddress2;
	private String wprAAddress3;
	private String wprEAddress3;
	private String wprZip;
	private Long wprTelephone;
	private Long wprFax;
	private Long wprGsm;
	private String wprEmail;
	private Long wprAge;
	private BigDecimal wprSumInsured;
	private Byte wprStatus;
	private Short wprEmploymentType;
	private String wprEmployerEName;
	private String wprEmployerAName;
	private Date wprValidityExpiryDate;
	private Long wprEndtId;
	private Integer wprRiRskCode;
	private Integer wprBasicRskCode;
	private BigDecimal wprSalary;
	private Integer wprPreparedBy;
	private Date wprPreparedDt;
	private Integer wprModifiedBy;
	private Date wprModifiedDt;
	private Date wprStartDate;
	private Date wprEndDate;
	private Long wprHazard;
	private Long wprTradeGroup;
	private Long wprBldId;
	private Short wprTerCode;
	private Short wprJurCode;
	private String wprFreeZone;
	private String wprJurDesc;
	private BigDecimal wprEmpLiabLmt;

	public TTrnWctplPersonQuo() {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	public TTrnWctplPersonQuo(TTrnWctplPersonQuoId id,
			Date wprValidityExpiryDate) {
		this.id = id;
		this.wprValidityExpiryDate = wprValidityExpiryDate;
	}

	public TTrnWctplPersonQuo(TTrnWctplPersonQuoId id, Long wprPolicyId,
			Long wprBasicRiskId, Long wprRskCode, Long wprRtCode,
			Long wprRcCode, String wprAName, String wprEName,
			String wprAAddress1, String wprEAddress1, String wprAAddress2,
			String wprEAddress2, String wprAAddress3, String wprEAddress3,
			String wprZip, Long wprTelephone, Long wprFax, Long wprGsm,
			String wprEmail, Long wprAge, BigDecimal wprSumInsured,
			Byte wprStatus, Short wprEmploymentType, String wprEmployerEName,
			String wprEmployerAName, Date wprValidityExpiryDate,
			Long wprEndtId, Integer wprRiRskCode, Integer wprBasicRskCode,
			BigDecimal wprSalary, Integer wprPreparedBy, Date wprPreparedDt,
			Integer wprModifiedBy, Date wprModifiedDt, Date wprStartDate,
			Date wprEndDate, Long wprHazard, Long wprTradeGroup, Long wprBldId,
			Short wprTerCode, Short wprJurCode, String wprFreeZone,
			String wprJurDesc, BigDecimal wprEmpLiabLmt) {
		this.id = id;
		this.wprPolicyId = wprPolicyId;
		this.wprBasicRiskId = wprBasicRiskId;
		this.wprRskCode = wprRskCode;
		this.wprRtCode = wprRtCode;
		this.wprRcCode = wprRcCode;
		this.wprAName = wprAName;
		this.wprEName = wprEName;
		this.wprAAddress1 = wprAAddress1;
		this.wprEAddress1 = wprEAddress1;
		this.wprAAddress2 = wprAAddress2;
		this.wprEAddress2 = wprEAddress2;
		this.wprAAddress3 = wprAAddress3;
		this.wprEAddress3 = wprEAddress3;
		this.wprZip = wprZip;
		this.wprTelephone = wprTelephone;
		this.wprFax = wprFax;
		this.wprGsm = wprGsm;
		this.wprEmail = wprEmail;
		this.wprAge = wprAge;
		this.wprSumInsured = wprSumInsured;
		this.wprStatus = wprStatus;
		this.wprEmploymentType = wprEmploymentType;
		this.wprEmployerEName = wprEmployerEName;
		this.wprEmployerAName = wprEmployerAName;
		this.wprValidityExpiryDate = wprValidityExpiryDate;
		this.wprEndtId = wprEndtId;
		this.wprRiRskCode = wprRiRskCode;
		this.wprBasicRskCode = wprBasicRskCode;
		this.wprSalary = wprSalary;
		this.wprPreparedBy = wprPreparedBy;
		this.wprPreparedDt = wprPreparedDt;
		this.wprModifiedBy = wprModifiedBy;
		this.wprModifiedDt = wprModifiedDt;
		this.wprStartDate = wprStartDate;
		this.wprEndDate = wprEndDate;
		this.wprHazard = wprHazard;
		this.wprTradeGroup = wprTradeGroup;
		this.wprBldId = wprBldId;
		this.wprTerCode = wprTerCode;
		this.wprJurCode = wprJurCode;
		this.wprFreeZone = wprFreeZone;
		this.wprJurDesc = wprJurDesc;
		this.wprEmpLiabLmt = wprEmpLiabLmt;
	}

	public TTrnWctplPersonQuoId getId() {
		return this.id;
	}

	public void setId(TTrnWctplPersonQuoId id) {
		this.id = id;
	}
	
	@Override
	public POJOId getPOJOId(){
		return this.getId();
	}
	
	@Override
	public void setPOJOId( POJOId id ){
		setId( (TTrnWctplPersonQuoId) id );
	}
	

	public Long getWprPolicyId() {
		return this.wprPolicyId;
	}

	public void setWprPolicyId(Long wprPolicyId) {
		this.wprPolicyId = wprPolicyId;
	}

	public Long getWprBasicRiskId() {
		return this.wprBasicRiskId;
	}

	public void setWprBasicRiskId(Long wprBasicRiskId) {
		this.wprBasicRiskId = wprBasicRiskId;
	}

	public Long getWprRskCode() {
		return this.wprRskCode;
	}

	public void setWprRskCode(Long wprRskCode) {
		this.wprRskCode = wprRskCode;
	}

	public Long getWprRtCode() {
		return this.wprRtCode;
	}

	public void setWprRtCode(Long wprRtCode) {
		this.wprRtCode = wprRtCode;
	}

	public Long getWprRcCode() {
		return this.wprRcCode;
	}

	public void setWprRcCode(Long wprRcCode) {
		this.wprRcCode = wprRcCode;
	}

	public String getWprAName() {
		return this.wprAName;
	}

	public void setWprAName(String wprAName) {
		this.wprAName = wprAName;
	}

	public String getWprEName() {
		return this.wprEName;
	}

	public void setWprEName(String wprEName) {
		this.wprEName = wprEName;
	}

	public String getWprAAddress1() {
		return this.wprAAddress1;
	}

	public void setWprAAddress1(String wprAAddress1) {
		this.wprAAddress1 = wprAAddress1;
	}

	public String getWprEAddress1() {
		return this.wprEAddress1;
	}

	public void setWprEAddress1(String wprEAddress1) {
		this.wprEAddress1 = wprEAddress1;
	}

	public String getWprAAddress2() {
		return this.wprAAddress2;
	}

	public void setWprAAddress2(String wprAAddress2) {
		this.wprAAddress2 = wprAAddress2;
	}

	public String getWprEAddress2() {
		return this.wprEAddress2;
	}

	public void setWprEAddress2(String wprEAddress2) {
		this.wprEAddress2 = wprEAddress2;
	}

	public String getWprAAddress3() {
		return this.wprAAddress3;
	}

	public void setWprAAddress3(String wprAAddress3) {
		this.wprAAddress3 = wprAAddress3;
	}

	public String getWprEAddress3() {
		return this.wprEAddress3;
	}

	public void setWprEAddress3(String wprEAddress3) {
		this.wprEAddress3 = wprEAddress3;
	}

	public String getWprZip() {
		return this.wprZip;
	}

	public void setWprZip(String wprZip) {
		this.wprZip = wprZip;
	}

	public Long getWprTelephone() {
		return this.wprTelephone;
	}

	public void setWprTelephone(Long wprTelephone) {
		this.wprTelephone = wprTelephone;
	}

	public Long getWprFax() {
		return this.wprFax;
	}

	public void setWprFax(Long wprFax) {
		this.wprFax = wprFax;
	}

	public Long getWprGsm() {
		return this.wprGsm;
	}

	public void setWprGsm(Long wprGsm) {
		this.wprGsm = wprGsm;
	}

	public String getWprEmail() {
		return this.wprEmail;
	}

	public void setWprEmail(String wprEmail) {
		this.wprEmail = wprEmail;
	}

	public Long getWprAge() {
		return this.wprAge;
	}

	public void setWprAge(Long wprAge) {
		this.wprAge = wprAge;
	}

	public BigDecimal getWprSumInsured() {
		return this.wprSumInsured;
	}

	public void setWprSumInsured(BigDecimal wprSumInsured) {
		this.wprSumInsured = wprSumInsured;
	}

	public Byte getWprStatus() {
		return this.wprStatus;
	}

	public void setWprStatus(Byte wprStatus) {
		this.wprStatus = wprStatus;
	}

	public Short getWprEmploymentType() {
		return this.wprEmploymentType;
	}

	public void setWprEmploymentType(Short wprEmploymentType) {
		this.wprEmploymentType = wprEmploymentType;
	}

	public String getWprEmployerEName() {
		return this.wprEmployerEName;
	}

	public void setWprEmployerEName(String wprEmployerEName) {
		this.wprEmployerEName = wprEmployerEName;
	}

	public String getWprEmployerAName() {
		return this.wprEmployerAName;
	}

	public void setWprEmployerAName(String wprEmployerAName) {
		this.wprEmployerAName = wprEmployerAName;
	}

	public Date getWprValidityExpiryDate() {
		return this.wprValidityExpiryDate;
	}

	public void setWprValidityExpiryDate(Date wprValidityExpiryDate) {
		this.wprValidityExpiryDate = wprValidityExpiryDate;
	}

	public Long getWprEndtId() {
		return this.wprEndtId;
	}

	public void setWprEndtId(Long wprEndtId) {
		this.wprEndtId = wprEndtId;
	}

	public Integer getWprRiRskCode() {
		return this.wprRiRskCode;
	}

	public void setWprRiRskCode(Integer wprRiRskCode) {
		this.wprRiRskCode = wprRiRskCode;
	}

	public Integer getWprBasicRskCode() {
		return this.wprBasicRskCode;
	}

	public void setWprBasicRskCode(Integer wprBasicRskCode) {
		this.wprBasicRskCode = wprBasicRskCode;
	}

	public BigDecimal getWprSalary() {
		return this.wprSalary;
	}

	public void setWprSalary(BigDecimal wprSalary) {
		this.wprSalary = wprSalary;
	}

	public Integer getWprPreparedBy() {
		return this.wprPreparedBy;
	}

	public void setWprPreparedBy(Integer wprPreparedBy) {
		this.wprPreparedBy = wprPreparedBy;
	}

	public Date getWprPreparedDt() {
		return this.wprPreparedDt;
	}

	public void setWprPreparedDt(Date wprPreparedDt) {
		this.wprPreparedDt = wprPreparedDt;
	}

	public Integer getWprModifiedBy() {
		return this.wprModifiedBy;
	}

	public void setWprModifiedBy(Integer wprModifiedBy) {
		this.wprModifiedBy = wprModifiedBy;
	}

	public Date getWprModifiedDt() {
		return this.wprModifiedDt;
	}

	public void setWprModifiedDt(Date wprModifiedDt) {
		this.wprModifiedDt = wprModifiedDt;
	}

	public Date getWprStartDate() {
		return this.wprStartDate;
	}

	public void setWprStartDate(Date wprStartDate) {
		this.wprStartDate = wprStartDate;
	}

	public Date getWprEndDate() {
		return this.wprEndDate;
	}

	public void setWprEndDate(Date wprEndDate) {
		this.wprEndDate = wprEndDate;
	}

	public Long getWprHazard() {
		return this.wprHazard;
	}

	public void setWprHazard(Long wprHazard) {
		this.wprHazard = wprHazard;
	}

	public Long getWprTradeGroup() {
		return this.wprTradeGroup;
	}

	public void setWprTradeGroup(Long wprTradeGroup) {
		this.wprTradeGroup = wprTradeGroup;
	}

	public Long getWprBldId() {
		return this.wprBldId;
	}

	public void setWprBldId(Long wprBldId) {
		this.wprBldId = wprBldId;
	}

	public Short getWprTerCode() {
		return this.wprTerCode;
	}

	public void setWprTerCode(Short wprTerCode) {
		this.wprTerCode = wprTerCode;
	}

	public Short getWprJurCode() {
		return this.wprJurCode;
	}

	public void setWprJurCode(Short wprJurCode) {
		this.wprJurCode = wprJurCode;
	}

	public String getWprFreeZone() {
		return this.wprFreeZone;
	}

	public void setWprFreeZone(String wprFreeZone) {
		this.wprFreeZone = wprFreeZone;
	}

	public String getWprJurDesc() {
		return this.wprJurDesc;
	}

	public void setWprJurDesc(String wprJurDesc) {
		this.wprJurDesc = wprJurDesc;
	}

	public BigDecimal getWprEmpLiabLmt() {
		return this.wprEmpLiabLmt;
	}

	public void setWprEmpLiabLmt(BigDecimal wprEmpLiabLmt) {
		this.wprEmpLiabLmt = wprEmpLiabLmt;
	}

	@Override
	public int getStatus(){
		return getWprStatus();
	}
	
	@Override
	public void setPreparedDate( Date preparedDate ){
		setWprPreparedDt( preparedDate );
	}
	
	@Override
	public Date getPreparedDate(){
		return getWprPreparedDt();
	} 
	
	@Override
	public void setStatus( Integer status ){
		
		if( Utils.isEmpty( status ) ){
			setWprStatus(null);
		}else{
			setWprStatus( status.byteValue() );
		}
	}
	
	@Override
	public void setEndtId( Long endtId ){
		setWprEndtId( endtId );
	}
	
	@Override
	public void setEndtNo( Long endtNo ){
		
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD 
	}
	
	@Override
	public void setValidityStartDate( Date vsd ){
		this.id.setWprValidityStartDate( vsd );
	}
	
	@Override
	public void setValidityExpiryDate( Date ved ){
		setWprValidityExpiryDate( ved );
	}

	@Override
	public void setPOJOWrapperId(POJOWrapperId id) {
		setId((TTrnWctplPersonQuoId)id);
	}

	@Override
	public POJOWrapperId getPOJOWrapperId() {
		return getId();
	}

	@Override
	public void setStatus(int status) {
		setWprStatus(Integer.valueOf(status).byteValue());
	}

	@Override
	public void setPreparedBy(Integer preparedBy) {
		setWprPreparedBy(preparedBy);
	}

	@Override
	public void setPreparedDt(Date preparedDt) {
		setWprPreparedDt(preparedDt);
	}

	@Override
	public void setModifiedBy(Integer modifiedBy) {
		setWprModifiedBy(modifiedBy);
	}

	@Override
	public void setModifiedDt(Date modifiedDt) {
		setWprModifiedDt(modifiedDt);
	}

	@Override
	public Integer getPreparedBy() {
		return getWprPreparedBy();
	}

	@Override
	public Date getPreparedDt() {
		return getWprPreparedDt();
	}

	@Override
	public Integer getModifiedBy() {
		return getWprModifiedBy();
	}

	@Override
	public Date getModifiedDt() {
		return getWprModifiedDt();
	}
}
