package com.rsaame.pas.b2c.cmn.handlers;

/**
 * This class contains all the email trigger point names for B2C
 * 
 * @author M1020859
 *
 */
public enum B2CEmailTriggers {
	
	TRAVEL_CREATE_QUOTE,
	HOME_CREATE_QUOTE,
	TRAVEL_SAVE_FOR_LATER,
	HOME_SAVE_FOR_LATER,
	TRAVEL_CONVERT_TO_POLICY,
	HOME_CONVERT_TO_POLICY,
	PAYMENT_FAILURE,
	REFERRAL,
	TRAVEL_CONVERT_TO_POLICY_REMINDER,
	HOME_CONVERT_TO_POLICY_REMINDER,
	REQUEST_CALL_BACK,
	SUBMIT_CLAIM,
	SUBMIT_GOLF_INSURANCE,
	SUBMIT_PERSONAL_ACCIDENT_INSURANCE
	;
	
}
