package com.rsaame.pas.dao.model;

// Generated Feb 3, 2012 12:22:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * TMasRiskTypeId generated by hbm2java
 */
public class TMasRiskTypeId implements java.io.Serializable {

	private int rtRskCode;
	private int rtCode;

	public TMasRiskTypeId() {
	}

	public TMasRiskTypeId(int rtRskCode, int rtCode) {
		this.rtRskCode = rtRskCode;
		this.rtCode = rtCode;
	}

	public int getRtRskCode() {
		return this.rtRskCode;
	}

	public void setRtRskCode(int rtRskCode) {
		this.rtRskCode = rtRskCode;
	}

	public int getRtCode() {
		return this.rtCode;
	}

	public void setRtCode(int rtCode) {
		this.rtCode = rtCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMasRiskTypeId))
			return false;
		TMasRiskTypeId castOther = (TMasRiskTypeId) other;

		return (this.getRtRskCode() == castOther.getRtRskCode())
				&& (this.getRtCode() == castOther.getRtCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRtRskCode();
		result = 37 * result + this.getRtCode();
		return result;
	}

}
