package com.rsaame.pas.b2b.ws.dao.vo;

// default package
// Generated Dec 7, 2018 7:48:29 PM by Hibernate Tools 5.3.0.Beta2

/**
 * EplatformWsStagingId generated by hbm2java
 */
public class EplatformWsStagingId implements java.io.Serializable {

	private long polPolicyId;
	private long polEndtId;

	public EplatformWsStagingId() {
	}

	public EplatformWsStagingId(long polPolicyId, long polEndtId) {
		this.polPolicyId = polPolicyId;
		this.polEndtId = polEndtId;
	}

	public long getPolPolicyId() {
		return this.polPolicyId;
	}

	public void setPolPolicyId(long polPolicyId) {
		this.polPolicyId = polPolicyId;
	}

	public long getPolEndtId() {
		return this.polEndtId;
	}

	public void setPolEndtId(long polEndtId) {
		this.polEndtId = polEndtId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EplatformWsStagingId))
			return false;
		EplatformWsStagingId castOther = (EplatformWsStagingId) other;

		return (this.getPolPolicyId() == castOther.getPolPolicyId())
				&& (this.getPolEndtId() == castOther.getPolEndtId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPolPolicyId();
		result = 37 * result + (int) this.getPolEndtId();
		return result;
	}

}
