package com.rsaame.pas.b2b.ws.dao.vo;

// default package
// Generated Dec 7, 2018 7:48:29 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Clob;
import java.util.Date;

/**
 * EplatformWsStaging generated by hbm2java
 */
public class EplatformWsStaging implements java.io.Serializable {

	private EplatformWsStagingId id;
	private Long polPolicyNo;
	private Long polEndtNo;
	private Byte polStatus;
	private Date polValidityStartDate;
	private Long polQuotationNo;
	private Long polLinkingId;
	private Long insInsuredCode;
	private Clob quoRequest;
	private Clob quoResponse;
	private Blob quoIntrResponseAdd; //manually added
	private Blob quoIntrBatchResponse;
	private Long twa_id;
	private Byte batchStatus;
	
	
	public Byte getBatchStatus() {
		return batchStatus;
	}
	public void setBatchStatus(Byte batchStatus) {
		this.batchStatus = batchStatus;
	}
	public Long getTwa_id() {
		return twa_id;
	}
	public void setTwa_id(Long twa_id) {
		this.twa_id = twa_id;
	}
	public EplatformWsStagingId getId() {
		return id;
	}
	public void setId(EplatformWsStagingId id) {
		this.id = id;
	}
	public Long getPolPolicyNo() {
		return polPolicyNo;
	}
	public void setPolPolicyNo(Long polPolicyNo) {
		this.polPolicyNo = polPolicyNo;
	}
	public Long getPolEndtNo() {
		return polEndtNo;
	}
	public void setPolEndtNo(Long polEndtNo) {
		this.polEndtNo = polEndtNo;
	}
	public Byte getPolStatus() {
		return polStatus;
	}
	public void setPolStatus(Byte polStatus) {
		this.polStatus = polStatus;
	}
	public Date getPolValidityStartDate() {
		return polValidityStartDate;
	}
	public void setPolValidityStartDate(Date polValidityStartDate) {
		this.polValidityStartDate = polValidityStartDate;
	}
	public Long getPolQuotationNo() {
		return polQuotationNo;
	}
	public void setPolQuotationNo(Long polQuotationNo) {
		this.polQuotationNo = polQuotationNo;
	}
	public Long getPolLinkingId() {
		return polLinkingId;
	}
	public void setPolLinkingId(Long polLinkingId) {
		this.polLinkingId = polLinkingId;
	}
	public Long getInsInsuredCode() {
		return this.insInsuredCode;
	}

	public void setInsInsuredCode(Long insInsuredCode) {
		this.insInsuredCode = insInsuredCode;
	}

	public Clob getQuoRequest() {
		return quoRequest;
	}
	public void setQuoRequest(Clob quoRequest) {
		this.quoRequest = quoRequest;
	}
	public Clob getQuoResponse() {
		return quoResponse;
	}
	public void setQuoResponse(Clob quoResponse) {
		this.quoResponse = quoResponse;
	}
	public Blob getQuoIntrResponseAdd() {
		return quoIntrResponseAdd;
	}
	public void setQuoIntrResponseAdd(Blob quoIntrResponseAdd) {
		this.quoIntrResponseAdd = quoIntrResponseAdd;
	}
	public Blob getQuoIntrBatchResponse() {
		return quoIntrBatchResponse;
	}
	public void setQuoIntrBatchResponse(Blob quoIntrBatchResponse) {
		this.quoIntrBatchResponse = quoIntrBatchResponse;
	}
	
	/*
	private Short polLocationCode;
	private Short polClassCode;
	private Short polDocumentCode;
	private Short polPolicyYear;
	private Long polRefPolicyNo;
	private Short polRefPolicyYear;
	private Short polPolicyType;
	private Long polProposalNo;
	private Date polProposalDate;
	private Date polIssueDate;
	private Date polExpiryDate;
	private Long polCustomerId;
	private Byte polSourceOfBusiness;
	private Long polAgentId;
	private BigDecimal polCommisionId;
	private Boolean polCoinsuranceIndicator;
	private Boolean polCoinsuranceType;
	private Long polCoverNoteNo;
	private Date polCoverNoteDate;
	private BigDecimal polPremium;
	private BigDecimal polGovernmentTax;
	private BigDecimal polPolicyFees;
	private Short polCurrencyCode;
	private BigDecimal polExchangeRate;
	private Date polProcessedDate;
	private Byte polFinancialIntInd;
	private Integer polApprovedBy;
	private Integer polUserId;
	private Date polEffectiveDate;
	private Date polPrintDate;
	private Short polCutCode;
	private Short polSpecialType;
	private Integer polCoverNoteHour;
	private Byte polCoverNoteMin;
	private Integer polIssueHour;
	private BigDecimal polIssueMin;
	private Byte polEffectiveHour;
	private String polEffectiveMin;
	private Long polExpiryHour;
	private Long polExpiryMin;
	private Long polCertificateNo;
	private Date polCertificateDate;
	private Date polValidityExpiryDate;
	private Date polEndtEffectiveDate;
	private Date polEndtExpiryDate;
	private Byte polRatingType;
	private Integer polCcgCode;
	private Integer polCtyCode;
	private Integer polRegCode;
	private Integer polPolicyTerm;
	private Long polRefPolicyId;
	private Integer polAccexecCode;
	private Long polInsuredId;
	private Date polQuotationDate;
	private Short polBrCode;
	private Byte polDctCode;
	private Integer polPreparedBy;
	private Date polPreparedDt;
	private Integer polModifiedBy;
	private Date polModifiedDt;
	private Date polPostedDate;
	private Date polRefreshDate;
	private String polConcPolicyNo;
	private Short polSocCode;
	private Short polTarCode;
	private String polRenTermTxt;
	private Integer polOtherInsurerCode;
	private Short polBusinessType;
	private Date polApprovalDate;
	private String polSuspendTransaction;
	private Long polInsuredCode;
	private Integer polDistributionChnl;
	private Short polRenewalCount;
	private Date polNajExpDate;
	private Short polReasonCode;
	private String polApprovedInd;
	private Long polRenClmCount;
	private Boolean polSbsInd;
	private Integer polProcLocCode;
	private Short polPepCode;
	private Date polPymntDueDate;
	private Date polPpwDate;
	private BigDecimal polFgnCurrPrm;
	private Character polAutoCession;
	private Integer polCcAgentCode;
	private BigDecimal polTechPremium;
	private Integer polSipCode;
	private String polPromoCode;
	private BigDecimal polRiskPremium;
	private String polLicenseLvl;
	private String polCrmQuotRefNo;
	private String polFacInYn;
	private String polDiscLoadFlag;
	private String polQuoteStage;
	private BigDecimal polNcdAmount;
	private Long polSamaUsrType;
	private Date polPrevExpDate;
	private Integer polOrangeIssueBranch;
	private Short polAmlCode;
	private String polCrmExclCountries;
	private Byte polFromAnotherInsurer;
	private String polComConsideration;
	private Boolean polInsuranceInstallment;
	private BigDecimal polLoyaltyDiscount;
	private Byte polLoyaltyDiscountPerc;
	private Byte polVatCode;
	private BigDecimal polVatRate;
	private String polVatRegnNo;
	private BigDecimal polVatAmount;
	private BigDecimal polVatablePrm;
	private BigDecimal polGuaranteeFund;
	private BigDecimal polPremiumBeforeDiscount;
	private Short polDeductionExplanation;
	private Long cshPolicyId;
	private Long cshCustomerId;
	private Byte cshNameTitle;
	private String cshASurnameTribe;
	private String cshESurnameTribe;
	private String cshAName1;
	private String cshEName1;
	private String cshAName2;
	private String cshEName2;
	private String cshAName3;
	private String cshEName3;
	private String cshAName4;
	private String cshEName4;
	private String cshAName5;
	private String cshEName5;
	private String cshAAddress1;
	private String cshEAddress1;
	private String cshAAddress2;
	private String cshEAddress2;
	private String cshAAddress3;
	private String cshEAddress3;
	private String cshAAddress4;
	private String cshEAddress4;
	private String cshAAddress5;
	private String cshEAddress5;
	private String cshAZipCode;
	private String cshEZipCode;
	private String cshAEmailId;
	private String cshEEmailId;
	private Long cshFaxNo;
	private String cshATelexNo;
	private String cshETelexNo;
	private String cshAPhoneNo;
	private String cshEPhoneNo;
	private String cshAGsmNo;
	private String cshEGsmNo;
	private Short cshNationality;
	private Integer cshOcCode;
	private Short cshCcgCode;
	private String cshACoRegnNo;
	private String cshECoRegnNo;
	private String cshAPassportNo;
	private String cshEPassportNo;
	private String cshAIdCardNo;
	private String cshEIdCardNo;
	private String cshAVisaNo;
	private String cshEVisaNo;
	private Integer cshUserId;
	private Date cshValidityStartDate;
	private Date cshValidityExpiryDate;
	private Integer cshCtyCode;
	private Integer cshRegCode;
	private Integer cshLocCode;
	private BigDecimal cshTotAccCode;
	private Long cshInsuredId;
	private Long cshEndtId;
	private Byte cshCutCode;
	private Integer cshPreparedBy;
	private Date cshPreparedDt;
	private Integer cshModifiedBy;
	private Date cshModifiedDt;
	private String cshBusiness;
	private String cshCustType;
	private String cshPoboxNo;
	private Integer cshTerritory;
	private Integer cshLaws;
	private String cshCompanyName;
	private String cshCompanyAddr1;
	private Integer cshIntAccExecCode;
	private Integer cshExtAccExecCode;
	private String cshLegalForm;
	private Date cshDtEstablishment;
	private String cshPlaceEstablishment;
	private Integer cshRegulatoryBody;
	private Integer cshExternalAuditor;
	private Short cshSourceOfCust;
	private Long cshMarketingFee;
	private Date cshDob;
	private String cshPob;
	private String cshAffinityRefNo;
	private Short cshEcmCode;
	private Short cshIdTypCode;
	private String cshIdNo;
	private Integer cshCity;
	private Integer cshCountry;
	private Character cshSex;
	private Short cshBusType;
	private String cshDueDilligence;
	private BigDecimal cshLossRatio;
	private BigDecimal cshLossAmt;
	private Long cshTurnover;
	private Integer cshNoOfEmp;
	private Integer cshProjPropId;
	private BigDecimal cshRoyaltyTypCode;
	private String cshFutureUpdate;
	private Integer cshSponCty;
	private Short cshSponReg;
	private Short cshEAddress6;
	private String cshEAddress7;
	private Integer cshEAddress8;
	private String cshEAddress9;
	private Integer cshEAddress10;
	private Boolean cshWaselInd;
	private Short cshWaselAddr1;
	private Short cshWaselAddr2;
	private Integer cshWaselAddr3;
	private String cshWaselAddr4;
	private String cshWaselAddr5;
	private String cshNationalId;
	private String cshEFullName;
	private Short cshBankId;
	private String cshIban;
	private Integer cshInsTypeSaaed;
	private String cshVatRegnNo;
	private Byte cshQualification;
	private Byte cshMaritalStatus;
	private Byte cshNoOfChildren;
	private Byte cshInsType;
	private Long insInsuredCode;
	private Short insCcgCode;
	private Byte insNameTitle;
	private String insEFirstName;
	private String insAFirstName;
	private String insEMiddleName;
	private String insAMiddleName;
	private String insELastName;
	private String insALastName;
	private String insCompanyName;
	private String insCompanyAddr1;
	private String insCompanyAddr2;
	private String insCompanyAddr3;
	private String insEZipCode;
	private Integer insCtyCode;
	private String insEMobileNo;
	private String insEEmailId;
	private Long insFaxNo;
	private Date insDob;
	private String insPlaceOfBirth;
	private Short insNationality;
	private Integer insOcCode;
	private String insBusiness;
	private String insEPassportNo;
	private String insECoRegnNo;
	private Integer insIntAccExecCode;
	private Integer insExtAccExecCode;
	private String insEPhoneNo;
	private String insWayNo;
	private String insBldgNo;
	private Short insCountry;
	private String insAffinityRefNo;
	private String insCustomerType;
	private String insExcComModes;
	private String insLegalForm;
	private Date insDtEstablishment;
	private String insPlaceEstablishment;
	private Integer insRegulatoryBody;
	private Integer insExternalAuditor;
	private Date insDtCollectionKyc;
	private Date insExpiryDate;
	private String insSuspendCustomer;
	private Integer insDistributionChnl;
	private Short insSourceOfCust;
	private Short insBrCode;
	private Long insAgentCode;
	private Long insCustomerId;
	private Integer insRegCode;
	private Integer insLocCode;
	private Short insIdTypCode;
	private String insIdNo;
	private Long insMarketingFee;
	private String insEAddress;
	private String insAAddress;
	private String insHintQuestion;
	private String insHintAnswer;
	private String insPassword;
	private Integer insStatus;
	private String insEFullName;
	private String insAFullName;
	private String insRemarks;
	private Integer insCity;
	private Integer insPreparedBy;
	private Date insPreparedDt;
	private Integer insModifiedBy;
	private Date insModifiedDt;
	private Long insLinkCode;
	private Character insSex;
	private Long insPostalCode;
	private Long insTurnover;
	private Integer insNoOfEmp;
	private String insSponNo;
	private Integer insSponCty;
	private Short insSponReg;
	private String insDrvLicenseNo;
	private String insDrvLicense;
	private String insTcfNo;
	private Short insAddtlNo;
	private String insResCity;
	private Integer insZipCode;
	private String insZoneName;
	private Integer insUnitNo;
	private Boolean insWaselInd;
	private Short insWaselBldngNo;
	private Short insWaselAddtlNo;
	private Integer insWaselZipCode;
	private String insWaselCity;
	private String insWaselZoneName;
	private String insNationalId;
	private Short insEAddress6;
	private String insEAddress7;
	private Integer insEAddress8;
	private String insEAddress9;
	private Integer insEAddress10;
	private Short insBorderInd;
	private String insVatRegnNo;
	private Byte insVatCode;
	private Integer insVatRegnCnty;
	private Date insVatRegnStartDate;
	private Date insVatRegnEndDate;
	private Byte insNoOfChildren;
	private Byte insQualification;
	private Byte insMaritalStatus;
	private Byte quoImportStatus;
	private Date quoImportDate;
	private Long quoParSecFlag;
	private Long quoPlSecFlag;
	private Long quoWcSecFlag;
	private Long quoDosSecFlag;
	private Long quoMbSecFlag;
	private Long quoEeSecFlag;
	private Long quoBiSecFlag;
	private Long quoTbSecFlag;
	private Long quoGpaSecFlag;
	private Long quoFgSecFlag;
	private Long quoMoneySecFlag;
	
	private Clob quoIntrResponse;
	private Clob quoIntrRequest;
	
*/

/*
	public EplatformWsStaging() {
	}

	public EplatformWsStaging(EplatformWsStagingId id) {
		this.id = id;
	}

	

	public EplatformWsStagingId getId() {
		return this.id;
	}

	public void setId(EplatformWsStagingId id) {
		this.id = id;
	}

	public Short getPolLocationCode() {
		return this.polLocationCode;
	}

	public void setPolLocationCode(Short polLocationCode) {
		this.polLocationCode = polLocationCode;
	}

	public Short getPolClassCode() {
		return this.polClassCode;
	}

	public void setPolClassCode(Short polClassCode) {
		this.polClassCode = polClassCode;
	}

	public Short getPolDocumentCode() {
		return this.polDocumentCode;
	}

	public void setPolDocumentCode(Short polDocumentCode) {
		this.polDocumentCode = polDocumentCode;
	}

	public Long getPolPolicyNo() {
		return this.polPolicyNo;
	}

	public void setPolPolicyNo(Long polPolicyNo) {
		this.polPolicyNo = polPolicyNo;
	}

	public Short getPolPolicyYear() {
		return this.polPolicyYear;
	}

	public void setPolPolicyYear(Short polPolicyYear) {
		this.polPolicyYear = polPolicyYear;
	}

	public Long getPolRefPolicyNo() {
		return this.polRefPolicyNo;
	}

	public void setPolRefPolicyNo(Long polRefPolicyNo) {
		this.polRefPolicyNo = polRefPolicyNo;
	}

	public Short getPolRefPolicyYear() {
		return this.polRefPolicyYear;
	}

	public void setPolRefPolicyYear(Short polRefPolicyYear) {
		this.polRefPolicyYear = polRefPolicyYear;
	}

	public Short getPolPolicyType() {
		return this.polPolicyType;
	}

	public void setPolPolicyType(Short polPolicyType) {
		this.polPolicyType = polPolicyType;
	}

	public Long getPolProposalNo() {
		return this.polProposalNo;
	}

	public void setPolProposalNo(Long polProposalNo) {
		this.polProposalNo = polProposalNo;
	}

	public Date getPolProposalDate() {
		return this.polProposalDate;
	}

	public void setPolProposalDate(Date polProposalDate) {
		this.polProposalDate = polProposalDate;
	}

	public Date getPolIssueDate() {
		return this.polIssueDate;
	}

	public void setPolIssueDate(Date polIssueDate) {
		this.polIssueDate = polIssueDate;
	}

	public Date getPolExpiryDate() {
		return this.polExpiryDate;
	}

	public void setPolExpiryDate(Date polExpiryDate) {
		this.polExpiryDate = polExpiryDate;
	}

	public Long getPolCustomerId() {
		return this.polCustomerId;
	}

	public void setPolCustomerId(Long polCustomerId) {
		this.polCustomerId = polCustomerId;
	}

	public Byte getPolSourceOfBusiness() {
		return this.polSourceOfBusiness;
	}

	public void setPolSourceOfBusiness(Byte polSourceOfBusiness) {
		this.polSourceOfBusiness = polSourceOfBusiness;
	}

	public Long getPolAgentId() {
		return this.polAgentId;
	}

	public void setPolAgentId(Long polAgentId) {
		this.polAgentId = polAgentId;
	}

	public BigDecimal getPolCommisionId() {
		return this.polCommisionId;
	}

	public void setPolCommisionId(BigDecimal polCommisionId) {
		this.polCommisionId = polCommisionId;
	}

	public Boolean getPolCoinsuranceIndicator() {
		return this.polCoinsuranceIndicator;
	}

	public void setPolCoinsuranceIndicator(Boolean polCoinsuranceIndicator) {
		this.polCoinsuranceIndicator = polCoinsuranceIndicator;
	}

	public Boolean getPolCoinsuranceType() {
		return this.polCoinsuranceType;
	}

	public void setPolCoinsuranceType(Boolean polCoinsuranceType) {
		this.polCoinsuranceType = polCoinsuranceType;
	}

	public Long getPolCoverNoteNo() {
		return this.polCoverNoteNo;
	}

	public void setPolCoverNoteNo(Long polCoverNoteNo) {
		this.polCoverNoteNo = polCoverNoteNo;
	}

	public Date getPolCoverNoteDate() {
		return this.polCoverNoteDate;
	}

	public void setPolCoverNoteDate(Date polCoverNoteDate) {
		this.polCoverNoteDate = polCoverNoteDate;
	}

	public BigDecimal getPolPremium() {
		return this.polPremium;
	}

	public void setPolPremium(BigDecimal polPremium) {
		this.polPremium = polPremium;
	}

	public BigDecimal getPolGovernmentTax() {
		return this.polGovernmentTax;
	}

	public void setPolGovernmentTax(BigDecimal polGovernmentTax) {
		this.polGovernmentTax = polGovernmentTax;
	}

	public BigDecimal getPolPolicyFees() {
		return this.polPolicyFees;
	}

	public void setPolPolicyFees(BigDecimal polPolicyFees) {
		this.polPolicyFees = polPolicyFees;
	}

	public Short getPolCurrencyCode() {
		return this.polCurrencyCode;
	}

	public void setPolCurrencyCode(Short polCurrencyCode) {
		this.polCurrencyCode = polCurrencyCode;
	}

	public BigDecimal getPolExchangeRate() {
		return this.polExchangeRate;
	}

	public void setPolExchangeRate(BigDecimal polExchangeRate) {
		this.polExchangeRate = polExchangeRate;
	}

	public Date getPolProcessedDate() {
		return this.polProcessedDate;
	}

	public void setPolProcessedDate(Date polProcessedDate) {
		this.polProcessedDate = polProcessedDate;
	}

	public Byte getPolStatus() {
		return this.polStatus;
	}

	public void setPolStatus(Byte polStatus) {
		this.polStatus = polStatus;
	}

	public Byte getPolFinancialIntInd() {
		return this.polFinancialIntInd;
	}

	public void setPolFinancialIntInd(Byte polFinancialIntInd) {
		this.polFinancialIntInd = polFinancialIntInd;
	}

	public Integer getPolApprovedBy() {
		return this.polApprovedBy;
	}

	public void setPolApprovedBy(Integer polApprovedBy) {
		this.polApprovedBy = polApprovedBy;
	}

	public Integer getPolUserId() {
		return this.polUserId;
	}

	public void setPolUserId(Integer polUserId) {
		this.polUserId = polUserId;
	}

	public Date getPolEffectiveDate() {
		return this.polEffectiveDate;
	}

	public void setPolEffectiveDate(Date polEffectiveDate) {
		this.polEffectiveDate = polEffectiveDate;
	}

	public Date getPolPrintDate() {
		return this.polPrintDate;
	}

	public void setPolPrintDate(Date polPrintDate) {
		this.polPrintDate = polPrintDate;
	}

	public Short getPolCutCode() {
		return this.polCutCode;
	}

	public void setPolCutCode(Short polCutCode) {
		this.polCutCode = polCutCode;
	}

	public Short getPolSpecialType() {
		return this.polSpecialType;
	}

	public void setPolSpecialType(Short polSpecialType) {
		this.polSpecialType = polSpecialType;
	}

	public Integer getPolCoverNoteHour() {
		return this.polCoverNoteHour;
	}

	public void setPolCoverNoteHour(Integer polCoverNoteHour) {
		this.polCoverNoteHour = polCoverNoteHour;
	}

	public Byte getPolCoverNoteMin() {
		return this.polCoverNoteMin;
	}

	public void setPolCoverNoteMin(Byte polCoverNoteMin) {
		this.polCoverNoteMin = polCoverNoteMin;
	}

	public Integer getPolIssueHour() {
		return this.polIssueHour;
	}

	public void setPolIssueHour(Integer polIssueHour) {
		this.polIssueHour = polIssueHour;
	}

	public BigDecimal getPolIssueMin() {
		return this.polIssueMin;
	}

	public void setPolIssueMin(BigDecimal polIssueMin) {
		this.polIssueMin = polIssueMin;
	}

	public Byte getPolEffectiveHour() {
		return this.polEffectiveHour;
	}

	public void setPolEffectiveHour(Byte polEffectiveHour) {
		this.polEffectiveHour = polEffectiveHour;
	}

	public String getPolEffectiveMin() {
		return this.polEffectiveMin;
	}

	public void setPolEffectiveMin(String polEffectiveMin) {
		this.polEffectiveMin = polEffectiveMin;
	}

	public Long getPolExpiryHour() {
		return this.polExpiryHour;
	}

	public void setPolExpiryHour(Long polExpiryHour) {
		this.polExpiryHour = polExpiryHour;
	}

	public Long getPolExpiryMin() {
		return this.polExpiryMin;
	}

	public void setPolExpiryMin(Long polExpiryMin) {
		this.polExpiryMin = polExpiryMin;
	}

	public Long getPolCertificateNo() {
		return this.polCertificateNo;
	}

	public void setPolCertificateNo(Long polCertificateNo) {
		this.polCertificateNo = polCertificateNo;
	}

	public Date getPolCertificateDate() {
		return this.polCertificateDate;
	}

	public void setPolCertificateDate(Date polCertificateDate) {
		this.polCertificateDate = polCertificateDate;
	}

	public Date getPolValidityStartDate() {
		return this.polValidityStartDate;
	}

	public void setPolValidityStartDate(Date polValidityStartDate) {
		this.polValidityStartDate = polValidityStartDate;
	}

	public Date getPolValidityExpiryDate() {
		return this.polValidityExpiryDate;
	}

	public void setPolValidityExpiryDate(Date polValidityExpiryDate) {
		this.polValidityExpiryDate = polValidityExpiryDate;
	}

	public Date getPolEndtEffectiveDate() {
		return this.polEndtEffectiveDate;
	}

	public void setPolEndtEffectiveDate(Date polEndtEffectiveDate) {
		this.polEndtEffectiveDate = polEndtEffectiveDate;
	}

	public Date getPolEndtExpiryDate() {
		return this.polEndtExpiryDate;
	}

	public void setPolEndtExpiryDate(Date polEndtExpiryDate) {
		this.polEndtExpiryDate = polEndtExpiryDate;
	}

	public Byte getPolRatingType() {
		return this.polRatingType;
	}

	public void setPolRatingType(Byte polRatingType) {
		this.polRatingType = polRatingType;
	}

	public Integer getPolCcgCode() {
		return this.polCcgCode;
	}

	public void setPolCcgCode(Integer polCcgCode) {
		this.polCcgCode = polCcgCode;
	}

	public Long getPolEndtNo() {
		return this.polEndtNo;
	}

	public void setPolEndtNo(Long polEndtNo) {
		this.polEndtNo = polEndtNo;
	}

	public Integer getPolCtyCode() {
		return this.polCtyCode;
	}

	public void setPolCtyCode(Integer polCtyCode) {
		this.polCtyCode = polCtyCode;
	}

	public Integer getPolRegCode() {
		return this.polRegCode;
	}

	public void setPolRegCode(Integer polRegCode) {
		this.polRegCode = polRegCode;
	}

	public Integer getPolPolicyTerm() {
		return this.polPolicyTerm;
	}

	public void setPolPolicyTerm(Integer polPolicyTerm) {
		this.polPolicyTerm = polPolicyTerm;
	}

	public Long getPolRefPolicyId() {
		return this.polRefPolicyId;
	}

	public void setPolRefPolicyId(Long polRefPolicyId) {
		this.polRefPolicyId = polRefPolicyId;
	}

	public Integer getPolAccexecCode() {
		return this.polAccexecCode;
	}

	public void setPolAccexecCode(Integer polAccexecCode) {
		this.polAccexecCode = polAccexecCode;
	}

	public Long getPolInsuredId() {
		return this.polInsuredId;
	}

	public void setPolInsuredId(Long polInsuredId) {
		this.polInsuredId = polInsuredId;
	}

	public Long getPolQuotationNo() {
		return this.polQuotationNo;
	}

	public void setPolQuotationNo(Long polQuotationNo) {
		this.polQuotationNo = polQuotationNo;
	}

	public Date getPolQuotationDate() {
		return this.polQuotationDate;
	}

	public void setPolQuotationDate(Date polQuotationDate) {
		this.polQuotationDate = polQuotationDate;
	}

	public Short getPolBrCode() {
		return this.polBrCode;
	}

	public void setPolBrCode(Short polBrCode) {
		this.polBrCode = polBrCode;
	}

	public Byte getPolDctCode() {
		return this.polDctCode;
	}

	public void setPolDctCode(Byte polDctCode) {
		this.polDctCode = polDctCode;
	}

	public Integer getPolPreparedBy() {
		return this.polPreparedBy;
	}

	public void setPolPreparedBy(Integer polPreparedBy) {
		this.polPreparedBy = polPreparedBy;
	}

	public Date getPolPreparedDt() {
		return this.polPreparedDt;
	}

	public void setPolPreparedDt(Date polPreparedDt) {
		this.polPreparedDt = polPreparedDt;
	}

	public Integer getPolModifiedBy() {
		return this.polModifiedBy;
	}

	public void setPolModifiedBy(Integer polModifiedBy) {
		this.polModifiedBy = polModifiedBy;
	}

	public Date getPolModifiedDt() {
		return this.polModifiedDt;
	}

	public void setPolModifiedDt(Date polModifiedDt) {
		this.polModifiedDt = polModifiedDt;
	}

	public Date getPolPostedDate() {
		return this.polPostedDate;
	}

	public void setPolPostedDate(Date polPostedDate) {
		this.polPostedDate = polPostedDate;
	}

	public Date getPolRefreshDate() {
		return this.polRefreshDate;
	}

	public void setPolRefreshDate(Date polRefreshDate) {
		this.polRefreshDate = polRefreshDate;
	}

	public String getPolConcPolicyNo() {
		return this.polConcPolicyNo;
	}

	public void setPolConcPolicyNo(String polConcPolicyNo) {
		this.polConcPolicyNo = polConcPolicyNo;
	}

	public Short getPolSocCode() {
		return this.polSocCode;
	}

	public void setPolSocCode(Short polSocCode) {
		this.polSocCode = polSocCode;
	}

	public Short getPolTarCode() {
		return this.polTarCode;
	}

	public void setPolTarCode(Short polTarCode) {
		this.polTarCode = polTarCode;
	}

	public String getPolRenTermTxt() {
		return this.polRenTermTxt;
	}

	public void setPolRenTermTxt(String polRenTermTxt) {
		this.polRenTermTxt = polRenTermTxt;
	}

	public Integer getPolOtherInsurerCode() {
		return this.polOtherInsurerCode;
	}

	public void setPolOtherInsurerCode(Integer polOtherInsurerCode) {
		this.polOtherInsurerCode = polOtherInsurerCode;
	}

	public Short getPolBusinessType() {
		return this.polBusinessType;
	}

	public void setPolBusinessType(Short polBusinessType) {
		this.polBusinessType = polBusinessType;
	}

	public Date getPolApprovalDate() {
		return this.polApprovalDate;
	}

	public void setPolApprovalDate(Date polApprovalDate) {
		this.polApprovalDate = polApprovalDate;
	}

	public String getPolSuspendTransaction() {
		return this.polSuspendTransaction;
	}

	public void setPolSuspendTransaction(String polSuspendTransaction) {
		this.polSuspendTransaction = polSuspendTransaction;
	}

	public Long getPolInsuredCode() {
		return this.polInsuredCode;
	}

	public void setPolInsuredCode(Long polInsuredCode) {
		this.polInsuredCode = polInsuredCode;
	}

	public Integer getPolDistributionChnl() {
		return this.polDistributionChnl;
	}

	public void setPolDistributionChnl(Integer polDistributionChnl) {
		this.polDistributionChnl = polDistributionChnl;
	}

	public Short getPolRenewalCount() {
		return this.polRenewalCount;
	}

	public void setPolRenewalCount(Short polRenewalCount) {
		this.polRenewalCount = polRenewalCount;
	}

	public Date getPolNajExpDate() {
		return this.polNajExpDate;
	}

	public void setPolNajExpDate(Date polNajExpDate) {
		this.polNajExpDate = polNajExpDate;
	}

	public Short getPolReasonCode() {
		return this.polReasonCode;
	}

	public void setPolReasonCode(Short polReasonCode) {
		this.polReasonCode = polReasonCode;
	}

	public String getPolApprovedInd() {
		return this.polApprovedInd;
	}

	public void setPolApprovedInd(String polApprovedInd) {
		this.polApprovedInd = polApprovedInd;
	}

	public Long getPolLinkingId() {
		return this.polLinkingId;
	}

	public void setPolLinkingId(Long polLinkingId) {
		this.polLinkingId = polLinkingId;
	}

	public Long getPolRenClmCount() {
		return this.polRenClmCount;
	}

	public void setPolRenClmCount(Long polRenClmCount) {
		this.polRenClmCount = polRenClmCount;
	}

	public Boolean getPolSbsInd() {
		return this.polSbsInd;
	}

	public void setPolSbsInd(Boolean polSbsInd) {
		this.polSbsInd = polSbsInd;
	}

	public Integer getPolProcLocCode() {
		return this.polProcLocCode;
	}

	public void setPolProcLocCode(Integer polProcLocCode) {
		this.polProcLocCode = polProcLocCode;
	}

	public Short getPolPepCode() {
		return this.polPepCode;
	}

	public void setPolPepCode(Short polPepCode) {
		this.polPepCode = polPepCode;
	}

	public Date getPolPymntDueDate() {
		return this.polPymntDueDate;
	}

	public void setPolPymntDueDate(Date polPymntDueDate) {
		this.polPymntDueDate = polPymntDueDate;
	}

	public Date getPolPpwDate() {
		return this.polPpwDate;
	}

	public void setPolPpwDate(Date polPpwDate) {
		this.polPpwDate = polPpwDate;
	}

	public BigDecimal getPolFgnCurrPrm() {
		return this.polFgnCurrPrm;
	}

	public void setPolFgnCurrPrm(BigDecimal polFgnCurrPrm) {
		this.polFgnCurrPrm = polFgnCurrPrm;
	}

	public Character getPolAutoCession() {
		return this.polAutoCession;
	}

	public void setPolAutoCession(Character polAutoCession) {
		this.polAutoCession = polAutoCession;
	}

	public Integer getPolCcAgentCode() {
		return this.polCcAgentCode;
	}

	public void setPolCcAgentCode(Integer polCcAgentCode) {
		this.polCcAgentCode = polCcAgentCode;
	}

	public BigDecimal getPolTechPremium() {
		return this.polTechPremium;
	}

	public void setPolTechPremium(BigDecimal polTechPremium) {
		this.polTechPremium = polTechPremium;
	}

	public Integer getPolSipCode() {
		return this.polSipCode;
	}

	public void setPolSipCode(Integer polSipCode) {
		this.polSipCode = polSipCode;
	}

	public String getPolPromoCode() {
		return this.polPromoCode;
	}

	public void setPolPromoCode(String polPromoCode) {
		this.polPromoCode = polPromoCode;
	}

	public BigDecimal getPolRiskPremium() {
		return this.polRiskPremium;
	}

	public void setPolRiskPremium(BigDecimal polRiskPremium) {
		this.polRiskPremium = polRiskPremium;
	}

	public String getPolLicenseLvl() {
		return this.polLicenseLvl;
	}

	public void setPolLicenseLvl(String polLicenseLvl) {
		this.polLicenseLvl = polLicenseLvl;
	}

	public String getPolCrmQuotRefNo() {
		return this.polCrmQuotRefNo;
	}

	public void setPolCrmQuotRefNo(String polCrmQuotRefNo) {
		this.polCrmQuotRefNo = polCrmQuotRefNo;
	}

	public String getPolFacInYn() {
		return this.polFacInYn;
	}

	public void setPolFacInYn(String polFacInYn) {
		this.polFacInYn = polFacInYn;
	}

	public String getPolDiscLoadFlag() {
		return this.polDiscLoadFlag;
	}

	public void setPolDiscLoadFlag(String polDiscLoadFlag) {
		this.polDiscLoadFlag = polDiscLoadFlag;
	}

	public String getPolQuoteStage() {
		return this.polQuoteStage;
	}

	public void setPolQuoteStage(String polQuoteStage) {
		this.polQuoteStage = polQuoteStage;
	}

	public BigDecimal getPolNcdAmount() {
		return this.polNcdAmount;
	}

	public void setPolNcdAmount(BigDecimal polNcdAmount) {
		this.polNcdAmount = polNcdAmount;
	}

	public Long getPolSamaUsrType() {
		return this.polSamaUsrType;
	}

	public void setPolSamaUsrType(Long polSamaUsrType) {
		this.polSamaUsrType = polSamaUsrType;
	}

	public Date getPolPrevExpDate() {
		return this.polPrevExpDate;
	}

	public void setPolPrevExpDate(Date polPrevExpDate) {
		this.polPrevExpDate = polPrevExpDate;
	}

	public Integer getPolOrangeIssueBranch() {
		return this.polOrangeIssueBranch;
	}

	public void setPolOrangeIssueBranch(Integer polOrangeIssueBranch) {
		this.polOrangeIssueBranch = polOrangeIssueBranch;
	}

	public Short getPolAmlCode() {
		return this.polAmlCode;
	}

	public void setPolAmlCode(Short polAmlCode) {
		this.polAmlCode = polAmlCode;
	}

	public String getPolCrmExclCountries() {
		return this.polCrmExclCountries;
	}

	public void setPolCrmExclCountries(String polCrmExclCountries) {
		this.polCrmExclCountries = polCrmExclCountries;
	}

	public Byte getPolFromAnotherInsurer() {
		return this.polFromAnotherInsurer;
	}

	public void setPolFromAnotherInsurer(Byte polFromAnotherInsurer) {
		this.polFromAnotherInsurer = polFromAnotherInsurer;
	}

	public String getPolComConsideration() {
		return this.polComConsideration;
	}

	public void setPolComConsideration(String polComConsideration) {
		this.polComConsideration = polComConsideration;
	}

	public Boolean getPolInsuranceInstallment() {
		return this.polInsuranceInstallment;
	}

	public void setPolInsuranceInstallment(Boolean polInsuranceInstallment) {
		this.polInsuranceInstallment = polInsuranceInstallment;
	}

	public BigDecimal getPolLoyaltyDiscount() {
		return this.polLoyaltyDiscount;
	}

	public void setPolLoyaltyDiscount(BigDecimal polLoyaltyDiscount) {
		this.polLoyaltyDiscount = polLoyaltyDiscount;
	}

	public Byte getPolLoyaltyDiscountPerc() {
		return this.polLoyaltyDiscountPerc;
	}

	public void setPolLoyaltyDiscountPerc(Byte polLoyaltyDiscountPerc) {
		this.polLoyaltyDiscountPerc = polLoyaltyDiscountPerc;
	}

	public Byte getPolVatCode() {
		return this.polVatCode;
	}

	public void setPolVatCode(Byte polVatCode) {
		this.polVatCode = polVatCode;
	}

	public BigDecimal getPolVatRate() {
		return this.polVatRate;
	}

	public void setPolVatRate(BigDecimal polVatRate) {
		this.polVatRate = polVatRate;
	}

	public String getPolVatRegnNo() {
		return this.polVatRegnNo;
	}

	public void setPolVatRegnNo(String polVatRegnNo) {
		this.polVatRegnNo = polVatRegnNo;
	}

	public BigDecimal getPolVatAmount() {
		return this.polVatAmount;
	}

	public void setPolVatAmount(BigDecimal polVatAmount) {
		this.polVatAmount = polVatAmount;
	}

	public BigDecimal getPolVatablePrm() {
		return this.polVatablePrm;
	}

	public void setPolVatablePrm(BigDecimal polVatablePrm) {
		this.polVatablePrm = polVatablePrm;
	}

	public BigDecimal getPolGuaranteeFund() {
		return this.polGuaranteeFund;
	}

	public void setPolGuaranteeFund(BigDecimal polGuaranteeFund) {
		this.polGuaranteeFund = polGuaranteeFund;
	}

	public BigDecimal getPolPremiumBeforeDiscount() {
		return this.polPremiumBeforeDiscount;
	}

	public void setPolPremiumBeforeDiscount(BigDecimal polPremiumBeforeDiscount) {
		this.polPremiumBeforeDiscount = polPremiumBeforeDiscount;
	}

	public Short getPolDeductionExplanation() {
		return this.polDeductionExplanation;
	}

	public void setPolDeductionExplanation(Short polDeductionExplanation) {
		this.polDeductionExplanation = polDeductionExplanation;
	}

	public Long getCshPolicyId() {
		return this.cshPolicyId;
	}

	public void setCshPolicyId(Long cshPolicyId) {
		this.cshPolicyId = cshPolicyId;
	}

	public Long getCshCustomerId() {
		return this.cshCustomerId;
	}

	public void setCshCustomerId(Long cshCustomerId) {
		this.cshCustomerId = cshCustomerId;
	}

	public Byte getCshNameTitle() {
		return this.cshNameTitle;
	}

	public void setCshNameTitle(Byte cshNameTitle) {
		this.cshNameTitle = cshNameTitle;
	}

	public String getCshASurnameTribe() {
		return this.cshASurnameTribe;
	}

	public void setCshASurnameTribe(String cshASurnameTribe) {
		this.cshASurnameTribe = cshASurnameTribe;
	}

	public String getCshESurnameTribe() {
		return this.cshESurnameTribe;
	}

	public void setCshESurnameTribe(String cshESurnameTribe) {
		this.cshESurnameTribe = cshESurnameTribe;
	}

	public String getCshAName1() {
		return this.cshAName1;
	}

	public void setCshAName1(String cshAName1) {
		this.cshAName1 = cshAName1;
	}

	public String getCshEName1() {
		return this.cshEName1;
	}

	public void setCshEName1(String cshEName1) {
		this.cshEName1 = cshEName1;
	}

	public String getCshAName2() {
		return this.cshAName2;
	}

	public void setCshAName2(String cshAName2) {
		this.cshAName2 = cshAName2;
	}

	public String getCshEName2() {
		return this.cshEName2;
	}

	public void setCshEName2(String cshEName2) {
		this.cshEName2 = cshEName2;
	}

	public String getCshAName3() {
		return this.cshAName3;
	}

	public void setCshAName3(String cshAName3) {
		this.cshAName3 = cshAName3;
	}

	public String getCshEName3() {
		return this.cshEName3;
	}

	public void setCshEName3(String cshEName3) {
		this.cshEName3 = cshEName3;
	}

	public String getCshAName4() {
		return this.cshAName4;
	}

	public void setCshAName4(String cshAName4) {
		this.cshAName4 = cshAName4;
	}

	public String getCshEName4() {
		return this.cshEName4;
	}

	public void setCshEName4(String cshEName4) {
		this.cshEName4 = cshEName4;
	}

	public String getCshAName5() {
		return this.cshAName5;
	}

	public void setCshAName5(String cshAName5) {
		this.cshAName5 = cshAName5;
	}

	public String getCshEName5() {
		return this.cshEName5;
	}

	public void setCshEName5(String cshEName5) {
		this.cshEName5 = cshEName5;
	}

	public String getCshAAddress1() {
		return this.cshAAddress1;
	}

	public void setCshAAddress1(String cshAAddress1) {
		this.cshAAddress1 = cshAAddress1;
	}

	public String getCshEAddress1() {
		return this.cshEAddress1;
	}

	public void setCshEAddress1(String cshEAddress1) {
		this.cshEAddress1 = cshEAddress1;
	}

	public String getCshAAddress2() {
		return this.cshAAddress2;
	}

	public void setCshAAddress2(String cshAAddress2) {
		this.cshAAddress2 = cshAAddress2;
	}

	public String getCshEAddress2() {
		return this.cshEAddress2;
	}

	public void setCshEAddress2(String cshEAddress2) {
		this.cshEAddress2 = cshEAddress2;
	}

	public String getCshAAddress3() {
		return this.cshAAddress3;
	}

	public void setCshAAddress3(String cshAAddress3) {
		this.cshAAddress3 = cshAAddress3;
	}

	public String getCshEAddress3() {
		return this.cshEAddress3;
	}

	public void setCshEAddress3(String cshEAddress3) {
		this.cshEAddress3 = cshEAddress3;
	}

	public String getCshAAddress4() {
		return this.cshAAddress4;
	}

	public void setCshAAddress4(String cshAAddress4) {
		this.cshAAddress4 = cshAAddress4;
	}

	public String getCshEAddress4() {
		return this.cshEAddress4;
	}

	public void setCshEAddress4(String cshEAddress4) {
		this.cshEAddress4 = cshEAddress4;
	}

	public String getCshAAddress5() {
		return this.cshAAddress5;
	}

	public void setCshAAddress5(String cshAAddress5) {
		this.cshAAddress5 = cshAAddress5;
	}

	public String getCshEAddress5() {
		return this.cshEAddress5;
	}

	public void setCshEAddress5(String cshEAddress5) {
		this.cshEAddress5 = cshEAddress5;
	}

	public String getCshAZipCode() {
		return this.cshAZipCode;
	}

	public void setCshAZipCode(String cshAZipCode) {
		this.cshAZipCode = cshAZipCode;
	}

	public String getCshEZipCode() {
		return this.cshEZipCode;
	}

	public void setCshEZipCode(String cshEZipCode) {
		this.cshEZipCode = cshEZipCode;
	}

	public String getCshAEmailId() {
		return this.cshAEmailId;
	}

	public void setCshAEmailId(String cshAEmailId) {
		this.cshAEmailId = cshAEmailId;
	}

	public String getCshEEmailId() {
		return this.cshEEmailId;
	}

	public void setCshEEmailId(String cshEEmailId) {
		this.cshEEmailId = cshEEmailId;
	}

	public Long getCshFaxNo() {
		return this.cshFaxNo;
	}

	public void setCshFaxNo(Long cshFaxNo) {
		this.cshFaxNo = cshFaxNo;
	}

	public String getCshATelexNo() {
		return this.cshATelexNo;
	}

	public void setCshATelexNo(String cshATelexNo) {
		this.cshATelexNo = cshATelexNo;
	}

	public String getCshETelexNo() {
		return this.cshETelexNo;
	}

	public void setCshETelexNo(String cshETelexNo) {
		this.cshETelexNo = cshETelexNo;
	}

	public String getCshAPhoneNo() {
		return this.cshAPhoneNo;
	}

	public void setCshAPhoneNo(String cshAPhoneNo) {
		this.cshAPhoneNo = cshAPhoneNo;
	}

	public String getCshEPhoneNo() {
		return this.cshEPhoneNo;
	}

	public void setCshEPhoneNo(String cshEPhoneNo) {
		this.cshEPhoneNo = cshEPhoneNo;
	}

	public String getCshAGsmNo() {
		return this.cshAGsmNo;
	}

	public void setCshAGsmNo(String cshAGsmNo) {
		this.cshAGsmNo = cshAGsmNo;
	}

	public String getCshEGsmNo() {
		return this.cshEGsmNo;
	}

	public void setCshEGsmNo(String cshEGsmNo) {
		this.cshEGsmNo = cshEGsmNo;
	}

	public Short getCshNationality() {
		return this.cshNationality;
	}

	public void setCshNationality(Short cshNationality) {
		this.cshNationality = cshNationality;
	}

	public Integer getCshOcCode() {
		return this.cshOcCode;
	}

	public void setCshOcCode(Integer cshOcCode) {
		this.cshOcCode = cshOcCode;
	}

	public Short getCshCcgCode() {
		return this.cshCcgCode;
	}

	public void setCshCcgCode(Short cshCcgCode) {
		this.cshCcgCode = cshCcgCode;
	}

	public String getCshACoRegnNo() {
		return this.cshACoRegnNo;
	}

	public void setCshACoRegnNo(String cshACoRegnNo) {
		this.cshACoRegnNo = cshACoRegnNo;
	}

	public String getCshECoRegnNo() {
		return this.cshECoRegnNo;
	}

	public void setCshECoRegnNo(String cshECoRegnNo) {
		this.cshECoRegnNo = cshECoRegnNo;
	}

	public String getCshAPassportNo() {
		return this.cshAPassportNo;
	}

	public void setCshAPassportNo(String cshAPassportNo) {
		this.cshAPassportNo = cshAPassportNo;
	}

	public String getCshEPassportNo() {
		return this.cshEPassportNo;
	}

	public void setCshEPassportNo(String cshEPassportNo) {
		this.cshEPassportNo = cshEPassportNo;
	}

	public String getCshAIdCardNo() {
		return this.cshAIdCardNo;
	}

	public void setCshAIdCardNo(String cshAIdCardNo) {
		this.cshAIdCardNo = cshAIdCardNo;
	}

	public String getCshEIdCardNo() {
		return this.cshEIdCardNo;
	}

	public void setCshEIdCardNo(String cshEIdCardNo) {
		this.cshEIdCardNo = cshEIdCardNo;
	}

	public String getCshAVisaNo() {
		return this.cshAVisaNo;
	}

	public void setCshAVisaNo(String cshAVisaNo) {
		this.cshAVisaNo = cshAVisaNo;
	}

	public String getCshEVisaNo() {
		return this.cshEVisaNo;
	}

	public void setCshEVisaNo(String cshEVisaNo) {
		this.cshEVisaNo = cshEVisaNo;
	}

	public Integer getCshUserId() {
		return this.cshUserId;
	}

	public void setCshUserId(Integer cshUserId) {
		this.cshUserId = cshUserId;
	}

	public Date getCshValidityStartDate() {
		return this.cshValidityStartDate;
	}

	public void setCshValidityStartDate(Date cshValidityStartDate) {
		this.cshValidityStartDate = cshValidityStartDate;
	}

	public Date getCshValidityExpiryDate() {
		return this.cshValidityExpiryDate;
	}

	public void setCshValidityExpiryDate(Date cshValidityExpiryDate) {
		this.cshValidityExpiryDate = cshValidityExpiryDate;
	}

	public Integer getCshCtyCode() {
		return this.cshCtyCode;
	}

	public void setCshCtyCode(Integer cshCtyCode) {
		this.cshCtyCode = cshCtyCode;
	}

	public Integer getCshRegCode() {
		return this.cshRegCode;
	}

	public void setCshRegCode(Integer cshRegCode) {
		this.cshRegCode = cshRegCode;
	}

	public Integer getCshLocCode() {
		return this.cshLocCode;
	}

	public void setCshLocCode(Integer cshLocCode) {
		this.cshLocCode = cshLocCode;
	}

	public BigDecimal getCshTotAccCode() {
		return this.cshTotAccCode;
	}

	public void setCshTotAccCode(BigDecimal cshTotAccCode) {
		this.cshTotAccCode = cshTotAccCode;
	}

	public Long getCshInsuredId() {
		return this.cshInsuredId;
	}

	public void setCshInsuredId(Long cshInsuredId) {
		this.cshInsuredId = cshInsuredId;
	}

	public Long getCshEndtId() {
		return this.cshEndtId;
	}

	public void setCshEndtId(Long cshEndtId) {
		this.cshEndtId = cshEndtId;
	}

	public Byte getCshCutCode() {
		return this.cshCutCode;
	}

	public void setCshCutCode(Byte cshCutCode) {
		this.cshCutCode = cshCutCode;
	}

	public Integer getCshPreparedBy() {
		return this.cshPreparedBy;
	}

	public void setCshPreparedBy(Integer cshPreparedBy) {
		this.cshPreparedBy = cshPreparedBy;
	}

	public Date getCshPreparedDt() {
		return this.cshPreparedDt;
	}

	public void setCshPreparedDt(Date cshPreparedDt) {
		this.cshPreparedDt = cshPreparedDt;
	}

	public Integer getCshModifiedBy() {
		return this.cshModifiedBy;
	}

	public void setCshModifiedBy(Integer cshModifiedBy) {
		this.cshModifiedBy = cshModifiedBy;
	}

	public Date getCshModifiedDt() {
		return this.cshModifiedDt;
	}

	public void setCshModifiedDt(Date cshModifiedDt) {
		this.cshModifiedDt = cshModifiedDt;
	}

	public String getCshBusiness() {
		return this.cshBusiness;
	}

	public void setCshBusiness(String cshBusiness) {
		this.cshBusiness = cshBusiness;
	}

	public String getCshCustType() {
		return this.cshCustType;
	}

	public void setCshCustType(String cshCustType) {
		this.cshCustType = cshCustType;
	}

	public String getCshPoboxNo() {
		return this.cshPoboxNo;
	}

	public void setCshPoboxNo(String cshPoboxNo) {
		this.cshPoboxNo = cshPoboxNo;
	}

	public Integer getCshTerritory() {
		return this.cshTerritory;
	}

	public void setCshTerritory(Integer cshTerritory) {
		this.cshTerritory = cshTerritory;
	}

	public Integer getCshLaws() {
		return this.cshLaws;
	}

	public void setCshLaws(Integer cshLaws) {
		this.cshLaws = cshLaws;
	}

	public String getCshCompanyName() {
		return this.cshCompanyName;
	}

	public void setCshCompanyName(String cshCompanyName) {
		this.cshCompanyName = cshCompanyName;
	}

	public String getCshCompanyAddr1() {
		return this.cshCompanyAddr1;
	}

	public void setCshCompanyAddr1(String cshCompanyAddr1) {
		this.cshCompanyAddr1 = cshCompanyAddr1;
	}

	public Integer getCshIntAccExecCode() {
		return this.cshIntAccExecCode;
	}

	public void setCshIntAccExecCode(Integer cshIntAccExecCode) {
		this.cshIntAccExecCode = cshIntAccExecCode;
	}

	public Integer getCshExtAccExecCode() {
		return this.cshExtAccExecCode;
	}

	public void setCshExtAccExecCode(Integer cshExtAccExecCode) {
		this.cshExtAccExecCode = cshExtAccExecCode;
	}

	public String getCshLegalForm() {
		return this.cshLegalForm;
	}

	public void setCshLegalForm(String cshLegalForm) {
		this.cshLegalForm = cshLegalForm;
	}

	public Date getCshDtEstablishment() {
		return this.cshDtEstablishment;
	}

	public void setCshDtEstablishment(Date cshDtEstablishment) {
		this.cshDtEstablishment = cshDtEstablishment;
	}

	public String getCshPlaceEstablishment() {
		return this.cshPlaceEstablishment;
	}

	public void setCshPlaceEstablishment(String cshPlaceEstablishment) {
		this.cshPlaceEstablishment = cshPlaceEstablishment;
	}

	public Integer getCshRegulatoryBody() {
		return this.cshRegulatoryBody;
	}

	public void setCshRegulatoryBody(Integer cshRegulatoryBody) {
		this.cshRegulatoryBody = cshRegulatoryBody;
	}

	public Integer getCshExternalAuditor() {
		return this.cshExternalAuditor;
	}

	public void setCshExternalAuditor(Integer cshExternalAuditor) {
		this.cshExternalAuditor = cshExternalAuditor;
	}

	public Short getCshSourceOfCust() {
		return this.cshSourceOfCust;
	}

	public void setCshSourceOfCust(Short cshSourceOfCust) {
		this.cshSourceOfCust = cshSourceOfCust;
	}

	public Long getCshMarketingFee() {
		return this.cshMarketingFee;
	}

	public void setCshMarketingFee(Long cshMarketingFee) {
		this.cshMarketingFee = cshMarketingFee;
	}

	public Date getCshDob() {
		return this.cshDob;
	}

	public void setCshDob(Date cshDob) {
		this.cshDob = cshDob;
	}

	public String getCshPob() {
		return this.cshPob;
	}

	public void setCshPob(String cshPob) {
		this.cshPob = cshPob;
	}

	public String getCshAffinityRefNo() {
		return this.cshAffinityRefNo;
	}

	public void setCshAffinityRefNo(String cshAffinityRefNo) {
		this.cshAffinityRefNo = cshAffinityRefNo;
	}

	public Short getCshEcmCode() {
		return this.cshEcmCode;
	}

	public void setCshEcmCode(Short cshEcmCode) {
		this.cshEcmCode = cshEcmCode;
	}

	public Short getCshIdTypCode() {
		return this.cshIdTypCode;
	}

	public void setCshIdTypCode(Short cshIdTypCode) {
		this.cshIdTypCode = cshIdTypCode;
	}

	public String getCshIdNo() {
		return this.cshIdNo;
	}

	public void setCshIdNo(String cshIdNo) {
		this.cshIdNo = cshIdNo;
	}

	public Integer getCshCity() {
		return this.cshCity;
	}

	public void setCshCity(Integer cshCity) {
		this.cshCity = cshCity;
	}

	public Integer getCshCountry() {
		return this.cshCountry;
	}

	public void setCshCountry(Integer cshCountry) {
		this.cshCountry = cshCountry;
	}

	public Character getCshSex() {
		return this.cshSex;
	}

	public void setCshSex(Character cshSex) {
		this.cshSex = cshSex;
	}

	public Short getCshBusType() {
		return this.cshBusType;
	}

	public void setCshBusType(Short cshBusType) {
		this.cshBusType = cshBusType;
	}

	public String getCshDueDilligence() {
		return this.cshDueDilligence;
	}

	public void setCshDueDilligence(String cshDueDilligence) {
		this.cshDueDilligence = cshDueDilligence;
	}

	public BigDecimal getCshLossRatio() {
		return this.cshLossRatio;
	}

	public void setCshLossRatio(BigDecimal cshLossRatio) {
		this.cshLossRatio = cshLossRatio;
	}

	public BigDecimal getCshLossAmt() {
		return this.cshLossAmt;
	}

	public void setCshLossAmt(BigDecimal cshLossAmt) {
		this.cshLossAmt = cshLossAmt;
	}

	public Long getCshTurnover() {
		return this.cshTurnover;
	}

	public void setCshTurnover(Long cshTurnover) {
		this.cshTurnover = cshTurnover;
	}

	public Integer getCshNoOfEmp() {
		return this.cshNoOfEmp;
	}

	public void setCshNoOfEmp(Integer cshNoOfEmp) {
		this.cshNoOfEmp = cshNoOfEmp;
	}

	public Integer getCshProjPropId() {
		return this.cshProjPropId;
	}

	public void setCshProjPropId(Integer cshProjPropId) {
		this.cshProjPropId = cshProjPropId;
	}

	public BigDecimal getCshRoyaltyTypCode() {
		return this.cshRoyaltyTypCode;
	}

	public void setCshRoyaltyTypCode(BigDecimal cshRoyaltyTypCode) {
		this.cshRoyaltyTypCode = cshRoyaltyTypCode;
	}

	public String getCshFutureUpdate() {
		return this.cshFutureUpdate;
	}

	public void setCshFutureUpdate(String cshFutureUpdate) {
		this.cshFutureUpdate = cshFutureUpdate;
	}

	public Integer getCshSponCty() {
		return this.cshSponCty;
	}

	public void setCshSponCty(Integer cshSponCty) {
		this.cshSponCty = cshSponCty;
	}

	public Short getCshSponReg() {
		return this.cshSponReg;
	}

	public void setCshSponReg(Short cshSponReg) {
		this.cshSponReg = cshSponReg;
	}

	public Short getCshEAddress6() {
		return this.cshEAddress6;
	}

	public void setCshEAddress6(Short cshEAddress6) {
		this.cshEAddress6 = cshEAddress6;
	}

	public String getCshEAddress7() {
		return this.cshEAddress7;
	}

	public void setCshEAddress7(String cshEAddress7) {
		this.cshEAddress7 = cshEAddress7;
	}

	public Integer getCshEAddress8() {
		return this.cshEAddress8;
	}

	public void setCshEAddress8(Integer cshEAddress8) {
		this.cshEAddress8 = cshEAddress8;
	}

	public String getCshEAddress9() {
		return this.cshEAddress9;
	}

	public void setCshEAddress9(String cshEAddress9) {
		this.cshEAddress9 = cshEAddress9;
	}

	public Integer getCshEAddress10() {
		return this.cshEAddress10;
	}

	public void setCshEAddress10(Integer cshEAddress10) {
		this.cshEAddress10 = cshEAddress10;
	}

	public Boolean getCshWaselInd() {
		return this.cshWaselInd;
	}

	public void setCshWaselInd(Boolean cshWaselInd) {
		this.cshWaselInd = cshWaselInd;
	}

	public Short getCshWaselAddr1() {
		return this.cshWaselAddr1;
	}

	public void setCshWaselAddr1(Short cshWaselAddr1) {
		this.cshWaselAddr1 = cshWaselAddr1;
	}

	public Short getCshWaselAddr2() {
		return this.cshWaselAddr2;
	}

	public void setCshWaselAddr2(Short cshWaselAddr2) {
		this.cshWaselAddr2 = cshWaselAddr2;
	}

	public Integer getCshWaselAddr3() {
		return this.cshWaselAddr3;
	}

	public void setCshWaselAddr3(Integer cshWaselAddr3) {
		this.cshWaselAddr3 = cshWaselAddr3;
	}

	public String getCshWaselAddr4() {
		return this.cshWaselAddr4;
	}

	public void setCshWaselAddr4(String cshWaselAddr4) {
		this.cshWaselAddr4 = cshWaselAddr4;
	}

	public String getCshWaselAddr5() {
		return this.cshWaselAddr5;
	}

	public void setCshWaselAddr5(String cshWaselAddr5) {
		this.cshWaselAddr5 = cshWaselAddr5;
	}

	public String getCshNationalId() {
		return this.cshNationalId;
	}

	public void setCshNationalId(String cshNationalId) {
		this.cshNationalId = cshNationalId;
	}

	public String getCshEFullName() {
		return this.cshEFullName;
	}

	public void setCshEFullName(String cshEFullName) {
		this.cshEFullName = cshEFullName;
	}

	public Short getCshBankId() {
		return this.cshBankId;
	}

	public void setCshBankId(Short cshBankId) {
		this.cshBankId = cshBankId;
	}

	public String getCshIban() {
		return this.cshIban;
	}

	public void setCshIban(String cshIban) {
		this.cshIban = cshIban;
	}

	public Integer getCshInsTypeSaaed() {
		return this.cshInsTypeSaaed;
	}

	public void setCshInsTypeSaaed(Integer cshInsTypeSaaed) {
		this.cshInsTypeSaaed = cshInsTypeSaaed;
	}

	public String getCshVatRegnNo() {
		return this.cshVatRegnNo;
	}

	public void setCshVatRegnNo(String cshVatRegnNo) {
		this.cshVatRegnNo = cshVatRegnNo;
	}

	public Byte getCshQualification() {
		return this.cshQualification;
	}

	public void setCshQualification(Byte cshQualification) {
		this.cshQualification = cshQualification;
	}

	public Byte getCshMaritalStatus() {
		return this.cshMaritalStatus;
	}

	public void setCshMaritalStatus(Byte cshMaritalStatus) {
		this.cshMaritalStatus = cshMaritalStatus;
	}

	public Byte getCshNoOfChildren() {
		return this.cshNoOfChildren;
	}

	public void setCshNoOfChildren(Byte cshNoOfChildren) {
		this.cshNoOfChildren = cshNoOfChildren;
	}

	public Byte getCshInsType() {
		return this.cshInsType;
	}

	public void setCshInsType(Byte cshInsType) {
		this.cshInsType = cshInsType;
	}

	public Long getInsInsuredCode() {
		return this.insInsuredCode;
	}

	public void setInsInsuredCode(Long insInsuredCode) {
		this.insInsuredCode = insInsuredCode;
	}

	public Short getInsCcgCode() {
		return this.insCcgCode;
	}

	public void setInsCcgCode(Short insCcgCode) {
		this.insCcgCode = insCcgCode;
	}

	public Byte getInsNameTitle() {
		return this.insNameTitle;
	}

	public void setInsNameTitle(Byte insNameTitle) {
		this.insNameTitle = insNameTitle;
	}

	public String getInsEFirstName() {
		return this.insEFirstName;
	}

	public void setInsEFirstName(String insEFirstName) {
		this.insEFirstName = insEFirstName;
	}

	public String getInsAFirstName() {
		return this.insAFirstName;
	}

	public void setInsAFirstName(String insAFirstName) {
		this.insAFirstName = insAFirstName;
	}

	public String getInsEMiddleName() {
		return this.insEMiddleName;
	}

	public void setInsEMiddleName(String insEMiddleName) {
		this.insEMiddleName = insEMiddleName;
	}

	public String getInsAMiddleName() {
		return this.insAMiddleName;
	}

	public void setInsAMiddleName(String insAMiddleName) {
		this.insAMiddleName = insAMiddleName;
	}

	public String getInsELastName() {
		return this.insELastName;
	}

	public void setInsELastName(String insELastName) {
		this.insELastName = insELastName;
	}

	public String getInsALastName() {
		return this.insALastName;
	}

	public void setInsALastName(String insALastName) {
		this.insALastName = insALastName;
	}

	public String getInsCompanyName() {
		return this.insCompanyName;
	}

	public void setInsCompanyName(String insCompanyName) {
		this.insCompanyName = insCompanyName;
	}

	public String getInsCompanyAddr1() {
		return this.insCompanyAddr1;
	}

	public void setInsCompanyAddr1(String insCompanyAddr1) {
		this.insCompanyAddr1 = insCompanyAddr1;
	}

	public String getInsCompanyAddr2() {
		return this.insCompanyAddr2;
	}

	public void setInsCompanyAddr2(String insCompanyAddr2) {
		this.insCompanyAddr2 = insCompanyAddr2;
	}

	public String getInsCompanyAddr3() {
		return this.insCompanyAddr3;
	}

	public void setInsCompanyAddr3(String insCompanyAddr3) {
		this.insCompanyAddr3 = insCompanyAddr3;
	}

	public String getInsEZipCode() {
		return this.insEZipCode;
	}

	public void setInsEZipCode(String insEZipCode) {
		this.insEZipCode = insEZipCode;
	}

	public Integer getInsCtyCode() {
		return this.insCtyCode;
	}

	public void setInsCtyCode(Integer insCtyCode) {
		this.insCtyCode = insCtyCode;
	}

	public String getInsEMobileNo() {
		return this.insEMobileNo;
	}

	public void setInsEMobileNo(String insEMobileNo) {
		this.insEMobileNo = insEMobileNo;
	}

	public String getInsEEmailId() {
		return this.insEEmailId;
	}

	public void setInsEEmailId(String insEEmailId) {
		this.insEEmailId = insEEmailId;
	}

	public Long getInsFaxNo() {
		return this.insFaxNo;
	}

	public void setInsFaxNo(Long insFaxNo) {
		this.insFaxNo = insFaxNo;
	}

	public Date getInsDob() {
		return this.insDob;
	}

	public void setInsDob(Date insDob) {
		this.insDob = insDob;
	}

	public String getInsPlaceOfBirth() {
		return this.insPlaceOfBirth;
	}

	public void setInsPlaceOfBirth(String insPlaceOfBirth) {
		this.insPlaceOfBirth = insPlaceOfBirth;
	}

	public Short getInsNationality() {
		return this.insNationality;
	}

	public void setInsNationality(Short insNationality) {
		this.insNationality = insNationality;
	}

	public Integer getInsOcCode() {
		return this.insOcCode;
	}

	public void setInsOcCode(Integer insOcCode) {
		this.insOcCode = insOcCode;
	}

	public String getInsBusiness() {
		return this.insBusiness;
	}

	public void setInsBusiness(String insBusiness) {
		this.insBusiness = insBusiness;
	}

	public String getInsEPassportNo() {
		return this.insEPassportNo;
	}

	public void setInsEPassportNo(String insEPassportNo) {
		this.insEPassportNo = insEPassportNo;
	}

	public String getInsECoRegnNo() {
		return this.insECoRegnNo;
	}

	public void setInsECoRegnNo(String insECoRegnNo) {
		this.insECoRegnNo = insECoRegnNo;
	}

	public Integer getInsIntAccExecCode() {
		return this.insIntAccExecCode;
	}

	public void setInsIntAccExecCode(Integer insIntAccExecCode) {
		this.insIntAccExecCode = insIntAccExecCode;
	}

	public Integer getInsExtAccExecCode() {
		return this.insExtAccExecCode;
	}

	public void setInsExtAccExecCode(Integer insExtAccExecCode) {
		this.insExtAccExecCode = insExtAccExecCode;
	}

	public String getInsEPhoneNo() {
		return this.insEPhoneNo;
	}

	public void setInsEPhoneNo(String insEPhoneNo) {
		this.insEPhoneNo = insEPhoneNo;
	}

	public String getInsWayNo() {
		return this.insWayNo;
	}

	public void setInsWayNo(String insWayNo) {
		this.insWayNo = insWayNo;
	}

	public String getInsBldgNo() {
		return this.insBldgNo;
	}

	public void setInsBldgNo(String insBldgNo) {
		this.insBldgNo = insBldgNo;
	}

	public Short getInsCountry() {
		return this.insCountry;
	}

	public void setInsCountry(Short insCountry) {
		this.insCountry = insCountry;
	}

	public String getInsAffinityRefNo() {
		return this.insAffinityRefNo;
	}

	public void setInsAffinityRefNo(String insAffinityRefNo) {
		this.insAffinityRefNo = insAffinityRefNo;
	}

	public String getInsCustomerType() {
		return this.insCustomerType;
	}

	public void setInsCustomerType(String insCustomerType) {
		this.insCustomerType = insCustomerType;
	}

	public String getInsExcComModes() {
		return this.insExcComModes;
	}

	public void setInsExcComModes(String insExcComModes) {
		this.insExcComModes = insExcComModes;
	}

	public String getInsLegalForm() {
		return this.insLegalForm;
	}

	public void setInsLegalForm(String insLegalForm) {
		this.insLegalForm = insLegalForm;
	}

	public Date getInsDtEstablishment() {
		return this.insDtEstablishment;
	}

	public void setInsDtEstablishment(Date insDtEstablishment) {
		this.insDtEstablishment = insDtEstablishment;
	}

	public String getInsPlaceEstablishment() {
		return this.insPlaceEstablishment;
	}

	public void setInsPlaceEstablishment(String insPlaceEstablishment) {
		this.insPlaceEstablishment = insPlaceEstablishment;
	}

	public Integer getInsRegulatoryBody() {
		return this.insRegulatoryBody;
	}

	public void setInsRegulatoryBody(Integer insRegulatoryBody) {
		this.insRegulatoryBody = insRegulatoryBody;
	}

	public Integer getInsExternalAuditor() {
		return this.insExternalAuditor;
	}

	public void setInsExternalAuditor(Integer insExternalAuditor) {
		this.insExternalAuditor = insExternalAuditor;
	}

	public Date getInsDtCollectionKyc() {
		return this.insDtCollectionKyc;
	}

	public void setInsDtCollectionKyc(Date insDtCollectionKyc) {
		this.insDtCollectionKyc = insDtCollectionKyc;
	}

	public Date getInsExpiryDate() {
		return this.insExpiryDate;
	}

	public void setInsExpiryDate(Date insExpiryDate) {
		this.insExpiryDate = insExpiryDate;
	}

	public String getInsSuspendCustomer() {
		return this.insSuspendCustomer;
	}

	public void setInsSuspendCustomer(String insSuspendCustomer) {
		this.insSuspendCustomer = insSuspendCustomer;
	}

	public Integer getInsDistributionChnl() {
		return this.insDistributionChnl;
	}

	public void setInsDistributionChnl(Integer insDistributionChnl) {
		this.insDistributionChnl = insDistributionChnl;
	}

	public Short getInsSourceOfCust() {
		return this.insSourceOfCust;
	}

	public void setInsSourceOfCust(Short insSourceOfCust) {
		this.insSourceOfCust = insSourceOfCust;
	}

	public Short getInsBrCode() {
		return this.insBrCode;
	}

	public void setInsBrCode(Short insBrCode) {
		this.insBrCode = insBrCode;
	}

	public Long getInsAgentCode() {
		return this.insAgentCode;
	}

	public void setInsAgentCode(Long insAgentCode) {
		this.insAgentCode = insAgentCode;
	}

	public Long getInsCustomerId() {
		return this.insCustomerId;
	}

	public void setInsCustomerId(Long insCustomerId) {
		this.insCustomerId = insCustomerId;
	}

	public Integer getInsRegCode() {
		return this.insRegCode;
	}

	public void setInsRegCode(Integer insRegCode) {
		this.insRegCode = insRegCode;
	}

	public Integer getInsLocCode() {
		return this.insLocCode;
	}

	public void setInsLocCode(Integer insLocCode) {
		this.insLocCode = insLocCode;
	}

	public Short getInsIdTypCode() {
		return this.insIdTypCode;
	}

	public void setInsIdTypCode(Short insIdTypCode) {
		this.insIdTypCode = insIdTypCode;
	}

	public String getInsIdNo() {
		return this.insIdNo;
	}

	public void setInsIdNo(String insIdNo) {
		this.insIdNo = insIdNo;
	}

	public Long getInsMarketingFee() {
		return this.insMarketingFee;
	}

	public void setInsMarketingFee(Long insMarketingFee) {
		this.insMarketingFee = insMarketingFee;
	}

	public String getInsEAddress() {
		return this.insEAddress;
	}

	public void setInsEAddress(String insEAddress) {
		this.insEAddress = insEAddress;
	}

	public String getInsAAddress() {
		return this.insAAddress;
	}

	public void setInsAAddress(String insAAddress) {
		this.insAAddress = insAAddress;
	}

	public String getInsHintQuestion() {
		return this.insHintQuestion;
	}

	public void setInsHintQuestion(String insHintQuestion) {
		this.insHintQuestion = insHintQuestion;
	}

	public String getInsHintAnswer() {
		return this.insHintAnswer;
	}

	public void setInsHintAnswer(String insHintAnswer) {
		this.insHintAnswer = insHintAnswer;
	}

	public String getInsPassword() {
		return this.insPassword;
	}

	public void setInsPassword(String insPassword) {
		this.insPassword = insPassword;
	}

	public Integer getInsStatus() {
		return this.insStatus;
	}

	public void setInsStatus(Integer insStatus) {
		this.insStatus = insStatus;
	}

	public String getInsEFullName() {
		return this.insEFullName;
	}

	public void setInsEFullName(String insEFullName) {
		this.insEFullName = insEFullName;
	}

	public String getInsAFullName() {
		return this.insAFullName;
	}

	public void setInsAFullName(String insAFullName) {
		this.insAFullName = insAFullName;
	}

	public String getInsRemarks() {
		return this.insRemarks;
	}

	public void setInsRemarks(String insRemarks) {
		this.insRemarks = insRemarks;
	}

	public Integer getInsCity() {
		return this.insCity;
	}

	public void setInsCity(Integer insCity) {
		this.insCity = insCity;
	}

	public Integer getInsPreparedBy() {
		return this.insPreparedBy;
	}

	public void setInsPreparedBy(Integer insPreparedBy) {
		this.insPreparedBy = insPreparedBy;
	}

	public Date getInsPreparedDt() {
		return this.insPreparedDt;
	}

	public void setInsPreparedDt(Date insPreparedDt) {
		this.insPreparedDt = insPreparedDt;
	}

	public Integer getInsModifiedBy() {
		return this.insModifiedBy;
	}

	public void setInsModifiedBy(Integer insModifiedBy) {
		this.insModifiedBy = insModifiedBy;
	}

	public Date getInsModifiedDt() {
		return this.insModifiedDt;
	}

	public void setInsModifiedDt(Date insModifiedDt) {
		this.insModifiedDt = insModifiedDt;
	}

	public Long getInsLinkCode() {
		return this.insLinkCode;
	}

	public void setInsLinkCode(Long insLinkCode) {
		this.insLinkCode = insLinkCode;
	}

	public Character getInsSex() {
		return this.insSex;
	}

	public void setInsSex(Character insSex) {
		this.insSex = insSex;
	}

	public Long getInsPostalCode() {
		return this.insPostalCode;
	}

	public void setInsPostalCode(Long insPostalCode) {
		this.insPostalCode = insPostalCode;
	}

	public Long getInsTurnover() {
		return this.insTurnover;
	}

	public void setInsTurnover(Long insTurnover) {
		this.insTurnover = insTurnover;
	}

	public Integer getInsNoOfEmp() {
		return this.insNoOfEmp;
	}

	public void setInsNoOfEmp(Integer insNoOfEmp) {
		this.insNoOfEmp = insNoOfEmp;
	}

	public String getInsSponNo() {
		return this.insSponNo;
	}

	public void setInsSponNo(String insSponNo) {
		this.insSponNo = insSponNo;
	}

	public Integer getInsSponCty() {
		return this.insSponCty;
	}

	public void setInsSponCty(Integer insSponCty) {
		this.insSponCty = insSponCty;
	}

	public Short getInsSponReg() {
		return this.insSponReg;
	}

	public void setInsSponReg(Short insSponReg) {
		this.insSponReg = insSponReg;
	}

	public String getInsDrvLicenseNo() {
		return this.insDrvLicenseNo;
	}

	public void setInsDrvLicenseNo(String insDrvLicenseNo) {
		this.insDrvLicenseNo = insDrvLicenseNo;
	}

	public String getInsDrvLicense() {
		return this.insDrvLicense;
	}

	public void setInsDrvLicense(String insDrvLicense) {
		this.insDrvLicense = insDrvLicense;
	}

	public String getInsTcfNo() {
		return this.insTcfNo;
	}

	public void setInsTcfNo(String insTcfNo) {
		this.insTcfNo = insTcfNo;
	}

	public Short getInsAddtlNo() {
		return this.insAddtlNo;
	}

	public void setInsAddtlNo(Short insAddtlNo) {
		this.insAddtlNo = insAddtlNo;
	}

	public String getInsResCity() {
		return this.insResCity;
	}

	public void setInsResCity(String insResCity) {
		this.insResCity = insResCity;
	}

	public Integer getInsZipCode() {
		return this.insZipCode;
	}

	public void setInsZipCode(Integer insZipCode) {
		this.insZipCode = insZipCode;
	}

	public String getInsZoneName() {
		return this.insZoneName;
	}

	public void setInsZoneName(String insZoneName) {
		this.insZoneName = insZoneName;
	}

	public Integer getInsUnitNo() {
		return this.insUnitNo;
	}

	public void setInsUnitNo(Integer insUnitNo) {
		this.insUnitNo = insUnitNo;
	}

	public Boolean getInsWaselInd() {
		return this.insWaselInd;
	}

	public void setInsWaselInd(Boolean insWaselInd) {
		this.insWaselInd = insWaselInd;
	}

	public Short getInsWaselBldngNo() {
		return this.insWaselBldngNo;
	}

	public void setInsWaselBldngNo(Short insWaselBldngNo) {
		this.insWaselBldngNo = insWaselBldngNo;
	}

	public Short getInsWaselAddtlNo() {
		return this.insWaselAddtlNo;
	}

	public void setInsWaselAddtlNo(Short insWaselAddtlNo) {
		this.insWaselAddtlNo = insWaselAddtlNo;
	}

	public Integer getInsWaselZipCode() {
		return this.insWaselZipCode;
	}

	public void setInsWaselZipCode(Integer insWaselZipCode) {
		this.insWaselZipCode = insWaselZipCode;
	}

	public String getInsWaselCity() {
		return this.insWaselCity;
	}

	public void setInsWaselCity(String insWaselCity) {
		this.insWaselCity = insWaselCity;
	}

	public String getInsWaselZoneName() {
		return this.insWaselZoneName;
	}

	public void setInsWaselZoneName(String insWaselZoneName) {
		this.insWaselZoneName = insWaselZoneName;
	}

	public String getInsNationalId() {
		return this.insNationalId;
	}

	public void setInsNationalId(String insNationalId) {
		this.insNationalId = insNationalId;
	}

	public Short getInsEAddress6() {
		return this.insEAddress6;
	}

	public void setInsEAddress6(Short insEAddress6) {
		this.insEAddress6 = insEAddress6;
	}

	public String getInsEAddress7() {
		return this.insEAddress7;
	}

	public void setInsEAddress7(String insEAddress7) {
		this.insEAddress7 = insEAddress7;
	}

	public Integer getInsEAddress8() {
		return this.insEAddress8;
	}

	public void setInsEAddress8(Integer insEAddress8) {
		this.insEAddress8 = insEAddress8;
	}

	public String getInsEAddress9() {
		return this.insEAddress9;
	}

	public void setInsEAddress9(String insEAddress9) {
		this.insEAddress9 = insEAddress9;
	}

	public Integer getInsEAddress10() {
		return this.insEAddress10;
	}

	public void setInsEAddress10(Integer insEAddress10) {
		this.insEAddress10 = insEAddress10;
	}

	public Short getInsBorderInd() {
		return this.insBorderInd;
	}

	public void setInsBorderInd(Short insBorderInd) {
		this.insBorderInd = insBorderInd;
	}

	public String getInsVatRegnNo() {
		return this.insVatRegnNo;
	}

	public void setInsVatRegnNo(String insVatRegnNo) {
		this.insVatRegnNo = insVatRegnNo;
	}

	public Byte getInsVatCode() {
		return this.insVatCode;
	}

	public void setInsVatCode(Byte insVatCode) {
		this.insVatCode = insVatCode;
	}

	public Integer getInsVatRegnCnty() {
		return this.insVatRegnCnty;
	}

	public void setInsVatRegnCnty(Integer insVatRegnCnty) {
		this.insVatRegnCnty = insVatRegnCnty;
	}

	public Date getInsVatRegnStartDate() {
		return this.insVatRegnStartDate;
	}

	public void setInsVatRegnStartDate(Date insVatRegnStartDate) {
		this.insVatRegnStartDate = insVatRegnStartDate;
	}

	public Date getInsVatRegnEndDate() {
		return this.insVatRegnEndDate;
	}

	public void setInsVatRegnEndDate(Date insVatRegnEndDate) {
		this.insVatRegnEndDate = insVatRegnEndDate;
	}

	public Byte getInsNoOfChildren() {
		return this.insNoOfChildren;
	}

	public void setInsNoOfChildren(Byte insNoOfChildren) {
		this.insNoOfChildren = insNoOfChildren;
	}

	public Byte getInsQualification() {
		return this.insQualification;
	}

	public void setInsQualification(Byte insQualification) {
		this.insQualification = insQualification;
	}

	public Byte getInsMaritalStatus() {
		return this.insMaritalStatus;
	}

	public void setInsMaritalStatus(Byte insMaritalStatus) {
		this.insMaritalStatus = insMaritalStatus;
	}

	public Byte getQuoImportStatus() {
		return this.quoImportStatus;
	}

	public void setQuoImportStatus(Byte quoImportStatus) {
		this.quoImportStatus = quoImportStatus;
	}

	public Date getQuoImportDate() {
		return this.quoImportDate;
	}

	public void setQuoImportDate(Date quoImportDate) {
		this.quoImportDate = quoImportDate;
	}

	public Long getQuoParSecFlag() {
		return this.quoParSecFlag;
	}

	public void setQuoParSecFlag(Long quoParSecFlag) {
		this.quoParSecFlag = quoParSecFlag;
	}

	public Long getQuoPlSecFlag() {
		return this.quoPlSecFlag;
	}

	public void setQuoPlSecFlag(Long quoPlSecFlag) {
		this.quoPlSecFlag = quoPlSecFlag;
	}

	public Long getQuoWcSecFlag() {
		return this.quoWcSecFlag;
	}

	public void setQuoWcSecFlag(Long quoWcSecFlag) {
		this.quoWcSecFlag = quoWcSecFlag;
	}

	public Long getQuoDosSecFlag() {
		return this.quoDosSecFlag;
	}

	public void setQuoDosSecFlag(Long quoDosSecFlag) {
		this.quoDosSecFlag = quoDosSecFlag;
	}

	public Long getQuoMbSecFlag() {
		return this.quoMbSecFlag;
	}

	public void setQuoMbSecFlag(Long quoMbSecFlag) {
		this.quoMbSecFlag = quoMbSecFlag;
	}

	public Long getQuoEeSecFlag() {
		return this.quoEeSecFlag;
	}

	public void setQuoEeSecFlag(Long quoEeSecFlag) {
		this.quoEeSecFlag = quoEeSecFlag;
	}

	public Long getQuoBiSecFlag() {
		return this.quoBiSecFlag;
	}

	public void setQuoBiSecFlag(Long quoBiSecFlag) {
		this.quoBiSecFlag = quoBiSecFlag;
	}

	public Long getQuoTbSecFlag() {
		return this.quoTbSecFlag;
	}

	public void setQuoTbSecFlag(Long quoTbSecFlag) {
		this.quoTbSecFlag = quoTbSecFlag;
	}

	public Long getQuoGpaSecFlag() {
		return this.quoGpaSecFlag;
	}

	public void setQuoGpaSecFlag(Long quoGpaSecFlag) {
		this.quoGpaSecFlag = quoGpaSecFlag;
	}

	public Long getQuoFgSecFlag() {
		return this.quoFgSecFlag;
	}

	public void setQuoFgSecFlag(Long quoFgSecFlag) {
		this.quoFgSecFlag = quoFgSecFlag;
	}

	public Long getQuoMoneySecFlag() {
		return this.quoMoneySecFlag;
	}

	public void setQuoMoneySecFlag(Long quoMoneySecFlag) {
		this.quoMoneySecFlag = quoMoneySecFlag;
	}

	public Clob getQuoRequest() {
		return this.quoRequest;
	}

	public void setQuoRequest(Clob quoRequest) {
		this.quoRequest = quoRequest;
	}

	public Clob getQuoResponse() {
		return this.quoResponse;
	}

	public void setQuoResponse(Clob quoResponse) {
		this.quoResponse = quoResponse;
	}

	public Clob getQuoIntrResponse() {
		return this.quoIntrResponse;
	}

	public void setQuoIntrResponse(Clob quoIntrResponse) {
		this.quoIntrResponse = quoIntrResponse;
	}

	public Clob getQuoIntrRequest() {
		return this.quoIntrRequest;
	}

	public void setQuoIntrRequest(Clob quoIntrRequest) {
		this.quoIntrRequest = quoIntrRequest;
	}
	
	public Blob getQuoIntrResponseAdd() {
		return this.quoIntrResponseAdd;
	}

	public void setQuoIntrResponseAdd(Blob quoIntrResponseAdd) {
		this.quoIntrResponseAdd = quoIntrResponseAdd;
	}

	public Blob getQuoIntrBatchResponse() {
		return quoIntrBatchResponse;
	}

	public void setQuoIntrBatchResponse(Blob quoIntrBatchResponse) {
		this.quoIntrBatchResponse = quoIntrBatchResponse;
	}
*/
	
}
