package com.rsaame.pas.dao.model;

// Generated Mar 5, 2012 10:41:01 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.mindtree.ruc.cmn.utils.Utils;
import com.rsaame.pas.cmn.pojo.POJOId;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapper;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapperId;

/**
 * TTrnWctplUnnamedPersonQuo generated by hbm2java
 */
public class TTrnWctplUnnamedPersonQuo   extends POJOWrapper implements java.io.Serializable {

	private static final long serialVersionUID = -5614796544685283723L;
	private TTrnWctplUnnamedPersonQuoId id;
	private Long wupPolicyId;
	private Long wupBasicRiskId;
	private Long wupRskCode;
	private Short wupRtCode;
	private Short wupRcCode;
	private Long wupNoOfPerson;
	private BigDecimal wupSumInsured;
	private Byte wupStatus;
	private Short wupEmploymentType;
	private String wupEmployerEName;
	private String wupEmployerAName;
	private Date wupValidityExpiryDate;
	private Long wupEndtId;
	private Integer wupRiRskCode;
	private Integer wupBasicRskCode;
	private String wupPlaceOfWork;
	private BigDecimal wupSalary;
	private Integer wupPreparedBy;
	private Date wupPreparedDt;
	private Integer wupModifiedBy;
	private Date wupModifiedDt;
	private Date wupStartDate;
	private Date wupEndDate;
	private Long wupHazard;
	private Long wupTradeGroup;
	private Long wupBldId;
	private Short wupTerCode;
	private Short wupJurCode;
	private String wupFreeZone;
	private String wupIndemnityDesc;
	private String wupJurDesc;
	private BigDecimal wupEmpLiabLmt;

	public TTrnWctplUnnamedPersonQuo() {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	public TTrnWctplUnnamedPersonQuo(TTrnWctplUnnamedPersonQuoId id,
			Date wupValidityExpiryDate) {
		this.id = id;
		this.wupValidityExpiryDate = wupValidityExpiryDate;
	}

	public TTrnWctplUnnamedPersonQuo(TTrnWctplUnnamedPersonQuoId id,
			Long wupPolicyId, Long wupBasicRiskId, Long wupRskCode,
			Short wupRtCode, Short wupRcCode, Long wupNoOfPerson,
			BigDecimal wupSumInsured, Byte wupStatus, Short wupEmploymentType,
			String wupEmployerEName, String wupEmployerAName,
			Date wupValidityExpiryDate, Long wupEndtId, Integer wupRiRskCode,
			Integer wupBasicRskCode, String wupPlaceOfWork,
			BigDecimal wupSalary, Integer wupPreparedBy, Date wupPreparedDt,
			Integer wupModifiedBy, Date wupModifiedDt, Date wupStartDate,
			Date wupEndDate, Long wupHazard, Long wupTradeGroup, Long wupBldId,
			Short wupTerCode, Short wupJurCode, String wupFreeZone,
			String wupIndemnityDesc, String wupJurDesc, BigDecimal wupEmpLiabLmt) {
		this.id = id;
		this.wupPolicyId = wupPolicyId;
		this.wupBasicRiskId = wupBasicRiskId;
		this.wupRskCode = wupRskCode;
		this.wupRtCode = wupRtCode;
		this.wupRcCode = wupRcCode;
		this.wupNoOfPerson = wupNoOfPerson;
		this.wupSumInsured = wupSumInsured;
		this.wupStatus = wupStatus;
		this.wupEmploymentType = wupEmploymentType;
		this.wupEmployerEName = wupEmployerEName;
		this.wupEmployerAName = wupEmployerAName;
		this.wupValidityExpiryDate = wupValidityExpiryDate;
		this.wupEndtId = wupEndtId;
		this.wupRiRskCode = wupRiRskCode;
		this.wupBasicRskCode = wupBasicRskCode;
		this.wupPlaceOfWork = wupPlaceOfWork;
		this.wupSalary = wupSalary;
		this.wupPreparedBy = wupPreparedBy;
		this.wupPreparedDt = wupPreparedDt;
		this.wupModifiedBy = wupModifiedBy;
		this.wupModifiedDt = wupModifiedDt;
		this.wupStartDate = wupStartDate;
		this.wupEndDate = wupEndDate;
		this.wupHazard = wupHazard;
		this.wupTradeGroup = wupTradeGroup;
		this.wupBldId = wupBldId;
		this.wupTerCode = wupTerCode;
		this.wupJurCode = wupJurCode;
		this.wupFreeZone = wupFreeZone;
		this.wupIndemnityDesc = wupIndemnityDesc;
		this.wupJurDesc = wupJurDesc;
		this.wupEmpLiabLmt = wupEmpLiabLmt;
	}

	public TTrnWctplUnnamedPersonQuoId getId() {
		return this.id;
	}

	public void setId(TTrnWctplUnnamedPersonQuoId id) {
		this.id = id;
	}

	public Long getWupPolicyId() {
		return this.wupPolicyId;
	}

	public void setWupPolicyId(Long wupPolicyId) {
		this.wupPolicyId = wupPolicyId;
	}

	public Long getWupBasicRiskId() {
		return this.wupBasicRiskId;
	}

	public void setWupBasicRiskId(Long wupBasicRiskId) {
		this.wupBasicRiskId = wupBasicRiskId;
	}

	public Long getWupRskCode() {
		return this.wupRskCode;
	}

	public void setWupRskCode(Long wupRskCode) {
		this.wupRskCode = wupRskCode;
	}

	public Short getWupRtCode() {
		return this.wupRtCode;
	}

	public void setWupRtCode(Short wupRtCode) {
		this.wupRtCode = wupRtCode;
	}

	public Short getWupRcCode() {
		return this.wupRcCode;
	}

	public void setWupRcCode(Short wupRcCode) {
		this.wupRcCode = wupRcCode;
	}

	public Long getWupNoOfPerson() {
		return this.wupNoOfPerson;
	}

	public void setWupNoOfPerson(Long wupNoOfPerson) {
		this.wupNoOfPerson = wupNoOfPerson;
	}

	public BigDecimal getWupSumInsured() {
		return this.wupSumInsured;
	}

	public void setWupSumInsured(BigDecimal wupSumInsured) {
		this.wupSumInsured = wupSumInsured;
	}

	public Byte getWupStatus() {
		return this.wupStatus;
	}

	public void setWupStatus(Byte wupStatus) {
		this.wupStatus = wupStatus;
	}

	public Short getWupEmploymentType() {
		return this.wupEmploymentType;
	}

	public void setWupEmploymentType(Short wupEmploymentType) {
		this.wupEmploymentType = wupEmploymentType;
	}

	public String getWupEmployerEName() {
		return this.wupEmployerEName;
	}

	public void setWupEmployerEName(String wupEmployerEName) {
		this.wupEmployerEName = wupEmployerEName;
	}

	public String getWupEmployerAName() {
		return this.wupEmployerAName;
	}

	public void setWupEmployerAName(String wupEmployerAName) {
		this.wupEmployerAName = wupEmployerAName;
	}

	public Date getWupValidityExpiryDate() {
		return this.wupValidityExpiryDate;
	}

	public void setWupValidityExpiryDate(Date wupValidityExpiryDate) {
		this.wupValidityExpiryDate = wupValidityExpiryDate;
	}

	public Long getWupEndtId() {
		return this.wupEndtId;
	}

	public void setWupEndtId(Long wupEndtId) {
		this.wupEndtId = wupEndtId;
	}

	public Integer getWupRiRskCode() {
		return this.wupRiRskCode;
	}

	public void setWupRiRskCode(Integer wupRiRskCode) {
		this.wupRiRskCode = wupRiRskCode;
	}

	public Integer getWupBasicRskCode() {
		return this.wupBasicRskCode;
	}

	public void setWupBasicRskCode(Integer wupBasicRskCode) {
		this.wupBasicRskCode = wupBasicRskCode;
	}

	public String getWupPlaceOfWork() {
		return this.wupPlaceOfWork;
	}

	public void setWupPlaceOfWork(String wupPlaceOfWork) {
		this.wupPlaceOfWork = wupPlaceOfWork;
	}

	public BigDecimal getWupSalary() {
		return this.wupSalary;
	}

	public void setWupSalary(BigDecimal wupSalary) {
		this.wupSalary = wupSalary;
	}

	public Integer getWupPreparedBy() {
		return this.wupPreparedBy;
	}

	public void setWupPreparedBy(Integer wupPreparedBy) {
		this.wupPreparedBy = wupPreparedBy;
	}

	public Date getWupPreparedDt() {
		return this.wupPreparedDt;
	}

	public void setWupPreparedDt(Date wupPreparedDt) {
		this.wupPreparedDt = wupPreparedDt;
	}

	public Integer getWupModifiedBy() {
		return this.wupModifiedBy;
	}

	public void setWupModifiedBy(Integer wupModifiedBy) {
		this.wupModifiedBy = wupModifiedBy;
	}

	public Date getWupModifiedDt() {
		return this.wupModifiedDt;
	}

	public void setWupModifiedDt(Date wupModifiedDt) {
		this.wupModifiedDt = wupModifiedDt;
	}

	public Date getWupStartDate() {
		return this.wupStartDate;
	}

	public void setWupStartDate(Date wupStartDate) {
		this.wupStartDate = wupStartDate;
	}

	public Date getWupEndDate() {
		return this.wupEndDate;
	}

	public void setWupEndDate(Date wupEndDate) {
		this.wupEndDate = wupEndDate;
	}

	public Long getWupHazard() {
		return this.wupHazard;
	}

	public void setWupHazard(Long wupHazard) {
		this.wupHazard = wupHazard;
	}

	public Long getWupTradeGroup() {
		return this.wupTradeGroup;
	}

	public void setWupTradeGroup(Long wupTradeGroup) {
		this.wupTradeGroup = wupTradeGroup;
	}

	public Long getWupBldId() {
		return this.wupBldId;
	}

	public void setWupBldId(Long wupBldId) {
		this.wupBldId = wupBldId;
	}

	public Short getWupTerCode() {
		return this.wupTerCode;
	}

	public void setWupTerCode(Short wupTerCode) {
		this.wupTerCode = wupTerCode;
	}

	public Short getWupJurCode() {
		return this.wupJurCode;
	}

	public void setWupJurCode(Short wupJurCode) {
		this.wupJurCode = wupJurCode;
	}

	public String getWupFreeZone() {
		return this.wupFreeZone;
	}

	public void setWupFreeZone(String wupFreeZone) {
		this.wupFreeZone = wupFreeZone;
	}

	public String getWupIndemnityDesc() {
		return this.wupIndemnityDesc;
	}

	public void setWupIndemnityDesc(String wupIndemnityDesc) {
		this.wupIndemnityDesc = wupIndemnityDesc;
	}

	public String getWupJurDesc() {
		return this.wupJurDesc;
	}

	public void setWupJurDesc(String wupJurDesc) {
		this.wupJurDesc = wupJurDesc;
	}

	public BigDecimal getWupEmpLiabLmt() {
		return this.wupEmpLiabLmt;
	}

	public void setWupEmpLiabLmt(BigDecimal wupEmpLiabLmt) {
		this.wupEmpLiabLmt = wupEmpLiabLmt;
	}

	@Override
	public void setEndtId( Long endtId ){
		setWupEndtId(  endtId );
	}
	
	@Override
	public POJOId getPOJOId(){
		return this.getId();
	}
	
	@Override
	public void setPOJOId( POJOId id ){
		setId( (TTrnWctplUnnamedPersonQuoId) id );
	}
	
	@Override
	public void setValidityExpiryDate( Date ved ){
		setWupValidityExpiryDate( ved );
	}
	

	@Override
	public void setValidityStartDate( Date vsd ){
		//setWupStartDate( vsd );
		
		if(!Utils.isEmpty(getId())) getId().setWupValidityStartDate(vsd);
	}
	
	
	@Override
	public void setStatus( Integer status ){
		setWupStatus( status.byteValue() );
	}
	
	@Override
	public int getStatus(){
		return getWupStatus();
	}
	
	@Override
	public void setPreparedDate( Date preparedDate ){
		setWupPreparedDt( preparedDate );
	}
	
	@Override
	public Date getPreparedDate(){
		return getWupPreparedDt();
	}

	@Override
	public void setPOJOWrapperId(POJOWrapperId id) {
		setId((TTrnWctplUnnamedPersonQuoId) id);
	}

	@Override
	public POJOWrapperId getPOJOWrapperId() {
		return getId();
	}

	@Override
	public void setStatus(int status) {
		setWupStatus(Integer.valueOf(status).byteValue());
	}

	@Override
	public void setEndtNo(Long endtNo) {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD

	}

	@Override
	public void setPreparedBy(Integer preparedBy) {
		setWupPreparedBy(preparedBy);
	}

	@Override
	public void setPreparedDt(Date preparedDt) {
		setWupPreparedDt(preparedDt);
	}

	@Override
	public void setModifiedBy(Integer modifiedBy) {
		setWupModifiedBy(modifiedBy);
	}

	@Override
	public void setModifiedDt(Date modifiedDt) {
		setWupModifiedDt(modifiedDt);
	}

	@Override
	public Integer getPreparedBy() {
		return getWupPreparedBy();
	}

	@Override
	public Date getPreparedDt() {
		return getWupPreparedDt();
	}

	@Override
	public Integer getModifiedBy() {
		return getWupModifiedBy();
	}

	@Override
	public Date getModifiedDt() {
		return getWupModifiedDt();
	}
}
