package com.rsaame.pas.dao.model;

// Generated Oct 23, 2012 3:45:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TTrnPrintBatchPas generated by hbm2java
 */
public class TTrnPrintBatchPas implements java.io.Serializable {

	private TTrnPrintBatchPasId id;
	private Long polPolicyNo;
	private Date polValidityStartDate;
	private long polEndtId;
	private Long renQuoNo;
	private String prnLocation;
	private Integer requesterId;
	private Date requestDate;
	private Date processedDate;
	private String prnStatus;
	private String remarks;

	public TTrnPrintBatchPas() {
	}

	public TTrnPrintBatchPas(TTrnPrintBatchPasId id, long polEndtId) {
		this.id = id;
		this.polEndtId = polEndtId;
	}

	public TTrnPrintBatchPas(TTrnPrintBatchPasId id, Long polPolicyNo,
			Date polValidityStartDate, long polEndtId, Long renQuoNo,
			String prnLocation, Integer requesterId, Date requestDate,
			Date processedDate, String prnStatus, String remarks) {
		this.id = id;
		this.polPolicyNo = polPolicyNo;
		this.polValidityStartDate = polValidityStartDate;
		this.polEndtId = polEndtId;
		this.renQuoNo = renQuoNo;
		this.prnLocation = prnLocation;
		this.requesterId = requesterId;
		this.requestDate = requestDate;
		this.processedDate = processedDate;
		this.prnStatus = prnStatus;
		this.remarks = remarks;
	}

	public TTrnPrintBatchPasId getId() {
		return this.id;
	}

	public void setId(TTrnPrintBatchPasId id) {
		this.id = id;
	}

	public Long getPolPolicyNo() {
		return this.polPolicyNo;
	}

	public void setPolPolicyNo(Long polPolicyNo) {
		this.polPolicyNo = polPolicyNo;
	}

	public Date getPolValidityStartDate() {
		return this.polValidityStartDate;
	}

	public void setPolValidityStartDate(Date polValidityStartDate) {
		this.polValidityStartDate = polValidityStartDate;
	}

	public long getPolEndtId() {
		return this.polEndtId;
	}

	public void setPolEndtId(long polEndtId) {
		this.polEndtId = polEndtId;
	}

	public Long getRenQuoNo() {
		return this.renQuoNo;
	}

	public void setRenQuoNo(Long renQuoNo) {
		this.renQuoNo = renQuoNo;
	}

	public String getPrnLocation() {
		return this.prnLocation;
	}

	public void setPrnLocation(String prnLocation) {
		this.prnLocation = prnLocation;
	}

	public Integer getRequesterId() {
		return this.requesterId;
	}

	public void setRequesterId(Integer requesterId) {
		this.requesterId = requesterId;
	}

	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	public Date getProcessedDate() {
		return this.processedDate;
	}

	public void setProcessedDate(Date processedDate) {
		this.processedDate = processedDate;
	}

	public String getPrnStatus() {
		return this.prnStatus;
	}

	public void setPrnStatus(String prnStatus) {
		this.prnStatus = prnStatus;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
