package com.rsaame.pas.dao.model;

// Generated May 17, 2012 9:15:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TTrnPolicyExclusion generated by hbm2java
 */
public class TTrnPolicyExclusion implements java.io.Serializable {

	private TTrnPolicyExclusionId id;
	private Integer tpeCovCode;
	private Integer tpeCtCode;
	private Integer tpeCstCode;
	private Date tpeValidityStartDate;
	private Date tpeValidityEndDate;
	private Byte tpeStatus;
	private Integer tpePreparedBy;
	private Date tpePreparedDt;
	private Integer tpeModifiedBy;
	private Date tpeModifiedDt;
	private String tpeAmount;
	private Boolean tpePrintFlag;

	public TTrnPolicyExclusion() {
	}

	public TTrnPolicyExclusion(TTrnPolicyExclusionId id) {
		this.id = id;
	}

	public TTrnPolicyExclusion(TTrnPolicyExclusionId id, Integer tpeCovCode,
			Integer tpeCtCode, Integer tpeCstCode, Date tpeValidityStartDate,
			Date tpeValidityEndDate, Byte tpeStatus, Integer tpePreparedBy,
			Date tpePreparedDt, Integer tpeModifiedBy, Date tpeModifiedDt,
			String tpeAmount, Boolean tpePrintFlag) {
		this.id = id;
		this.tpeCovCode = tpeCovCode;
		this.tpeCtCode = tpeCtCode;
		this.tpeCstCode = tpeCstCode;
		this.tpeValidityStartDate = tpeValidityStartDate;
		this.tpeValidityEndDate = tpeValidityEndDate;
		this.tpeStatus = tpeStatus;
		this.tpePreparedBy = tpePreparedBy;
		this.tpePreparedDt = tpePreparedDt;
		this.tpeModifiedBy = tpeModifiedBy;
		this.tpeModifiedDt = tpeModifiedDt;
		this.tpeAmount = tpeAmount;
		this.tpePrintFlag = tpePrintFlag;
	}

	public TTrnPolicyExclusionId getId() {
		return this.id;
	}

	public void setId(TTrnPolicyExclusionId id) {
		this.id = id;
	}

	public Integer getTpeCovCode() {
		return this.tpeCovCode;
	}

	public void setTpeCovCode(Integer tpeCovCode) {
		this.tpeCovCode = tpeCovCode;
	}

	public Integer getTpeCtCode() {
		return this.tpeCtCode;
	}

	public void setTpeCtCode(Integer tpeCtCode) {
		this.tpeCtCode = tpeCtCode;
	}

	public Integer getTpeCstCode() {
		return this.tpeCstCode;
	}

	public void setTpeCstCode(Integer tpeCstCode) {
		this.tpeCstCode = tpeCstCode;
	}

	public Date getTpeValidityStartDate() {
		return this.tpeValidityStartDate;
	}

	public void setTpeValidityStartDate(Date tpeValidityStartDate) {
		this.tpeValidityStartDate = tpeValidityStartDate;
	}

	public Date getTpeValidityEndDate() {
		return this.tpeValidityEndDate;
	}

	public void setTpeValidityEndDate(Date tpeValidityEndDate) {
		this.tpeValidityEndDate = tpeValidityEndDate;
	}

	public Byte getTpeStatus() {
		return this.tpeStatus;
	}

	public void setTpeStatus(Byte tpeStatus) {
		this.tpeStatus = tpeStatus;
	}

	public Integer getTpePreparedBy() {
		return this.tpePreparedBy;
	}

	public void setTpePreparedBy(Integer tpePreparedBy) {
		this.tpePreparedBy = tpePreparedBy;
	}

	public Date getTpePreparedDt() {
		return this.tpePreparedDt;
	}

	public void setTpePreparedDt(Date tpePreparedDt) {
		this.tpePreparedDt = tpePreparedDt;
	}

	public Integer getTpeModifiedBy() {
		return this.tpeModifiedBy;
	}

	public void setTpeModifiedBy(Integer tpeModifiedBy) {
		this.tpeModifiedBy = tpeModifiedBy;
	}

	public Date getTpeModifiedDt() {
		return this.tpeModifiedDt;
	}

	public void setTpeModifiedDt(Date tpeModifiedDt) {
		this.tpeModifiedDt = tpeModifiedDt;
	}

	public String getTpeAmount() {
		return this.tpeAmount;
	}

	public void setTpeAmount(String tpeAmount) {
		this.tpeAmount = tpeAmount;
	}

	public Boolean getTpePrintFlag() {
		return this.tpePrintFlag;
	}

	public void setTpePrintFlag(Boolean tpePrintFlag) {
		this.tpePrintFlag = tpePrintFlag;
	}

}
