//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.30 at 03:36:42 PM IST 
//


package com.mindtree.devtools.b2b.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fieldType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fieldType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="a" type="{}fieldInstanceType"/>
 *         &lt;element name="b" type="{}fieldInstanceType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="mapper-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="srcAccessorMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="srcMutatorMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="destAccessorMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="destMutatorMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="converter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="converterDefaultDir" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fieldType", propOrder = {
    "a",
    "b"
})
public class FieldType {

    @XmlElement(required = true)
    protected FieldInstanceType a;
    @XmlElement(required = true)
    protected FieldInstanceType b;
    @XmlAttribute
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object ref;
    @XmlAttribute(name = "mapper-type")
    protected String mapperType;
    @XmlAttribute
    protected String srcAccessorMethod;
    @XmlAttribute
    protected String srcMutatorMethod;
    @XmlAttribute
    protected String destAccessorMethod;
    @XmlAttribute
    protected String destMutatorMethod;
    @XmlAttribute
    protected String converter;
    @XmlAttribute
    protected String converterDefaultDir;

    /**
     * Gets the value of the a property.
     * 
     * @return
     *     possible object is
     *     {@link FieldInstanceType }
     *     
     */
    public FieldInstanceType getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldInstanceType }
     *     
     */
    public void setA(FieldInstanceType value) {
        this.a = value;
    }

    /**
     * Gets the value of the b property.
     * 
     * @return
     *     possible object is
     *     {@link FieldInstanceType }
     *     
     */
    public FieldInstanceType getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldInstanceType }
     *     
     */
    public void setB(FieldInstanceType value) {
        this.b = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRef(Object value) {
        this.ref = value;
    }

    /**
     * Gets the value of the mapperType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapperType() {
        return mapperType;
    }

    /**
     * Sets the value of the mapperType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapperType(String value) {
        this.mapperType = value;
    }

    /**
     * Gets the value of the srcAccessorMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcAccessorMethod() {
        return srcAccessorMethod;
    }

    /**
     * Sets the value of the srcAccessorMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcAccessorMethod(String value) {
        this.srcAccessorMethod = value;
    }

    /**
     * Gets the value of the srcMutatorMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcMutatorMethod() {
        return srcMutatorMethod;
    }

    /**
     * Sets the value of the srcMutatorMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcMutatorMethod(String value) {
        this.srcMutatorMethod = value;
    }

    /**
     * Gets the value of the destAccessorMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestAccessorMethod() {
        return destAccessorMethod;
    }

    /**
     * Sets the value of the destAccessorMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestAccessorMethod(String value) {
        this.destAccessorMethod = value;
    }

    /**
     * Gets the value of the destMutatorMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestMutatorMethod() {
        return destMutatorMethod;
    }

    /**
     * Sets the value of the destMutatorMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestMutatorMethod(String value) {
        this.destMutatorMethod = value;
    }

    /**
     * Gets the value of the converter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConverter() {
        return converter;
    }

    /**
     * Sets the value of the converter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConverter(String value) {
        this.converter = value;
    }

    /**
     * Gets the value of the converterDefaultDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConverterDefaultDir() {
        return converterDefaultDir;
    }

    /**
     * Sets the value of the converterDefaultDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConverterDefaultDir(String value) {
        this.converterDefaultDir = value;
    }

}
