package com.rsaame.pas.dao.model;

// Generated Jan 18, 2012 5:30:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.mindtree.ruc.cmn.utils.Utils;
import com.rsaame.pas.cmn.pojo.POJO;
import com.rsaame.pas.cmn.pojo.POJOId;

/**
 * TTrnSectionDetailsQuo generated by hbm2java
 */
public class TTrnSectionDetailsQuo extends POJO implements java.io.Serializable {

	private TTrnSectionDetailsQuoId id;
	private Long secEndtId;
	private Short secClCode;
	private Short secPtCode;
	private BigDecimal secCommVal;
	private Date secValidityExpiryDate;
	private String secNonStdText;
	private Byte secStatus;


	public TTrnSectionDetailsQuo() {
	}

	public TTrnSectionDetailsQuo(TTrnSectionDetailsQuoId id) {
		this.id = id;
	}

	public TTrnSectionDetailsQuo(TTrnSectionDetailsQuoId id, Long secEndtId,
			Short secClCode, Short secPtCode, BigDecimal secCommVal,
			Date secValidityExpiryDate, String secNonStdText,Byte secStatus) {
		this.id = id;
		this.secEndtId = secEndtId;
		this.secClCode = secClCode;
		this.secPtCode = secPtCode;
		this.secCommVal = secCommVal;
		this.secValidityExpiryDate = secValidityExpiryDate;
		this.secNonStdText = secNonStdText;
		this.secStatus = secStatus;
		
	}

	public TTrnSectionDetailsQuoId getId() {
		return this.id;
	}

	public void setId(TTrnSectionDetailsQuoId id) {
		this.id = id;
	}

	public Long getSecEndtId() {
		return this.secEndtId;
	}

	public void setSecEndtId(Long secEndtId) {
		this.secEndtId = secEndtId;
	}

	public Short getSecClCode() {
		return this.secClCode;
	}

	public void setSecClCode(Short secClCode) {
		this.secClCode = secClCode;
	}

	public Short getSecPtCode() {
		return this.secPtCode;
	}

	public void setSecPtCode(Short secPtCode) {
		this.secPtCode = secPtCode;
	}

	public BigDecimal getSecCommVal() {
		return this.secCommVal;
	}

	public void setSecCommVal(BigDecimal secCommVal) {
		this.secCommVal = secCommVal;
	}

	public Date getSecValidityExpiryDate() {
		return this.secValidityExpiryDate;
	}

	public void setSecValidityExpiryDate(Date secValidityExpiryDate) {
		this.secValidityExpiryDate = secValidityExpiryDate;
	}

	public String getSecNonStdText() {
		return this.secNonStdText;
	}

	public void setSecNonStdText(String secNonStdText) {
		this.secNonStdText = secNonStdText;
	}

	/**
	 * @return the secStatus
	 */
	public Byte getSecStatus(){
		return secStatus;
	}

	/**
	 * @param secStatus the secStatus to set
	 */
	public void setSecStatus( Byte secStatus ){
		this.secStatus = secStatus;
	}

	@Override
	public int getStatus(){
		return getSecStatus();
	}
	
	@Override
	public void setStatus( Integer status ){
		setSecStatus( status.byteValue() );
	}
	
	@Override
	public void setEndtId( Long endtId ){
		setSecEndtId( endtId );
	}
	
	@Override
	public void setValidityExpiryDate( Date ved ){
		setSecValidityExpiryDate( ved );
	}
	
	@Override
	public void setValidityStartDate( Date vsd ){
		if( !Utils.isEmpty( getId() ) ) getId().setSecValidityStartDate( vsd );
	}
	
	@Override
	public POJOId getPOJOId(){
		return this.getId();
	}
	
	@Override
	public void setPOJOId( POJOId id ){
		setId( (TTrnSectionDetailsQuoId) id );
	}
}
