//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GeneralInfoVO.java
//  @ Date : 12/20/2011
//  @ Author : 
//
//



package com.rsaame.pas.vo.bus;

import java.util.List;

import com.mindtree.ruc.cmn.base.BaseVO;


public class GeneralInfoVO extends BaseVO {
	private static final long serialVersionUID = 1L;
	private InsuredVO insured;
	private String jurisdiction;
	private AdditionalInsuredInfoVO additionalInfo;
	private SourceOfBusinessVO sourceOfBus;
	private ClaimsSummaryVO claimsHistory;
	private Boolean isChannelChanged;
	private String newCustomer;
	private String customerSaveReq;
	private UWQuestionsVO questionsVO;
	// Phasee/Home/travel changes:
	//Following fields have to be stored in t_mas_cash_customer table. 
	//So moving them to GeneralInfoVO to avoid the cash customer mapping issue in BaseSaveOperation
	private Integer intAccExecCode;
	private Integer extAccExecCode;
	// CoInsurance, Prev Insurer, Financier created for Ph 4
	private List<InsurerVO> coInsurer;
	private List<InsurerVO> previousInsurer;
	private List<FinancierVO> financier;
	private int vatCode;
	

	public int getVatCode() {
		return vatCode;
	}



	public void setVatCode(int vatCode) {
		this.vatCode = vatCode;
	}



	public Object getFieldValue( String fieldName ){
		Object fieldValue = null;

		if( "insured".equals( fieldName ) ) fieldValue = getInsured();
		if( "jurisdiction".equals( fieldName ) ) fieldValue = getJurisdiction();
		if( "additionalInfo".equals( fieldName ) ) fieldValue = getAdditionalInfo();
		if( "sourceOfBus".equals( fieldName ) ) fieldValue = getSourceOfBus();
		if( "claimsHistory".equals( fieldName ) ) fieldValue = getClaimsHistory();
		if( "isChannelChanged".equals( fieldName ) ) fieldValue = getIsChannelChanged();
		if( "newCustomer".equals( fieldName ) ) fieldValue = getNewCustomer();
		if("customerSaveReq".equals(fieldName)) fieldValue = getCustomerSaveReq();
		if("questionsVO".equals(fieldName)) fieldValue = getQuestionsVO();
		if("coInsurer".equals(fieldName)) fieldValue = getCoInsurer();
		if("previousInsurer".equals(fieldName)) fieldValue = getPreviousInsurer();
		if("financier".equals(fieldName)) fieldValue = getFinancier();
		return fieldValue;
	}
	
	
	
	/**
	 * @return the questionsVO
	 */
	public UWQuestionsVO getQuestionsVO(){
		return questionsVO;
	}



	/**
	 * @param questionsVO the questionsVO to set
	 */
	public void setQuestionsVO( UWQuestionsVO questionsVO ){
		this.questionsVO = questionsVO;
	}



	public InsuredVO getInsured(){
		return insured;
	}
	public void setInsured( InsuredVO insured ){
		this.insured = insured;
	}
	public String getJurisdiction(){
		return jurisdiction;
	}
	public void setJurisdiction( String jurisdiction ){
		this.jurisdiction = jurisdiction;
	}
	public AdditionalInsuredInfoVO getAdditionalInfo(){
		return additionalInfo;
	}
	public void setAdditionalInfo( AdditionalInsuredInfoVO additionalInfo ){
		this.additionalInfo = additionalInfo;
	}
	public SourceOfBusinessVO getSourceOfBus(){
		return sourceOfBus;
	}
	public void setSourceOfBus( SourceOfBusinessVO sourceOfBus ){
		this.sourceOfBus = sourceOfBus;
	}

	public ClaimsSummaryVO getClaimsHistory(){
		return claimsHistory;
	}
	public void setClaimsHistory( ClaimsSummaryVO claimsHistory ){
		this.claimsHistory = claimsHistory;
	}

	public Boolean getIsChannelChanged() {
		return isChannelChanged;
	}

	public void setIsChannelChanged(Boolean isChannelChanged) {
		this.isChannelChanged = isChannelChanged;
	}

	public String getNewCustomer() {
		return newCustomer;
	}

	public void setNewCustomer(String newCustomer) {
		this.newCustomer = newCustomer;
	}
	
	public String getCustomerSaveReq() {
		return customerSaveReq;
	}

	public void setCustomerSaveReq(String customerSaveReq) {
		this.customerSaveReq = customerSaveReq;
	}
	public Integer getIntAccExecCode(){
		return intAccExecCode;
	}
	public void setIntAccExecCode( Integer intAccExecCode ){
		this.intAccExecCode = intAccExecCode;
	}
	public Integer getExtAccExecCode(){
		return extAccExecCode;
	}
	public void setExtAccExecCode( Integer extAccExecCode ){
		this.extAccExecCode = extAccExecCode;
	}



	@Override
	public String toString(){
		return "GeneralInfoVO [insured=" + insured + ", jurisdiction=" + jurisdiction + ", additionalInfo=" + additionalInfo + ", sourceOfBus=" + sourceOfBus + ", claimsHistory="
				+ claimsHistory + ", isChannelChanged=" + isChannelChanged + ", newCustomer=" + newCustomer + ", customerSaveReq=" + customerSaveReq + ", questionsVO="
				+ questionsVO + ", intAccExecCode=" + intAccExecCode + ", extAccExecCode=" + extAccExecCode + ", coInsurer = " + coInsurer + ", previousInsurer = " + previousInsurer 
				+ ", financier = " + financier + "]";
	}

	/**
	 * get Co Insurer details
	 * @return
	 */
	public List<InsurerVO> getCoInsurer() {
		if(coInsurer == null){
			coInsurer = new com.mindtree.ruc.cmn.utils.List<InsurerVO>(InsurerVO.class);
		}
		return coInsurer;
	}
	
	public void setCoInsurer(List<InsurerVO> coInsurer) {
		this.coInsurer = coInsurer;
	}



	/**
	 * get Previous Insurer details
	 * @return
	 */
	public List<InsurerVO> getPreviousInsurer() {
		if(previousInsurer == null){
			previousInsurer = new com.mindtree.ruc.cmn.utils.List<InsurerVO>(InsurerVO.class);
		}
		return previousInsurer;
	}

	/**
	 * Get Financier details
	 * @return
	 */
	public List<FinancierVO> getFinancier() {
		if(financier == null){
			financier = new com.mindtree.ruc.cmn.utils.List<FinancierVO>(FinancierVO.class);
		}
		return financier;
	}

	public void setPreviousInsurer(List<InsurerVO> previousInsurer) {
		this.previousInsurer = previousInsurer;
	}



	public void setFinancier(List<FinancierVO> financier) {
		this.financier = financier;
	}


}
