package com.rsaame.pas.dao.model;

// Generated Feb 10, 2012 5:52:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * VParBldDeductibles generated by hbm2java
 */
public class VParBldDeductibles implements java.io.Serializable {

	private VParBldDeductiblesId id;

	public VParBldDeductibles() {
	}

	public VParBldDeductibles(VParBldDeductiblesId id) {
		this.id = id;
	}

	public VParBldDeductiblesId getId() {
		return this.id;
	}

	public void setId(VParBldDeductiblesId id) {
		this.id = id;
	}

}
