//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EndorsmentVO.java
//  @ Date : 12/20/2011
//  @ Author : 
//
//

package com.rsaame.pas.vo.bus;

import java.util.Date;

import com.mindtree.ruc.cmn.base.BaseVO;
import com.mindtree.ruc.cmn.reflect.IFieldValue;
import com.mindtree.ruc.cmn.utils.Utils;

public class EndorsmentVO extends BaseVO implements IFieldValue , Comparable<EndorsmentVO>{
	private static final long serialVersionUID = 1L;

	private Long endtId;
	private Long policyId;
	private Long endNo;
	private Integer slNo;
	private Date endCreateDate;
	private Date endEffDate;
	private Date endExpiryDate;
	private Integer endSecId;

	private Boolean proRate;
	private String endDesc;
	private String endText;
	
	private Date endDate;
	private String endHeader;
	private String endFooter;
	private String endType;

	PremiumVO oldPremiumVO;
	PremiumVO premiumVO;
	PremiumVO canPremiumVO;

	private String endRichText;
	private String endRtfFlag;
	private boolean isPolicyToBeCancelled=false;
	private boolean isShortTermCancellation=false;
	private Double shortTermCancellationPerc;
	private Integer recCreatedBy;
	private Date    recCreaDate;
	private Integer recModifiedBy;
	private Date 	recModifiedDt;
	
	private double payablePremium;
	
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getEndHeader() {
		return endHeader;
	}

	public void setEndHeader(String endHeader) {
		this.endHeader = endHeader;
	}

	public String getEndFooter() {
		return endFooter;
	}

	public void setEndFooter(String endFooter) {
		this.endFooter = endFooter;
	}

	public String getEndType() {
		return endType;
	}

	public void setEndType(String endType) {
		this.endType = endType;
	}

	public PremiumVO getOldPremiumVO() {
		return oldPremiumVO;
	}

	public void setOldPremiumVO(PremiumVO oldPremiumVO) {
		this.oldPremiumVO = oldPremiumVO;
	}

	public PremiumVO getPremiumVO() {
		return premiumVO;
	}

	public void setPremiumVO(PremiumVO premiumVO) {
		this.premiumVO = premiumVO;
	}

	public String getEndRichText() {
		return endRichText;
	}

	public void setEndRichText(String endRichText) {
		this.endRichText = endRichText;
	}

	public String getEndRtfFlag() {
		return endRtfFlag;
	}

	public void setEndRtfFlag(String endRtfFlag) {
		this.endRtfFlag = endRtfFlag;
	}

	
	

	public PremiumVO getCanPremiumVO(){
		return canPremiumVO;
	}

	public void setCanPremiumVO( PremiumVO canPremiumVO ){
		this.canPremiumVO = canPremiumVO;
	}

	public Object getFieldValue(String fieldName) {
		Object fieldValue = null;

		if ("endNo".equals(fieldName))
			fieldValue = getEndNo();
		if ("endCreateDate".equals(fieldName))
			fieldValue = getEndCreateDate();
		if ("endEffDate".equals(fieldName))
			fieldValue = getEndEffDate();
		if ("proRate".equals(fieldName))
			fieldValue = getProRate();
		if ("endDesc".equals(fieldName))
			fieldValue = getEndDesc();

		return fieldValue;
	}

	public Long getEndNo() {
		return endNo;
	}

	public void setEndNo(Long endNo) {
		this.endNo = endNo;
	}

	public Date getEndCreateDate() {
		return endCreateDate;
	}

	public void setEndCreateDate(Date endCreateDate) {
		this.endCreateDate = endCreateDate;
	}

	public Date getEndEffDate() {
		return endEffDate;
	}

	public void setEndEffDate(Date endEffDate) {
		this.endEffDate = endEffDate;
	}

	public Boolean getProRate() {
		return proRate;
	}

	public void setProRate(Boolean proRate) {
		this.proRate = proRate;
	}

	public String getEndDesc() {
		return endDesc;
	}

	public void setEndDesc(String endDesc) {
		this.endDesc = endDesc;
	}

	/**
	 * @param endExpiryDate
	 *            the endExpiryDate to set
	 */
	public void setEndExpiryDate(Date endExpiryDate) {
		this.endExpiryDate = endExpiryDate;
	}

	/**
	 * @return the endExpiryDate
	 */
	public Date getEndExpiryDate() {
		return endExpiryDate;
	}

	/**
	 * @param endText
	 *            the endText to set
	 */
	public void setEndText(String endText) {
		this.endText = endText;
	}

	/**
	 * @return the endText
	 */
	public String getEndText() {
		return endText;
	}

	/**
	 * @param endtId
	 *            the endtId to set
	 */
	public void setEndtId(Long endtId) {
		this.endtId = endtId;
	}

	/**
	 * @return the endtId
	 */
	public Long getEndtId() {
		return endtId;
	}

	/**
	 * @param policyId
	 *            the policyId to set
	 */
	public void setPolicyId(Long policyId) {
		this.policyId = policyId;
	}

	/**
	 * @return the policyId
	 */
	public Long getPolicyId() {
		return policyId;
	}

	/**
	 * @param slNo
	 *            the slNo to set
	 */
	public void setSlNo(Integer slNo) {
		this.slNo = slNo;
	}

	/**
	 * @return the slNo
	 */
	public Integer getSlNo() {
		return slNo;
	}

	/**
	 * @param isPolicyToBeCancelled the isPolicyToBeCancelled to set
	 */
	public void setPolicyToBeCancelled(boolean isPolicyToBeCancelled) {
		this.isPolicyToBeCancelled = isPolicyToBeCancelled;
	}

	/**
	 * @return the isPolicyToBeCancelled
	 */
	public boolean isPolicyToBeCancelled() {
		return isPolicyToBeCancelled;
	}

	public Integer getRecCreatedBy() {
		return recCreatedBy;
	}

	public void setRecCreatedBy(Integer recCreatedBy) {
		this.recCreatedBy = recCreatedBy;
	}

	public Date getRecCreaDate() {
		return recCreaDate;
	}

	public void setRecCreaDate(Date recCreaDate) {
		this.recCreaDate = recCreaDate;
	}

	public Integer getRecModifiedBy() {
		return recModifiedBy;
	}

	public void setRecModifiedBy(Integer recModifiedBy) {
		this.recModifiedBy = recModifiedBy;
	}

	public Date getRecModifiedDt() {
		return recModifiedDt;
	}

	public void setRecModifiedDt(Date recModifiedDt) {
		this.recModifiedDt = recModifiedDt;
	}

	public double getPayablePremium(){
		return payablePremium;
	}

	public void setPayablePremium( double payablePremium ){
		this.payablePremium = payablePremium;
	}
	
	
	
	public Integer getEndSecId() {
		return endSecId;
	}

	public void setEndSecId(Integer endSecId) {
		this.endSecId = endSecId;
	}

	//Added for period based cancellation for Oman
	/**
	 * @return the isShortTermCancellation
	 */
	public boolean isShortTermCancellation(){
		return isShortTermCancellation;
	}

	/**
	 * @param isShortTermCancellation the isShortTermCancellation to set
	 */
	public void setShortTermCancellation( boolean isShortTermCancellation ){
		this.isShortTermCancellation = isShortTermCancellation;
	}
	/**
	 * @return the shortTermCancellationPerc
	 */
	public Double getShortTermCancellationPerc(){
		return shortTermCancellationPerc;
	}

	/**
	 * @param shortTermCancellationPerc the shortTermCancellationPerc to set
	 */
	public void setShortTermCancellationPerc( Double shortTermCancellationPerc ){
		this.shortTermCancellationPerc = shortTermCancellationPerc;
	}

	@Override
	public int compareTo( EndorsmentVO other ){
		if( !Utils.isEmpty( this.getSlNo() ) && !Utils.isEmpty( other.getSlNo() ) ){
			return this.getSlNo() - other.getSlNo();
		}
		return 0;
	}
}
