//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LocationAddressVO.java
//  @ Date : 12/20/2011
//  @ Author : 
//
//



package com.rsaame.pas.vo.bus;

import com.mindtree.ruc.cmn.base.BaseVO;
import com.mindtree.ruc.cmn.utils.Utils;


public class LocationAddressVO extends BaseVO {
	private static final long serialVersionUID = 1L;
	private String officeShopNo;
	private String floor;
	private String buildingName;
	private String streetName;
	private Integer locOverrideTer; // Territory code for the location 
	private Integer locOverrideJur; // Jurisdiction code for the loc
	private String poBox;
	private String wayNo;
	private String blockNo;
	private String area;
	private boolean isPoBoxChanged;
	//Added for Informap Changes
	private Double latitude;
	private Double longitude;
	private String addressInDetail;
	private String inforMapStatus;
		
	public Double getLatitude() {
		return latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public String getAddressInDetail() {
		return addressInDetail;
	}

	public void setAddressInDetail(String addressInDetail) {
		this.addressInDetail = addressInDetail;
	}

	public Double getLongitude() {
		return longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	

	public Object getFieldValue( String fieldName ){
		Object fieldValue = null;

		if( "officeShopNo".equals( fieldName ) ) fieldValue = getOfficeShopNo();
		if( "floor".equals( fieldName ) ) fieldValue = getFloor();
		if( "buildingName".equals( fieldName ) ) fieldValue = getBuildingName();
		if( "streetName".equals( fieldName ) ) fieldValue = getStreetName();
		if( "locOverrideTer".equals( fieldName ) ) fieldValue = getLocOverrideTer();
		if( "locOverrideJur".equals( fieldName ) ) fieldValue = getLocOverrideJur();
		if("poBox".equals( fieldName )) fieldValue = getPoBox();
		//Added for Informap changes
		if("latitude".equals( fieldName )) fieldValue = getLatitude();
		if("longitude".equals( fieldName )) fieldValue = getLongitude();
		return fieldValue;
	}
	
	public String getOfficeShopNo(){
		return officeShopNo;
	}
	public void setOfficeShopNo( String officeShopNo ){
		this.officeShopNo = officeShopNo;
	}
	public String getFloor(){
		return floor;
	}
	public void setFloor( String floor ){
		this.floor = floor;
	}
	public String getBuildingName(){
		return buildingName;
	}
	public void setBuildingName( String buildingName ){
		this.buildingName = buildingName;
	}
	public String getStreetName(){
		return streetName;
	}
	public void setStreetName( String streetName ){
		this.streetName = streetName;
	}

	/**
	 * @return the locOverrideTer
	 */
	public Integer getLocOverrideTer() {
		return locOverrideTer;
	}

	/**
	 * @param locOverrideTer the locOverrideTer to set
	 */
	public void setLocOverrideTer(Integer locOverrideTer) {
		this.locOverrideTer = locOverrideTer;
	}

	/**
	 * @return the locOverrideJur
	 */
	public Integer getLocOverrideJur() {
		return locOverrideJur;
	}

	/**
	 * @param locOverrideJur the locOverrideJur to set
	 */
	public void setLocOverrideJur(Integer locOverrideJur) {
		this.locOverrideJur = locOverrideJur;
	}

	public String getPoBox() {
		return poBox;
	}

	public void setPoBox(String poBox) {
		this.poBox = poBox;
	}
	
	

	/**
	 * @return the wayNo
	 */
	public String getWayNo(){
		return wayNo;
	}

	/**
	 * @param wayNo the wayNo to set
	 */
	public void setWayNo( String wayNo ){
		this.wayNo = wayNo;
	}

	/**
	 * @return the blockNo
	 */
	public String getBlockNo(){
		return blockNo;
	}

	/**
	 * @param blockNo the blockNo to set
	 */
	public void setBlockNo( String blockNo ){
		this.blockNo = blockNo;
	}

	/**
	 * @return the area
	 */
	public String getArea(){
		return area;
	}

	/**
	 * @param area the area to set
	 */
	public void setArea( String area ){
		this.area = area;
	}
	
	

	public boolean isPoBoxChanged() {
		return isPoBoxChanged;
	}

	public void setPoBoxChanged(boolean isPoBoxChanged) {
		this.isPoBoxChanged = isPoBoxChanged;
	}

	@Override
	public String toString() {
		return "LocationAddressVO [officeShopNo=" + officeShopNo + ", floor="
				+ floor + ", buildingName=" + buildingName + ", streetName="
				+ streetName + ", locOverrideTer=" + locOverrideTer
				+ ", locOverrideJur=" + locOverrideJur + ", poBox=" + poBox
				+ "]";
	}
	
	public LocationAddressVO copy(){
		LocationAddressVO copy = new LocationAddressVO();
		 
		copy.buildingName = this.buildingName;
		copy.floor = this.floor;
		copy.locOverrideJur = this.locOverrideJur;
		copy.locOverrideTer = this.locOverrideTer;
		copy.streetName = this.streetName;
		copy.officeShopNo = this.officeShopNo;
		copy.poBox=this.poBox;
		copy.blockNo = this.blockNo;
		copy.area = this.area;
		copy.wayNo = this.wayNo;
		copy.isPoBoxChanged =this.isPoBoxChanged;
		return copy;
	}
	
	public void merge( LocationAddressVO otherVO ){
		if( Utils.isEmpty( otherVO ) ) return;
		
		if( Utils.isEmpty( this.buildingName ) ) this.buildingName = otherVO.buildingName;
		if( Utils.isEmpty( this.floor ) ) this.floor = otherVO.floor;
		if( Utils.isEmpty( this.locOverrideJur ) ) this.locOverrideJur = otherVO.locOverrideJur;
		if( Utils.isEmpty( this.locOverrideTer ) ) this.locOverrideTer = otherVO.locOverrideTer;
		if( Utils.isEmpty( this.streetName ) ) this.streetName = otherVO.streetName;
		if( Utils.isEmpty( this.officeShopNo ) ) this.officeShopNo = otherVO.officeShopNo;
		if( Utils.isEmpty( this.poBox ) ) this.poBox = otherVO.poBox;
		if( Utils.isEmpty( this.blockNo ) ) this.blockNo = otherVO.blockNo;
		if( Utils.isEmpty( this.area ) ) this.area = otherVO.area;
		if( Utils.isEmpty( this.wayNo ) ) this.wayNo = otherVO.wayNo;
		if( Utils.isEmpty(this.isPoBoxChanged))this.isPoBoxChanged = otherVO.isPoBoxChanged;
		
	}
	
	//Added for Informap changes
		public String getInforMapStatus() {
			return inforMapStatus;
		}

		public void setInforMapStatus(String inforMapStatus) {
			this.inforMapStatus = inforMapStatus;
		}
}
