//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EMLUWDetailsVO.java
//  @ Date : 12/20/2011
//  @ Author : 
//
//



package com.rsaame.pas.vo.bus;


public class PLUWDetailsVO extends UWDetails {
	
	private static final long serialVersionUID = 1L;
	private SimpleUWDetailsVO uwMinDetails;
	
	public Object getFieldValue( String fieldName ){
		Object fieldValue = null;

		if( "uwMinDetails".equals( fieldName ) ) fieldValue = getUwMinDetails();

		return fieldValue;
	}

	public SimpleUWDetailsVO getUwMinDetails(){
		return uwMinDetails;
	}

	public void setUwMinDetails( SimpleUWDetailsVO uwMinDetails ){
		this.uwMinDetails = uwMinDetails;
	}
	
}
