//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DOSVO.java
//  @ Date : 12/20/2011
//  @ Author : 
//
//



package com.rsaame.pas.vo.bus;


public class PublicLiabilityVO extends RiskGroupDetails {
	
	private static final long serialVersionUID = 1L;
	private SumInsuredVO sumInsuredDets; 
	private Integer indemnityAmtLimit;
	private Integer sumInsuredBasis;
	
	private Long wbdId;
	
	/*
	 * Added liabilityLimit for JLT Web Service Referral flow
	 * To capture the limit if limit is more than >10M to send to rule engine
	 * For display in the task list
	 */
	private Double liabilityLimit;
	
	public Object getFieldValue( String fieldName ){
		Object fieldValue = null;

		if( "sumInsuredDets".equals( fieldName ) ) fieldValue = getSumInsuredDets();
		if( "indemnityAmtLimit".equals( fieldName ) ) fieldValue = getIndemnityAmtLimit();
		if( "sumInsuredBasis".equals( fieldName ) ) fieldValue = getSumInsuredBasis();

		return fieldValue;
	}
	

	public Integer getIndemnityAmtLimit(){
		return indemnityAmtLimit;
	}
	public void setIndemnityAmtLimit( Integer indemnityAmtLimit ){
		this.indemnityAmtLimit = indemnityAmtLimit;
	}


	/**
	 * @return the sumInsuredDets
	 */
	public SumInsuredVO getSumInsuredDets() {
		return sumInsuredDets;
	}


	/**
	 * @param sumInsuredDets the sumInsuredDets to set
	 */
	public void setSumInsuredDets(SumInsuredVO sumInsuredDets) {
		this.sumInsuredDets = sumInsuredDets;
	}


	/**
	 * @return the sumInsuredBasis
	 */
	public Integer getSumInsuredBasis() {
		return sumInsuredBasis;
	}


	/**
	 * @param sumInsuredBasis the sumInsuredBasis to set
	 */
	public void setSumInsuredBasis(Integer sumInsuredBasis) {
		this.sumInsuredBasis = sumInsuredBasis;
	}

	

	/**
	 * @return the wbdId
	 */
	public Long getWbdId() {
		return wbdId;
	}


	/**
	 * @param wbdId the wbdId to set
	 */
	public void setWbdId(Long wbdId) {
		this.wbdId = wbdId;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "PublicLiabilityVO [sumInsuredDets=" + sumInsuredDets
				+ ", indemnityAmtLimit=" + indemnityAmtLimit
				+ ", sumInsuredBasis=" + sumInsuredBasis + ", wbdId=" + wbdId
				+ "]";
	}
	
	public Double getLiabilityLimit() {
		return liabilityLimit;
	}

	public void setLiabilityLimit(Double liabilityLimit) {
		this.liabilityLimit = liabilityLimit;
	}

}
