package com.rsaame.pas.vo.bus;

import java.math.BigDecimal;
import java.util.Date;

import com.mindtree.ruc.cmn.base.BaseVO;

/**
 * TTrnSectionDetailsQuo generated by hbm2java
 */
public class SectionDetailsVO extends BaseVO{

	private static final long serialVersionUID = 1L;
	private long secPolicyId;
	private short secSecId;
	private Date secValidityStartDate;
	private Long secEndtId;
	private Short secClCode;
	private Short secPtCode;
	private BigDecimal secCommVal;
	private Date secValidityExpiryDate;
	private String secNonStdText;
	private Short policyTariffCode;

	public Object getFieldValue( String fieldName ){
		Object fieldValue = null;

		if( "secPolicyId".equals( fieldName ) ) fieldValue = getSecPolicyId();
		if( "secSecId".equals( fieldName ) ) fieldValue = getSecSecId();
		if( "secValidityStartDate".equals( fieldName ) ) fieldValue = getSecValidityStartDate();
		if( "secEndtId".equals( fieldName ) ) fieldValue = getSecEndtId();
		if( "secClCode".equals( fieldName ) ) fieldValue = getSecClCode();
		if( "secPtCode".equals( fieldName ) ) fieldValue = getSecPtCode();
		if( "secCommVal".equals( fieldName ) ) fieldValue = getSecCommVal();
		if( "secValidityExpiryDate".equals( fieldName ) ) fieldValue = getSecValidityExpiryDate();
		if( "secNonStdText".equals( fieldName ) ) fieldValue = getSecNonStdText();
		if( "policyTariffCode".equals( fieldName ) ) fieldValue = getPolicyTariffCode();

		return fieldValue;
	}

	/**
	 * @return the secPolicyId
	 */
	public long getSecPolicyId(){
		return secPolicyId;
	}

	/**
	 * @param secPolicyId the secPolicyId to set
	 */
	public void setSecPolicyId( long secPolicyId ){
		this.secPolicyId = secPolicyId;
	}

	/**
	 * @return the secSecId
	 */
	public short getSecSecId(){
		return secSecId;
	}

	/**
	 * @param secSecId the secSecId to set
	 */
	public void setSecSecId( short secSecId ){
		this.secSecId = secSecId;
	}

	/**
	 * @return the secValidityStartDate
	 */
	public Date getSecValidityStartDate(){
		return secValidityStartDate;
	}

	/**
	 * @param secValidityStartDate the secValidityStartDate to set
	 */
	public void setSecValidityStartDate( Date secValidityStartDate ){
		this.secValidityStartDate = secValidityStartDate;
	}

	/**
	 * @return the secEndtId
	 */
	public Long getSecEndtId(){
		return secEndtId;
	}

	/**
	 * @param secEndtId the secEndtId to set
	 */
	public void setSecEndtId( Long secEndtId ){
		this.secEndtId = secEndtId;
	}

	/**
	 * @return the secClCode
	 */
	public Short getSecClCode(){
		return secClCode;
	}

	/**
	 * @param secClCode the secClCode to set
	 */
	public void setSecClCode( Short secClCode ){
		this.secClCode = secClCode;
	}

	/**
	 * @return the secPtCode
	 */
	public Short getSecPtCode(){
		return secPtCode;
	}

	/**
	 * @param secPtCode the secPtCode to set
	 */
	public void setSecPtCode( Short secPtCode ){
		this.secPtCode = secPtCode;
	}

	/**
	 * @return the secCommVal
	 */
	public BigDecimal getSecCommVal(){
		return secCommVal;
	}

	/**
	 * @param secCommVal the secCommVal to set
	 */
	public void setSecCommVal( BigDecimal secCommVal ){
		this.secCommVal = secCommVal;
	}

	/**
	 * @return the secValidityExpiryDate
	 */
	public Date getSecValidityExpiryDate(){
		return secValidityExpiryDate;
	}

	/**
	 * @param secValidityExpiryDate the secValidityExpiryDate to set
	 */
	public void setSecValidityExpiryDate( Date secValidityExpiryDate ){
		this.secValidityExpiryDate = secValidityExpiryDate;
	}

	/**
	 * @return the secNonStdText
	 */
	public String getSecNonStdText(){
		return secNonStdText;
	}

	/**
	 * @param secNonStdText the secNonStdText to set
	 */
	public void setSecNonStdText( String secNonStdText ){
		this.secNonStdText = secNonStdText;
	}

	/**
	 * @return the policyTariffCode
	 */
	public Short getPolicyTariffCode(){
		return policyTariffCode;
	}

	/**
	 * @param policyTariffCode the policyTariffCode to set
	 */
	public void setPolicyTariffCode( Short policyTariffCode ){
		this.policyTariffCode = policyTariffCode;
	}

}
