//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SourceOfBusinessVO.java
//  @ Date : 12/20/2011
//  @ Author : 
//
//

package com.rsaame.pas.vo.bus;

import com.mindtree.ruc.cmn.base.BaseVO;

public class SourceOfBusinessVO extends BaseVO {
	private static final long serialVersionUID = 1L;
	// private Integer brokerType;
	private Integer distributionChannel;
	private Integer brokerName;
	private Long directSubAgent;
	private String customerSource;
	private String promoCode;
	private String promoCodeDesc;
	private String partnerName;
	private String partnerId;
	private String replyToEmailId;
	private String ccEmailId;
	private String callCentreNo;
	private String policyTerms;
	private Long defaultAssignToUser;
	private Double defaultOnlineDiscount;
	private String fromEmailID;
	private Integer sourceOfBusiness;
	private String faqUrl;
	private String policyTermUrl;
    private String emailDomain;

	
	public Object getFieldValue(String fieldName) {
		Object fieldValue = null;

		/* if( "brokerType".equals( fieldName ) ) fieldValue = getBrokerType(); */
		if ("distributionChannel".equals(fieldName))
			fieldValue = getDistributionChannel();
		if ("brokerName".equals(fieldName))
			fieldValue = getBrokerName();
		if ("directSubAgent".equals(fieldName))
			fieldValue = getDirectSubAgent();
		if ("customerSource".equals(fieldName))
			fieldValue = getCustomerSource();
		if ("promoCode".equals(fieldName))
			fieldValue = getPromoCode();
		if ("promoCodeDesc".equals(fieldName))
			fieldValue = getPromoCodeDesc();
		if ("partnerId".equals(fieldName))
			fieldValue = getPartnerId();
		if ("partnerName".equals(fieldName))
			fieldValue = getPartnerName();
		if ("defaultAssignToUser".equals(fieldName))
			fieldValue = getDefaultAssignToUser();
		return fieldValue;
	}

	/*
	 * public int getBrokerType(){ return brokerType; } public void
	 * setBrokerType( int brokerType ){ this.brokerType = brokerType; }
	 */

	public String getCustomerSource() {
		return customerSource;
	}

	public void setCustomerSource(String customerSource) {
		this.customerSource = customerSource;
	}

	public String getPromoCode() {
		return promoCode;
	}

	public void setPromoCode(String promoCode) {
		this.promoCode = promoCode;
	}

	/**
	 * @return the promoCodeDesc
	 */
	public String getPromoCodeDesc(){
		return promoCodeDesc;
	}

	/**
	 * @param promoCodeDesc the promoCodeDesc to set
	 */
	public void setPromoCodeDesc( String promoCodeDesc ){
		this.promoCodeDesc = promoCodeDesc;
	}

	public Integer getDistributionChannel() {
		return distributionChannel;
	}

	public void setDistributionChannel(Integer distributionChannel) {
		this.distributionChannel = distributionChannel;
	}

	public Integer getBrokerName() {
		return brokerName;
	}

	public void setBrokerName(Integer brokerName) {
		this.brokerName = brokerName;
	}

	public Long getDirectSubAgent() {
		return directSubAgent;
	}

	public void setDirectSubAgent(Long directSubAgent) {
		this.directSubAgent = directSubAgent;
	}
	
	public String getPartnerName() {
		return partnerName;
	}

	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}
	public String getPartnerId() {
		return partnerId;
	}

	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId;
	}

	public String getReplyToEmailId() {
		return replyToEmailId;
	}

	public void setReplyToEmailId(String replyToEmailId) {
		this.replyToEmailId = replyToEmailId;
	}

	public void setDefaultOnlineDiscount(Double defaultOnlineDiscount) {
		this.defaultOnlineDiscount = defaultOnlineDiscount;
	}

	public String getCcEmailId() {
		return ccEmailId;
	}

	public void setCcEmailId(String ccEmailId) {
		this.ccEmailId = ccEmailId;
	}

	public String getCallCentreNo() {
		return callCentreNo;
	}

	public void setCallCentreNo(String callCentreNo) {
		this.callCentreNo = callCentreNo;
	}

	public String getPolicyTerms() {
		return policyTerms;
	}

	public void setPolicyTerms(String policyTerms) {
		this.policyTerms = policyTerms;
	}

	/**
	 * @return the defaultAssignToUser
	 */
	public Long getDefaultAssignToUser(){
		return defaultAssignToUser;
	}

	/**
	 * @param defaultAssignToUser the defaultAssignToUser to set
	 */
	public void setDefaultAssignToUser( Long defaultAssignToUser ){
		this.defaultAssignToUser = defaultAssignToUser;
	}

	/**
	 * @return the defaultOnlineDiscount
	 */
	public Double getDefaultOnlineDiscount() {
		return defaultOnlineDiscount;
	}

	public String getFromEmailID() {
		return fromEmailID;
	}

	public void setFromEmailID(String fromEmailID) {
		this.fromEmailID = fromEmailID;
	}

	public Integer getSourceOfBusiness() {
		return sourceOfBusiness;
	}

	public void setSourceOfBusiness(Integer sourceOfBusiness) {
		this.sourceOfBusiness = sourceOfBusiness;
	}
	
	public String getFaqUrl() {
		return faqUrl;
	}

	public void setFaqUrl(String faqUrl) {
		this.faqUrl = faqUrl;
	}


	public String getPolicyTermUrl() {
		return policyTermUrl;
	}

	public void setPolicyTermUrl(String policyTermUrl) {
		this.policyTermUrl = policyTermUrl;
     }
	//m1043116-email domain validation
	public String getEmailDomain() {
		return emailDomain;
	}
	
	public void setEmailDomain(String emailDomain) {
		this.emailDomain = emailDomain;
		
	}
	
}
