//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UWQuestionVO.java
//  @ Date : 12/20/2011
//  @ Author : 
//
//



package com.rsaame.pas.vo.bus;

import java.util.Date;

import com.mindtree.ruc.cmn.base.BaseVO;


public class UWQuestionVO extends BaseVO implements Comparable<UWQuestionVO>{
	private static final long serialVersionUID = 1L;
	private Short qId;
	private String qDesc;
	private UWQuestionRespType responseType;
	private String response;
	private Date preparedDate;
	
	public UWQuestionVO(UWQuestionRespType uwQuestionRespType) {
		this.responseType = uwQuestionRespType;
		}
	
	public UWQuestionVO()
	{
		
	}
	
	public Object getFieldValue( String fieldName ){
		Object fieldValue = null;

		if( "qId".equals( fieldName ) ) fieldValue = getQId();
		if( "qDesc".equals( fieldName ) ) fieldValue = getQDesc();
		if( "responseType".equals( fieldName ) ) fieldValue = getResponseType();
		if( "response".equals( fieldName ) ) fieldValue = getResponse();
		if( "response".equals( fieldName ) ) fieldValue = getResponse();
		if( "preparedDate".equals( fieldName ) ) fieldValue = getResponse();
		return fieldValue;
	}
	
	public Short getQId(){
		return qId;
	}
	public void setQId( Short qId ){
		this.qId = qId;
	}
	public String getQDesc(){
		return qDesc;
	}
	public void setQDesc( String qDesc ){
		this.qDesc = qDesc;
	}
	public UWQuestionRespType getResponseType(){
		return responseType;
	}
	public void setResponseType( UWQuestionRespType responseType ){
		this.responseType = responseType;
	}
	public String getResponse(){
		return response;
	}
	public void setResponse( String response ){
		this.response = response;
	}
	
	public Date getPreparedDate() {
		return preparedDate;
	}

	public void setPreparedDate(Date preparedDate) {
		this.preparedDate = preparedDate;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString(){
		return "UWQuestionVO [qId=" + qId + ", qDesc=" + qDesc + ", responseType=" + responseType + ", response=" + response + "]";
	}

	@Override
	public int compareTo( UWQuestionVO o ){
		
		return this.qId-o.qId;
	}
	
	
}
