package com.rsaame.pas.dao.model;

// Generated Feb 1, 2012 11:52:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TMasCoverType generated by hbm2java
 */
public class TMasCoverType implements java.io.Serializable {

	private TMasCoverTypeId id;
	private String ctADesc;
	private String ctEDesc;
	private Short ctUserCode;
	private Integer ctPreparedBy;
	private Date ctPreparedDt;
	private Integer ctModifiedBy;
	private Date ctModifiedDt;
	private Set TMasCoverSubTypes = new HashSet(0);

	public TMasCoverType() {
	}

	public TMasCoverType(TMasCoverTypeId id) {
		this.id = id;
	}

	public TMasCoverType(TMasCoverTypeId id, String ctADesc, String ctEDesc,
			Short ctUserCode, Integer ctPreparedBy, Date ctPreparedDt,
			Integer ctModifiedBy, Date ctModifiedDt, Set TMasCoverSubTypes) {
		this.id = id;
		this.ctADesc = ctADesc;
		this.ctEDesc = ctEDesc;
		this.ctUserCode = ctUserCode;
		this.ctPreparedBy = ctPreparedBy;
		this.ctPreparedDt = ctPreparedDt;
		this.ctModifiedBy = ctModifiedBy;
		this.ctModifiedDt = ctModifiedDt;
		this.TMasCoverSubTypes = TMasCoverSubTypes;
	}

	public TMasCoverTypeId getId() {
		return this.id;
	}

	public void setId(TMasCoverTypeId id) {
		this.id = id;
	}

	public String getCtADesc() {
		return this.ctADesc;
	}

	public void setCtADesc(String ctADesc) {
		this.ctADesc = ctADesc;
	}

	public String getCtEDesc() {
		return this.ctEDesc;
	}

	public void setCtEDesc(String ctEDesc) {
		this.ctEDesc = ctEDesc;
	}

	public Short getCtUserCode() {
		return this.ctUserCode;
	}

	public void setCtUserCode(Short ctUserCode) {
		this.ctUserCode = ctUserCode;
	}

	public Integer getCtPreparedBy() {
		return this.ctPreparedBy;
	}

	public void setCtPreparedBy(Integer ctPreparedBy) {
		this.ctPreparedBy = ctPreparedBy;
	}

	public Date getCtPreparedDt() {
		return this.ctPreparedDt;
	}

	public void setCtPreparedDt(Date ctPreparedDt) {
		this.ctPreparedDt = ctPreparedDt;
	}

	public Integer getCtModifiedBy() {
		return this.ctModifiedBy;
	}

	public void setCtModifiedBy(Integer ctModifiedBy) {
		this.ctModifiedBy = ctModifiedBy;
	}

	public Date getCtModifiedDt() {
		return this.ctModifiedDt;
	}

	public void setCtModifiedDt(Date ctModifiedDt) {
		this.ctModifiedDt = ctModifiedDt;
	}

	public Set getTMasCoverSubTypes() {
		return this.TMasCoverSubTypes;
	}

	public void setTMasCoverSubTypes(Set TMasCoverSubTypes) {
		this.TMasCoverSubTypes = TMasCoverSubTypes;
	}

}
