package com.rsaame.pas.dao.model;

// Generated Feb 1, 2012 11:52:36 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TMasCoverSubType generated by hbm2java
 */
public class TMasCoverSubType implements java.io.Serializable {

	private TMasCoverSubTypeId id;
	private TMasCoverType TMasCoverType;
	private String cstADesc;
	private String cstEDesc;
	private String cstColumnReference;
	private BigDecimal cstValueFrom;
	private BigDecimal cstValueTo;
	private Short cstUserCode;
	private Byte cstSitypeCode;
	private Integer cstPreparedBy;
	private Date cstPreparedDt;
	private Integer cstModifiedBy;
	private Date cstModifiedDt;
	private Integer cstStatus;

	public TMasCoverSubType() {
	}

	public TMasCoverSubType(TMasCoverSubTypeId id, TMasCoverType TMasCoverType) {
		this.id = id;
		this.TMasCoverType = TMasCoverType;
	}

	public TMasCoverSubType(TMasCoverSubTypeId id, TMasCoverType TMasCoverType,
			String cstADesc, String cstEDesc, String cstColumnReference,
			BigDecimal cstValueFrom, BigDecimal cstValueTo, Short cstUserCode,
			Byte cstSitypeCode, Integer cstPreparedBy, Date cstPreparedDt,
			Integer cstModifiedBy, Date cstModifiedDt, Integer cstStatus) {
		this.id = id;
		this.TMasCoverType = TMasCoverType;
		this.cstADesc = cstADesc;
		this.cstEDesc = cstEDesc;
		this.cstColumnReference = cstColumnReference;
		this.cstValueFrom = cstValueFrom;
		this.cstValueTo = cstValueTo;
		this.cstUserCode = cstUserCode;
		this.cstSitypeCode = cstSitypeCode;
		this.cstPreparedBy = cstPreparedBy;
		this.cstPreparedDt = cstPreparedDt;
		this.cstModifiedBy = cstModifiedBy;
		this.cstModifiedDt = cstModifiedDt;
		this.cstStatus = cstStatus;
	}

	public TMasCoverSubTypeId getId() {
		return this.id;
	}

	public void setId(TMasCoverSubTypeId id) {
		this.id = id;
	}

	public TMasCoverType getTMasCoverType() {
		return this.TMasCoverType;
	}

	public void setTMasCoverType(TMasCoverType TMasCoverType) {
		this.TMasCoverType = TMasCoverType;
	}

	public String getCstADesc() {
		return this.cstADesc;
	}

	public void setCstADesc(String cstADesc) {
		this.cstADesc = cstADesc;
	}

	public String getCstEDesc() {
		return this.cstEDesc;
	}

	public void setCstEDesc(String cstEDesc) {
		this.cstEDesc = cstEDesc;
	}

	public String getCstColumnReference() {
		return this.cstColumnReference;
	}

	public void setCstColumnReference(String cstColumnReference) {
		this.cstColumnReference = cstColumnReference;
	}

	public BigDecimal getCstValueFrom() {
		return this.cstValueFrom;
	}

	public void setCstValueFrom(BigDecimal cstValueFrom) {
		this.cstValueFrom = cstValueFrom;
	}

	public BigDecimal getCstValueTo() {
		return this.cstValueTo;
	}

	public void setCstValueTo(BigDecimal cstValueTo) {
		this.cstValueTo = cstValueTo;
	}

	public Short getCstUserCode() {
		return this.cstUserCode;
	}

	public void setCstUserCode(Short cstUserCode) {
		this.cstUserCode = cstUserCode;
	}

	public Byte getCstSitypeCode() {
		return this.cstSitypeCode;
	}

	public void setCstSitypeCode(Byte cstSitypeCode) {
		this.cstSitypeCode = cstSitypeCode;
	}

	public Integer getCstPreparedBy() {
		return this.cstPreparedBy;
	}

	public void setCstPreparedBy(Integer cstPreparedBy) {
		this.cstPreparedBy = cstPreparedBy;
	}

	public Date getCstPreparedDt() {
		return this.cstPreparedDt;
	}

	public void setCstPreparedDt(Date cstPreparedDt) {
		this.cstPreparedDt = cstPreparedDt;
	}

	public Integer getCstModifiedBy() {
		return this.cstModifiedBy;
	}

	public void setCstModifiedBy(Integer cstModifiedBy) {
		this.cstModifiedBy = cstModifiedBy;
	}

	public Date getCstModifiedDt() {
		return this.cstModifiedDt;
	}

	public void setCstModifiedDt(Date cstModifiedDt) {
		this.cstModifiedDt = cstModifiedDt;
	}

	public Integer getCstStatus() {
		return this.cstStatus;
	}

	public void setCstStatus(Integer cstStatus) {
		this.cstStatus = cstStatus;
	}

}
