package com.rsaame.pas.dao.model;

// Generated Feb 1, 2012 11:52:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * TMasRiskSubCategoryId generated by hbm2java
 */
public class TMasRiskSubCategoryId implements java.io.Serializable {

	private int rscRskCode;
	private int rscRtCode;
	private int rscRcCode;
	private int rscCode;

	public TMasRiskSubCategoryId() {
	}

	public TMasRiskSubCategoryId(int rscRskCode, int rscRtCode, int rscRcCode,
			int rscCode) {
		this.rscRskCode = rscRskCode;
		this.rscRtCode = rscRtCode;
		this.rscRcCode = rscRcCode;
		this.rscCode = rscCode;
	}

	public int getRscRskCode() {
		return this.rscRskCode;
	}

	public void setRscRskCode(int rscRskCode) {
		this.rscRskCode = rscRskCode;
	}

	public int getRscRtCode() {
		return this.rscRtCode;
	}

	public void setRscRtCode(int rscRtCode) {
		this.rscRtCode = rscRtCode;
	}

	public int getRscRcCode() {
		return this.rscRcCode;
	}

	public void setRscRcCode(int rscRcCode) {
		this.rscRcCode = rscRcCode;
	}

	public int getRscCode() {
		return this.rscCode;
	}

	public void setRscCode(int rscCode) {
		this.rscCode = rscCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMasRiskSubCategoryId))
			return false;
		TMasRiskSubCategoryId castOther = (TMasRiskSubCategoryId) other;

		return (this.getRscRskCode() == castOther.getRscRskCode())
				&& (this.getRscRtCode() == castOther.getRscRtCode())
				&& (this.getRscRcCode() == castOther.getRscRcCode())
				&& (this.getRscCode() == castOther.getRscCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRscRskCode();
		result = 37 * result + this.getRscRtCode();
		result = 37 * result + this.getRscRcCode();
		result = 37 * result + this.getRscCode();
		return result;
	}

}
