package com.rsaame.pas.dao.model;

// Generated Feb 15, 2012 3:19:16 PM by Hibernate Tools 3.4.0.CR1

/**
 * TMasUwMappingId generated by hbm2java
 */
public class TMasUwMappingId implements java.io.Serializable {

	private short uwmUwqCode;
	private short uwmTarCode;

	public TMasUwMappingId() {
	}

	public TMasUwMappingId(short uwmUwqCode, short uwmTarCode) {
		this.uwmUwqCode = uwmUwqCode;
		this.uwmTarCode = uwmTarCode;
	}

	public short getUwmUwqCode() {
		return this.uwmUwqCode;
	}

	public void setUwmUwqCode(short uwmUwqCode) {
		this.uwmUwqCode = uwmUwqCode;
	}

	public short getUwmTarCode() {
		return this.uwmTarCode;
	}

	public void setUwmTarCode(short uwmTarCode) {
		this.uwmTarCode = uwmTarCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMasUwMappingId))
			return false;
		TMasUwMappingId castOther = (TMasUwMappingId) other;

		return (this.getUwmUwqCode() == castOther.getUwmUwqCode())
				&& (this.getUwmTarCode() == castOther.getUwmTarCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUwmUwqCode();
		result = 37 * result + this.getUwmTarCode();
		return result;
	}

}
