package com.rsaame.pas.dao.model;

// Generated May 17, 2012 10:24:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TMasPolicyCondition generated by hbm2java
 */
public class TMasPolicyCondition implements java.io.Serializable {

	private TMasPolicyConditionId id;
	private String pcAText;
	private String pcEText;
	private Integer pcDefaultInd;
	private Integer pcCtCode;
	private Integer pcCstCode;
	private Integer pcUserCode;
	private Integer pcPhrCode;
	private String pcAmount;
	private Integer pcPreparedBy;
	private Date pcPreparedDt;
	private Integer pcModifiedBy;
	private Date pcModifiedDt;
	private String pcDocRef;
	private Boolean pcDocFlag;
	private Boolean pcPrintFlag;
	private Date pcEffectiveDate;
	private Date pcExpiryDate;
	private Integer pcOldCode;

	
	public TMasPolicyCondition() {
	}

	public TMasPolicyCondition(TMasPolicyConditionId id) {
		this.id = id;
	}

	
	public Date getPcEffectiveDate(){
		return pcEffectiveDate;
	}

	public void setPcEffectiveDate( Date pcEffectiveDate ){
		this.pcEffectiveDate = pcEffectiveDate;
	}

	public Date getPcExpiryDate(){
		return pcExpiryDate;
	}

	public void setPcExpiryDate( Date pcExpiryDate ){
		this.pcExpiryDate = pcExpiryDate;
	}

	public Integer getPcOldCode(){
		return pcOldCode;
	}

	public void setPcOldCode( Integer pcOldCode ){
		this.pcOldCode = pcOldCode;
	}

	public TMasPolicyCondition(TMasPolicyConditionId id, String pcAText,
			String pcEText, Integer pcDefaultInd, Integer pcCtCode,
			Integer pcCstCode, Integer pcUserCode, Integer pcPhrCode,
			String pcAmount, Integer pcPreparedBy, Date pcPreparedDt,
			Integer pcModifiedBy, Date pcModifiedDt, String pcDocRef,
			Boolean pcDocFlag, Boolean pcPrintFlag) {
		this.id = id;
		this.pcAText = pcAText;
		this.pcEText = pcEText;
		this.pcDefaultInd = pcDefaultInd;
		this.pcCtCode = pcCtCode;
		this.pcCstCode = pcCstCode;
		this.pcUserCode = pcUserCode;
		this.pcPhrCode = pcPhrCode;
		this.pcAmount = pcAmount;
		this.pcPreparedBy = pcPreparedBy;
		this.pcPreparedDt = pcPreparedDt;
		this.pcModifiedBy = pcModifiedBy;
		this.pcModifiedDt = pcModifiedDt;
		this.pcDocRef = pcDocRef;
		this.pcDocFlag = pcDocFlag;
		this.pcPrintFlag = pcPrintFlag;
	}

	public TMasPolicyConditionId getId() {
		return this.id;
	}

	public void setId(TMasPolicyConditionId id) {
		this.id = id;
	}

	public String getPcAText() {
		return this.pcAText;
	}

	public void setPcAText(String pcAText) {
		this.pcAText = pcAText;
	}

	public String getPcEText() {
		return this.pcEText;
	}

	public void setPcEText(String pcEText) {
		this.pcEText = pcEText;
	}

	public Integer getPcDefaultInd() {
		return this.pcDefaultInd;
	}

	public void setPcDefaultInd(Integer pcDefaultInd) {
		this.pcDefaultInd = pcDefaultInd;
	}

	public Integer getPcCtCode() {
		return this.pcCtCode;
	}

	public void setPcCtCode(Integer pcCtCode) {
		this.pcCtCode = pcCtCode;
	}

	public Integer getPcCstCode() {
		return this.pcCstCode;
	}

	public void setPcCstCode(Integer pcCstCode) {
		this.pcCstCode = pcCstCode;
	}

	public Integer getPcUserCode() {
		return this.pcUserCode;
	}

	public void setPcUserCode(Integer pcUserCode) {
		this.pcUserCode = pcUserCode;
	}

	public Integer getPcPhrCode() {
		return this.pcPhrCode;
	}

	public void setPcPhrCode(Integer pcPhrCode) {
		this.pcPhrCode = pcPhrCode;
	}

	public String getPcAmount() {
		return this.pcAmount;
	}

	public void setPcAmount(String pcAmount) {
		this.pcAmount = pcAmount;
	}

	public Integer getPcPreparedBy() {
		return this.pcPreparedBy;
	}

	public void setPcPreparedBy(Integer pcPreparedBy) {
		this.pcPreparedBy = pcPreparedBy;
	}

	public Date getPcPreparedDt() {
		return this.pcPreparedDt;
	}

	public void setPcPreparedDt(Date pcPreparedDt) {
		this.pcPreparedDt = pcPreparedDt;
	}

	public Integer getPcModifiedBy() {
		return this.pcModifiedBy;
	}

	public void setPcModifiedBy(Integer pcModifiedBy) {
		this.pcModifiedBy = pcModifiedBy;
	}

	public Date getPcModifiedDt() {
		return this.pcModifiedDt;
	}

	public void setPcModifiedDt(Date pcModifiedDt) {
		this.pcModifiedDt = pcModifiedDt;
	}

	public String getPcDocRef() {
		return this.pcDocRef;
	}

	public void setPcDocRef(String pcDocRef) {
		this.pcDocRef = pcDocRef;
	}

	public Boolean getPcDocFlag() {
		return this.pcDocFlag;
	}

	public void setPcDocFlag(Boolean pcDocFlag) {
		this.pcDocFlag = pcDocFlag;
	}

	public Boolean getPcPrintFlag() {
		return this.pcPrintFlag;
	}

	public void setPcPrintFlag(Boolean pcPrintFlag) {
		this.pcPrintFlag = pcPrintFlag;
	}

}
