package com.rsaame.pas.dao.model;

// Generated Feb 1, 2012 11:52:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TMasRisk generated by hbm2java
 */
public class TMasRisk implements java.io.Serializable {

	private int rskCode;
	private String rskADesc;
	private String rskEDesc;
	private Integer rskUserCode;
	private Integer rskPreparedBy;
	private Date rskPreparedDt;
	private Integer rskModifiedBy;
	private Date rskModifiedDt;

	public TMasRisk() {
	}

	public TMasRisk(int rskCode) {
		this.rskCode = rskCode;
	}

	public TMasRisk(int rskCode, String rskADesc, String rskEDesc,
			Integer rskUserCode, Integer rskPreparedBy, Date rskPreparedDt,
			Integer rskModifiedBy, Date rskModifiedDt) {
		this.rskCode = rskCode;
		this.rskADesc = rskADesc;
		this.rskEDesc = rskEDesc;
		this.rskUserCode = rskUserCode;
		this.rskPreparedBy = rskPreparedBy;
		this.rskPreparedDt = rskPreparedDt;
		this.rskModifiedBy = rskModifiedBy;
		this.rskModifiedDt = rskModifiedDt;
	}

	public int getRskCode() {
		return this.rskCode;
	}

	public void setRskCode(int rskCode) {
		this.rskCode = rskCode;
	}

	public String getRskADesc() {
		return this.rskADesc;
	}

	public void setRskADesc(String rskADesc) {
		this.rskADesc = rskADesc;
	}

	public String getRskEDesc() {
		return this.rskEDesc;
	}

	public void setRskEDesc(String rskEDesc) {
		this.rskEDesc = rskEDesc;
	}

	public Integer getRskUserCode() {
		return this.rskUserCode;
	}

	public void setRskUserCode(Integer rskUserCode) {
		this.rskUserCode = rskUserCode;
	}

	public Integer getRskPreparedBy() {
		return this.rskPreparedBy;
	}

	public void setRskPreparedBy(Integer rskPreparedBy) {
		this.rskPreparedBy = rskPreparedBy;
	}

	public Date getRskPreparedDt() {
		return this.rskPreparedDt;
	}

	public void setRskPreparedDt(Date rskPreparedDt) {
		this.rskPreparedDt = rskPreparedDt;
	}

	public Integer getRskModifiedBy() {
		return this.rskModifiedBy;
	}

	public void setRskModifiedBy(Integer rskModifiedBy) {
		this.rskModifiedBy = rskModifiedBy;
	}

	public Date getRskModifiedDt() {
		return this.rskModifiedDt;
	}

	public void setRskModifiedDt(Date rskModifiedDt) {
		this.rskModifiedDt = rskModifiedDt;
	}

}
