package com.rsaame.pas.dao.model;

// Generated May 17, 2012 10:25:33 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TMasPolicyWarranty generated by hbm2java
 */
public class TMasPolicyWarranty implements java.io.Serializable {

	private TMasPolicyWarrantyId id;
	private String pwAText;
	private String pwEText;
	private Integer pwDefaultInd;
	private Integer pwCtCode;
	private Integer pwCstCode;
	private Integer pwUserCode;
	private Integer pwPhrCode;
	private String pwAmount;
	private Integer pwPreparedBy;
	private Date pwPreparedDt;
	private Integer pwModifiedBy;
	private Date pwModifiedDt;
	private String pwDocRef;
	private Boolean pwDocFlag;
	private Date pwEffectiveDate;
	private Date pwExpiryDate;
	private Integer pwOldCode;

	public TMasPolicyWarranty() {
	}

	public TMasPolicyWarranty(TMasPolicyWarrantyId id) {
		this.id = id;
	}

	
	public Date getPwEffectiveDate(){
		return pwEffectiveDate;
	}

	public void setPwEffectiveDate( Date pwEffectiveDate ){
		this.pwEffectiveDate = pwEffectiveDate;
	}

	public Date getPwExpiryDate(){
		return pwExpiryDate;
	}

	public void setPwExpiryDate( Date pwExpiryDate ){
		this.pwExpiryDate = pwExpiryDate;
	}

	public Integer getPwOldCode(){
		return pwOldCode;
	}

	public void setPwOldCode( Integer pwOldCode ){
		this.pwOldCode = pwOldCode;
	}

	public TMasPolicyWarranty(TMasPolicyWarrantyId id, String pwAText,
			String pwEText, Integer pwDefaultInd, Integer pwCtCode,
			Integer pwCstCode, Integer pwUserCode, Integer pwPhrCode,
			String pwAmount, Integer pwPreparedBy, Date pwPreparedDt,
			Integer pwModifiedBy, Date pwModifiedDt, String pwDocRef,
			Boolean pwDocFlag) {
		this.id = id;
		this.pwAText = pwAText;
		this.pwEText = pwEText;
		this.pwDefaultInd = pwDefaultInd;
		this.pwCtCode = pwCtCode;
		this.pwCstCode = pwCstCode;
		this.pwUserCode = pwUserCode;
		this.pwPhrCode = pwPhrCode;
		this.pwAmount = pwAmount;
		this.pwPreparedBy = pwPreparedBy;
		this.pwPreparedDt = pwPreparedDt;
		this.pwModifiedBy = pwModifiedBy;
		this.pwModifiedDt = pwModifiedDt;
		this.pwDocRef = pwDocRef;
		this.pwDocFlag = pwDocFlag;
	}

	public TMasPolicyWarrantyId getId() {
		return this.id;
	}

	public void setId(TMasPolicyWarrantyId id) {
		this.id = id;
	}

	public String getPwAText() {
		return this.pwAText;
	}

	public void setPwAText(String pwAText) {
		this.pwAText = pwAText;
	}

	public String getPwEText() {
		return this.pwEText;
	}

	public void setPwEText(String pwEText) {
		this.pwEText = pwEText;
	}

	public Integer getPwDefaultInd() {
		return this.pwDefaultInd;
	}

	public void setPwDefaultInd(Integer pwDefaultInd) {
		this.pwDefaultInd = pwDefaultInd;
	}

	public Integer getPwCtCode() {
		return this.pwCtCode;
	}

	public void setPwCtCode(Integer pwCtCode) {
		this.pwCtCode = pwCtCode;
	}

	public Integer getPwCstCode() {
		return this.pwCstCode;
	}

	public void setPwCstCode(Integer pwCstCode) {
		this.pwCstCode = pwCstCode;
	}

	public Integer getPwUserCode() {
		return this.pwUserCode;
	}

	public void setPwUserCode(Integer pwUserCode) {
		this.pwUserCode = pwUserCode;
	}

	public Integer getPwPhrCode() {
		return this.pwPhrCode;
	}

	public void setPwPhrCode(Integer pwPhrCode) {
		this.pwPhrCode = pwPhrCode;
	}

	public String getPwAmount() {
		return this.pwAmount;
	}

	public void setPwAmount(String pwAmount) {
		this.pwAmount = pwAmount;
	}

	public Integer getPwPreparedBy() {
		return this.pwPreparedBy;
	}

	public void setPwPreparedBy(Integer pwPreparedBy) {
		this.pwPreparedBy = pwPreparedBy;
	}

	public Date getPwPreparedDt() {
		return this.pwPreparedDt;
	}

	public void setPwPreparedDt(Date pwPreparedDt) {
		this.pwPreparedDt = pwPreparedDt;
	}

	public Integer getPwModifiedBy() {
		return this.pwModifiedBy;
	}

	public void setPwModifiedBy(Integer pwModifiedBy) {
		this.pwModifiedBy = pwModifiedBy;
	}

	public Date getPwModifiedDt() {
		return this.pwModifiedDt;
	}

	public void setPwModifiedDt(Date pwModifiedDt) {
		this.pwModifiedDt = pwModifiedDt;
	}

	public String getPwDocRef() {
		return this.pwDocRef;
	}

	public void setPwDocRef(String pwDocRef) {
		this.pwDocRef = pwDocRef;
	}

	public Boolean getPwDocFlag() {
		return this.pwDocFlag;
	}

	public void setPwDocFlag(Boolean pwDocFlag) {
		this.pwDocFlag = pwDocFlag;
	}

}
