package com.rsaame.pas.dao.model;

// Generated May 20, 2013 11:08:40 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TMasPromoDiscCoverId generated by hbm2java
 */
public class TMasPromoDiscCoverId implements java.io.Serializable {

	private String pdcProCode;
	private BigDecimal pdcSchemeCode;
	private BigDecimal pdcPerc;
	private BigDecimal pdcCovCode;
	private BigDecimal pdcCtCode;
	private Integer pdcPreparedBy;
	private Date pdcPreparedDate;
	private Integer pdcModifiedBy;
	private Date pdcModifiedDate;

	public TMasPromoDiscCoverId() {
	}

	public TMasPromoDiscCoverId(String pdcProCode, BigDecimal pdcSchemeCode,
			BigDecimal pdcPerc, BigDecimal pdcCovCode, BigDecimal pdcCtCode,
			Integer pdcPreparedBy, Date pdcPreparedDate, Integer pdcModifiedBy,
			Date pdcModifiedDate) {
		this.pdcProCode = pdcProCode;
		this.pdcSchemeCode = pdcSchemeCode;
		this.pdcPerc = pdcPerc;
		this.pdcCovCode = pdcCovCode;
		this.pdcCtCode = pdcCtCode;
		this.pdcPreparedBy = pdcPreparedBy;
		this.pdcPreparedDate = pdcPreparedDate;
		this.pdcModifiedBy = pdcModifiedBy;
		this.pdcModifiedDate = pdcModifiedDate;
	}

	public String getPdcProCode() {
		return this.pdcProCode;
	}

	public void setPdcProCode(String pdcProCode) {
		this.pdcProCode = pdcProCode;
	}

	public BigDecimal getPdcSchemeCode() {
		return this.pdcSchemeCode;
	}

	public void setPdcSchemeCode(BigDecimal pdcSchemeCode) {
		this.pdcSchemeCode = pdcSchemeCode;
	}

	public BigDecimal getPdcPerc() {
		return this.pdcPerc;
	}

	public void setPdcPerc(BigDecimal pdcPerc) {
		this.pdcPerc = pdcPerc;
	}

	public BigDecimal getPdcCovCode() {
		return this.pdcCovCode;
	}

	public void setPdcCovCode(BigDecimal pdcCovCode) {
		this.pdcCovCode = pdcCovCode;
	}

	public BigDecimal getPdcCtCode() {
		return this.pdcCtCode;
	}

	public void setPdcCtCode(BigDecimal pdcCtCode) {
		this.pdcCtCode = pdcCtCode;
	}

	public Integer getPdcPreparedBy() {
		return this.pdcPreparedBy;
	}

	public void setPdcPreparedBy(Integer pdcPreparedBy) {
		this.pdcPreparedBy = pdcPreparedBy;
	}

	public Date getPdcPreparedDate() {
		return this.pdcPreparedDate;
	}

	public void setPdcPreparedDate(Date pdcPreparedDate) {
		this.pdcPreparedDate = pdcPreparedDate;
	}

	public Integer getPdcModifiedBy() {
		return this.pdcModifiedBy;
	}

	public void setPdcModifiedBy(Integer pdcModifiedBy) {
		this.pdcModifiedBy = pdcModifiedBy;
	}

	public Date getPdcModifiedDate() {
		return this.pdcModifiedDate;
	}

	public void setPdcModifiedDate(Date pdcModifiedDate) {
		this.pdcModifiedDate = pdcModifiedDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMasPromoDiscCoverId))
			return false;
		TMasPromoDiscCoverId castOther = (TMasPromoDiscCoverId) other;

		return ((this.getPdcProCode() == castOther.getPdcProCode()) || (this
				.getPdcProCode() != null && castOther.getPdcProCode() != null && this
				.getPdcProCode().equals(castOther.getPdcProCode())))
				&& ((this.getPdcSchemeCode() == castOther.getPdcSchemeCode()) || (this
						.getPdcSchemeCode() != null
						&& castOther.getPdcSchemeCode() != null && this
						.getPdcSchemeCode()
						.equals(castOther.getPdcSchemeCode())))
				&& ((this.getPdcPerc() == castOther.getPdcPerc()) || (this
						.getPdcPerc() != null && castOther.getPdcPerc() != null && this
						.getPdcPerc().equals(castOther.getPdcPerc())))
				&& ((this.getPdcCovCode() == castOther.getPdcCovCode()) || (this
						.getPdcCovCode() != null
						&& castOther.getPdcCovCode() != null && this
						.getPdcCovCode().equals(castOther.getPdcCovCode())))
				&& ((this.getPdcCtCode() == castOther.getPdcCtCode()) || (this
						.getPdcCtCode() != null
						&& castOther.getPdcCtCode() != null && this
						.getPdcCtCode().equals(castOther.getPdcCtCode())))
				&& ((this.getPdcPreparedBy() == castOther.getPdcPreparedBy()) || (this
						.getPdcPreparedBy() != null
						&& castOther.getPdcPreparedBy() != null && this
						.getPdcPreparedBy()
						.equals(castOther.getPdcPreparedBy())))
				&& ((this.getPdcPreparedDate() == castOther
						.getPdcPreparedDate()) || (this.getPdcPreparedDate() != null
						&& castOther.getPdcPreparedDate() != null && this
						.getPdcPreparedDate().equals(
								castOther.getPdcPreparedDate())))
				&& ((this.getPdcModifiedBy() == castOther.getPdcModifiedBy()) || (this
						.getPdcModifiedBy() != null
						&& castOther.getPdcModifiedBy() != null && this
						.getPdcModifiedBy()
						.equals(castOther.getPdcModifiedBy())))
				&& ((this.getPdcModifiedDate() == castOther
						.getPdcModifiedDate()) || (this.getPdcModifiedDate() != null
						&& castOther.getPdcModifiedDate() != null && this
						.getPdcModifiedDate().equals(
								castOther.getPdcModifiedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPdcProCode() == null ? 0 : this.getPdcProCode()
						.hashCode());
		result = 37
				* result
				+ (getPdcSchemeCode() == null ? 0 : this.getPdcSchemeCode()
						.hashCode());
		result = 37 * result
				+ (getPdcPerc() == null ? 0 : this.getPdcPerc().hashCode());
		result = 37
				* result
				+ (getPdcCovCode() == null ? 0 : this.getPdcCovCode()
						.hashCode());
		result = 37 * result
				+ (getPdcCtCode() == null ? 0 : this.getPdcCtCode().hashCode());
		result = 37
				* result
				+ (getPdcPreparedBy() == null ? 0 : this.getPdcPreparedBy()
						.hashCode());
		result = 37
				* result
				+ (getPdcPreparedDate() == null ? 0 : this.getPdcPreparedDate()
						.hashCode());
		result = 37
				* result
				+ (getPdcModifiedBy() == null ? 0 : this.getPdcModifiedBy()
						.hashCode());
		result = 37
				* result
				+ (getPdcModifiedDate() == null ? 0 : this.getPdcModifiedDate()
						.hashCode());
		return result;
	}

}
