package com.rsaame.pas.dao.model;

// Generated Feb 3, 2012 8:32:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TMasCommisionType generated by hbm2java
 */
public class TMasCommisionType implements java.io.Serializable {

	private TMasCommisionTypeId id;
	private String comADesc;
	private String comEDesc;
	private BigDecimal comPerc;
	private Integer comPtCode;
	private Integer comPreparedBy;
	private Date comPreparedDt;
	private Integer comModifiedBy;
	private Date comModifiedDt;
	private Byte comInterType;
	private Integer comInterCode;
	private Short comType;
	private Date comEffDate;
	private Date comExpDate;
	private Integer comScheme;
	private Integer comDocument;
	private String comChannelName;

	public TMasCommisionType() {
	}

	public TMasCommisionType(TMasCommisionTypeId id, String comADesc,
			String comEDesc, BigDecimal comPerc) {
		this.id = id;
		this.comADesc = comADesc;
		this.comEDesc = comEDesc;
		this.comPerc = comPerc;
	}

	public TMasCommisionType(TMasCommisionTypeId id, String comADesc,
			String comEDesc, BigDecimal comPerc, Integer comPtCode,
			Integer comPreparedBy, Date comPreparedDt, Integer comModifiedBy,
			Date comModifiedDt, Byte comInterType, Integer comInterCode,
			Short comType, Date comEffDate, Date comExpDate, Integer comScheme,
			Integer comDocument, String comChannelName) {
		this.id = id;
		this.comADesc = comADesc;
		this.comEDesc = comEDesc;
		this.comPerc = comPerc;
		this.comPtCode = comPtCode;
		this.comPreparedBy = comPreparedBy;
		this.comPreparedDt = comPreparedDt;
		this.comModifiedBy = comModifiedBy;
		this.comModifiedDt = comModifiedDt;
		this.comInterType = comInterType;
		this.comInterCode = comInterCode;
		this.comType = comType;
		this.comEffDate = comEffDate;
		this.comExpDate = comExpDate;
		this.comScheme = comScheme;
		this.comDocument = comDocument;
		this.comChannelName = comChannelName;
	}

	public TMasCommisionTypeId getId() {
		return this.id;
	}

	public void setId(TMasCommisionTypeId id) {
		this.id = id;
	}

	public String getComADesc() {
		return this.comADesc;
	}

	public void setComADesc(String comADesc) {
		this.comADesc = comADesc;
	}

	public String getComEDesc() {
		return this.comEDesc;
	}

	public void setComEDesc(String comEDesc) {
		this.comEDesc = comEDesc;
	}

	public BigDecimal getComPerc() {
		return this.comPerc;
	}

	public void setComPerc(BigDecimal comPerc) {
		this.comPerc = comPerc;
	}

	public Integer getComPtCode() {
		return this.comPtCode;
	}

	public void setComPtCode(Integer comPtCode) {
		this.comPtCode = comPtCode;
	}

	public Integer getComPreparedBy() {
		return this.comPreparedBy;
	}

	public void setComPreparedBy(Integer comPreparedBy) {
		this.comPreparedBy = comPreparedBy;
	}

	public Date getComPreparedDt() {
		return this.comPreparedDt;
	}

	public void setComPreparedDt(Date comPreparedDt) {
		this.comPreparedDt = comPreparedDt;
	}

	public Integer getComModifiedBy() {
		return this.comModifiedBy;
	}

	public void setComModifiedBy(Integer comModifiedBy) {
		this.comModifiedBy = comModifiedBy;
	}

	public Date getComModifiedDt() {
		return this.comModifiedDt;
	}

	public void setComModifiedDt(Date comModifiedDt) {
		this.comModifiedDt = comModifiedDt;
	}

	public Byte getComInterType() {
		return this.comInterType;
	}

	public void setComInterType(Byte comInterType) {
		this.comInterType = comInterType;
	}

	public Integer getComInterCode() {
		return this.comInterCode;
	}

	public void setComInterCode(Integer comInterCode) {
		this.comInterCode = comInterCode;
	}

	public Short getComType() {
		return this.comType;
	}

	public void setComType(Short comType) {
		this.comType = comType;
	}

	public Date getComEffDate() {
		return this.comEffDate;
	}

	public void setComEffDate(Date comEffDate) {
		this.comEffDate = comEffDate;
	}

	public Date getComExpDate() {
		return this.comExpDate;
	}

	public void setComExpDate(Date comExpDate) {
		this.comExpDate = comExpDate;
	}

	public Integer getComScheme() {
		return this.comScheme;
	}

	public void setComScheme(Integer comScheme) {
		this.comScheme = comScheme;
	}

	public Integer getComDocument() {
		return this.comDocument;
	}

	public void setComDocument(Integer comDocument) {
		this.comDocument = comDocument;
	}

	public String getComChannelName() {
		return this.comChannelName;
	}

	public void setComChannelName(String comChannelName) {
		this.comChannelName = comChannelName;
	}

}
