package com.rsaame.pas.dao.model;

// Generated Feb 1, 2012 11:52:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TMasRiskCategory generated by hbm2java
 */
public class TMasRiskCategory implements java.io.Serializable {

	private TMasRiskCategoryId id;
	private String rcADesc;
	private String rcEDesc;
	private Integer rcUserCode;
	private Integer rcPreparedBy;
	private Date rcPreparedDt;
	private Integer rcModifiedBy;
	private Date rcModifiedDt;
	private Set TMasRiskSubCategories = new HashSet(0);

	public TMasRiskCategory() {
	}

	public TMasRiskCategory(TMasRiskCategoryId id) {
		this.id = id;
	}

	public TMasRiskCategory(TMasRiskCategoryId id, String rcADesc,
			String rcEDesc, Integer rcUserCode, Integer rcPreparedBy,
			Date rcPreparedDt, Integer rcModifiedBy, Date rcModifiedDt,
			Set TMasRiskSubCategories) {
		this.id = id;
		this.rcADesc = rcADesc;
		this.rcEDesc = rcEDesc;
		this.rcUserCode = rcUserCode;
		this.rcPreparedBy = rcPreparedBy;
		this.rcPreparedDt = rcPreparedDt;
		this.rcModifiedBy = rcModifiedBy;
		this.rcModifiedDt = rcModifiedDt;
		this.TMasRiskSubCategories = TMasRiskSubCategories;
	}

	public TMasRiskCategoryId getId() {
		return this.id;
	}

	public void setId(TMasRiskCategoryId id) {
		this.id = id;
	}

	public String getRcADesc() {
		return this.rcADesc;
	}

	public void setRcADesc(String rcADesc) {
		this.rcADesc = rcADesc;
	}

	public String getRcEDesc() {
		return this.rcEDesc;
	}

	public void setRcEDesc(String rcEDesc) {
		this.rcEDesc = rcEDesc;
	}

	public Integer getRcUserCode() {
		return this.rcUserCode;
	}

	public void setRcUserCode(Integer rcUserCode) {
		this.rcUserCode = rcUserCode;
	}

	public Integer getRcPreparedBy() {
		return this.rcPreparedBy;
	}

	public void setRcPreparedBy(Integer rcPreparedBy) {
		this.rcPreparedBy = rcPreparedBy;
	}

	public Date getRcPreparedDt() {
		return this.rcPreparedDt;
	}

	public void setRcPreparedDt(Date rcPreparedDt) {
		this.rcPreparedDt = rcPreparedDt;
	}

	public Integer getRcModifiedBy() {
		return this.rcModifiedBy;
	}

	public void setRcModifiedBy(Integer rcModifiedBy) {
		this.rcModifiedBy = rcModifiedBy;
	}

	public Date getRcModifiedDt() {
		return this.rcModifiedDt;
	}

	public void setRcModifiedDt(Date rcModifiedDt) {
		this.rcModifiedDt = rcModifiedDt;
	}

	public Set getTMasRiskSubCategories() {
		return this.TMasRiskSubCategories;
	}

	public void setTMasRiskSubCategories(Set TMasRiskSubCategories) {
		this.TMasRiskSubCategories = TMasRiskSubCategories;
	}

}
