package com.rsaame.pas.dao.model;

import java.util.Date;

// Generated Mar 14, 2012 11:33:03 AM by Hibernate Tools 3.4.0.CR1

/**
 * TTrnTempPasReferral generated by hbm2java
 */
public class TTrnPasReferralDetails implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private TTrnPasReferralDetailsId id;
	private String refText;
	private String refStatus;
	private Integer refApprovedBy;
	private Integer refCreatedBy;
	private Date refCreatedDate;
	private Date refModifiedDate;

	/**
	 * @return the id
	 */
	public TTrnPasReferralDetailsId getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(TTrnPasReferralDetailsId id) {
		this.id = id;
	}

	/**
	 * @return the refText
	 */
	public String getRefText() {
		return refText;
	}

	/**
	 * @param refText
	 *            the refText to set
	 */
	public void setRefText(String refText) {
		this.refText = refText;
	}
	
	public String getRefStatus(){
		return refStatus;
	}

	public void setRefStatus( String refStatus ){
		this.refStatus = refStatus;
	}

	/**
	 * @return the refApprovedBy
	 */
	public Integer getRefApprovedBy(){
		return refApprovedBy;
	}

	/**
	 * @param refApprovedBy the refApprovedBy to set
	 */
	public void setRefApprovedBy( Integer refApprovedBy ){
		this.refApprovedBy = refApprovedBy;
	}

	/**
	 * @return the refCreatedBy
	 */
	public Integer getRefCreatedBy(){
		return refCreatedBy;
	}

	/**
	 * @param refCreatedBy the refCreatedBy to set
	 */
	public void setRefCreatedBy( Integer refCreatedBy ){
		this.refCreatedBy = refCreatedBy;
	}

	/**
	 * @return the refCreateDate
	 */
	public Date getRefCreatedDate(){
		return refCreatedDate;
	}

	/**
	 * @param refCreateDate the refCreateDate to set
	 */
	public void setRefCreatedDate( Date refCreatedDate ){
		this.refCreatedDate = refCreatedDate;
	}

	/**
	 * @return the refModifiedDate
	 */
	public Date getRefModifiedDate(){
		return refModifiedDate;
	}

	/**
	 * @param refModifiedDate the refModifiedDate to set
	 */
	public void setRefModifiedDate( Date refModifiedDate ){
		this.refModifiedDate = refModifiedDate;
	}
	
	

}
