package com.rsaame.pas.dao.model;

import java.util.Date;

// Generated May 17, 2012 9:17:00 AM by Hibernate Tools 3.4.0.CR1

/**
 * TTrnPolicyWarrantyQuo generated by hbm2java
 */
public class TTrnPolicyWarrantyQuo implements java.io.Serializable {

	private TTrnPolicyWarrantyQuoId id;
	private Integer tpwCovCode;
	private Integer tpwCtCode;
	private Integer tpwCstCode;
	private Date tpwValidityStartDate;
	private Date tpwValidityEndDate;
	private Byte tpwStatus;
	private Integer tpwPreparedBy;
	private Date tpwPreparedDt;
	private Integer tpwModifiedBy;
	private Date tpwModifiedDt;
	private String tpwAmount;
	private Boolean tpwPrintFlag;

	public TTrnPolicyWarrantyQuo() {
	}

	public TTrnPolicyWarrantyQuo(TTrnPolicyWarrantyQuoId id,Integer tpwCovCode, Integer tpwCtCode, Integer tpwCstCode,
			Date tpwValidityStartDate, Date tpwValidityEndDate, Byte tpwStatus, Integer tpwPreparedBy, Date tpwPreparedDt,
			Integer tpwModifiedBy, Date tpwModifiedDt, String tpwAmount,
			Boolean tpwPrintFlag) {
		this.id = id;
		this.tpwCovCode = tpwCovCode;
		this.tpwCtCode = tpwCtCode;
		this.tpwCstCode = tpwCstCode;
		this.tpwValidityStartDate = tpwValidityStartDate;
		this.tpwValidityEndDate = tpwValidityEndDate;
		this.tpwStatus = tpwStatus;
		this.tpwPreparedBy = tpwPreparedBy;
		this.tpwPreparedDt = tpwPreparedDt;
		this.tpwModifiedBy = tpwModifiedBy;
		this.tpwModifiedDt = tpwModifiedDt;
		this.tpwAmount = tpwAmount;
		this.tpwPrintFlag = tpwPrintFlag;
	}

	public TTrnPolicyWarrantyQuoId getId() {
		return this.id;
	}

	public void setId(TTrnPolicyWarrantyQuoId id) {
		this.id = id;
	}
	
	public Integer getTpwCovCode() {
		return this.tpwCovCode;
	}

	public void setTpwCovCode(Integer tpwCovCode) {
		this.tpwCovCode = tpwCovCode;
	}

	public Integer getTpwCtCode() {
		return this.tpwCtCode;
	}

	public void setTpwCtCode(Integer tpwCtCode) {
		this.tpwCtCode = tpwCtCode;
	}

	public Integer getTpwCstCode() {
		return this.tpwCstCode;
	}

	public void setTpwCstCode(Integer tpwCstCode) {
		this.tpwCstCode = tpwCstCode;
	}

	public Date getTpwValidityStartDate() {
		return this.tpwValidityStartDate;
	}

	public void setTpwValidityStartDate(Date tpwValidityStartDate) {
		this.tpwValidityStartDate = tpwValidityStartDate;
	}

	public Date getTpwValidityEndDate() {
		return this.tpwValidityEndDate;
	}

	public void setTpwValidityEndDate(Date tpwValidityEndDate) {
		this.tpwValidityEndDate = tpwValidityEndDate;
	}

	public Byte getTpwStatus() {
		return this.tpwStatus;
	}

	public void setTpwStatus(Byte tpwStatus) {
		this.tpwStatus = tpwStatus;
	}

	public Integer getTpwPreparedBy() {
		return this.tpwPreparedBy;
	}

	public void setTpwPreparedBy(Integer tpwPreparedBy) {
		this.tpwPreparedBy = tpwPreparedBy;
	}

	public Date getTpwPreparedDt() {
		return this.tpwPreparedDt;
	}

	public void setTpwPreparedDt(Date tpwPreparedDt) {
		this.tpwPreparedDt = tpwPreparedDt;
	}

	public Integer getTpwModifiedBy() {
		return this.tpwModifiedBy;
	}

	public void setTpwModifiedBy(Integer tpwModifiedBy) {
		this.tpwModifiedBy = tpwModifiedBy;
	}

	public Date getTpwModifiedDt() {
		return this.tpwModifiedDt;
	}

	public void setTpwModifiedDt(Date tpwModifiedDt) {
		this.tpwModifiedDt = tpwModifiedDt;
	}

	public String getTpwAmount() {
		return this.tpwAmount;
	}

	public void setTpwAmount(String tpwAmount) {
		this.tpwAmount = tpwAmount;
	}

	public Boolean getTpwPrintFlag() {
		return this.tpwPrintFlag;
	}

	public void setTpwPrintFlag(Boolean tpwPrintFlag) {
		this.tpwPrintFlag = tpwPrintFlag;
	}
	



	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		// Commented to fix sonar issue on 27-10-2017
		//if (!(other instanceof TTrnPolicyWarrantyQuoId))
		//Added class name TTrnPolicyWarrantyQuo to fix sonar violation 0n 27-10-2017
		if (!(other instanceof TTrnPolicyWarrantyQuo))
		
			return false;
		TTrnPolicyWarrantyQuo castOther = (TTrnPolicyWarrantyQuo) other;

		return ((this.getTpwCovCode().equals( castOther.getTpwCovCode())) || (this
						.getTpwCovCode() != null
						&& castOther.getTpwCovCode() != null && this
						.getTpwCovCode().equals(castOther.getTpwCovCode())))
				&& ((this.getTpwCtCode() .equals(castOther.getTpwCtCode())) || (this
						.getTpwCtCode() != null
						&& castOther.getTpwCtCode() != null && this
						.getTpwCtCode().equals(castOther.getTpwCtCode())))
				&& ((this.getTpwCstCode().equals(castOther.getTpwCstCode())) || (this
						.getTpwCstCode() != null
						&& castOther.getTpwCstCode() != null && this
						.getTpwCstCode().equals(castOther.getTpwCstCode())))
				&& ((this.getTpwValidityStartDate() == castOther
						.getTpwValidityStartDate()) || (this
						.getTpwValidityStartDate() != null
						&& castOther.getTpwValidityStartDate() != null && this
						.getTpwValidityStartDate().equals(
								castOther.getTpwValidityStartDate())))
				&& ((this.getTpwValidityEndDate() == castOther
						.getTpwValidityEndDate()) || (this
						.getTpwValidityEndDate() != null
						&& castOther.getTpwValidityEndDate() != null && this
						.getTpwValidityEndDate().equals(
								castOther.getTpwValidityEndDate())))
				&& ((this.getTpwStatus() == castOther.getTpwStatus()) || (this
						.getTpwStatus() != null
						&& castOther.getTpwStatus() != null && this
						.getTpwStatus().equals(castOther.getTpwStatus())))
				&& ((this.getTpwPreparedBy() .equals(castOther.getTpwPreparedBy())) || (this
						.getTpwPreparedBy() != null
						&& castOther.getTpwPreparedBy() != null && this
						.getTpwPreparedBy()
						.equals(castOther.getTpwPreparedBy())))
				&& ((this.getTpwPreparedDt().equals(castOther.getTpwPreparedDt())) || (this
						.getTpwPreparedDt() != null
						&& castOther.getTpwPreparedDt() != null && this
						.getTpwPreparedDt()
						.equals(castOther.getTpwPreparedDt())))
				&& ((this.getTpwModifiedBy().equals(castOther.getTpwModifiedBy())) || (this
						.getTpwModifiedBy() != null
						&& castOther.getTpwModifiedBy() != null && this
						.getTpwModifiedBy()
						.equals(castOther.getTpwModifiedBy())))
				&& ((this.getTpwModifiedDt().equals(castOther.getTpwModifiedDt())) || (this
						.getTpwModifiedDt() != null
						&& castOther.getTpwModifiedDt() != null && this
						.getTpwModifiedDt()
						.equals(castOther.getTpwModifiedDt())))
				&& ((this.getTpwAmount() .equals(castOther.getTpwAmount())) || (this
						.getTpwAmount() != null
						&& castOther.getTpwAmount() != null && this
						.getTpwAmount().equals(castOther.getTpwAmount())))
				&& ((this.getTpwPrintFlag().equals(castOther.getTpwPrintFlag())) || (this
						.getTpwPrintFlag() != null
						&& castOther.getTpwPrintFlag() != null && this
						.getTpwPrintFlag().equals(castOther.getTpwPrintFlag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTpwCovCode() == null ? 0 : this.getTpwCovCode()
						.hashCode());
		result = 37 * result
				+ (getTpwCtCode() == null ? 0 : this.getTpwCtCode().hashCode());
		result = 37
				* result
				+ (getTpwCstCode() == null ? 0 : this.getTpwCstCode()
						.hashCode());
		result = 37
				* result
				+ (getTpwValidityStartDate() == null ? 0 : this
						.getTpwValidityStartDate().hashCode());
		result = 37
				* result
				+ (getTpwValidityEndDate() == null ? 0 : this
						.getTpwValidityEndDate().hashCode());
		result = 37 * result
				+ (getTpwStatus() == null ? 0 : this.getTpwStatus().hashCode());
		result = 37
				* result
				+ (getTpwPreparedBy() == null ? 0 : this.getTpwPreparedBy()
						.hashCode());
		result = 37
				* result
				+ (getTpwPreparedDt() == null ? 0 : this.getTpwPreparedDt()
						.hashCode());
		result = 37
				* result
				+ (getTpwModifiedBy() == null ? 0 : this.getTpwModifiedBy()
						.hashCode());
		result = 37
				* result
				+ (getTpwModifiedDt() == null ? 0 : this.getTpwModifiedDt()
						.hashCode());
		result = 37 * result
				+ (getTpwAmount() == null ? 0 : this.getTpwAmount().hashCode());
		result = 37
				* result
				+ (getTpwPrintFlag() == null ? 0 : this.getTpwPrintFlag()
						.hashCode());
		return result;
	}

	
}
