package com.rsaame.pas.dao.model;

// Generated Mar 3, 2012 11:52:17 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.mindtree.ruc.cmn.utils.Utils;
import com.rsaame.pas.cmn.pojo.POJO;
import com.rsaame.pas.cmn.pojo.POJOId;

/**
 * TTrnGaccBuildingQuo generated by hbm2java
 */
public class TTrnGaccBuildingQuo extends POJO implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private TTrnGaccBuildingQuoId id;
	private Long gbdPolicyId;
	private Long gbdRskCode;
	private Long gbdConstructionCode;
	private Date gbdStartDate;
	private Date gbdEndDate;
	private Long gbdFlatNo;
	private String gbdNo;
	private String gbdEName;
	private String gbdAName;
	private Long gbdWayNo;
	private String gbdEStreetName;
	private String gbdAStreetName;
	private Long gbdBlockNo;
	private Long gbdDirCode;
	private Long gbdMunCode;
	private String gbdAAddress1;
	private String gbdEAddress1;
	private String gbdZip;
	private BigDecimal gbdSumInsured;
	private Byte gbdStatus;
	private Date gbdValidityExpiryDate;
	private Long gbdBusinessCode;
	private Long gbdEndtId;
	private Integer gbdRiRskCode;
	private Boolean gbdPremiseType;
	private Integer gbdCbCode;
	private Date gbdRetroactiveDate;
	private Integer gbdPreparedBy;
	private Date gbdPreparedDt;
	private Integer gbdModifiedBy;
	private Date gbdModifiedDt;
	private Long gbdBldId;

	public TTrnGaccBuildingQuo() {
	}

	public TTrnGaccBuildingQuo(TTrnGaccBuildingQuoId id,
			Date gbdValidityExpiryDate) {
		this.id = id;
		this.gbdValidityExpiryDate = gbdValidityExpiryDate;
	}

	public TTrnGaccBuildingQuo(TTrnGaccBuildingQuoId id, Long gbdPolicyId,
			Long gbdRskCode, Long gbdConstructionCode, Date gbdStartDate,
			Date gbdEndDate, Long gbdFlatNo, String gbdNo, String gbdEName,
			String gbdAName, Long gbdWayNo, String gbdEStreetName,
			String gbdAStreetName, Long gbdBlockNo, Long gbdDirCode,
			Long gbdMunCode, String gbdAAddress1, String gbdEAddress1,
			String gbdZip, BigDecimal gbdSumInsured, Byte gbdStatus,
			Date gbdValidityExpiryDate, Long gbdBusinessCode, Long gbdEndtId,
			Integer gbdRiRskCode, Boolean gbdPremiseType, Integer gbdCbCode,
			Date gbdRetroactiveDate, Integer gbdPreparedBy, Date gbdPreparedDt,
			Integer gbdModifiedBy, Date gbdModifiedDt, Long gbdBldId) {
		this.id = id;
		this.gbdPolicyId = gbdPolicyId;
		this.gbdRskCode = gbdRskCode;
		this.gbdConstructionCode = gbdConstructionCode;
		this.gbdStartDate = gbdStartDate;
		this.gbdEndDate = gbdEndDate;
		this.gbdFlatNo = gbdFlatNo;
		this.gbdNo = gbdNo;
		this.gbdEName = gbdEName;
		this.gbdAName = gbdAName;
		this.gbdWayNo = gbdWayNo;
		this.gbdEStreetName = gbdEStreetName;
		this.gbdAStreetName = gbdAStreetName;
		this.gbdBlockNo = gbdBlockNo;
		this.gbdDirCode = gbdDirCode;
		this.gbdMunCode = gbdMunCode;
		this.gbdAAddress1 = gbdAAddress1;
		this.gbdEAddress1 = gbdEAddress1;
		this.gbdZip = gbdZip;
		this.gbdSumInsured = gbdSumInsured;
		this.gbdStatus = gbdStatus;
		this.gbdValidityExpiryDate = gbdValidityExpiryDate;
		this.gbdBusinessCode = gbdBusinessCode;
		this.gbdEndtId = gbdEndtId;
		this.gbdRiRskCode = gbdRiRskCode;
		this.gbdPremiseType = gbdPremiseType;
		this.gbdCbCode = gbdCbCode;
		this.gbdRetroactiveDate = gbdRetroactiveDate;
		this.gbdPreparedBy = gbdPreparedBy;
		this.gbdPreparedDt = gbdPreparedDt;
		this.gbdModifiedBy = gbdModifiedBy;
		this.gbdModifiedDt = gbdModifiedDt;
		this.gbdBldId = gbdBldId;
	}

	public TTrnGaccBuildingQuoId getId() {
		return this.id;
	}

	public void setId(TTrnGaccBuildingQuoId id) {
		this.id = id;
	}

	public Long getGbdPolicyId() {
		return this.gbdPolicyId;
	}

	public void setGbdPolicyId(Long gbdPolicyId) {
		this.gbdPolicyId = gbdPolicyId;
	}

	public Long getGbdRskCode() {
		return this.gbdRskCode;
	}

	public void setGbdRskCode(Long gbdRskCode) {
		this.gbdRskCode = gbdRskCode;
	}

	public Long getGbdConstructionCode() {
		return this.gbdConstructionCode;
	}

	public void setGbdConstructionCode(Long gbdConstructionCode) {
		this.gbdConstructionCode = gbdConstructionCode;
	}

	public Date getGbdStartDate() {
		return this.gbdStartDate;
	}

	public void setGbdStartDate(Date gbdStartDate) {
		this.gbdStartDate = gbdStartDate;
	}

	public Date getGbdEndDate() {
		return this.gbdEndDate;
	}

	public void setGbdEndDate(Date gbdEndDate) {
		this.gbdEndDate = gbdEndDate;
	}

	public Long getGbdFlatNo() {
		return this.gbdFlatNo;
	}

	public void setGbdFlatNo(Long gbdFlatNo) {
		this.gbdFlatNo = gbdFlatNo;
	}

	public String getGbdNo() {
		return this.gbdNo;
	}

	public void setGbdNo(String gbdNo) {
		this.gbdNo = gbdNo;
	}

	public String getGbdEName() {
		return this.gbdEName;
	}

	public void setGbdEName(String gbdEName) {
		this.gbdEName = gbdEName;
	}

	public String getGbdAName() {
		return this.gbdAName;
	}

	public void setGbdAName(String gbdAName) {
		this.gbdAName = gbdAName;
	}

	public Long getGbdWayNo() {
		return this.gbdWayNo;
	}

	public void setGbdWayNo(Long gbdWayNo) {
		this.gbdWayNo = gbdWayNo;
	}

	public String getGbdEStreetName() {
		return this.gbdEStreetName;
	}

	public void setGbdEStreetName(String gbdEStreetName) {
		this.gbdEStreetName = gbdEStreetName;
	}

	public String getGbdAStreetName() {
		return this.gbdAStreetName;
	}

	public void setGbdAStreetName(String gbdAStreetName) {
		this.gbdAStreetName = gbdAStreetName;
	}

	public Long getGbdBlockNo() {
		return this.gbdBlockNo;
	}

	public void setGbdBlockNo(Long gbdBlockNo) {
		this.gbdBlockNo = gbdBlockNo;
	}

	public Long getGbdDirCode() {
		return this.gbdDirCode;
	}

	public void setGbdDirCode(Long gbdDirCode) {
		this.gbdDirCode = gbdDirCode;
	}

	public Long getGbdMunCode() {
		return this.gbdMunCode;
	}

	public void setGbdMunCode(Long gbdMunCode) {
		this.gbdMunCode = gbdMunCode;
	}

	public String getGbdAAddress1() {
		return this.gbdAAddress1;
	}

	public void setGbdAAddress1(String gbdAAddress1) {
		this.gbdAAddress1 = gbdAAddress1;
	}

	public String getGbdEAddress1() {
		return this.gbdEAddress1;
	}

	public void setGbdEAddress1(String gbdEAddress1) {
		this.gbdEAddress1 = gbdEAddress1;
	}

	public String getGbdZip() {
		return this.gbdZip;
	}

	public void setGbdZip(String gbdZip) {
		this.gbdZip = gbdZip;
	}

	public BigDecimal getGbdSumInsured() {
		return this.gbdSumInsured;
	}

	public void setGbdSumInsured(BigDecimal gbdSumInsured) {
		this.gbdSumInsured = gbdSumInsured;
	}

	public Byte getGbdStatus() {
		return this.gbdStatus;
	}

	public void setGbdStatus(Byte gbdStatus) {
		this.gbdStatus = gbdStatus;
	}

	public Date getGbdValidityExpiryDate() {
		return this.gbdValidityExpiryDate;
	}

	public void setGbdValidityExpiryDate(Date gbdValidityExpiryDate) {
		this.gbdValidityExpiryDate = gbdValidityExpiryDate;
	}

	public Long getGbdBusinessCode() {
		return this.gbdBusinessCode;
	}

	public void setGbdBusinessCode(Long gbdBusinessCode) {
		this.gbdBusinessCode = gbdBusinessCode;
	}

	public Long getGbdEndtId() {
		return this.gbdEndtId;
	}

	public void setGbdEndtId(Long gbdEndtId) {
		this.gbdEndtId = gbdEndtId;
	}

	public Integer getGbdRiRskCode() {
		return this.gbdRiRskCode;
	}

	public void setGbdRiRskCode(Integer gbdRiRskCode) {
		this.gbdRiRskCode = gbdRiRskCode;
	}

	public Boolean getGbdPremiseType() {
		return this.gbdPremiseType;
	}

	public void setGbdPremiseType(Boolean gbdPremiseType) {
		this.gbdPremiseType = gbdPremiseType;
	}

	public Integer getGbdCbCode() {
		return this.gbdCbCode;
	}

	public void setGbdCbCode(Integer gbdCbCode) {
		this.gbdCbCode = gbdCbCode;
	}

	public Date getGbdRetroactiveDate() {
		return this.gbdRetroactiveDate;
	}

	public void setGbdRetroactiveDate(Date gbdRetroactiveDate) {
		this.gbdRetroactiveDate = gbdRetroactiveDate;
	}

	public Integer getGbdPreparedBy() {
		return this.gbdPreparedBy;
	}

	public void setGbdPreparedBy(Integer gbdPreparedBy) {
		this.gbdPreparedBy = gbdPreparedBy;
	}

	public Date getGbdPreparedDt() {
		return this.gbdPreparedDt;
	}

	public void setGbdPreparedDt(Date gbdPreparedDt) {
		this.gbdPreparedDt = gbdPreparedDt;
	}

	public Integer getGbdModifiedBy() {
		return this.gbdModifiedBy;
	}

	public void setGbdModifiedBy(Integer gbdModifiedBy) {
		this.gbdModifiedBy = gbdModifiedBy;
	}

	public Date getGbdModifiedDt() {
		return this.gbdModifiedDt;
	}

	public void setGbdModifiedDt(Date gbdModifiedDt) {
		this.gbdModifiedDt = gbdModifiedDt;
	}

	public Long getGbdBldId() {
		return this.gbdBldId;
	}

	public void setGbdBldId(Long gbdBldId) {
		this.gbdBldId = gbdBldId;
	}

	@Override
	public int getStatus(){
		return getGbdStatus();
	}
	
	@Override
	public void setEndtId( Long endtId ){
		setGbdEndtId( endtId );
	}
	
	@Override
	public POJOId getPOJOId(){
		return this.getId();
	}
	
	@Override
	public void setPOJOId( POJOId id ){
		setId( (TTrnGaccBuildingQuoId) id );
	}
	
	@Override
	public void setStatus( Integer status ){
		setGbdStatus( status.byteValue() );
	}
	
	@Override
	public void setValidityExpiryDate( Date ved ){
		setGbdValidityExpiryDate( ved );
	}
	
	@Override
	public void setValidityStartDate( Date vsd ){
		if( !Utils.isEmpty( getId() ) ) getId().setGbdValidityStartDate( vsd );
	}
	
	@Override
	public void setPreparedDate( Date preparedDate ){
		setGbdPreparedDt( preparedDate );
	}
	
	@Override
	public Date getPreparedDate(){
		return getGbdPreparedDt();
	}
}
