package com.rsaame.pas.dao.model;

// Generated Apr 25, 2012 5:30:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * TTrnPolicySectionsQuoId generated by hbm2java
 */
public class TTrnPolicySectionsQuoId implements java.io.Serializable {

	private long tpsLinkingId;
	private long tpsEndtNo;
	private short tpsSecId;

	public TTrnPolicySectionsQuoId() {
	}

	public TTrnPolicySectionsQuoId(long tpsLinkingId, long tpsEndtNo,
			short tpsSecId) {
		this.tpsLinkingId = tpsLinkingId;
		this.tpsEndtNo = tpsEndtNo;
		this.tpsSecId = tpsSecId;
	}

	public long getTpsLinkingId() {
		return this.tpsLinkingId;
	}

	public void setTpsLinkingId(long tpsLinkingId) {
		this.tpsLinkingId = tpsLinkingId;
	}

	public long getTpsEndtNo() {
		return this.tpsEndtNo;
	}

	public void setTpsEndtNo(long tpsEndtNo) {
		this.tpsEndtNo = tpsEndtNo;
	}

	public short getTpsSecId() {
		return this.tpsSecId;
	}

	public void setTpsSecId(short tpsSecId) {
		this.tpsSecId = tpsSecId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTrnPolicySectionsQuoId))
			return false;
		TTrnPolicySectionsQuoId castOther = (TTrnPolicySectionsQuoId) other;

		return (this.getTpsLinkingId() == castOther.getTpsLinkingId())
				&& (this.getTpsEndtNo() == castOther.getTpsEndtNo())
				&& (this.getTpsSecId() == castOther.getTpsSecId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTpsLinkingId();
		result = 37 * result + (int) this.getTpsEndtNo();
		result = 37 * result + this.getTpsSecId();
		return result;
	}

}
