package com.rsaame.pas.dao.model;

// Generated May 26, 2014 2:07:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TTrnMakeClaim generated by hbm2java
 */
public class TTrnMakeClaim implements java.io.Serializable {

	private static final long serialVersionUID = 9009466590989634052L;
	private long macClaimId;
	private String macInsuredName;
	private BigDecimal macContactNo;
	private String macEmailId;
/*	private String macTPName;*/
	private String macAccidentType;
	/*private String macTPInvolved;*/
	private String macMRTAForm;
	private String macClaimForm;
	private BigDecimal macMakeCode;
	private BigDecimal macModelCode;
	private String macVehregNo;
	private Date macAccidentDate;
	private String macLossDesc;
	private String macPoliceReport;
	private String macRegcardCopy;
	private String macDriverName;
	private String macDriverLicenseNo;
	/*private String macVehicleMake;
	private String macMakeAndModel;*/
	private String macDriverLicense;
	private String macRepairLoc;
	private String macClaimRemarks;
	private String macPolicyNo;
	private Date macPreparedDate;

	public TTrnMakeClaim() {
	}

	public TTrnMakeClaim(long macClaimId, BigDecimal macPolicyNo) {
		this.macClaimId = macClaimId;
	}

	public TTrnMakeClaim(long macClaimId, String macInsuredName,
			BigDecimal macContactNo, String macEmailId, BigDecimal macMakeCode,
			BigDecimal macModelCode, String macVehregNo,
			Date macAccidentDate, String macLossDesc, String macPoliceReport,
			String macRegcardCopy, String macDriverLicense,
			String macRepairLoc, String macClaimRemarks,
			String macPolicyNo, Date macPreparedDate) {
		this.macClaimId = macClaimId;
		this.macInsuredName = macInsuredName;
		this.macContactNo = macContactNo;
		this.macEmailId = macEmailId;
		this.macMakeCode = macMakeCode;
		this.macModelCode = macModelCode;
		this.macVehregNo = macVehregNo;
		this.macAccidentDate = macAccidentDate;
		this.macLossDesc = macLossDesc;
		this.macPoliceReport = macPoliceReport;
		this.macRegcardCopy = macRegcardCopy;
		this.macDriverLicense = macDriverLicense;
		this.macRepairLoc = macRepairLoc;
		this.macClaimRemarks = macClaimRemarks;
		this.macPolicyNo = macPolicyNo;
		this.macPreparedDate = macPreparedDate;
	}

	public long getMacClaimId() {
		return this.macClaimId;
	}

	public void setMacClaimId(long macClaimId) {
		this.macClaimId = macClaimId;
	}

	public String getMacInsuredName() {
		return this.macInsuredName;
	}

	public void setMacInsuredName(String macInsuredName) {
		this.macInsuredName = macInsuredName;
	}

	public BigDecimal getMacContactNo() {
		return this.macContactNo;
	}

	public void setMacContactNo(BigDecimal macContactNo) {
		this.macContactNo = macContactNo;
	}

	public String getMacEmailId() {
		return this.macEmailId;
	}

	public void setMacEmailId(String macEmailId) {
		this.macEmailId = macEmailId;
	}

	/*public String getMacTPName() {
		return macTPName;
	}

	public void setMacTPName(String macTPName) {
		this.macTPName = macTPName;
	}*/
	
	public String getMacAccidentType() {
		return macAccidentType;
	}

	public void setMacAccidentType(String macAccidentType) {
		this.macAccidentType = macAccidentType;
	}

	/*public String getMacTPInvolved() {
		return macTPInvolved;
	}

	public void setMacTPInvolved(String macTPInvolved) {
		this.macTPInvolved = macTPInvolved;
	}
*/
	public String getMacMRTAForm() {
		return macMRTAForm;
	}

	public void setMacMRTAForm(String macMRTAForm) {
		this.macMRTAForm = macMRTAForm;
	}

	public String getMacClaimForm() {
		return macClaimForm;
	}

	public void setMacClaimForm(String macClaimForm) {
		this.macClaimForm = macClaimForm;
	}

	public String getMacDriverName() {
		return macDriverName;
	}

	public void setMacDriverName(String macDriverName) {
		this.macDriverName = macDriverName;
	}

	public String getMacDriverLicenseNo() {
		return macDriverLicenseNo;
	}

	public void setMacDriverLicenseNo(String macDriverLicenseNo) {
		this.macDriverLicenseNo = macDriverLicenseNo;
	}

/*	public String getMacVehicleMake() {
		return macVehicleMake;
	}

	public void setMacVehicleMake(String macVehicleMake) {
		this.macVehicleMake = macVehicleMake;
	}

	public String getMacMakeAndModel() {
		return macMakeAndModel;
	}

	public void setMacMakeAndModel(String macMakeAndModel) {
		this.macMakeAndModel = macMakeAndModel;
	}
*/
	public BigDecimal getMacMakeCode() {
		return this.macMakeCode;
	}

	public void setMacMakeCode(BigDecimal macMakeCode) {
		this.macMakeCode = macMakeCode;
	}

	public BigDecimal getMacModelCode() {
		return this.macModelCode;
	}

	public void setMacModelCode(BigDecimal macModelCode) {
		this.macModelCode = macModelCode;
	}

	public String getMacVehregNo() {
		return this.macVehregNo;
	}

	public void setMacVehregNo(String macVehregNo) {
		this.macVehregNo = macVehregNo;
	}

	public Date getMacAccidentDate() {
		return this.macAccidentDate;
	}

	public void setMacAccidentDate(Date macAccidentDate) {
		this.macAccidentDate = macAccidentDate;
	}

	public String getMacLossDesc() {
		return this.macLossDesc;
	}

	public void setMacLossDesc(String macLossDesc) {
		this.macLossDesc = macLossDesc;
	}

	public String getMacPoliceReport() {
		return this.macPoliceReport;
	}

	public void setMacPoliceReport(String macPoliceReport) {
		this.macPoliceReport = macPoliceReport;
	}

	public String getMacRegcardCopy() {
		return this.macRegcardCopy;
	}

	public void setMacRegcardCopy(String macRegcardCopy) {
		this.macRegcardCopy = macRegcardCopy;
	}

	public String getMacDriverLicense() {
		return this.macDriverLicense;
	}

	public void setMacDriverLicense(String macDriverLicense) {
		this.macDriverLicense = macDriverLicense;
	}

	public String getMacRepairLoc() {
		return this.macRepairLoc;
	}

	public void setMacRepairLoc(String macRepairLoc) {
		this.macRepairLoc = macRepairLoc;
	}

	public String getMacClaimRemarks() {
		return this.macClaimRemarks;
	}

	public void setMacClaimRemarks(String macClaimRemarks) {
		this.macClaimRemarks = macClaimRemarks;
	}

	public String getMacPolicyNo() {
		return this.macPolicyNo;
	}

	public void setMacPolicyNo(String macPolicyNo) {
		this.macPolicyNo = macPolicyNo;
	}

	public Date getMacPreparedDate() {
		return macPreparedDate;
	}

	public void setMacPreparedDate(Date macPreparedDate) {
		this.macPreparedDate = macPreparedDate;
	}

}
