package com.rsaame.pas.dao.model;

// Generated Apr 12, 2012 12:55:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * TTrnTempConExcWarId generated by hbm2java
 */
public class TTrnTempConExcWarId implements java.io.Serializable {

	private Long tempPolicyId;
	private Long tempEndtId;
	private Short tempSecId;
	private Short tempCode;
	private String tempFlag;

	public TTrnTempConExcWarId() {
	}

	public TTrnTempConExcWarId(Long tempPolicyId, Long tempEndtId,
			Short tempSecId, Short tempCode, String tempFlag) {
		this.tempPolicyId = tempPolicyId;
		this.tempEndtId = tempEndtId;
		this.tempSecId = tempSecId;
		this.tempCode = tempCode;
		this.tempFlag = tempFlag;
	}

	public Long getTempPolicyId() {
		return this.tempPolicyId;
	}

	public void setTempPolicyId(Long tempPolicyId) {
		this.tempPolicyId = tempPolicyId;
	}

	public Long getTempEndtId() {
		return this.tempEndtId;
	}

	public void setTempEndtId(Long tempEndtId) {
		this.tempEndtId = tempEndtId;
	}

	public Short getTempSecId() {
		return this.tempSecId;
	}

	public void setTempSecId(Short tempSecId) {
		this.tempSecId = tempSecId;
	}

	public Short getTempCode() {
		return this.tempCode;
	}

	public void setTempCode(Short tempCode) {
		this.tempCode = tempCode;
	}

	public String getTempFlag() {
		return this.tempFlag;
	}

	public void setTempFlag(String tempFlag) {
		this.tempFlag = tempFlag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTrnTempConExcWarId))
			return false;
		TTrnTempConExcWarId castOther = (TTrnTempConExcWarId) other;

		return ((this.getTempPolicyId() == castOther.getTempPolicyId()) || (this
				.getTempPolicyId() != null
				&& castOther.getTempPolicyId() != null && this
				.getTempPolicyId().equals(castOther.getTempPolicyId())))
				&& ((this.getTempEndtId() == castOther.getTempEndtId()) || (this
						.getTempEndtId() != null
						&& castOther.getTempEndtId() != null && this
						.getTempEndtId().equals(castOther.getTempEndtId())))
				&& ((this.getTempSecId() == castOther.getTempSecId()) || (this
						.getTempSecId() != null
						&& castOther.getTempSecId() != null && this
						.getTempSecId().equals(castOther.getTempSecId())))
				&& ((this.getTempCode() == castOther.getTempCode()) || (this
						.getTempCode() != null
						&& castOther.getTempCode() != null && this
						.getTempCode().equals(castOther.getTempCode())))
				&& ((this.getTempFlag() == castOther.getTempFlag()) || (this
						.getTempFlag() != null
						&& castOther.getTempFlag() != null && this
						.getTempFlag().equals(castOther.getTempFlag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTempPolicyId() == null ? 0 : this.getTempPolicyId()
						.hashCode());
		result = 37
				* result
				+ (getTempEndtId() == null ? 0 : this.getTempEndtId()
						.hashCode());
		result = 37 * result
				+ (getTempSecId() == null ? 0 : this.getTempSecId().hashCode());
		result = 37 * result
				+ (getTempCode() == null ? 0 : this.getTempCode().hashCode());
		result = 37 * result
				+ (getTempFlag() == null ? 0 : this.getTempFlag().hashCode());
		return result;
	}

}
