package com.rsaame.pas.dao.model;

// Generated May 17, 2012 9:16:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TTrnPolicyWarranty generated by hbm2java
 */
public class TTrnPolicyWarranty implements java.io.Serializable {

	private TTrnPolicyWarrantyId id;
	private Integer tpwCovCode;
	private Integer tpwCtCode;
	private Integer tpwCstCode;
	private Date tpwValidityStartDate;
	private Date tpwValidityEndDate;
	private Byte tpwStatus;
	private Integer tpwPreparedBy;
	private Date tpwPreparedDt;
	private Integer tpwModifiedBy;
	private Date tpwModifiedDt;
	private String tpwAmount;
	private Boolean tpwPrintFlag;

	public TTrnPolicyWarranty() {
	}

	public TTrnPolicyWarranty(TTrnPolicyWarrantyId id) {
		this.id = id;
	}

	public TTrnPolicyWarranty(TTrnPolicyWarrantyId id, Integer tpwCovCode,
			Integer tpwCtCode, Integer tpwCstCode, Date tpwValidityStartDate,
			Date tpwValidityEndDate, Byte tpwStatus, Integer tpwPreparedBy,
			Date tpwPreparedDt, Integer tpwModifiedBy, Date tpwModifiedDt,
			String tpwAmount, Boolean tpwPrintFlag) {
		this.id = id;
		this.tpwCovCode = tpwCovCode;
		this.tpwCtCode = tpwCtCode;
		this.tpwCstCode = tpwCstCode;
		this.tpwValidityStartDate = tpwValidityStartDate;
		this.tpwValidityEndDate = tpwValidityEndDate;
		this.tpwStatus = tpwStatus;
		this.tpwPreparedBy = tpwPreparedBy;
		this.tpwPreparedDt = tpwPreparedDt;
		this.tpwModifiedBy = tpwModifiedBy;
		this.tpwModifiedDt = tpwModifiedDt;
		this.tpwAmount = tpwAmount;
		this.tpwPrintFlag = tpwPrintFlag;
	}

	public TTrnPolicyWarrantyId getId() {
		return this.id;
	}

	public void setId(TTrnPolicyWarrantyId id) {
		this.id = id;
	}

	public Integer getTpwCovCode() {
		return this.tpwCovCode;
	}

	public void setTpwCovCode(Integer tpwCovCode) {
		this.tpwCovCode = tpwCovCode;
	}

	public Integer getTpwCtCode() {
		return this.tpwCtCode;
	}

	public void setTpwCtCode(Integer tpwCtCode) {
		this.tpwCtCode = tpwCtCode;
	}

	public Integer getTpwCstCode() {
		return this.tpwCstCode;
	}

	public void setTpwCstCode(Integer tpwCstCode) {
		this.tpwCstCode = tpwCstCode;
	}

	public Date getTpwValidityStartDate() {
		return this.tpwValidityStartDate;
	}

	public void setTpwValidityStartDate(Date tpwValidityStartDate) {
		this.tpwValidityStartDate = tpwValidityStartDate;
	}

	public Date getTpwValidityEndDate() {
		return this.tpwValidityEndDate;
	}

	public void setTpwValidityEndDate(Date tpwValidityEndDate) {
		this.tpwValidityEndDate = tpwValidityEndDate;
	}

	public Byte getTpwStatus() {
		return this.tpwStatus;
	}

	public void setTpwStatus(Byte tpwStatus) {
		this.tpwStatus = tpwStatus;
	}

	public Integer getTpwPreparedBy() {
		return this.tpwPreparedBy;
	}

	public void setTpwPreparedBy(Integer tpwPreparedBy) {
		this.tpwPreparedBy = tpwPreparedBy;
	}

	public Date getTpwPreparedDt() {
		return this.tpwPreparedDt;
	}

	public void setTpwPreparedDt(Date tpwPreparedDt) {
		this.tpwPreparedDt = tpwPreparedDt;
	}

	public Integer getTpwModifiedBy() {
		return this.tpwModifiedBy;
	}

	public void setTpwModifiedBy(Integer tpwModifiedBy) {
		this.tpwModifiedBy = tpwModifiedBy;
	}

	public Date getTpwModifiedDt() {
		return this.tpwModifiedDt;
	}

	public void setTpwModifiedDt(Date tpwModifiedDt) {
		this.tpwModifiedDt = tpwModifiedDt;
	}

	public String getTpwAmount() {
		return this.tpwAmount;
	}

	public void setTpwAmount(String tpwAmount) {
		this.tpwAmount = tpwAmount;
	}

	public Boolean getTpwPrintFlag() {
		return this.tpwPrintFlag;
	}

	public void setTpwPrintFlag(Boolean tpwPrintFlag) {
		this.tpwPrintFlag = tpwPrintFlag;
	}

}
