package com.rsaame.pas.dao.model;

// Generated May 8, 2012 7:11:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.rsaame.pas.cmn.pojo.POJOId;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapper;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapperId;

/**
 * TTrnNonStdText generated by hbm2java
 */
public class TTrnNonStdTextQuo extends POJOWrapper implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TTrnNonStdTextQuoId id;
	private String nstAText;
	private String nstEText;
	private Date nstValidityStartDate;
	private Date nstValidityExpiryDate;
	private Byte nstPhrCode;
	private Integer nstPreparedBy;
	private Date nstPreparedDt;
	private Integer nstModifiedBy;
	private Date nstModifiedDt;
	private Byte nstStatus;

	public TTrnNonStdTextQuo() {
	}

	public TTrnNonStdTextQuo(TTrnNonStdTextQuoId id) {
		this.id = id;
	}

	public TTrnNonStdTextQuo(TTrnNonStdTextQuoId id, String nstAText,
			String nstEText, Date nstValidityStartDate,
			Date nstValidityExpiryDate, Byte nstPhrCode, Integer nstPreparedBy,
			Date nstPreparedDt, Integer nstModifiedBy, Date nstModifiedDt ,Byte nstStatus) {
		this.id = id;
		this.nstAText = nstAText;
		this.nstEText = nstEText;
		this.nstValidityStartDate = nstValidityStartDate;
		this.nstValidityExpiryDate = nstValidityExpiryDate;
		this.nstPhrCode = nstPhrCode;
		this.nstPreparedBy = nstPreparedBy;
		this.nstPreparedDt = nstPreparedDt;
		this.nstModifiedBy = nstModifiedBy;
		this.nstModifiedDt = nstModifiedDt;
		this.nstStatus = nstStatus;
	}

	public TTrnNonStdTextQuoId getId() {
		return this.id;
	}

	public void setId(TTrnNonStdTextQuoId id) {
		this.id = id;
	}

	/**
	 * @return the nstStatus
	 */
	public Byte getNstStatus(){
		return nstStatus;
	}

	/**
	 * @param nstStatus the nstStatus to set
	 */
	public void setNstStatus( Byte nstStatus ){
		this.nstStatus = nstStatus;
	}

	public String getNstAText() {
		return this.nstAText;
	}

	public void setNstAText(String nstAText) {
		this.nstAText = nstAText;
	}

	public String getNstEText() {
		return this.nstEText;
	}

	public void setNstEText(String nstEText) {
		this.nstEText = nstEText;
	}

	public Date getNstValidityStartDate() {
		return this.nstValidityStartDate;
	}

	public void setNstValidityStartDate(Date nstValidityStartDate) {
		this.nstValidityStartDate = nstValidityStartDate;
	}

	
	public Byte getNstPhrCode() {
		return this.nstPhrCode;
	}

	public void setNstPhrCode(Byte nstPhrCode) {
		this.nstPhrCode = nstPhrCode;
	}

	public Integer getNstPreparedBy() {
		return this.nstPreparedBy;
	}

	public void setNstPreparedBy(Integer nstPreparedBy) {
		this.nstPreparedBy = nstPreparedBy;
	}

	public Date getNstPreparedDt() {
		return this.nstPreparedDt;
	}

	public void setNstPreparedDt(Date nstPreparedDt) {
		this.nstPreparedDt = nstPreparedDt;
	}

	public Integer getNstModifiedBy() {
		return this.nstModifiedBy;
	}

	public void setNstModifiedBy(Integer nstModifiedBy) {
		this.nstModifiedBy = nstModifiedBy;
	}

	public Date getNstModifiedDt() {
		return this.nstModifiedDt;
	}

	public void setNstModifiedDt(Date nstModifiedDt) {
		this.nstModifiedDt = nstModifiedDt;
	}

	public Date getNstValidityExpiryDate() {
		return nstValidityExpiryDate;
	}

	public void setNstValidityExpiryDate(Date nstValidityExpiryDate) {
		this.nstValidityExpiryDate = nstValidityExpiryDate;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode(){
		final int prime = 31;
		int result = 1;
		result = prime * result + ( ( id == null ) ? 0 : id.hashCode() );
		result = prime * result + ( ( nstAText == null ) ? 0 : nstAText.hashCode() );
		result = prime * result + ( ( nstEText == null ) ? 0 : nstEText.hashCode() );
		result = prime * result + ( ( nstModifiedBy == null ) ? 0 : nstModifiedBy.hashCode() );
		result = prime * result + ( ( nstModifiedDt == null ) ? 0 : nstModifiedDt.hashCode() );
		result = prime * result + ( ( nstPhrCode == null ) ? 0 : nstPhrCode.hashCode() );
		result = prime * result + ( ( nstPreparedBy == null ) ? 0 : nstPreparedBy.hashCode() );
		result = prime * result + ( ( nstPreparedDt == null ) ? 0 : nstPreparedDt.hashCode() );
		result = prime * result + ( ( nstStatus == null ) ? 0 : nstStatus.hashCode() );
		result = prime * result + ( ( nstValidityExpiryDate == null ) ? 0 : nstValidityExpiryDate.hashCode() );
		result = prime * result + ( ( nstValidityStartDate == null ) ? 0 : nstValidityStartDate.hashCode() );
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals( Object obj ){
		if( this == obj ) return true;
		if( obj == null ) return false;
		if( getClass() != obj.getClass() ) return false;
		TTrnNonStdTextQuo other = (TTrnNonStdTextQuo) obj;
		if( id == null ){
			if( other.id != null ) return false;
		}
		else if( !id.equals( other.id ) ) return false;
		if( nstAText == null ){
			if( other.nstAText != null ) return false;
		}
		else if( !nstAText.equals( other.nstAText ) ) return false;
		if( nstEText == null ){
			if( other.nstEText != null ) return false;
		}
		else if( !nstEText.equals( other.nstEText ) ) return false;
		if( nstModifiedBy == null ){
			if( other.nstModifiedBy != null ) return false;
		}
		else if( !nstModifiedBy.equals( other.nstModifiedBy ) ) return false;
		if( nstModifiedDt == null ){
			if( other.nstModifiedDt != null ) return false;
		}
		else if( !nstModifiedDt.equals( other.nstModifiedDt ) ) return false;
		if( nstPhrCode == null ){
			if( other.nstPhrCode != null ) return false;
		}
		else if( !nstPhrCode.equals( other.nstPhrCode ) ) return false;
		if( nstPreparedBy == null ){
			if( other.nstPreparedBy != null ) return false;
		}
		else if( !nstPreparedBy.equals( other.nstPreparedBy ) ) return false;
		if( nstPreparedDt == null ){
			if( other.nstPreparedDt != null ) return false;
		}
		else if( !nstPreparedDt.equals( other.nstPreparedDt ) ) return false;
		if( nstValidityExpiryDate == null ){
			if( other.nstValidityExpiryDate != null ) return false;
		}
		else if( !nstStatus.equals( other.nstStatus ) ) return false;
		if( nstStatus == null ){
			if( other.nstStatus != null ) return false;
		}
		else if( !nstValidityExpiryDate.equals( other.nstValidityExpiryDate ) ) return false;
		if( nstValidityStartDate == null ){
			if( other.nstValidityStartDate != null ) return false;
		}
		else if( !nstValidityStartDate.equals( other.nstValidityStartDate ) ) return false;
		return true;
	}
	
	@Override
	public POJOId getPOJOId(){
		return this.getId();
	}
    
	public int getStatus(){
		return getNstStatus();
	}
	
	@Override
	public void setPreparedDate( Date preparedDate ){
		setNstPreparedDt( preparedDate );
	}

	@Override
	public void setPOJOWrapperId(POJOWrapperId id) {
		setId((TTrnNonStdTextQuoId) id);
		
	}

	@Override
	public POJOWrapperId getPOJOWrapperId() {
		return this.id;
	}

	@Override
	public void setStatus(int status) {
		this.nstStatus = Integer.valueOf(status).byteValue();
		
	}

	@Override
	public void setEndtId(Long endtId) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void setEndtNo(Long endtNo) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void setValidityStartDate(Date vsd) {
		this.nstValidityStartDate = vsd;
		
	}

	@Override
	public void setValidityExpiryDate(Date ved) {
		this.nstValidityExpiryDate = ved;
		
	}

	@Override
	public void setPreparedBy(Integer preparedBy) {
		this.nstPreparedBy = preparedBy;
		
	}

	@Override
	public void setPreparedDt(Date preparedDt) {
		this.nstPreparedDt = preparedDt;
		
	}

	@Override
	public void setModifiedBy(Integer modifiedBy) {
		this.nstModifiedBy = modifiedBy;
		
	}

	@Override
	public void setModifiedDt(Date modifiedDt) {
		this.nstModifiedDt = modifiedDt;
	}

	@Override
	public Integer getPreparedBy() {
		return this.nstPreparedBy;
	}

	@Override
	public Date getPreparedDt() {
		return this.nstPreparedDt;
	}

	@Override
	public Integer getModifiedBy() {
		return this.nstModifiedBy;
	}

	@Override
	public Date getModifiedDt() {
		return this.nstModifiedDt;
	}

	@Override
	public Date getPreparedDate(){
		return getNstPreparedDt();
	}
}
