package com.rsaame.pas.dao.model;

// Generated Mar 3, 2012 11:52:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.rsaame.pas.cmn.pojo.POJOId;

/**
 * TTrnGaccCashQuoId generated by hbm2java
 */
public class TTrnGaccCashQuoId implements java.io.Serializable, POJOId {
	private static final long serialVersionUID = 1L;
	
	private long gchId;
	private Date gchValidityStartDate;

	public TTrnGaccCashQuoId() {
	}

	public TTrnGaccCashQuoId(long gchId, Date gchValidityStartDate) {
		this.gchId = gchId;
		this.gchValidityStartDate = gchValidityStartDate;
	}

	public long getGchId() {
		return this.gchId;
	}

	public void setGchId(long gchId) {
		this.gchId = gchId;
	}

	public Date getGchValidityStartDate() {
		return this.gchValidityStartDate;
	}

	public void setGchValidityStartDate(Date gchValidityStartDate) {
		this.gchValidityStartDate = gchValidityStartDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTrnGaccCashQuoId))
			return false;
		TTrnGaccCashQuoId castOther = (TTrnGaccCashQuoId) other;

		return (this.getGchId() == castOther.getGchId())
				&& ((this.getGchValidityStartDate() == castOther
						.getGchValidityStartDate()) || (this
						.getGchValidityStartDate() != null
						&& castOther.getGchValidityStartDate() != null && this
						.getGchValidityStartDate().equals(
								castOther.getGchValidityStartDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getGchId();
		result = 37
				* result
				+ (getGchValidityStartDate() == null ? 0 : this
						.getGchValidityStartDate().hashCode());
		return result;
	}

}
