package com.rsaame.pas.dao.model;

// Generated Feb 16, 2012 4:43:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TTrnPolicyCommentsId generated by hbm2java
 */
public class TTrnPolicyCommentsId implements java.io.Serializable {

	private long pocPolicyId;
	private long pocEndtId;
	
	public TTrnPolicyCommentsId(){
		
	}


	public TTrnPolicyCommentsId(long pocPolicyId, long pocEndtId) {
		super();
		this.pocPolicyId = pocPolicyId;
		this.pocEndtId = pocEndtId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (pocEndtId ^ (pocEndtId >>> 32));
		result = prime * result + (int) (pocPolicyId ^ (pocPolicyId >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TTrnPolicyCommentsId other = (TTrnPolicyCommentsId) obj;
		if (pocEndtId != other.pocEndtId)
			return false;
		if (pocPolicyId != other.pocPolicyId)
			return false;
		return true;
	}

	public long getPocPolicyId() {
		return this.pocPolicyId;
	}

	public void setPocPolicyId(long pocPolicyId) {
		this.pocPolicyId = pocPolicyId;
	}

	public long getPocEndtId() {
		return this.pocEndtId;
	}

	public void setPocEndtId(long pocEndtId) {
		this.pocEndtId = pocEndtId;
	}

	
}
