package com.rsaame.pas.dao.model;

// Generated Mar 14, 2012 6:53:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.mindtree.ruc.cmn.utils.Utils;
import com.rsaame.pas.cmn.pojo.POJO;
import com.rsaame.pas.cmn.pojo.POJOId;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapper;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapperId;

/**
 * TTrnUwQuestionsQuo generated by hbm2java
 */
public class TTrnUwQuestionsQuo extends POJOWrapper implements java.io.Serializable {

	private TTrnUwQuestionsQuoId id;
	private String uqtUwqAnswer;
	private Date uqtValidityStartDate;
	private Date uqtValidityExpiryDate;
	private Integer uqtPreparedBy;
	private Date uqtPreparedDt;
	private Integer uqtModifiedBy;
	private Date uqtModifiedDt;
	private Byte uqtStatus;

	public TTrnUwQuestionsQuo() {
	}

	public TTrnUwQuestionsQuo(TTrnUwQuestionsQuoId id,
			Date uqtValidityExpiryDate) {
		this.id = id;
		this.uqtValidityExpiryDate = uqtValidityExpiryDate;
	}

	public TTrnUwQuestionsQuo(TTrnUwQuestionsQuoId id, String uqtUwqAnswer,
			Date uqtValidityStartDate, Date uqtValidityExpiryDate,
			Integer uqtPreparedBy, Date uqtPreparedDt, Integer uqtModifiedBy,
			Date uqtModifiedDt,Byte uqtStatus) {
		this.id = id;
		this.uqtUwqAnswer = uqtUwqAnswer;
		this.uqtValidityStartDate = uqtValidityStartDate;
		this.uqtValidityExpiryDate = uqtValidityExpiryDate;
		this.uqtPreparedBy = uqtPreparedBy;
		this.uqtPreparedDt = uqtPreparedDt;
		this.uqtModifiedBy = uqtModifiedBy;
		this.uqtModifiedDt = uqtModifiedDt;
		this.uqtStatus = uqtStatus;
	}

	public TTrnUwQuestionsQuoId getId() {
		return this.id;
	}

	public void setId(TTrnUwQuestionsQuoId id) {
		this.id = id;
	}

	public String getUqtUwqAnswer() {
		return this.uqtUwqAnswer;
	}

	public void setUqtUwqAnswer(String uqtUwqAnswer) {
		this.uqtUwqAnswer = uqtUwqAnswer;
	}

	public Date getUqtValidityStartDate() {
		return this.uqtValidityStartDate;
	}

	public void setUqtValidityStartDate(Date uqtValidityStartDate) {
		this.uqtValidityStartDate = uqtValidityStartDate;
	}

	public Date getUqtValidityExpiryDate() {
		return this.uqtValidityExpiryDate;
	}

	public void setUqtValidityExpiryDate(Date uqtValidityExpiryDate) {
		this.uqtValidityExpiryDate = uqtValidityExpiryDate;
	}

	public Integer getUqtPreparedBy() {
		return this.uqtPreparedBy;
	}

	public void setUqtPreparedBy(Integer uqtPreparedBy) {
		this.uqtPreparedBy = uqtPreparedBy;
	}

	public Date getUqtPreparedDt() {
		return this.uqtPreparedDt;
	}

	public void setUqtPreparedDt(Date uqtPreparedDt) {
		this.uqtPreparedDt = uqtPreparedDt;
	}

	public Integer getUqtModifiedBy() {
		return this.uqtModifiedBy;
	}

	public void setUqtModifiedBy(Integer uqtModifiedBy) {
		this.uqtModifiedBy = uqtModifiedBy;
	}

	public Date getUqtModifiedDt() {
		return this.uqtModifiedDt;
	}

	public void setUqtModifiedDt(Date uqtModifiedDt) {
		this.uqtModifiedDt = uqtModifiedDt;
	}
	
	

	public Byte getUqtStatus(){
		return uqtStatus;
	}

	public void setUqtStatus( Byte uqtStatus ){
		this.uqtStatus = uqtStatus;
	}

	@Override
	public int getStatus(){
		return getUqtStatus();
	}
	
	@Override
	public POJOId getPOJOId(){
		return this.getId();
	}
	
	@Override
	public void setPOJOId( POJOId id ){
		if(!Utils.isEmpty( id )) setId( (TTrnUwQuestionsQuoId) id );
	}
	
	@Override
	public void setValidityExpiryDate( Date ved ){
		setUqtValidityExpiryDate( ved );
	}
	
	
	@Override
	public void setStatus( Integer status ){
		setUqtStatus( status.byteValue() );
	}
	
	@Override
	public void setValidityStartDate(Date vsd){
		setUqtValidityStartDate( vsd );
	}
	
	@Override
	public void setEndtId( Long endtId ){
		if( !Utils.isEmpty( getId() ) ) getId().setUqtPolEndtId( endtId );
	}

	@Override
	public void setPOJOWrapperId( POJOWrapperId id ){
		this.id =  (TTrnUwQuestionsQuoId) id ;
		
	}

	@Override
	public POJOWrapperId getPOJOWrapperId(){
		return this.id;
	}

	@Override
	public void setStatus( int status ){
		// TODO Auto-generated method stub
		
	}

	@Override
	public void setEndtNo( Long endtNo ){
		// TODO Auto-generated method stub
		
	}

	@Override
	public void setPreparedBy( Integer preparedBy ){
		this.uqtPreparedBy = preparedBy;
	}

	@Override
	public void setPreparedDt( Date preparedDt ){
		this.uqtPreparedDt = preparedDt;
	}

	@Override
	public void setModifiedBy( Integer modifiedBy ){
		this.uqtModifiedBy = modifiedBy;
	}

	@Override
	public void setModifiedDt( Date modifiedDt ){
		this.uqtModifiedDt = modifiedDt;
		
	}

	@Override
	public Integer getPreparedBy(){
		return getUqtPreparedBy();
	}

	@Override
	public Date getPreparedDt(){
		return getUqtPreparedDt();
	}

	@Override
	public Integer getModifiedBy(){
		return getUqtModifiedBy();
	}

	@Override
	public Date getModifiedDt(){
		return getUqtModifiedDt();
	}
	
	@Override
	public void setPreparedDate( Date preparedDate ){
		setUqtPreparedDt( preparedDate );
	}
	
	@Override
	public Date getPreparedDate(){
		return getUqtPreparedDt();
	}
}
