package com.rsaame.pas.dao.model;

// Generated Mar 14, 2012 11:33:03 AM by Hibernate Tools 3.4.0.CR1

/**
 * TTrnTempPasReferral generated by hbm2java
 */
public class TTrnTempPasReferral implements java.io.Serializable {

	private TTrnTempPasReferralId id;
	private String tprRefText;

	private  Integer tprUserId;
	private String tprUserRole;

	
	public TTrnTempPasReferral() {
	}

	public String getTprRefText() {
		return tprRefText;
	}

	public void setTprRefText(String tprRefText) {
		this.tprRefText = tprRefText;
	}

	public TTrnTempPasReferral(TTrnTempPasReferralId id) {
		this.id = id;
	}

	public TTrnTempPasReferralId getId() {
		return this.id;
	}

	public void setId(TTrnTempPasReferralId id) {
		this.id = id;
	}

	public Integer getTprUserId() {
		return tprUserId;
	}

	public void setTprUserId(Integer tprUserId) {
		this.tprUserId = tprUserId;
	}

	public String getTprUserRole() {
		return tprUserRole;
	}

	public void setTprUserRole(String tprUserRole) {
		this.tprUserRole = tprUserRole;
	}

}
