package com.rsaame.pas.dao.model;

// Generated Mar 29, 2012 12:35:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * VMasPasFetchBasicDtls generated by hbm2java
 */
public class VMasPasFetchBasicDtls implements java.io.Serializable {

	private VMasPasFetchBasicDtlsId id;

	public VMasPasFetchBasicDtls() {
	}

	public VMasPasFetchBasicDtls(VMasPasFetchBasicDtlsId id) {
		this.id = id;
	}

	public VMasPasFetchBasicDtlsId getId() {
		return this.id;
	}

	public void setId(VMasPasFetchBasicDtlsId id) {
		this.id = id;
	}

}
