package com.rsaame.pas.dao.model;

// Generated Mar 28, 2012 12:20:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * VMasPasFetchAddlDtlsId generated by hbm2java
 */
public class VMasPasFetchAddlDtlsId implements java.io.Serializable {

	private Short secId;
	private Short prClCode;
	private Short prCovCode;
	private Short prCtCode;
	private Short prCstCode;
	private Integer prRskCode;
	private Integer prRtCode;
	private Integer prRcCode;
	private Integer prRscCode;
	private BigDecimal prCompulsoryExcess;
	private Integer prTariff;
	private BigDecimal prSumInsured;
	private BigDecimal prLimit;
	private BigDecimal prAggLimit;
	private String pcrEDesc;
	private Short secNumPersons;

	public VMasPasFetchAddlDtlsId() {
	}

	public VMasPasFetchAddlDtlsId(Short secId, Short prClCode, Short prCovCode,
			Short prCtCode, Short prCstCode, Integer prRskCode,
			Integer prRtCode, Integer prRcCode, Integer prRscCode,
			BigDecimal prCompulsoryExcess, Integer prTariff,
			BigDecimal prSumInsured, BigDecimal prLimit, BigDecimal prAggLimit,
			String pcrEDesc, Short secNumPersons) {
		this.secId = secId;
		this.prClCode = prClCode;
		this.prCovCode = prCovCode;
		this.prCtCode = prCtCode;
		this.prCstCode = prCstCode;
		this.prRskCode = prRskCode;
		this.prRtCode = prRtCode;
		this.prRcCode = prRcCode;
		this.prRscCode = prRscCode;
		this.prCompulsoryExcess = prCompulsoryExcess;
		this.prTariff = prTariff;
		this.prSumInsured = prSumInsured;
		this.prLimit = prLimit;
		this.prAggLimit = prAggLimit;
		this.pcrEDesc = pcrEDesc;
		this.secNumPersons = secNumPersons;
	}

	public Short getSecId() {
		return this.secId;
	}

	public void setSecId(Short secId) {
		this.secId = secId;
	}

	public Short getPrClCode() {
		return this.prClCode;
	}

	public void setPrClCode(Short prClCode) {
		this.prClCode = prClCode;
	}

	public Short getPrCovCode() {
		return this.prCovCode;
	}

	public void setPrCovCode(Short prCovCode) {
		this.prCovCode = prCovCode;
	}

	public Short getPrCtCode() {
		return this.prCtCode;
	}

	public void setPrCtCode(Short prCtCode) {
		this.prCtCode = prCtCode;
	}

	public Short getPrCstCode() {
		return this.prCstCode;
	}

	public void setPrCstCode(Short prCstCode) {
		this.prCstCode = prCstCode;
	}

	public Integer getPrRskCode() {
		return this.prRskCode;
	}

	public void setPrRskCode(Integer prRskCode) {
		this.prRskCode = prRskCode;
	}

	public Integer getPrRtCode() {
		return this.prRtCode;
	}

	public void setPrRtCode(Integer prRtCode) {
		this.prRtCode = prRtCode;
	}

	public Integer getPrRcCode() {
		return this.prRcCode;
	}

	public void setPrRcCode(Integer prRcCode) {
		this.prRcCode = prRcCode;
	}

	public Integer getPrRscCode() {
		return this.prRscCode;
	}

	public void setPrRscCode(Integer prRscCode) {
		this.prRscCode = prRscCode;
	}

	public BigDecimal getPrCompulsoryExcess() {
		return this.prCompulsoryExcess;
	}

	public void setPrCompulsoryExcess(BigDecimal prCompulsoryExcess) {
		this.prCompulsoryExcess = prCompulsoryExcess;
	}

	public Integer getPrTariff() {
		return this.prTariff;
	}

	public void setPrTariff(Integer prTariff) {
		this.prTariff = prTariff;
	}

	public BigDecimal getPrSumInsured() {
		return this.prSumInsured;
	}

	public void setPrSumInsured(BigDecimal prSumInsured) {
		this.prSumInsured = prSumInsured;
	}

	public BigDecimal getPrLimit() {
		return this.prLimit;
	}

	public void setPrLimit(BigDecimal prLimit) {
		this.prLimit = prLimit;
	}

	public BigDecimal getPrAggLimit() {
		return this.prAggLimit;
	}

	public void setPrAggLimit(BigDecimal prAggLimit) {
		this.prAggLimit = prAggLimit;
	}

	public String getPcrEDesc() {
		return this.pcrEDesc;
	}

	public void setPcrEDesc(String pcrEDesc) {
		this.pcrEDesc = pcrEDesc;
	}

	public Short getSecNumPersons() {
		return this.secNumPersons;
	}

	public void setSecNumPersons(Short secNumPersons) {
		this.secNumPersons = secNumPersons;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VMasPasFetchAddlDtlsId))
			return false;
		VMasPasFetchAddlDtlsId castOther = (VMasPasFetchAddlDtlsId) other;

		return ((this.getSecId() == castOther.getSecId()) || (this.getSecId() != null
				&& castOther.getSecId() != null && this.getSecId().equals(
				castOther.getSecId())))
				&& ((this.getPrClCode() == castOther.getPrClCode()) || (this
						.getPrClCode() != null
						&& castOther.getPrClCode() != null && this
						.getPrClCode().equals(castOther.getPrClCode())))
				&& ((this.getPrCovCode() == castOther.getPrCovCode()) || (this
						.getPrCovCode() != null
						&& castOther.getPrCovCode() != null && this
						.getPrCovCode().equals(castOther.getPrCovCode())))
				&& ((this.getPrCtCode() == castOther.getPrCtCode()) || (this
						.getPrCtCode() != null
						&& castOther.getPrCtCode() != null && this
						.getPrCtCode().equals(castOther.getPrCtCode())))
				&& ((this.getPrCstCode() == castOther.getPrCstCode()) || (this
						.getPrCstCode() != null
						&& castOther.getPrCstCode() != null && this
						.getPrCstCode().equals(castOther.getPrCstCode())))
				&& ((this.getPrRskCode() == castOther.getPrRskCode()) || (this
						.getPrRskCode() != null
						&& castOther.getPrRskCode() != null && this
						.getPrRskCode().equals(castOther.getPrRskCode())))
				&& ((this.getPrRtCode() == castOther.getPrRtCode()) || (this
						.getPrRtCode() != null
						&& castOther.getPrRtCode() != null && this
						.getPrRtCode().equals(castOther.getPrRtCode())))
				&& ((this.getPrRcCode() == castOther.getPrRcCode()) || (this
						.getPrRcCode() != null
						&& castOther.getPrRcCode() != null && this
						.getPrRcCode().equals(castOther.getPrRcCode())))
				&& ((this.getPrRscCode() == castOther.getPrRscCode()) || (this
						.getPrRscCode() != null
						&& castOther.getPrRscCode() != null && this
						.getPrRscCode().equals(castOther.getPrRscCode())))
				&& ((this.getPrCompulsoryExcess() == castOther
						.getPrCompulsoryExcess()) || (this
						.getPrCompulsoryExcess() != null
						&& castOther.getPrCompulsoryExcess() != null && this
						.getPrCompulsoryExcess().equals(
								castOther.getPrCompulsoryExcess())))
				&& ((this.getPrTariff() == castOther.getPrTariff()) || (this
						.getPrTariff() != null
						&& castOther.getPrTariff() != null && this
						.getPrTariff().equals(castOther.getPrTariff())))
				&& ((this.getPrSumInsured() == castOther.getPrSumInsured()) || (this
						.getPrSumInsured() != null
						&& castOther.getPrSumInsured() != null && this
						.getPrSumInsured().equals(castOther.getPrSumInsured())))
				&& ((this.getPrLimit() == castOther.getPrLimit()) || (this
						.getPrLimit() != null && castOther.getPrLimit() != null && this
						.getPrLimit().equals(castOther.getPrLimit())))
				&& ((this.getPrAggLimit() == castOther.getPrAggLimit()) || (this
						.getPrAggLimit() != null
						&& castOther.getPrAggLimit() != null && this
						.getPrAggLimit().equals(castOther.getPrAggLimit())))
				&& ((this.getPcrEDesc() == castOther.getPcrEDesc()) || (this
						.getPcrEDesc() != null
						&& castOther.getPcrEDesc() != null && this
						.getPcrEDesc().equals(castOther.getPcrEDesc())))
				&& ((this.getSecNumPersons() == castOther.getSecNumPersons()) || (this
						.getSecNumPersons() != null
						&& castOther.getSecNumPersons() != null && this
						.getSecNumPersons()
						.equals(castOther.getSecNumPersons())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSecId() == null ? 0 : this.getSecId().hashCode());
		result = 37 * result
				+ (getPrClCode() == null ? 0 : this.getPrClCode().hashCode());
		result = 37 * result
				+ (getPrCovCode() == null ? 0 : this.getPrCovCode().hashCode());
		result = 37 * result
				+ (getPrCtCode() == null ? 0 : this.getPrCtCode().hashCode());
		result = 37 * result
				+ (getPrCstCode() == null ? 0 : this.getPrCstCode().hashCode());
		result = 37 * result
				+ (getPrRskCode() == null ? 0 : this.getPrRskCode().hashCode());
		result = 37 * result
				+ (getPrRtCode() == null ? 0 : this.getPrRtCode().hashCode());
		result = 37 * result
				+ (getPrRcCode() == null ? 0 : this.getPrRcCode().hashCode());
		result = 37 * result
				+ (getPrRscCode() == null ? 0 : this.getPrRscCode().hashCode());
		result = 37
				* result
				+ (getPrCompulsoryExcess() == null ? 0 : this
						.getPrCompulsoryExcess().hashCode());
		result = 37 * result
				+ (getPrTariff() == null ? 0 : this.getPrTariff().hashCode());
		result = 37
				* result
				+ (getPrSumInsured() == null ? 0 : this.getPrSumInsured()
						.hashCode());
		result = 37 * result
				+ (getPrLimit() == null ? 0 : this.getPrLimit().hashCode());
		result = 37
				* result
				+ (getPrAggLimit() == null ? 0 : this.getPrAggLimit()
						.hashCode());
		result = 37 * result
				+ (getPcrEDesc() == null ? 0 : this.getPcrEDesc().hashCode());
		result = 37
				* result
				+ (getSecNumPersons() == null ? 0 : this.getSecNumPersons()
						.hashCode());
		return result;
	}

}
