package com.rsaame.pas.dao.model;

// Generated Feb 10, 2012 5:52:40 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * VParBldDeductiblesId generated by hbm2java
 */
public class VParBldDeductiblesId implements java.io.Serializable {

	private BigDecimal compulsoryExcess;
	private int rtCode;

	public VParBldDeductiblesId() {
	}

	public VParBldDeductiblesId(int rtCode) {
		this.rtCode = rtCode;
	}

	public VParBldDeductiblesId(BigDecimal compulsoryExcess, int rtCode) {
		this.compulsoryExcess = compulsoryExcess;
		this.rtCode = rtCode;
	}

	public BigDecimal getCompulsoryExcess() {
		return this.compulsoryExcess;
	}

	public void setCompulsoryExcess(BigDecimal compulsoryExcess) {
		this.compulsoryExcess = compulsoryExcess;
	}

	public int getRtCode() {
		return this.rtCode;
	}

	public void setRtCode(int rtCode) {
		this.rtCode = rtCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VParBldDeductiblesId))
			return false;
		VParBldDeductiblesId castOther = (VParBldDeductiblesId) other;

		return ((this.getCompulsoryExcess() == castOther.getCompulsoryExcess()) || (this
				.getCompulsoryExcess() != null
				&& castOther.getCompulsoryExcess() != null && this
				.getCompulsoryExcess().equals(castOther.getCompulsoryExcess())))
				&& (this.getRtCode() == castOther.getRtCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCompulsoryExcess() == null ? 0 : this
						.getCompulsoryExcess().hashCode());
		result = 37 * result + this.getRtCode();
		return result;
	}

}
