package com.rsaame.pas.dao.model;

// Generated Jul 11, 2012 2:50:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * VTrnRenewalPoliciesSbsId generated by hbm2java
 */
public class VTrnRenewalPoliciesSbsId implements java.io.Serializable {

	private Long polLinkingId;


	public VTrnRenewalPoliciesSbsId() {
	}

	public VTrnRenewalPoliciesSbsId(Long polLinkingId) {
		this.polLinkingId = polLinkingId;
	}

	public Long getPolLinkingId() {
		return this.polLinkingId;
	}

	public void setPolLinkingId(Long polLinkingId) {
		this.polLinkingId = polLinkingId;
	}

	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VTrnRenewalPoliciesSbsId))
			return false;
		VTrnRenewalPoliciesSbsId castOther = (VTrnRenewalPoliciesSbsId) other;

		return ((this.getPolLinkingId() == castOther.getPolLinkingId()) || (this
				.getPolLinkingId() != null
				&& castOther.getPolLinkingId() != null && this
				.getPolLinkingId().equals(castOther.getPolLinkingId())));
			
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPolLinkingId() == null ? 0 : this.getPolLinkingId()
						.hashCode());
		
		return result;
	}

}
