package com.rsaame.pas.dao.model;

// Generated Aug 16, 2012 7:36:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * VTrnPasPremSumLocTmp generated by hbm2java
 */
public class VTrnPasPremSumLoc implements java.io.Serializable {

	private VTrnPasPremSumLocId id;

	public VTrnPasPremSumLoc() {
	}

	public VTrnPasPremSumLoc(VTrnPasPremSumLocId id) {
		this.id = id;
	}

	public VTrnPasPremSumLocId getId() {
		return this.id;
	}

	public void setId(VTrnPasPremSumLocId id) {
		this.id = id;
	}

}
