package com.rsaame.pas.dao.model;

// Generated Mar 12, 2012 4:59:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * VTrnTaskId generated by hbm2java
 */
public class VTrnTaskId implements java.io.Serializable {

	private Long tskId;
	private Integer tskAssignor;
	private Integer tskAssignee;
	

	public VTrnTaskId() {
	}

	public VTrnTaskId(Long tskId, Integer tskAssignor, Integer tskAssignee) {
		this.tskId = tskId;
		this.tskAssignor = tskAssignor;
		this.tskAssignee = tskAssignee;
		
	}

	public Long getTskId() {
		return this.tskId;
	}

	public void setTskId(Long tskId) {
		this.tskId = tskId;
	}

	public Integer getTskAssignor() {
		return this.tskAssignor;
	}

	public void setTskAssignor(Integer tskAssignor) {
		this.tskAssignor = tskAssignor;
	}

	public Integer getTskAssignee() {
		return this.tskAssignee;
	}

	public void setTskAssignee(Integer tskAssignee) {
		this.tskAssignee = tskAssignee;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VTrnTaskId))
			return false;
		VTrnTaskId castOther = (VTrnTaskId) other;

		return ((this.getTskId() == castOther.getTskId()) || (this.getTskId() != null
				&& castOther.getTskId() != null && this.getTskId().equals(
				castOther.getTskId())))
				&& ((this.getTskAssignor() == castOther.getTskAssignor()) || (this
						.getTskAssignor() != null
						&& castOther.getTskAssignor() != null && this
						.getTskAssignor().equals(castOther.getTskAssignor())))
				&& ((this.getTskAssignee() == castOther.getTskAssignee()) || (this
						.getTskAssignee() != null
						&& castOther.getTskAssignee() != null && this
						.getTskAssignee().equals(castOther.getTskAssignee())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTskId() == null ? 0 : this.getTskId().hashCode());
		result = 37
				* result
				+ (getTskAssignor() == null ? 0 : this.getTskAssignor()
						.hashCode());
		result = 37
				* result
				+ (getTskAssignee() == null ? 0 : this.getTskAssignee()
						.hashCode());
		
		return result;
	}

}
