package com.rsaame.pas.dao.model;

import java.math.BigDecimal;
import java.util.Date;

// Generated May 1, 2012 12:48:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * VTrnPasPremiumSummary generated by hbm2java
 */
public class VTrnPasPremiumSummary implements java.io.Serializable {

	private VTrnPasPremiumSummaryId id;
	private BigDecimal commission;
	private BigDecimal coverSiAmt;
	private BigDecimal coverPrmAmt;
	private Date valStartDate;
	private Date valExpDate;
	private Byte status;
	private Character polQuoFlag;

	/**
	 * @return the commission
	 */
	public BigDecimal getCommission(){
		return commission;
	}

	/**
	 * @return the coverSiAmt
	 */
	public BigDecimal getCoverSiAmt(){
		return coverSiAmt;
	}

	/**
	 * @return the coverPrmAmt
	 */
	public BigDecimal getCoverPrmAmt(){
		return coverPrmAmt;
	}

	/**
	 * @return the valStartDate
	 */
	public Date getValStartDate(){
		return valStartDate;
	}

	/**
	 * @return the valExpDate
	 */
	public Date getValExpDate(){
		return valExpDate;
	}

	/**
	 * @return the status
	 */
	public Byte getStatus(){
		return status;
	}

	/**
	 * @return the polQuoFlag
	 */
	public Character getPolQuoFlag(){
		return polQuoFlag;
	}

	/**
	 * @param commission the commission to set
	 */
	public void setCommission( BigDecimal commission ){
		this.commission = commission;
	}

	/**
	 * @param coverSiAmt the coverSiAmt to set
	 */
	public void setCoverSiAmt( BigDecimal coverSiAmt ){
		this.coverSiAmt = coverSiAmt;
	}

	/**
	 * @param coverPrmAmt the coverPrmAmt to set
	 */
	public void setCoverPrmAmt( BigDecimal coverPrmAmt ){
		this.coverPrmAmt = coverPrmAmt;
	}

	/**
	 * @param valStartDate the valStartDate to set
	 */
	public void setValStartDate( Date valStartDate ){
		this.valStartDate = valStartDate;
	}

	/**
	 * @param valExpDate the valExpDate to set
	 */
	public void setValExpDate( Date valExpDate ){
		this.valExpDate = valExpDate;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus( Byte status ){
		this.status = status;
	}

	/**
	 * @param polQuoFlag the polQuoFlag to set
	 */
	public void setPolQuoFlag( Character polQuoFlag ){
		this.polQuoFlag = polQuoFlag;
	}

	public VTrnPasPremiumSummary() {
	}

	public VTrnPasPremiumSummary(VTrnPasPremiumSummaryId id) {
		this.id = id;
	}

	public VTrnPasPremiumSummaryId getId() {
		return this.id;
	}

	public void setId(VTrnPasPremiumSummaryId id) {
		this.id = id;
	}

}
