//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SectionVO.java
//  @ Date : 12/20/2011
//  @ Author : 
//
//

package com.rsaame.pas.vo.bus;

import java.util.Map;

import com.mindtree.ruc.cmn.base.BaseVO;
import com.mindtree.ruc.cmn.reflect.IFieldValue;
import com.mindtree.ruc.cmn.utils.Utils;

public class SectionVO extends BaseVO implements IFieldValue{
	private static final long serialVersionUID = 1L;

	private RiskGroupingLevel riskGroupingLevel;
	private Double commission;
	private Long policyId;
	private java.util.Map<? extends RiskGroup, ? extends RiskGroupDetails> riskGroupDetails;
	private java.util.List<StandardClause> standardClauses =new com.mindtree.ruc.cmn.utils.List<StandardClause>(StandardClause.class);
	private String sectionName;
	private Integer sectionId;
	private Integer classCode;

	public SectionVO( RiskGroupingLevel riskGroupingLevel ){
		this.riskGroupingLevel = riskGroupingLevel;
	}

	

	@Override
	public Object getFieldValue( String fieldName ){
		Object fieldValue = null;

		if( "riskGroupingLevel".equals( fieldName ) ) fieldValue = getRiskGroupingLevel();
		if( "riskGroupDetails".equals( fieldName ) ) fieldValue = getRiskGroupDetails();
		if( "sectionName".equals( fieldName ) ) fieldValue = getSectionName();
		if( "sectionId".equals( fieldName ) ) fieldValue = getSectionId();
		if( "policyId".equals( fieldName ) ) fieldValue = getPolicyId();
		if( "standardClauses".equals( fieldName ) ) fieldValue = getStandardClauses();

		return fieldValue;
	}
	
	public void addRiskGroupDetails( RiskGroup riskGroup, RiskGroupDetails riskGroupDetails ){
		
		//SONARFIX -- 26/04/2018 -- DO NOTHING IN METHOD.

	}

	public RiskGroupingLevel getRiskGroupingLevel(){
		return riskGroupingLevel;
	}

	public void setRiskGroupingLevel( RiskGroupingLevel riskGroupingLevel ){
		this.riskGroupingLevel = riskGroupingLevel;
	}

	public Map<? extends RiskGroup, ? extends RiskGroupDetails> getRiskGroupDetails(){
		return riskGroupDetails;
	}

	public void setRiskGroupDetails( Map<? extends RiskGroup, ? extends RiskGroupDetails> riskGroupDetails ){
		this.riskGroupDetails = riskGroupDetails;
	}





	/**
	 * @return the sectionName
	 */
	public String getSectionName() {
		return sectionName;
	}



	/**
	 * @param sectionName the sectionName to set
	 */
	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}



	/**
	 * @return the sectionId
	 */
	public Integer getSectionId() {
		return sectionId;
	}



	/**
	 * @param sectionId the sectionId to set
	 */
	public void setSectionId(Integer sectionId) {
		this.sectionId = sectionId;
		this.classCode = Integer.valueOf( Utils.getSingleValueAppConfig( Utils.concat( "SEC_", sectionId.toString()) ) );
	}



	public Double getCommission() {
		return commission;
	}



	public void setCommission(Double commission) {
		this.commission = commission;
	}



	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((sectionId == null) ? 0 : sectionId.hashCode());
		return result;
	}



	@Override
	public boolean equals( Object obj ){
		boolean equal = false;

		equalsCheck: {
			if( Utils.isEmpty( obj ) || !( obj instanceof SectionVO ) ) break equalsCheck;

			SectionVO theOtherVO = (SectionVO) obj;
			if( Utils.isEmpty( this.getSectionId() ) && Utils.isEmpty( theOtherVO.getSectionId() ) ){
				equal = true;
				break equalsCheck;
			}
			
			if( !Utils.isEmpty( this.getSectionId() ) ){
				equal = this.getSectionId().equals( theOtherVO.getSectionId() );
			}
		}

		return equal;
	}



	public Long getPolicyId(){
		return policyId;
	}



	public void setPolicyId( Long policyId ){
		this.policyId = policyId;
	}

	/**
	 * @return the standardClauses
	 */
	public java.util.List<StandardClause> getStandardClauses(){
		return standardClauses;
	}



	/**
	 * @param standardClauses the standardClauses to set
	 */
	public void setStandardClauses( java.util.List<StandardClause> standardClauses ){
		this.standardClauses = standardClauses;
	}

	public Integer getClassCode(){
		return classCode;
	}



	@Override
	public String toString(){
		return "SectionVO [riskGroupingLevel=" + riskGroupingLevel + ", commission=" + commission + ", policyId=" + policyId + ", riskGroupDetails=" + riskGroupDetails
				+ ", standardClauses=" + standardClauses + ", sectionName=" + sectionName + ", sectionId=" + sectionId + ", classCode=" + classCode + "]";
	}



}
