package com.rsaame.pas.dao.model;

// Generated Feb 1, 2012 11:52:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * TMasCoverId generated by hbm2java
 */
public class TMasCoverId implements java.io.Serializable {

	private short covClCode;
	private short covPtCode;
	private short covCode;

	public TMasCoverId() {
	}

	public TMasCoverId(short covClCode, short covPtCode, short covCode) {
		this.covClCode = covClCode;
		this.covPtCode = covPtCode;
		this.covCode = covCode;
	}

	public short getCovClCode() {
		return this.covClCode;
	}

	public void setCovClCode(short covClCode) {
		this.covClCode = covClCode;
	}

	public short getCovPtCode() {
		return this.covPtCode;
	}

	public void setCovPtCode(short covPtCode) {
		this.covPtCode = covPtCode;
	}

	public short getCovCode() {
		return this.covCode;
	}

	public void setCovCode(short covCode) {
		this.covCode = covCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMasCoverId))
			return false;
		TMasCoverId castOther = (TMasCoverId) other;

		return (this.getCovClCode() == castOther.getCovClCode())
				&& (this.getCovPtCode() == castOther.getCovPtCode())
				&& (this.getCovCode() == castOther.getCovCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCovClCode();
		result = 37 * result + this.getCovPtCode();
		result = 37 * result + this.getCovCode();
		return result;
	}

}
