package com.rsaame.pas.dao.model;

import java.util.Date;

// Generated Feb 16, 2012 4:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * TTrnPolicyComments generated by hbm2java
 */
public class TTrnPolicyComments implements java.io.Serializable {


	private long pocPolicyId;
	private long pocEndtId;
	private Short pocReasonCode;
	private String pocComments;
	private Byte pocPolicyStatus;
	private Date pocDate;
	private Integer pocPreparedBy;
	private Date pocPreparedDt;
	private Integer pocModifiedBy;
	private Date pocModifiedDt;
	private Byte pocDocumentCode;
	
	public Short getPocReasonCode() {
		return pocReasonCode;
	}

	public void setPocReasonCode(Short pocReasonCode) {
		this.pocReasonCode = pocReasonCode;
	}

	public String getPocComments() {
		return pocComments;
	}

	public void setPocComments(String pocComments) {
		this.pocComments = pocComments;
	}

	public Byte getPocPolicyStatus() {
		return pocPolicyStatus;
	}

	public void setPocPolicyStatus(Byte pocPolicyStatus) {
		this.pocPolicyStatus = pocPolicyStatus;
	}

	public Date getPocDate() {
		return pocDate;
	}

	public void setPocDate(Date pocDate) {
		this.pocDate = pocDate;
	}

	public Integer getPocPreparedBy() {
		return pocPreparedBy;
	}

	public void setPocPreparedBy(Integer pocPreparedBy) {
		this.pocPreparedBy = pocPreparedBy;
	}

	public Date getPocPreparedDt() {
		return pocPreparedDt;
	}

	public void setPocPreparedDt(Date pocPreparedDt) {
		this.pocPreparedDt = pocPreparedDt;
	}

	public Integer getPocModifiedBy() {
		return pocModifiedBy;
	}

	public void setPocModifiedBy(Integer pocModifiedBy) {
		this.pocModifiedBy = pocModifiedBy;
	}

	public Date getPocModifiedDt() {
		return pocModifiedDt;
	}

	public void setPocModifiedDt(Date pocModifiedDt) {
		this.pocModifiedDt = pocModifiedDt;
	}

	public Byte getPocDocumentCode() {
		return pocDocumentCode;
	}

	public void setPocDocumentCode(Byte pocDocumentCode) {
		this.pocDocumentCode = pocDocumentCode;
	}

	public TTrnPolicyComments() {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	/**
	 * @return the pocPolicyId
	 */
	public long getPocPolicyId(){
		return pocPolicyId;
	}

	/**
	 * @param pocPolicyId the pocPolicyId to set
	 */
	public void setPocPolicyId( long pocPolicyId ){
		this.pocPolicyId = pocPolicyId;
	}

	/**
	 * @return the pocEndtId
	 */
	public long getPocEndtId(){
		return pocEndtId;
	}

	/**
	 * @param pocEndtId the pocEndtId to set
	 */
	public void setPocEndtId( long pocEndtId ){
		this.pocEndtId = pocEndtId;
	}

}
