package com.rsaame.pas.dao.model;

// Generated Mar 4, 2014 6:15:40 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapper;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapperId;

/**
 * TTrnHirePurchase generated by hbm2java
 */
public class TTrnHirePurchaseQuo extends POJOWrapper implements java.io.Serializable {

	private static final long serialVersionUID = 888L;

	private TTrnHirePurchaseQuoId id;
	private BigDecimal hpAmount;
	private Date hpExpiryDate;
	
	private Date hpValidityExpiryDate;
	private Byte hpStatus;
	private Integer hpPreparedBy;
	private Date hpPreparedDt;
	private Integer hpModifiedBy;
	private Date hpModifiedDt;

	public TTrnHirePurchaseQuo() {
	}

	public TTrnHirePurchaseQuo(TTrnHirePurchaseQuoId id, Date hpValidityExpiryDate) {
		this.id = id;
		this.hpValidityExpiryDate = hpValidityExpiryDate;
	}

	public TTrnHirePurchaseQuo(TTrnHirePurchaseQuoId id, BigDecimal hpAmount,
			Date hpExpiryDate, Date hpValidityExpiryDate, 
			Byte hpStatus, Integer hpPreparedBy,
			Date hpPreparedDt, Integer hpModifiedBy, Date hpModifiedDt) {
		this.id = id;
		this.hpAmount = hpAmount;
		this.hpExpiryDate = hpExpiryDate;
	
		this.hpValidityExpiryDate = hpValidityExpiryDate;
		this.hpStatus = hpStatus;
		this.hpPreparedBy = hpPreparedBy;
		this.hpPreparedDt = hpPreparedDt;
		this.hpModifiedBy = hpModifiedBy;
		this.hpModifiedDt = hpModifiedDt;
	}

	public TTrnHirePurchaseQuoId getId() {
		return this.id;
	}

	public void setId(TTrnHirePurchaseQuoId id) {
		this.id = id;
	}

	public BigDecimal getHpAmount() {
		return this.hpAmount;
	}

	public void setHpAmount(BigDecimal hpAmount) {
		this.hpAmount = hpAmount;
	}

	public Date getHpExpiryDate() {
		return this.hpExpiryDate;
	}

	public void setHpExpiryDate(Date hpExpiryDate) {
		this.hpExpiryDate = hpExpiryDate;
	}

	public Date getHpValidityExpiryDate() {
		return this.hpValidityExpiryDate;
	}

	public void setHpValidityExpiryDate(Date hpValidityExpiryDate) {
		this.hpValidityExpiryDate = hpValidityExpiryDate;
	}

	public Byte getHpStatus() {
		return this.hpStatus;
	}

	public void setHpStatus(Byte hpStatus) {
		this.hpStatus = hpStatus;
	}

	public Integer getHpPreparedBy() {
		return this.hpPreparedBy;
	}

	public void setHpPreparedBy(Integer hpPreparedBy) {
		this.hpPreparedBy = hpPreparedBy;
	}

	public Date getHpPreparedDt() {
		return this.hpPreparedDt;
	}

	public void setHpPreparedDt(Date hpPreparedDt) {
		this.hpPreparedDt = hpPreparedDt;
	}

	public Integer getHpModifiedBy() {
		return this.hpModifiedBy;
	}

	public void setHpModifiedBy(Integer hpModifiedBy) {
		this.hpModifiedBy = hpModifiedBy;
	}

	public Date getHpModifiedDt() {
		return this.hpModifiedDt;
	}

	public void setHpModifiedDt(Date hpModifiedDt) {
		this.hpModifiedDt = hpModifiedDt;
	}

	@Override
	public void setPOJOWrapperId(POJOWrapperId id) {
		setId((TTrnHirePurchaseQuoId)id);
	}

	@Override
	public POJOWrapperId getPOJOWrapperId() {
		return getId();
	}

	@Override
	public void setStatus(int status) {
		setHpStatus((Integer.valueOf(status)).byteValue());
	}

	@Override
	public void setEndtId(Long endtId) {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	@Override
	public void setEndtNo(Long endtNo) {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	@Override
	public void setValidityStartDate(Date vsd) {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	@Override
	public void setValidityExpiryDate(Date ved) {
		setHpValidityExpiryDate(ved);
	}

	@Override
	public void setPreparedBy(Integer preparedBy) {
		setHpPreparedBy(preparedBy);
		
	}

	@Override
	public void setPreparedDt(Date preparedDt) {
		setHpPreparedDt(preparedDt);
	}

	@Override
	public void setModifiedBy(Integer modifiedBy) {
		setHpModifiedBy(modifiedBy);
	}

	@Override
	public void setModifiedDt(Date modifiedDt) {
		setHpModifiedDt(modifiedDt);
	}

	@Override
	public Integer getPreparedBy() {
		return getHpPreparedBy();
	}

	@Override
	public Date getPreparedDt() {
		return getHpPreparedDt();
	}

	@Override
	public Integer getModifiedBy() {
		return getHpModifiedBy();
	}

	@Override
	public Date getModifiedDt() {
		return getHpModifiedDt();
	}

}
