package com.rsaame.pas.dao.model;

// Generated Feb 1, 2012 11:52:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TMasPolicyType generated by hbm2java
 */
public class TMasPolicyType implements java.io.Serializable {

	private TMasPolicyTypeId id;
	private String ptADesc;
	private String ptEDesc;
	private Short ptUserCode;
	private Boolean ptRiDisplayCode;
	private Integer ptPreparedBy;
	private Date ptPreparedDt;
	private Integer ptModifiedBy;
	private Date ptModifiedDt;
	private Integer ptStatus;
	private String ptETerLimits;
	private String ptATerLimits;
	private Set TMasCovers = new HashSet(0);

	public TMasPolicyType() {
	}

	public TMasPolicyType(TMasPolicyTypeId id) {
		this.id = id;
	}

	public TMasPolicyType(TMasPolicyTypeId id, String ptADesc, String ptEDesc,
			Short ptUserCode, Boolean ptRiDisplayCode, Integer ptPreparedBy,
			Date ptPreparedDt, Integer ptModifiedBy, Date ptModifiedDt,
			Integer ptStatus, String ptETerLimits, String ptATerLimits,
			Set TMasCovers) {
		this.id = id;
		this.ptADesc = ptADesc;
		this.ptEDesc = ptEDesc;
		this.ptUserCode = ptUserCode;
		this.ptRiDisplayCode = ptRiDisplayCode;
		this.ptPreparedBy = ptPreparedBy;
		this.ptPreparedDt = ptPreparedDt;
		this.ptModifiedBy = ptModifiedBy;
		this.ptModifiedDt = ptModifiedDt;
		this.ptStatus = ptStatus;
		this.ptETerLimits = ptETerLimits;
		this.ptATerLimits = ptATerLimits;
		this.TMasCovers = TMasCovers;
	}

	public TMasPolicyTypeId getId() {
		return this.id;
	}

	public void setId(TMasPolicyTypeId id) {
		this.id = id;
	}

	public String getPtADesc() {
		return this.ptADesc;
	}

	public void setPtADesc(String ptADesc) {
		this.ptADesc = ptADesc;
	}

	public String getPtEDesc() {
		return this.ptEDesc;
	}

	public void setPtEDesc(String ptEDesc) {
		this.ptEDesc = ptEDesc;
	}

	public Short getPtUserCode() {
		return this.ptUserCode;
	}

	public void setPtUserCode(Short ptUserCode) {
		this.ptUserCode = ptUserCode;
	}

	public Boolean getPtRiDisplayCode() {
		return this.ptRiDisplayCode;
	}

	public void setPtRiDisplayCode(Boolean ptRiDisplayCode) {
		this.ptRiDisplayCode = ptRiDisplayCode;
	}

	public Integer getPtPreparedBy() {
		return this.ptPreparedBy;
	}

	public void setPtPreparedBy(Integer ptPreparedBy) {
		this.ptPreparedBy = ptPreparedBy;
	}

	public Date getPtPreparedDt() {
		return this.ptPreparedDt;
	}

	public void setPtPreparedDt(Date ptPreparedDt) {
		this.ptPreparedDt = ptPreparedDt;
	}

	public Integer getPtModifiedBy() {
		return this.ptModifiedBy;
	}

	public void setPtModifiedBy(Integer ptModifiedBy) {
		this.ptModifiedBy = ptModifiedBy;
	}

	public Date getPtModifiedDt() {
		return this.ptModifiedDt;
	}

	public void setPtModifiedDt(Date ptModifiedDt) {
		this.ptModifiedDt = ptModifiedDt;
	}

	public Integer getPtStatus() {
		return this.ptStatus;
	}

	public void setPtStatus(Integer ptStatus) {
		this.ptStatus = ptStatus;
	}

	public String getPtETerLimits() {
		return this.ptETerLimits;
	}

	public void setPtETerLimits(String ptETerLimits) {
		this.ptETerLimits = ptETerLimits;
	}

	public String getPtATerLimits() {
		return this.ptATerLimits;
	}

	public void setPtATerLimits(String ptATerLimits) {
		this.ptATerLimits = ptATerLimits;
	}

	public Set getTMasCovers() {
		return this.TMasCovers;
	}

	public void setTMasCovers(Set TMasCovers) {
		this.TMasCovers = TMasCovers;
	}

}
