package com.rsaame.pas.dao.model;

// Generated Feb 1, 2012 11:52:36 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TMasCover generated by hbm2java
 */
public class TMasCover implements java.io.Serializable {

	private TMasCoverId id;
	private TMasPolicyType TMasPolicyType;
	private String covADesc;
	private String covEDesc;
	private Boolean covPlusOrMinusFlag;
	private Short covUserCode;
	private Boolean covRiDisplayCode;
	private Byte covSitypeCode;
	private Short covMinAge;
	private Short covMaxAge;
	private Short covMinTerm;
	private Short covMaxTerm;
	private BigDecimal covMinSi;
	private BigDecimal covMaxSi;
	private String covEShortDesc;
	private Integer covPreparedBy;
	private Date covPreparedDt;
	private Integer covModifiedBy;
	private Date covModifiedDt;

	public TMasCover() {
	}

	public TMasCover(TMasCoverId id, TMasPolicyType TMasPolicyType) {
		this.id = id;
		this.TMasPolicyType = TMasPolicyType;
	}

	public TMasCover(TMasCoverId id, TMasPolicyType TMasPolicyType,
			String covADesc, String covEDesc, Boolean covPlusOrMinusFlag,
			Short covUserCode, Boolean covRiDisplayCode, Byte covSitypeCode,
			Short covMinAge, Short covMaxAge, Short covMinTerm,
			Short covMaxTerm, BigDecimal covMinSi, BigDecimal covMaxSi,
			String covEShortDesc, Integer covPreparedBy, Date covPreparedDt,
			Integer covModifiedBy, Date covModifiedDt) {
		this.id = id;
		this.TMasPolicyType = TMasPolicyType;
		this.covADesc = covADesc;
		this.covEDesc = covEDesc;
		this.covPlusOrMinusFlag = covPlusOrMinusFlag;
		this.covUserCode = covUserCode;
		this.covRiDisplayCode = covRiDisplayCode;
		this.covSitypeCode = covSitypeCode;
		this.covMinAge = covMinAge;
		this.covMaxAge = covMaxAge;
		this.covMinTerm = covMinTerm;
		this.covMaxTerm = covMaxTerm;
		this.covMinSi = covMinSi;
		this.covMaxSi = covMaxSi;
		this.covEShortDesc = covEShortDesc;
		this.covPreparedBy = covPreparedBy;
		this.covPreparedDt = covPreparedDt;
		this.covModifiedBy = covModifiedBy;
		this.covModifiedDt = covModifiedDt;
	}

	public TMasCoverId getId() {
		return this.id;
	}

	public void setId(TMasCoverId id) {
		this.id = id;
	}

	public TMasPolicyType getTMasPolicyType() {
		return this.TMasPolicyType;
	}

	public void setTMasPolicyType(TMasPolicyType TMasPolicyType) {
		this.TMasPolicyType = TMasPolicyType;
	}

	public String getCovADesc() {
		return this.covADesc;
	}

	public void setCovADesc(String covADesc) {
		this.covADesc = covADesc;
	}

	public String getCovEDesc() {
		return this.covEDesc;
	}

	public void setCovEDesc(String covEDesc) {
		this.covEDesc = covEDesc;
	}

	public Boolean getCovPlusOrMinusFlag() {
		return this.covPlusOrMinusFlag;
	}

	public void setCovPlusOrMinusFlag(Boolean covPlusOrMinusFlag) {
		this.covPlusOrMinusFlag = covPlusOrMinusFlag;
	}

	public Short getCovUserCode() {
		return this.covUserCode;
	}

	public void setCovUserCode(Short covUserCode) {
		this.covUserCode = covUserCode;
	}

	public Boolean getCovRiDisplayCode() {
		return this.covRiDisplayCode;
	}

	public void setCovRiDisplayCode(Boolean covRiDisplayCode) {
		this.covRiDisplayCode = covRiDisplayCode;
	}

	public Byte getCovSitypeCode() {
		return this.covSitypeCode;
	}

	public void setCovSitypeCode(Byte covSitypeCode) {
		this.covSitypeCode = covSitypeCode;
	}

	public Short getCovMinAge() {
		return this.covMinAge;
	}

	public void setCovMinAge(Short covMinAge) {
		this.covMinAge = covMinAge;
	}

	public Short getCovMaxAge() {
		return this.covMaxAge;
	}

	public void setCovMaxAge(Short covMaxAge) {
		this.covMaxAge = covMaxAge;
	}

	public Short getCovMinTerm() {
		return this.covMinTerm;
	}

	public void setCovMinTerm(Short covMinTerm) {
		this.covMinTerm = covMinTerm;
	}

	public Short getCovMaxTerm() {
		return this.covMaxTerm;
	}

	public void setCovMaxTerm(Short covMaxTerm) {
		this.covMaxTerm = covMaxTerm;
	}

	public BigDecimal getCovMinSi() {
		return this.covMinSi;
	}

	public void setCovMinSi(BigDecimal covMinSi) {
		this.covMinSi = covMinSi;
	}

	public BigDecimal getCovMaxSi() {
		return this.covMaxSi;
	}

	public void setCovMaxSi(BigDecimal covMaxSi) {
		this.covMaxSi = covMaxSi;
	}

	public String getCovEShortDesc() {
		return this.covEShortDesc;
	}

	public void setCovEShortDesc(String covEShortDesc) {
		this.covEShortDesc = covEShortDesc;
	}

	public Integer getCovPreparedBy() {
		return this.covPreparedBy;
	}

	public void setCovPreparedBy(Integer covPreparedBy) {
		this.covPreparedBy = covPreparedBy;
	}

	public Date getCovPreparedDt() {
		return this.covPreparedDt;
	}

	public void setCovPreparedDt(Date covPreparedDt) {
		this.covPreparedDt = covPreparedDt;
	}

	public Integer getCovModifiedBy() {
		return this.covModifiedBy;
	}

	public void setCovModifiedBy(Integer covModifiedBy) {
		this.covModifiedBy = covModifiedBy;
	}

	public Date getCovModifiedDt() {
		return this.covModifiedDt;
	}

	public void setCovModifiedDt(Date covModifiedDt) {
		this.covModifiedDt = covModifiedDt;
	}

}
