package com.rsaame.pas.dao.model;

import java.util.List;

// Generated May 7, 2013 6:08:32 PM by Hibernate Tools 3.4.0.CR1

/**
 * VProductConfigPas generated by hbm2java
 */
public class VMasProductConfigPasWrapper implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4893650722803705085L;
	
	private List<VMasProductConfigPas> vProductConfigPasList;

	public VMasProductConfigPasWrapper() {
	}

	public VMasProductConfigPasWrapper(List<VMasProductConfigPas> vProductConfigPasList) {
		this.vProductConfigPasList = vProductConfigPasList;
	}

	public List<VMasProductConfigPas> getVProductConfigPasList() {
		return this.vProductConfigPasList;
	}

	public void setVProductConfigPasList(List<VMasProductConfigPas> vProductConfigPasList) {
		this.vProductConfigPasList = vProductConfigPasList;
	}

}
