package com.rsaame.pas.dao.model;

// Generated Mar 4, 2014 6:14:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.mindtree.ruc.cmn.utils.Utils;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapper;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapperId;

/**
 * TTrnCoinsuranceQuo generated by hbm2java
 */
public class TTrnCoinsuranceQuo extends POJOWrapper implements java.io.Serializable {

	private static final long serialVersionUID = 1021201L;
	
	private TTrnCoinsuranceQuoId id;
	private BigDecimal coiPercentage;
	private String coiPolicyNo;
	private BigDecimal coiCommissionPerc;
	private Date coiValidityExpiryDate;
	private Boolean coiLeadFlag;
	private Integer coiPreparedBy;
	private Date coiPreparedDt;
	private Integer coiModifiedBy;
	private Date coiModifiedDt;
	private String coiEndtNo;
	private Long coiEndtId;
	

	public TTrnCoinsuranceQuo() {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	public TTrnCoinsuranceQuo(TTrnCoinsuranceQuoId id,
			Date coiValidityExpiryDate) {
		this.id = id;
		this.coiValidityExpiryDate = coiValidityExpiryDate;
	}

	public TTrnCoinsuranceQuo(TTrnCoinsuranceQuoId id,
			BigDecimal coiPercentage, String coiPolicyNo,
			BigDecimal coiCommissionPerc, 
			Date coiValidityExpiryDate, Boolean coiLeadFlag,
			Integer coiPreparedBy, Date coiPreparedDt, Integer coiModifiedBy,
			Date coiModifiedDt, String coiEndtNo, Long coiEndtId) {
		this.id = id;
		this.coiPercentage = coiPercentage;
		this.coiPolicyNo = coiPolicyNo;
		this.coiCommissionPerc = coiCommissionPerc;
		
		this.coiValidityExpiryDate = coiValidityExpiryDate;
		this.coiLeadFlag = coiLeadFlag;
		this.coiPreparedBy = coiPreparedBy;
		this.coiPreparedDt = coiPreparedDt;
		this.coiModifiedBy = coiModifiedBy;
		this.coiModifiedDt = coiModifiedDt;
		this.coiEndtNo = coiEndtNo;
		this.coiEndtId = coiEndtId;
	}

	public TTrnCoinsuranceQuoId getId() {
		return this.id;
	}

	public void setId(TTrnCoinsuranceQuoId id) {
		this.id = id;
	}

	public BigDecimal getCoiPercentage() {
		return this.coiPercentage;
	}

	public void setCoiPercentage(BigDecimal coiPercentage) {
		this.coiPercentage = coiPercentage;
	}

	public String getCoiPolicyNo() {
		return this.coiPolicyNo;
	}

	public void setCoiPolicyNo(String coiPolicyNo) {
		this.coiPolicyNo = coiPolicyNo;
	}

	public BigDecimal getCoiCommissionPerc() {
		return this.coiCommissionPerc;
	}

	public void setCoiCommissionPerc(BigDecimal coiCommissionPerc) {
		this.coiCommissionPerc = coiCommissionPerc;
	}

	public Date getCoiValidityExpiryDate() {
		return this.coiValidityExpiryDate;
	}

	public void setCoiValidityExpiryDate(Date coiValidityExpiryDate) {
		this.coiValidityExpiryDate = coiValidityExpiryDate;
	}

	public Boolean getCoiLeadFlag() {
		return this.coiLeadFlag;
	}

	public void setCoiLeadFlag(Boolean coiLeadFlag) {
		this.coiLeadFlag = coiLeadFlag;
	}

	public Integer getCoiPreparedBy() {
		return this.coiPreparedBy;
	}

	public void setCoiPreparedBy(Integer coiPreparedBy) {
		this.coiPreparedBy = coiPreparedBy;
	}

	public Date getCoiPreparedDt() {
		return this.coiPreparedDt;
	}

	public void setCoiPreparedDt(Date coiPreparedDt) {
		this.coiPreparedDt = coiPreparedDt;
	}

	public Integer getCoiModifiedBy() {
		return this.coiModifiedBy;
	}

	public void setCoiModifiedBy(Integer coiModifiedBy) {
		this.coiModifiedBy = coiModifiedBy;
	}

	public Date getCoiModifiedDt() {
		return this.coiModifiedDt;
	}

	public void setCoiModifiedDt(Date coiModifiedDt) {
		this.coiModifiedDt = coiModifiedDt;
	}

	public String getCoiEndtNo() {
		return this.coiEndtNo;
	}

	public void setCoiEndtNo(String coiEndtNo) {
		this.coiEndtNo = coiEndtNo;
	}

	public Long getCoiEndtId() {
		return coiEndtId;
	}

	public void setCoiEndtId(Long coiEndtId) {
		this.coiEndtId = coiEndtId;
	}

	

	@Override
	public void setPOJOWrapperId(POJOWrapperId id) {
		setId((TTrnCoinsuranceQuoId)id);
		
	}

	@Override
	public POJOWrapperId getPOJOWrapperId() {
		return getId();
	}

	@Override
	public void setStatus(int status) {
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	@Override
	public void setEndtId(Long endtId) {
		setCoiEndtId(endtId);
	}

	@Override
	public void setEndtNo(Long endtNo) {
		setCoiEndtNo(endtNo.toString());
		
	}

	@Override
	public void setValidityStartDate(Date vsd) {
		if(!Utils.isEmpty(getId())) getId().setCoiValidityStartDate(vsd);
	}

	@Override
	public void setValidityExpiryDate(Date ved) {
		setCoiValidityExpiryDate(ved);
		
	}

	@Override
	public void setPreparedBy(Integer preparedBy) {
		setCoiPreparedBy(preparedBy);
		
	}

	@Override
	public void setPreparedDt(Date preparedDt) {
		setCoiPreparedDt(preparedDt);
	}

	@Override
	public void setModifiedBy(Integer modifiedBy) {
		setCoiModifiedBy(modifiedBy);
	}

	@Override
	public void setModifiedDt(Date modifiedDt) {
		setCoiModifiedDt(modifiedDt);
		
	}

	@Override
	public Integer getPreparedBy() {

		return getCoiPreparedBy();
	}

	@Override
	public Date getPreparedDt() {
		return getCoiPreparedDt();
	}

	@Override
	public Integer getModifiedBy() {
		return getCoiModifiedBy();
	}

	@Override
	public Date getModifiedDt() {
		return getCoiModifiedDt();
	}

}
