package com.rsaame.pas.dao.model;

import java.util.Date;

import com.rsaame.pas.cmn.pojo.POJOId;

// Generated Jul 10, 2012 6:11:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * TTrnMarineTransitId generated by hbm2java
 */
public class TTrnMarineTransitQuoId implements java.io.Serializable, POJOId {

    private static final long serialVersionUID = 1L;
    private long mtPolicyId;
    private long mtEndtId;
    private long mtDeclarationId;
    private int mtSerialNo;
    private Date mtValidityStartDate;

    public TTrnMarineTransitQuoId() {
    }

    public TTrnMarineTransitQuoId(long mtPolicyId, long mtEndtId,
	    long mtDeclarationId, int mtSerialNo,Date mtValidityStartDate) {
	this.mtPolicyId = mtPolicyId;
	this.mtEndtId = mtEndtId;
	this.mtDeclarationId = mtDeclarationId;
	this.mtSerialNo = mtSerialNo;
	this.mtValidityStartDate = mtValidityStartDate;
    }

    public long getMtPolicyId() {
	return this.mtPolicyId;
    }

    public void setMtPolicyId(long mtPolicyId) {
	this.mtPolicyId = mtPolicyId;
    }

    public long getMtEndtId() {
	return this.mtEndtId;
    }

    public void setMtEndtId(long mtEndtId) {
	this.mtEndtId = mtEndtId;
    }

    public long getMtDeclarationId() {
	return this.mtDeclarationId;
    }

    public void setMtDeclarationId(long mtDeclarationId) {
	this.mtDeclarationId = mtDeclarationId;
    }

    public int getMtSerialNo() {
	return this.mtSerialNo;
    }

    public void setMtSerialNo(int mtSerialNo) {
	this.mtSerialNo = mtSerialNo;
    }

    public Date getMtValidityStartDate() {
	return this.mtValidityStartDate;
    }

    public void setMtValidityStartDate(Date mtValidityStartDate) {
	this.mtValidityStartDate = mtValidityStartDate;
    }

    @Override
    public int hashCode() {
	final int prime = 37;
	int result = 17;
	result = prime * result
		+ (int) (mtDeclarationId ^ (mtDeclarationId >>> 32));
	result = prime * result + (int) (mtEndtId ^ (mtEndtId >>> 32));
	result = prime * result + (int) (mtPolicyId ^ (mtPolicyId >>> 32));
	result = prime * result + mtSerialNo;
	result = prime
		* result
		+ ((mtValidityStartDate == null) ? 0 : mtValidityStartDate
			.hashCode());
	return result;
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (obj == null)
	    return false;
	if (getClass() != obj.getClass())
	    return false;
	TTrnMarineTransitQuoId other = (TTrnMarineTransitQuoId) obj;
	if (mtDeclarationId != other.mtDeclarationId)
	    return false;
	if (mtEndtId != other.mtEndtId)
	    return false;
	if (mtPolicyId != other.mtPolicyId)
	    return false;
	if (mtSerialNo != other.mtSerialNo)
	    return false;
	if (mtValidityStartDate == null) {
	    if (other.mtValidityStartDate != null)
		return false;
	} else if (!mtValidityStartDate.equals(other.mtValidityStartDate))
	    return false;
	return true;
    }
    
    

}
