package com.rsaame.pas.dao.model;

// Generated Sep 27, 2012 7:34:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TMasBroadcastMsg generated by hbm2java
 */
public class TMasBroadcastMsg implements java.io.Serializable {

	private Long brdMsgId;
	private Integer brdMsgDistChnl;
	private Short brdMsgBrkId;
	private Long brdMsgAgntId;
	private Integer brdMsgUsrId;
	private Integer brdMsgSchCode;
	private Integer brdLocCode;
	private String brdMsgText;
	private Date brdMsgEffDate;
	private Date brdMsgExpDate;
	private Character brdRsaUsersFlag;
	private Short brdMsgCategory;
	private Boolean brdSystemId;
	private Integer brdPreparedBy;
	private Date brdPreparedDt;
	private Integer brdModifiedBy;
	private Date brdModifiedDt;

	public TMasBroadcastMsg() {
	}

	public TMasBroadcastMsg(Long brdMsgId, Integer brdMsgDistChnl,
			Short brdMsgBrkId, Long brdMsgAgntId, Integer brdMsgUsrId,
			Integer brdMsgSchCode, Integer brdLocCode, String brdMsgText,
			Date brdMsgEffDate, Date brdMsgExpDate, Character brdRsaUsersFlag,
			Short brdMsgCategory, Boolean brdSystemId, Integer brdPreparedBy,
			Date brdPreparedDt, Integer brdModifiedBy, Date brdModifiedDt) {
		this.brdMsgId = brdMsgId;
		this.brdMsgDistChnl = brdMsgDistChnl;
		this.brdMsgBrkId = brdMsgBrkId;
		this.brdMsgAgntId = brdMsgAgntId;
		this.brdMsgUsrId = brdMsgUsrId;
		this.brdMsgSchCode = brdMsgSchCode;
		this.brdLocCode = brdLocCode;
		this.brdMsgText = brdMsgText;
		this.brdMsgEffDate = brdMsgEffDate;
		this.brdMsgExpDate = brdMsgExpDate;
		this.brdRsaUsersFlag = brdRsaUsersFlag;
		this.brdMsgCategory = brdMsgCategory;
		this.brdSystemId = brdSystemId;
		this.brdPreparedBy = brdPreparedBy;
		this.brdPreparedDt = brdPreparedDt;
		this.brdModifiedBy = brdModifiedBy;
		this.brdModifiedDt = brdModifiedDt;
	}

	public Long getBrdMsgId() {
		return this.brdMsgId;
	}

	public void setBrdMsgId(Long brdMsgId) {
		this.brdMsgId = brdMsgId;
	}

	public Integer getBrdMsgDistChnl() {
		return this.brdMsgDistChnl;
	}

	public void setBrdMsgDistChnl(Integer brdMsgDistChnl) {
		this.brdMsgDistChnl = brdMsgDistChnl;
	}

	public Short getBrdMsgBrkId() {
		return this.brdMsgBrkId;
	}

	public void setBrdMsgBrkId(Short brdMsgBrkId) {
		this.brdMsgBrkId = brdMsgBrkId;
	}

	public Long getBrdMsgAgntId() {
		return this.brdMsgAgntId;
	}

	public void setBrdMsgAgntId(Long brdMsgAgntId) {
		this.brdMsgAgntId = brdMsgAgntId;
	}

	public Integer getBrdMsgUsrId() {
		return this.brdMsgUsrId;
	}

	public void setBrdMsgUsrId(Integer brdMsgUsrId) {
		this.brdMsgUsrId = brdMsgUsrId;
	}

	public Integer getBrdMsgSchCode() {
		return this.brdMsgSchCode;
	}

	public void setBrdMsgSchCode(Integer brdMsgSchCode) {
		this.brdMsgSchCode = brdMsgSchCode;
	}

	public Integer getBrdLocCode() {
		return this.brdLocCode;
	}

	public void setBrdLocCode(Integer brdLocCode) {
		this.brdLocCode = brdLocCode;
	}

	public String getBrdMsgText() {
		return this.brdMsgText;
	}

	public void setBrdMsgText(String brdMsgText) {
		this.brdMsgText = brdMsgText;
	}

	public Date getBrdMsgEffDate() {
		return this.brdMsgEffDate;
	}

	public void setBrdMsgEffDate(Date brdMsgEffDate) {
		this.brdMsgEffDate = brdMsgEffDate;
	}

	public Date getBrdMsgExpDate() {
		return this.brdMsgExpDate;
	}

	public void setBrdMsgExpDate(Date brdMsgExpDate) {
		this.brdMsgExpDate = brdMsgExpDate;
	}

	public Character getBrdRsaUsersFlag() {
		return this.brdRsaUsersFlag;
	}

	public void setBrdRsaUsersFlag(Character brdRsaUsersFlag) {
		this.brdRsaUsersFlag = brdRsaUsersFlag;
	}

	public Short getBrdMsgCategory() {
		return this.brdMsgCategory;
	}

	public void setBrdMsgCategory(Short brdMsgCategory) {
		this.brdMsgCategory = brdMsgCategory;
	}

	public Boolean getBrdSystemId() {
		return this.brdSystemId;
	}

	public void setBrdSystemId(Boolean brdSystemId) {
		this.brdSystemId = brdSystemId;
	}

	public Integer getBrdPreparedBy() {
		return this.brdPreparedBy;
	}

	public void setBrdPreparedBy(Integer brdPreparedBy) {
		this.brdPreparedBy = brdPreparedBy;
	}

	public Date getBrdPreparedDt() {
		return this.brdPreparedDt;
	}

	public void setBrdPreparedDt(Date brdPreparedDt) {
		this.brdPreparedDt = brdPreparedDt;
	}

	public Integer getBrdModifiedBy() {
		return this.brdModifiedBy;
	}

	public void setBrdModifiedBy(Integer brdModifiedBy) {
		this.brdModifiedBy = brdModifiedBy;
	}

	public Date getBrdModifiedDt() {
		return this.brdModifiedDt;
	}

	public void setBrdModifiedDt(Date brdModifiedDt) {
		this.brdModifiedDt = brdModifiedDt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMasBroadcastMsg))
			return false;
		TMasBroadcastMsg castOther = (TMasBroadcastMsg) other;

		return ((this.getBrdMsgId() == castOther.getBrdMsgId()) || (this
				.getBrdMsgId() != null && castOther.getBrdMsgId() != null && this
				.getBrdMsgId().equals(castOther.getBrdMsgId())))
				&& ((this.getBrdMsgDistChnl() == castOther.getBrdMsgDistChnl()) || (this
						.getBrdMsgDistChnl() != null
						&& castOther.getBrdMsgDistChnl() != null && this
						.getBrdMsgDistChnl().equals(
								castOther.getBrdMsgDistChnl())))
				&& ((this.getBrdMsgBrkId() == castOther.getBrdMsgBrkId()) || (this
						.getBrdMsgBrkId() != null
						&& castOther.getBrdMsgBrkId() != null && this
						.getBrdMsgBrkId().equals(castOther.getBrdMsgBrkId())))
				&& ((this.getBrdMsgAgntId() == castOther.getBrdMsgAgntId()) || (this
						.getBrdMsgAgntId() != null
						&& castOther.getBrdMsgAgntId() != null && this
						.getBrdMsgAgntId().equals(castOther.getBrdMsgAgntId())))
				&& ((this.getBrdMsgUsrId() == castOther.getBrdMsgUsrId()) || (this
						.getBrdMsgUsrId() != null
						&& castOther.getBrdMsgUsrId() != null && this
						.getBrdMsgUsrId().equals(castOther.getBrdMsgUsrId())))
				&& ((this.getBrdMsgSchCode() == castOther.getBrdMsgSchCode()) || (this
						.getBrdMsgSchCode() != null
						&& castOther.getBrdMsgSchCode() != null && this
						.getBrdMsgSchCode()
						.equals(castOther.getBrdMsgSchCode())))
				&& ((this.getBrdLocCode() == castOther.getBrdLocCode()) || (this
						.getBrdLocCode() != null
						&& castOther.getBrdLocCode() != null && this
						.getBrdLocCode().equals(castOther.getBrdLocCode())))
				&& ((this.getBrdMsgText() == castOther.getBrdMsgText()) || (this
						.getBrdMsgText() != null
						&& castOther.getBrdMsgText() != null && this
						.getBrdMsgText().equals(castOther.getBrdMsgText())))
				&& ((this.getBrdMsgEffDate() == castOther.getBrdMsgEffDate()) || (this
						.getBrdMsgEffDate() != null
						&& castOther.getBrdMsgEffDate() != null && this
						.getBrdMsgEffDate()
						.equals(castOther.getBrdMsgEffDate())))
				&& ((this.getBrdMsgExpDate() == castOther.getBrdMsgExpDate()) || (this
						.getBrdMsgExpDate() != null
						&& castOther.getBrdMsgExpDate() != null && this
						.getBrdMsgExpDate()
						.equals(castOther.getBrdMsgExpDate())))
				&& ((this.getBrdRsaUsersFlag() == castOther
						.getBrdRsaUsersFlag()) || (this.getBrdRsaUsersFlag() != null
						&& castOther.getBrdRsaUsersFlag() != null && this
						.getBrdRsaUsersFlag().equals(
								castOther.getBrdRsaUsersFlag())))
				&& ((this.getBrdMsgCategory() == castOther.getBrdMsgCategory()) || (this
						.getBrdMsgCategory() != null
						&& castOther.getBrdMsgCategory() != null && this
						.getBrdMsgCategory().equals(
								castOther.getBrdMsgCategory())))
				&& ((this.getBrdSystemId() == castOther.getBrdSystemId()) || (this
						.getBrdSystemId() != null
						&& castOther.getBrdSystemId() != null && this
						.getBrdSystemId().equals(castOther.getBrdSystemId())))
				&& ((this.getBrdPreparedBy() == castOther.getBrdPreparedBy()) || (this
						.getBrdPreparedBy() != null
						&& castOther.getBrdPreparedBy() != null && this
						.getBrdPreparedBy()
						.equals(castOther.getBrdPreparedBy())))
				&& ((this.getBrdPreparedDt() == castOther.getBrdPreparedDt()) || (this
						.getBrdPreparedDt() != null
						&& castOther.getBrdPreparedDt() != null && this
						.getBrdPreparedDt()
						.equals(castOther.getBrdPreparedDt())))
				&& ((this.getBrdModifiedBy() == castOther.getBrdModifiedBy()) || (this
						.getBrdModifiedBy() != null
						&& castOther.getBrdModifiedBy() != null && this
						.getBrdModifiedBy()
						.equals(castOther.getBrdModifiedBy())))
				&& ((this.getBrdModifiedDt() == castOther.getBrdModifiedDt()) || (this
						.getBrdModifiedDt() != null
						&& castOther.getBrdModifiedDt() != null && this
						.getBrdModifiedDt()
						.equals(castOther.getBrdModifiedDt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBrdMsgId() == null ? 0 : this.getBrdMsgId().hashCode());
		result = 37
				* result
				+ (getBrdMsgDistChnl() == null ? 0 : this.getBrdMsgDistChnl()
						.hashCode());
		result = 37
				* result
				+ (getBrdMsgBrkId() == null ? 0 : this.getBrdMsgBrkId()
						.hashCode());
		result = 37
				* result
				+ (getBrdMsgAgntId() == null ? 0 : this.getBrdMsgAgntId()
						.hashCode());
		result = 37
				* result
				+ (getBrdMsgUsrId() == null ? 0 : this.getBrdMsgUsrId()
						.hashCode());
		result = 37
				* result
				+ (getBrdMsgSchCode() == null ? 0 : this.getBrdMsgSchCode()
						.hashCode());
		result = 37
				* result
				+ (getBrdLocCode() == null ? 0 : this.getBrdLocCode()
						.hashCode());
		result = 37
				* result
				+ (getBrdMsgText() == null ? 0 : this.getBrdMsgText()
						.hashCode());
		result = 37
				* result
				+ (getBrdMsgEffDate() == null ? 0 : this.getBrdMsgEffDate()
						.hashCode());
		result = 37
				* result
				+ (getBrdMsgExpDate() == null ? 0 : this.getBrdMsgExpDate()
						.hashCode());
		result = 37
				* result
				+ (getBrdRsaUsersFlag() == null ? 0 : this.getBrdRsaUsersFlag()
						.hashCode());
		result = 37
				* result
				+ (getBrdMsgCategory() == null ? 0 : this.getBrdMsgCategory()
						.hashCode());
		result = 37
				* result
				+ (getBrdSystemId() == null ? 0 : this.getBrdSystemId()
						.hashCode());
		result = 37
				* result
				+ (getBrdPreparedBy() == null ? 0 : this.getBrdPreparedBy()
						.hashCode());
		result = 37
				* result
				+ (getBrdPreparedDt() == null ? 0 : this.getBrdPreparedDt()
						.hashCode());
		result = 37
				* result
				+ (getBrdModifiedBy() == null ? 0 : this.getBrdModifiedBy()
						.hashCode());
		result = 37
				* result
				+ (getBrdModifiedDt() == null ? 0 : this.getBrdModifiedDt()
						.hashCode());
		return result;
	}

}
