package com.rsaame.pas.dao.model;

// Generated Feb 3, 2012 11:21:12 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TMasProductCriteriaId generated by hbm2java
 */
public class TMasProductCriteriaId implements java.io.Serializable {

	private Short pcrSchCode;
	private Integer pcrTarCode;
	private Integer pcrCriCode;
	private Integer pcrRtRskCode;
	private Integer pcrRtCode;
	
	public TMasProductCriteriaId() {
	}

	public TMasProductCriteriaId(Short pcrSchCode, Integer pcrTarCode,
			Integer pcrCriCode, Integer pcrRtCode, Integer pcrRtRskCode,
			String pcrEDesc, String pcrADesc, BigDecimal pcrMinVal,
			BigDecimal pcrMaxVal, Date pcrEffectiveDate, Date pcrExpiryDate,
			Boolean pcrStatus, Integer pcrPreparedBy, Date pcrPreparedDt,
			Integer pcrModifiedBy, Date pcrModifiedDt) {
		this.pcrSchCode = pcrSchCode;
		this.pcrTarCode = pcrTarCode;
		this.pcrCriCode = pcrCriCode;
		this.pcrRtRskCode = pcrRtRskCode;
	
	}

	public Short getPcrSchCode() {
		return this.pcrSchCode;
	}

	public void setPcrSchCode(Short pcrSchCode) {
		this.pcrSchCode = pcrSchCode;
	}

	public Integer getPcrTarCode() {
		return this.pcrTarCode;
	}

	public void setPcrTarCode(Integer pcrTarCode) {
		this.pcrTarCode = pcrTarCode;
	}

	public Integer getPcrCriCode() {
		return this.pcrCriCode;
	}

	public void setPcrCriCode(Integer pcrCriCode) {
		this.pcrCriCode = pcrCriCode;
	}

	public Integer getPcrRtRskCode() {
		return pcrRtRskCode;
	}

	public void setPcrRtRskCode(Integer pcrRtRskCode) {
		this.pcrRtRskCode = pcrRtRskCode;
	}

	
	/**
	 * @return the pcrRtCode
	 */
	public Integer getPcrRtCode() {
		return pcrRtCode;
	}

	/**
	 * @param pcrRtCode the pcrRtCode to set
	 */
	public void setPcrRtCode(Integer pcrRtCode) {
		this.pcrRtCode = pcrRtCode;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((pcrCriCode == null) ? 0 : pcrCriCode.hashCode());
		result = prime * result
				+ ((pcrRtCode == null) ? 0 : pcrRtCode.hashCode());
		result = prime * result
				+ ((pcrRtRskCode == null) ? 0 : pcrRtRskCode.hashCode());
		result = prime * result
				+ ((pcrSchCode == null) ? 0 : pcrSchCode.hashCode());
		result = prime * result
				+ ((pcrTarCode == null) ? 0 : pcrTarCode.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TMasProductCriteriaId other = (TMasProductCriteriaId) obj;
		if (pcrCriCode == null) {
			if (other.pcrCriCode != null)
				return false;
		} else if (!pcrCriCode.equals(other.pcrCriCode))
			return false;
		if (pcrRtCode == null) {
			if (other.pcrRtCode != null)
				return false;
		} else if (!pcrRtCode.equals(other.pcrRtCode))
			return false;
		if (pcrRtRskCode == null) {
			if (other.pcrRtRskCode != null)
				return false;
		} else if (!pcrRtRskCode.equals(other.pcrRtRskCode))
			return false;
		if (pcrSchCode == null) {
			if (other.pcrSchCode != null)
				return false;
		} else if (!pcrSchCode.equals(other.pcrSchCode))
			return false;
		if (pcrTarCode == null) {
			if (other.pcrTarCode != null)
				return false;
		} else if (!pcrTarCode.equals(other.pcrTarCode))
			return false;
		return true;
	}

	
	

}
