package com.rsaame.pas.dao.model;

// Generated Jul 3, 2013 6:48:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TTrnSms generated by hbm2java
 */
public class TTrnSms implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private long trnSmsId;
	private long trnSmsPolicyId;
	private long trnSmsEndtId;
	private Short trnSmsLocCode;
	private String trnSmsMode;
	private byte trnSmsLevel;
	private Byte trnSmsStatus;
	private String trnSmsGsmNo;
	private String trnSmsEText;
	private String trnSmsAText;
	private String trnSmsLangType;
	private Date trnSmsSubDate;
	private Date trnSmsSentDate;
	private String trnSmsRemarks;
	private String trnSmsSubmittedBy;

	public TTrnSms() {
	}

	public TTrnSms(long trnSmsId, long trnSmsPolicyId, long trnSmsEndtId,
			String trnSmsMode, byte trnSmsLevel) {
		this.trnSmsId = trnSmsId;
		this.trnSmsPolicyId = trnSmsPolicyId;
		this.trnSmsEndtId = trnSmsEndtId;
		this.trnSmsMode = trnSmsMode;
		this.trnSmsLevel = trnSmsLevel;
	}

	public TTrnSms(long trnSmsId, long trnSmsPolicyId, long trnSmsEndtId,
			Short trnSmsLocCode, String trnSmsMode, byte trnSmsLevel,
			Byte trnSmsStatus, String trnSmsGsmNo, String trnSmsEText,
			String trnSmsAText, String trnSmsLangType, Date trnSmsSubDate,
			Date trnSmsSentDate, String trnSmsRemarks, String trnSmsSubmittedBy) {
		this.trnSmsId = trnSmsId;
		this.trnSmsPolicyId = trnSmsPolicyId;
		this.trnSmsEndtId = trnSmsEndtId;
		this.trnSmsLocCode = trnSmsLocCode;
		this.trnSmsMode = trnSmsMode;
		this.trnSmsLevel = trnSmsLevel;
		this.trnSmsStatus = trnSmsStatus;
		this.trnSmsGsmNo = trnSmsGsmNo;
		this.trnSmsEText = trnSmsEText;
		this.trnSmsAText = trnSmsAText;
		this.trnSmsLangType = trnSmsLangType;
		this.trnSmsSubDate = trnSmsSubDate;
		this.trnSmsSentDate = trnSmsSentDate;
		this.trnSmsRemarks = trnSmsRemarks;
		this.trnSmsSubmittedBy = trnSmsSubmittedBy;
	}

	public long getTrnSmsId() {
		return this.trnSmsId;
	}

	public void setTrnSmsId(long trnSmsId) {
		this.trnSmsId = trnSmsId;
	}

	public long getTrnSmsPolicyId() {
		return this.trnSmsPolicyId;
	}

	public void setTrnSmsPolicyId(long trnSmsPolicyId) {
		this.trnSmsPolicyId = trnSmsPolicyId;
	}

	public long getTrnSmsEndtId() {
		return this.trnSmsEndtId;
	}

	public void setTrnSmsEndtId(long trnSmsEndtId) {
		this.trnSmsEndtId = trnSmsEndtId;
	}

	public Short getTrnSmsLocCode() {
		return this.trnSmsLocCode;
	}

	public void setTrnSmsLocCode(Short trnSmsLocCode) {
		this.trnSmsLocCode = trnSmsLocCode;
	}

	public String getTrnSmsMode() {
		return this.trnSmsMode;
	}

	public void setTrnSmsMode(String trnSmsMode) {
		this.trnSmsMode = trnSmsMode;
	}

	public byte getTrnSmsLevel() {
		return this.trnSmsLevel;
	}

	public void setTrnSmsLevel(byte trnSmsLevel) {
		this.trnSmsLevel = trnSmsLevel;
	}

	public Byte getTrnSmsStatus() {
		return this.trnSmsStatus;
	}

	public void setTrnSmsStatus(Byte trnSmsStatus) {
		this.trnSmsStatus = trnSmsStatus;
	}

	public String getTrnSmsGsmNo() {
		return this.trnSmsGsmNo;
	}

	public void setTrnSmsGsmNo(String trnSmsGsmNo) {
		this.trnSmsGsmNo = trnSmsGsmNo;
	}

	public String getTrnSmsEText() {
		return this.trnSmsEText;
	}

	public void setTrnSmsEText(String trnSmsEText) {
		this.trnSmsEText = trnSmsEText;
	}

	public String getTrnSmsAText() {
		return this.trnSmsAText;
	}

	public void setTrnSmsAText(String trnSmsAText) {
		this.trnSmsAText = trnSmsAText;
	}

	public String getTrnSmsLangType() {
		return this.trnSmsLangType;
	}

	public void setTrnSmsLangType(String trnSmsLangType) {
		this.trnSmsLangType = trnSmsLangType;
	}

	public Date getTrnSmsSubDate() {
		return this.trnSmsSubDate;
	}

	public void setTrnSmsSubDate(Date trnSmsSubDate) {
		this.trnSmsSubDate = trnSmsSubDate;
	}

	public Date getTrnSmsSentDate() {
		return this.trnSmsSentDate;
	}

	public void setTrnSmsSentDate(Date trnSmsSentDate) {
		this.trnSmsSentDate = trnSmsSentDate;
	}

	public String getTrnSmsRemarks() {
		return this.trnSmsRemarks;
	}

	public void setTrnSmsRemarks(String trnSmsRemarks) {
		this.trnSmsRemarks = trnSmsRemarks;
	}

	public String getTrnSmsSubmittedBy() {
		return this.trnSmsSubmittedBy;
	}

	public void setTrnSmsSubmittedBy(String trnSmsSubmittedBy) {
		this.trnSmsSubmittedBy = trnSmsSubmittedBy;
	}

}
