package com.rsaame.pas.dao.model;

// Generated Oct 23, 2012 3:45:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * TTrnPrintBatchPasId generated by hbm2java
 */
public class TTrnPrintBatchPasId implements java.io.Serializable {

	private long prnBatchReqId;
	private long polLinkingId;
	private long policyId;

	public TTrnPrintBatchPasId() {
	}	

	/**
	 * @param prnBatchReqId
	 * @param polLinkingId
	 * @param policyId
	 */
	public TTrnPrintBatchPasId(long prnBatchReqId, long polLinkingId,
			long policyId) {
		this.prnBatchReqId = prnBatchReqId;
		this.polLinkingId = polLinkingId;
		this.policyId = policyId;
	}



	public long getPrnBatchReqId() {
		return this.prnBatchReqId;
	}

	public void setPrnBatchReqId(long prnBatchReqId) {
		this.prnBatchReqId = prnBatchReqId;
	}

	public long getPolLinkingId() {
		return this.polLinkingId;
	}

	public void setPolLinkingId(long polLinkingId) {
		this.polLinkingId = polLinkingId;
	}	

	/**
	 * @return the policyId
	 */
	public long getPolicyId() {
		return policyId;
	}

	/**
	 * @param policyId the policyId to set
	 */
	public void setPolicyId(long policyId) {
		this.policyId = policyId;
	}
	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTrnPrintBatchPasId))
			return false;
		TTrnPrintBatchPasId castOther = (TTrnPrintBatchPasId) other;

		return (this.getPrnBatchReqId() == castOther.getPrnBatchReqId())
				&& (this.getPolLinkingId() == castOther.getPolLinkingId()) && (this.getPolicyId() == castOther.getPolicyId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int)this.getPrnBatchReqId();
		result = 37 * result + (int) this.getPolLinkingId();
		result = 37 * result + (int) this.getPolicyId();
		return result;
	}
	
}
