package com.rsaame.pas.dao.model;

// Generated Jun 26, 2012 3:09:02 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.mindtree.ruc.cmn.utils.Utils;
import com.rsaame.pas.cmn.pojo.POJOId;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapper;
import com.rsaame.pas.cmn.pojo.wrapper.POJOWrapperId;

/**
 * TTrnGaccPersonQuo generated by hbm2java
 */
public class TTrnGaccPersonQuo extends POJOWrapper  implements java.io.Serializable {

	private static final long serialVersionUID = -4110217945093873538L;
	private TTrnGaccPersonQuoId id;
	private Long gprPolicyId;
	private Long gprBasicRiskId;
	private Long gprRskCode;
	private Long gprRtCode;
	private Long gprRcCode;
	private String gprAName;
	private String gprEName;
	private String gprAAddress1;
	private String gprEAddress1;
	private String gprAAddress2;
	private String gprEAddress2;
	private String gprAAddress3;
	private String gprEAddress3;
	private String gprZip;
	private Long gprTelephone;
	private Long gprFax;
	private Long gprGsm;
	private String gprEmail;
	private Short gprAge;
	private Short gprOcCode;
	private BigDecimal gprSumInsured;
	private Byte gprStatus;
	private Date gprValidityExpiryDate;
	private Long gprEndtId;
	private Integer gprRiRskCode;
	private Integer gprBasicRskCode;
	private Character gprGender;
	private Byte gprRelation;
	private Date gprRetroactiveDate;
	private BigDecimal gprSalary;
	private Integer gprPreparedBy;
	private Date gprPreparedDt;
	private Integer gprModifiedBy;
	private Date gprModifiedDt;
	private Date gprStartDate;
	private Date gprEndDate;
	private Date gprDateOfBirth;
	private String gprDescription;
	private String gprPersonId;
	private Date gprDateOfJoining;
	private Long gprBldId;
	private Long gprTradeGroup;
	private BigDecimal gprAgrLmt;
	private Short gprNtyEDesc;

	public TTrnGaccPersonQuo() {
	}

	public TTrnGaccPersonQuo(TTrnGaccPersonQuoId id, Date gprValidityExpiryDate) {
		this.id = id;
		this.gprValidityExpiryDate = gprValidityExpiryDate;
	}

	public TTrnGaccPersonQuo(TTrnGaccPersonQuoId id, Long gprPolicyId,
			Long gprBasicRiskId, Long gprRskCode, Long gprRtCode,
			Long gprRcCode, String gprAName, String gprEName,
			String gprAAddress1, String gprEAddress1, String gprAAddress2,
			String gprEAddress2, String gprAAddress3, String gprEAddress3,
			String gprZip, Long gprTelephone, Long gprFax, Long gprGsm,
			String gprEmail, Short gprAge, Short gprOcCode,
			BigDecimal gprSumInsured, Byte gprStatus,
			Date gprValidityExpiryDate, Long gprEndtId, Integer gprRiRskCode,
			Integer gprBasicRskCode, Character gprGender, Byte gprRelation,
			Date gprRetroactiveDate, BigDecimal gprSalary,
			Integer gprPreparedBy, Date gprPreparedDt, Integer gprModifiedBy,
			Date gprModifiedDt, Date gprStartDate, Date gprEndDate,
			Date gprDateOfBirth, String gprDescription, String gprPersonId,
			Date gprDateOfJoining, Long gprBldId, Long gprTradeGroup,
			BigDecimal gprAgrLmt, Short gprNtyEDesc) {
		this.id = id;
		this.gprPolicyId = gprPolicyId;
		this.gprBasicRiskId = gprBasicRiskId;
		this.gprRskCode = gprRskCode;
		this.gprRtCode = gprRtCode;
		this.gprRcCode = gprRcCode;
		this.gprAName = gprAName;
		this.gprEName = gprEName;
		this.gprAAddress1 = gprAAddress1;
		this.gprEAddress1 = gprEAddress1;
		this.gprAAddress2 = gprAAddress2;
		this.gprEAddress2 = gprEAddress2;
		this.gprAAddress3 = gprAAddress3;
		this.gprEAddress3 = gprEAddress3;
		this.gprZip = gprZip;
		this.gprTelephone = gprTelephone;
		this.gprFax = gprFax;
		this.gprGsm = gprGsm;
		this.gprEmail = gprEmail;
		this.gprAge = gprAge;
		this.gprOcCode = gprOcCode;
		this.gprSumInsured = gprSumInsured;
		this.gprStatus = gprStatus;
		this.gprValidityExpiryDate = gprValidityExpiryDate;
		this.gprEndtId = gprEndtId;
		this.gprRiRskCode = gprRiRskCode;
		this.gprBasicRskCode = gprBasicRskCode;
		this.gprGender = gprGender;
		this.gprRelation = gprRelation;
		this.gprRetroactiveDate = gprRetroactiveDate;
		this.gprSalary = gprSalary;
		this.gprPreparedBy = gprPreparedBy;
		this.gprPreparedDt = gprPreparedDt;
		this.gprModifiedBy = gprModifiedBy;
		this.gprModifiedDt = gprModifiedDt;
		this.gprStartDate = gprStartDate;
		this.gprEndDate = gprEndDate;
		this.gprDateOfBirth = gprDateOfBirth;
		this.gprDescription = gprDescription;
		this.gprPersonId = gprPersonId;
		this.gprDateOfJoining = gprDateOfJoining;
		this.gprBldId = gprBldId;
		this.gprTradeGroup = gprTradeGroup;
		this.gprAgrLmt = gprAgrLmt;
		this.gprNtyEDesc = gprNtyEDesc;
	}

	public TTrnGaccPersonQuoId getId() {
		return this.id;
	}

	public void setId(TTrnGaccPersonQuoId id) {
		this.id = id;
	}

	public Long getGprPolicyId() {
		return this.gprPolicyId;
	}

	public void setGprPolicyId(Long gprPolicyId) {
		this.gprPolicyId = gprPolicyId;
	}

	public Long getGprBasicRiskId() {
		return this.gprBasicRiskId;
	}

	public void setGprBasicRiskId(Long gprBasicRiskId) {
		this.gprBasicRiskId = gprBasicRiskId;
	}

	public Long getGprRskCode() {
		return this.gprRskCode;
	}

	public void setGprRskCode(Long gprRskCode) {
		this.gprRskCode = gprRskCode;
	}

	public Long getGprRtCode() {
		return this.gprRtCode;
	}

	public void setGprRtCode(Long gprRtCode) {
		this.gprRtCode = gprRtCode;
	}

	public Long getGprRcCode() {
		return this.gprRcCode;
	}

	public void setGprRcCode(Long gprRcCode) {
		this.gprRcCode = gprRcCode;
	}

	public String getGprAName() {
		return this.gprAName;
	}

	public void setGprAName(String gprAName) {
		this.gprAName = gprAName;
	}

	public String getGprEName() {
		return this.gprEName;
	}

	public void setGprEName(String gprEName) {
		this.gprEName = gprEName;
	}

	public String getGprAAddress1() {
		return this.gprAAddress1;
	}

	public void setGprAAddress1(String gprAAddress1) {
		this.gprAAddress1 = gprAAddress1;
	}

	public String getGprEAddress1() {
		return this.gprEAddress1;
	}

	public void setGprEAddress1(String gprEAddress1) {
		this.gprEAddress1 = gprEAddress1;
	}

	public String getGprAAddress2() {
		return this.gprAAddress2;
	}

	public void setGprAAddress2(String gprAAddress2) {
		this.gprAAddress2 = gprAAddress2;
	}

	public String getGprEAddress2() {
		return this.gprEAddress2;
	}

	public void setGprEAddress2(String gprEAddress2) {
		this.gprEAddress2 = gprEAddress2;
	}

	public String getGprAAddress3() {
		return this.gprAAddress3;
	}

	public void setGprAAddress3(String gprAAddress3) {
		this.gprAAddress3 = gprAAddress3;
	}

	public String getGprEAddress3() {
		return this.gprEAddress3;
	}

	public void setGprEAddress3(String gprEAddress3) {
		this.gprEAddress3 = gprEAddress3;
	}

	public String getGprZip() {
		return this.gprZip;
	}

	public void setGprZip(String gprZip) {
		this.gprZip = gprZip;
	}

	public Long getGprTelephone() {
		return this.gprTelephone;
	}

	public void setGprTelephone(Long gprTelephone) {
		this.gprTelephone = gprTelephone;
	}

	public Long getGprFax() {
		return this.gprFax;
	}

	public void setGprFax(Long gprFax) {
		this.gprFax = gprFax;
	}

	public Long getGprGsm() {
		return this.gprGsm;
	}

	public void setGprGsm(Long gprGsm) {
		this.gprGsm = gprGsm;
	}

	public String getGprEmail() {
		return this.gprEmail;
	}

	public void setGprEmail(String gprEmail) {
		this.gprEmail = gprEmail;
	}

	public Short getGprAge() {
		return this.gprAge;
	}

	public void setGprAge(Short gprAge) {
		this.gprAge = gprAge;
	}

	public Short getGprOcCode() {
		return this.gprOcCode;
	}

	public void setGprOcCode(Short gprOcCode) {
		this.gprOcCode = gprOcCode;
	}

	public BigDecimal getGprSumInsured() {
		return this.gprSumInsured;
	}

	public void setGprSumInsured(BigDecimal gprSumInsured) {
		this.gprSumInsured = gprSumInsured;
	}

	public Byte getGprStatus() {
		return this.gprStatus;
	}

	public void setGprStatus(Byte gprStatus) {
		this.gprStatus = gprStatus;
	}

	public Date getGprValidityExpiryDate() {
		return this.gprValidityExpiryDate;
	}

	public void setGprValidityExpiryDate(Date gprValidityExpiryDate) {
		this.gprValidityExpiryDate = gprValidityExpiryDate;
	}

	public Long getGprEndtId() {
		return this.gprEndtId;
	}

	public void setGprEndtId(Long gprEndtId) {
		this.gprEndtId = gprEndtId;
	}

	public Integer getGprRiRskCode() {
		return this.gprRiRskCode;
	}

	public void setGprRiRskCode(Integer gprRiRskCode) {
		this.gprRiRskCode = gprRiRskCode;
	}

	public Integer getGprBasicRskCode() {
		return this.gprBasicRskCode;
	}

	public void setGprBasicRskCode(Integer gprBasicRskCode) {
		this.gprBasicRskCode = gprBasicRskCode;
	}

	public Character getGprGender() {
		return this.gprGender;
	}

	public void setGprGender(Character gprGender) {
		this.gprGender = gprGender;
	}

	public Byte getGprRelation() {
		return this.gprRelation;
	}

	public void setGprRelation(Byte gprRelation) {
		this.gprRelation = gprRelation;
	}

	public Date getGprRetroactiveDate() {
		return this.gprRetroactiveDate;
	}

	public void setGprRetroactiveDate(Date gprRetroactiveDate) {
		this.gprRetroactiveDate = gprRetroactiveDate;
	}

	public BigDecimal getGprSalary() {
		return this.gprSalary;
	}

	public void setGprSalary(BigDecimal gprSalary) {
		this.gprSalary = gprSalary;
	}

	public Integer getGprPreparedBy() {
		return this.gprPreparedBy;
	}

	public void setGprPreparedBy(Integer gprPreparedBy) {
		this.gprPreparedBy = gprPreparedBy;
	}

	public Date getGprPreparedDt() {
		return this.gprPreparedDt;
	}

	public void setGprPreparedDt(Date gprPreparedDt) {
		this.gprPreparedDt = gprPreparedDt;
	}

	public Integer getGprModifiedBy() {
		return this.gprModifiedBy;
	}

	public void setGprModifiedBy(Integer gprModifiedBy) {
		this.gprModifiedBy = gprModifiedBy;
	}

	public Date getGprModifiedDt() {
		return this.gprModifiedDt;
	}

	public void setGprModifiedDt(Date gprModifiedDt) {
		this.gprModifiedDt = gprModifiedDt;
	}

	public Date getGprStartDate() {
		return this.gprStartDate;
	}

	public void setGprStartDate(Date gprStartDate) {
		this.gprStartDate = gprStartDate;
	}

	public Date getGprEndDate() {
		return this.gprEndDate;
	}

	public void setGprEndDate(Date gprEndDate) {
		this.gprEndDate = gprEndDate;
	}

	public Date getGprDateOfBirth() {
		return this.gprDateOfBirth;
	}

	public void setGprDateOfBirth(Date gprDateOfBirth) {
		this.gprDateOfBirth = gprDateOfBirth;
	}

	public String getGprDescription() {
		return this.gprDescription;
	}

	public void setGprDescription(String gprDescription) {
		this.gprDescription = gprDescription;
	}

	public String getGprPersonId() {
		return this.gprPersonId;
	}

	public void setGprPersonId(String gprPersonId) {
		this.gprPersonId = gprPersonId;
	}

	public Date getGprDateOfJoining() {
		return this.gprDateOfJoining;
	}

	public void setGprDateOfJoining(Date gprDateOfJoining) {
		this.gprDateOfJoining = gprDateOfJoining;
	}

	public Long getGprBldId() {
		return this.gprBldId;
	}

	public void setGprBldId(Long gprBldId) {
		this.gprBldId = gprBldId;
	}

	public Long getGprTradeGroup() {
		return this.gprTradeGroup;
	}

	public void setGprTradeGroup(Long gprTradeGroup) {
		this.gprTradeGroup = gprTradeGroup;
	}

	public BigDecimal getGprAgrLmt() {
		return this.gprAgrLmt;
	}

	public void setGprAgrLmt(BigDecimal gprAgrLmt) {
		this.gprAgrLmt = gprAgrLmt;
	}

	public Short getGprNtyEDesc() {
		return this.gprNtyEDesc;
	}

	public void setGprNtyEDesc(Short gprNtyEDesc) {
		this.gprNtyEDesc = gprNtyEDesc;
	}

	@Override
	public int getStatus(){
		return getGprStatus();
	}
	
	@Override
	public void setStatus( Integer status ){
		setGprStatus( status.byteValue() );
	}
	
	@Override
	public void setEndtId( Long endtId ){
		setGprEndtId( endtId );
	}
	
	@Override
	public POJOId getPOJOId(){
		return this.getId();
	}
	
	@Override
	public void setPOJOId( POJOId id ){
		setId( (TTrnGaccPersonQuoId) id );
	}
	
	@Override
	public void setValidityExpiryDate( Date ved ){
		setGprValidityExpiryDate( ved );
	}
	
	@Override
	public void setValidityStartDate( Date vsd ){
		if( !Utils.isEmpty( getId() ) ) getId().setGprValidityStartDate( vsd );
	}

	@Override
	public void setStatus( int status ){
		this.gprStatus = Integer.valueOf( status ).byteValue();
	}

	@Override
	public void setEndtNo( Long endtNo ){
		//SONARFIX--26-04-2018---DO NOTHING IN METHOD
	}

	@Override
	public void setPreparedBy( Integer preparedBy ){
		this.gprPreparedBy = preparedBy;
	}

	@Override
	public void setPreparedDt( Date preparedDt ){
		this.gprPreparedDt = preparedDt;
	}

	@Override
	public void setModifiedBy( Integer modifiedBy ){
		this.gprModifiedBy = modifiedBy;		
	}

	@Override
	public void setModifiedDt( Date modifiedDt ){
		this.gprModifiedDt = modifiedDt;		
	}

	@Override
	public void setPOJOWrapperId( POJOWrapperId id ){
		this.setId((TTrnGaccPersonQuoId) id);
	}

	@Override
	public POJOWrapperId getPOJOWrapperId(){
		return getId();
	}

	@Override
	public Integer getPreparedBy(){
		return getGprPreparedBy();
	}

	@Override
	public Date getPreparedDt(){
		return getGprPreparedDt();
	}

	@Override
	public Integer getModifiedBy(){
		return getGprModifiedBy();
	}

	@Override
	public Date getModifiedDt(){
		return getGprModifiedDt();
	}
	
	@Override
	public void setPreparedDate( Date preparedDate ){
		setGprPreparedDt( preparedDate );
	}
	
	@Override
	public Date getPreparedDate(){
		return getGprPreparedDt();
	}
}
