package com.rsaame.pas.dao.model;

// Generated Oct 3, 2012 5:23:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * VTrnRenewalQuotationsSbs generated by hbm2java
 */
public class VTrnRenewalQuotationsSbsId implements java.io.Serializable {

	private Long polLinkingId;

	public VTrnRenewalQuotationsSbsId() {
	}

	public VTrnRenewalQuotationsSbsId(Long polLinkingId) {
		this.polLinkingId = polLinkingId;
	}

	public Long getPolLinkingId() {
		return this.polLinkingId;
	}

	public void setPolLinkingId(Long polLinkingId) {
		this.polLinkingId = polLinkingId;
	}
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VTrnRenewalQuotationsSbsId))
			return false;
		VTrnRenewalQuotationsSbsId castOther = (VTrnRenewalQuotationsSbsId) other;

		return ((this.getPolLinkingId() == castOther.getPolLinkingId()) || (this
				.getPolLinkingId() != null
				&& castOther.getPolLinkingId() != null && this
				.getPolLinkingId().equals(castOther.getPolLinkingId())));
			
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPolLinkingId() == null ? 0 : this.getPolLinkingId()
						.hashCode());
		
		return result;
	}

}
